In [199]:
import numpy as np
import pandas as pd

In [200]:
df = pd.read_csv('netflix_titles.csv')

In [201]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8807 entries, 0 to 8806
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8807 non-null   object
 1   type          8807 non-null   object
 2   title         8807 non-null   object
 3   director      6173 non-null   object
 4   cast          7982 non-null   object
 5   country       7976 non-null   object
 6   date_added    8797 non-null   object
 7   release_year  8807 non-null   int64
 8   rating        8803 non-null   object
 9   duration      8804 non-null   object
 10  listed_in     8807 non-null   object
 11  description   8807 non-null   object
dtypes: int64(1), object(11)
memory usage: 825.8+ KB

In [202]:
df.sample(5)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
4304,s4305,TV Show,Hymn of Death,NaN,"Lee Jong-suk, Shin Hye-sun, Kim Myeong-su, Par...",South Korea,"December 14, 2018",2018,TV-14,1 Season,"International TV Shows, Korean TV Shows, Roman...","During the Japanese colonial period, married p..."
4884,s4885,Movie,Jailbreak,Jimmy Henderson,"Jean-Paul Ly, Dara Our, Tharoth Sam, Dara Phan...",Cambodia,"May 2, 2018",2017,TV-MA,92 min,"Action & Adventure, International Movies",Four cops escorting a mobster to a high-securi...
3298,s3299,TV Show,Wild District,NaN,"Juan Pablo Raba, Cristina Umaña, Camila Sodi, ...",Colombia,"November 8, 2019",2019,TV-MA,2 Seasons,"Crime TV Shows, International TV Shows, Spanis...","After surrendering to Bogotá police, an ex-gue..."
6744,s6745,TV Show,Fear Files... Har Mod Pe Darr,NaN,NaN,India,"June 1, 2017",2015,TV-MA,1 Season,"International TV Shows, TV Horror, TV Thrillers","Possessed lovers, witches, haunted houses and ..."
296,s297,TV Show,Hit & Run,NaN,"Lior Raz, Kaelen Ohm, Sanaa Lathan, Moran Rose...","Israel, United States","August 6, 2021",2021,TV-MA,1 Season,"TV Action & Adventure, TV Dramas, TV Mysteries",A man searching for the truth behind his wife'...

In [203]:
df.duplicated().sum()

np.int64(0)

##### **`type` Column:**

In [204]:
df['type'].value_counts()

type
Movie      6131
TV Show    2676
Name: count, dtype: int64

In [205]:
df['type'].isna().sum()

np.int64(0)

##### **`title` Column:**

In [206]:
df['title'].unique() # rows = 8807, # tite unique values = 8807

array(['Dick Johnson Is Dead', 'Blood & Water', 'Ganglands', ...,
       'Zombieland', 'Zoom', 'Zubaan'], shape=(8807,), dtype=object)

##### **`director` Column:**

In [207]:
df['director'].value_counts()

director
Rajiv Chilaka              19
Raúl Campos, Jan Suter     18
Suhas Kadav                16
Marcus Raboy               16
Jay Karas                  14
                           ..
James Brown                 1
Ivona Juka                  1
Mu Chu                      1
Chandra Prakash Dwivedi     1
Majid Al Ansari             1
Name: count, Length: 4528, dtype: int64

In [208]:
df['director'].isna().sum()

np.int64(2634)

In [209]:
missing_directors = df.loc[df['director'].isna(), ['title', 'director']]
missing_directors.sample(5)

                                    title director
2751                         Akbar Birbal      NaN
5611                     Grillo vs Grillo      NaN
8588                      Tientsin Mystic      NaN
902                                  Mine      NaN
2998  ​SAINT SEIYA: Knights of the Zodiac      NaN

In [210]:
missing_directors_title = list(missing_directors['title'])

In [211]:
na_directors_titles_1 = missing_directors_title[:201]
na_directors_titles_1

['Blood & Water',
 'Jailbirds New Orleans',
 'Kota Factory',
 'Vendetta: Truth, Lies and The Mafia',
 'Crime Stories: India Detectives',
 'Dear White People',
 'Falsa identidad',
 'Jaguar',
 'Resurrection: Ertugrul',
 'Love on the Spectrum',
 'Chicago Party Aunt',
 'Sex Education',
 'Squid Game',
 'Tayo and Little Wizards',
 'Angry Birds',
 'Chhota Bheem',
 'He-Man and the Masters of the Universe',
 'Castle and Castle',
 'Dharmakshetra',
 'Nailed It',
 'Numberblocks',
 'Raja Rasoi Aur Anya Kahaniyan',
 'Saved by the Bell',
 'Stories by Rabindranath Tagore',
 'Too Hot To Handle: Latino',
 'Jack Whitehall: Travels with My Father',
 "The World's Most Amazing Vacation Rentals",
 'Yowamushi Pedal',
 'Lucifer',
 'Metal Shop Masters',
 'Pokémon Master Journeys: The Series',
 'Titipo Titipo',
 'Mighty Raju',
 'Into the Night',
 'The Circle',
 'Kid Cosmic',
 'Octonauts: Above & Beyond',
 'On the Verge',
 'Tobot Galaxy Detectives',
 'Tayo the Little Bus',
 "Bunk'd",
 'Dive Club',
 'La casa de papel',
 'Sharkdog',
 'Heroes of Goo Jit Zu',
 'Hotel Del Luna',
 'Luv Kushh',
 'Pororo - The Little Penguin',
 'Q-Force',
 'Brave Animated Series',
 'How to Be a Cowboy',
 'Kid-E-Cats',
 "Kuroko's Basketball",
 'Major Dad',
 'Oldsters',
 'Turning Point: 9/11 and the War on Terror',
 'Sparking Joy',
 'Hometown Cha-Cha-Cha',
 'The Ingenuity of the Househusband',
 'Bread Barbershop',
 'D.P.',
 'Deadly Sins',
 'I Heart Arlo',
 'Rebellion',
 'RIDE ON TIME',
 'Titletown High',
 'EDENS ZERO',
 'Family Reunion',
 'Motel Makeover',
 'Open Your Eyes',
 'Post Mortem: No One Dies in Skarnes',
 'Wheel of Fortune',
 'Oggy Oggy',
 'Manifest',
 'Comedy Premium League',
 'Everything Will Be Fine',
 'Korean Cold Noodle Rhapsody',
 'The Chair',
 'Go! Go! Cory Carson',
 'The Defeated',
 'Mother Goose Club',
 'Rascal Does Not Dream of Bunny Girl Senpai',
 'The Creative Indians',
 'Winx Club',
 'Brand New Cherry Flavor',
 'Fast & Furious Spy Racers',
 'Grace and Frankie',
 'The Kingdom',
 'AlRawabi School for Girls',
 'Bake Squad',
 "Gabby's Dollhouse",
 'Las muñecas de la mafia',
 'The Crowned Clown',
 'SHAMAN KING',
 'Hit & Run',
 'Car Masters: Rust to Riches',
 'Control Z',
 'Cooking With Paris',
 "Autumn's Concerto",
 'The Prince Who Turns into a Frog',
 'Top Secret UFO Projects: Declassified',
 'Two Fathers',
 "You're My Destiny",
 '30 Rock',
 '44 Cats',
 'Darwin’s Game',
 'Friday Night Lights',
 'Hunter X Hunter (2011)',
 'Charmed',
 'Centaurworld',
 'Glow Up',
 'Khawatir',
 'Myth & Mogul: John DeLorean',
 'Outer Banks',
 'Transformers: War for Cybertron: Kingdom',
 'Tattoo Redo',
 'The Snitch Cartel: Origins',
 'All American',
 'How to Sell Drugs Online (Fast)',
 'Mighty Express',
 'The Walking Dead',
 'Wynonna Earp',
 'Feels Like Ishq',
 'Masters of the Universe: Revelation',
 'Revelations: The Masters of the Universe: Revelation Aftershow',
 'Sky Rojo',
 'The Movies That Made Us',
 '9to5: The Story of a Movement',
 'Chicago Med',
 'Sexy Beasts',
 'Too Hot to Handle: Brazil',
 'Okupas',
 'Touch Your Heart',
 'Explained',
 'Johnny Test',
 'BEASTARS',
 'Her Private Life',
 'Never Have I Ever',
 'Heist',
 'My Unorthodox Life',
 'Bridgerton - The Afterparty',
 'Ridley Jones',
 'Atypical',
 'Biohackers',
 'How to Become a Tyrant',
 'Last Summer',
 'The Cook of Castamar',
 'Virgin River',
 'Elize Matsunaga: Once Upon a Crime',
 'RESIDENT EVIL: Infinite Darkness',
 'Cat People',
 'Dogs',
 'The War Next-door',
 'Ask the StoryBots',
 'Between',
 'Chelsea',
 'Code Lyoko',
 'Colony',
 'Cuckoo',
 'Derry Girls',
 'Girl from Nowhere',
 'Good Morning Call',
 'I AM A KILLER',
 'I Think You Should Leave with Tim Robinson',
 "Kim's Convenience",
 'Larva',
 'Marcella',
 'Midnight Diner: Tokyo Stories',
 'My Little Pony: Friendship Is Magic',
 'Orange Is the New Black',
 'Puffin Rock',
 'Richie Rich',
 'Scream',
 'Shtisel',
 'Some Assembly Required',
 'Tales by Light',
 'Terrace House: Opening New Doors',
 'The A List',
 'The New Legends of Monkey',
 'The Worst Witch',
 'Undercover',
 "Workin' Moms",
 'YooHoo to the Rescue',
 'You Are My Spring',
 'We the People',
 "Grey's Anatomy",
 'Big Timber',
 'Mortel',
 'Bureau of Magical Things',
 'Generation 56k',
 'Rainbow Rangers',
 'Sailor Moon Crystal',
 'Young Royals',
 "Droppin' Cash: Los Angeles",
 'Somos.',
 'The Daily Life of the Immortal King',
 'StarBeam',
 'The Seven Deadly Sins',
 'Sex/Life',
 'Godzilla Singular Point',
 'Jiva!']

In [212]:
movies_and_directors_1 = {
    '30 Rock': 'Don Scardino',
    '44 Cats': 'Iginio Straffi',
    '9to5: The Story of a Movement': 'Julia Reichert',
    'AlRawabi School for Girls': 'Tima Shomali',
    'All American': 'Michael Schultz',
    'Angry Birds': 'Clay Kaytis',
    'Ask the StoryBots': 'Evan Spiridellis',
    'Atypical': 'Michael Patrick Jann',
    "Autumn's Concerto": 'Chen Hui-ling',
    'BEASTARS': 'Shinichi Matsumi',
    'Bake Squad': 'Michael Pearlman',
    'Between': 'Jon Cassar',
    'Big Timber': 'Dustin Lucas',
    'Biohackers': 'Christian Ditter',
    'Blood & Water': 'Nosipho Dumisa',
    'Brand New Cherry Flavor': 'Arkasha Stevenson',
    'Brave Animated Series': 'Michael J. Luisi',
    'Bread Barbershop': 'Jung Ji-hwan',
    'Bridgerton - The Afterparty': 'Krysia Plonka',
    "Bunk'd": 'Rich Correll',
    'Bureau of Magical Things': 'Evan Clarry',
    'Car Masters: Rust to Riches': 'Michael Pearlman',
    'Castle and Castle': 'Tope Oshin',
    'Cat People': 'Donald Thoms',
    'Centaurworld': 'Megan Nicole Dong',
    'Charmed': 'Brad Silberling',
    'Chelsea': 'Eddie Schmidt',
    'Chhota Bheem': 'Rajiv Chilaka',
    'Chicago Med': 'Michael Waxman',
    'Chicago Party Aunt': 'Jon Le Bail',
    'Code Lyoko': 'Jerome Mouscadet',
    'Colony': 'Juan José Campanella',
    'Comedy Premium League': 'Karan Mady',
    'Control Z': 'Alejandro Lozano',
    'Cooking With Paris': 'Michael Pearlman',
    'Crime Stories: India Detectives': 'Niren Bhatt',
    'Cuckoo': 'Ben Taylor',
    'D.P.': 'Han Jun-hee',
    'Darwin’s Game': 'Yoshinobu Tokumoto',
    'Deadly Sins': 'Steve Vosburgh',
    'Dear White People': 'Justin Simien',
    'Derry Girls': 'Michael Lennox',
    'Dharmakshetra': 'Gaurav Shukla',
    'Dive Club': 'Rhiannon Bannenberg',
    'Dogs': 'Glen Zipper',
    "Droppin' Cash: Los Angeles": 'Michael D. Ratner',
    'EDENS ZERO': 'Shinji Ishihira',
    'Elize Matsunaga: Once Upon a Crime': 'Eliza Capai',
    'Everything Will Be Fine': 'Diego Luna',
    'Explained': 'Trish Lipman',
    'Falsa identidad': 'Conrado Martínez',
    'Family Reunion': 'Robbie Countryman',
    'Fast & Furious Spy Racers': 'James Yang',
    'Feels Like Ishq': 'Anand Tiwari',
    'Friday Night Lights': 'Peter Berg',
    "Gabby's Dollhouse": 'Traci Paige Johnson',
    'Generation 56k': 'Francesco Ebbasta',
    'Girl from Nowhere': 'Sitisiri Mongkolsiri',
    'Glow Up': 'Michael Pearlman',
    'Go! Go! Cory Carson': 'Stanley Moore',
    'Godzilla Singular Point': 'Atsushi Takahashi',
    'Good Morning Call': 'Yo Koutoku',
    'Grace and Frankie': 'Alex Hardcastle',
    "Grey's Anatomy": 'Rob Corn',
    'He-Man and the Masters of the Universe': 'Rob David',
    'Heist': 'Nick Frew',
    'Her Private Life': 'Hong Jong-chan',
    'Heroes of Goo Jit Zu': 'Sean Gorman',
    'Hit & Run': 'Mike Barker',
    'Hometown Cha-Cha-Cha': 'Yoo Je-won',
    'Hotel Del Luna': 'Oh Choong-hwan',
    'How to Be a Cowboy': 'John Feldmann',
    'How to Become a Tyrant': 'Peter Dinklage',
    'How to Sell Drugs Online (Fast)': 'Arne Feldhusen',
    'Hunter X Hunter (2011)': 'Hiroshi Kōjina',
    'I AM A KILLER': 'Ned Parker',
    'I Heart Arlo': 'Ryan Crego',
    'I Think You Should Leave with Tim Robinson': 'Akiva Schaffer',
    'Into the Night': 'Inti Calfat',
    'Jack Whitehall: Travels with My Father': 'Leo Pearlman',
    'Jaguar': 'Carlos Sedes',
    'Jailbirds New Orleans': 'Ramy Romany',
    'Jiva!': 'Busisiwe Ntintili',
    'Johnny Test': 'Tim Stuby',
    'Khawatir': 'Ahmad Al Shugairi',
    'Kid Cosmic': 'Craig McCracken',
    'Kid-E-Cats': 'Dmitry Vysotsky',
    "Kim's Convenience": 'Aleysa Young',
    'Korean Cold Noodle Rhapsody': 'Kim Jin-young',
    'Kota Factory': 'Raghav Subbu',
    "Kuroko's Basketball": 'Shunsuke Tada',
    'La casa de papel': 'Jesús Colmenar',
    'Larva': 'Ahn Byoung-wook',
    'Las muñecas de la mafia': 'Luis Alberto Restrepo',
    'Last Summer': 'Jon Jones',
    'Love on the Spectrum': "Cian O'Clery",
    'Lucifer': 'Nathan Hope',
    'Luv Kushh': 'Rajiv Chilaka',
    'Major Dad': 'Michael Lembeck',
    'Manifest': 'Romeo Tirone',
    'Marcella': 'Charles Martin',
    'Masters of the Universe: Revelation': 'Kevin Smith',
    'Metal Shop Masters': 'Michael Pearlman',
    'Midnight Diner: Tokyo Stories': 'Joji Matsuoka',
    'Mighty Express': 'Clint Butler',
    'Mighty Raju': 'Rajiv Chilaka',
    'Mortel': 'Simon Astier',
    'Motel Makeover': 'Sarah James',
    'Mother Goose Club': 'John S. Bennett',
    'My Little Pony: Friendship Is Magic': 'Jayson Thiessen',
    'My Unorthodox Life': 'Elan Gale',
    'Myth & Mogul: John DeLorean': 'Mike Christie',
    'Nailed It': 'Paul Starkman',
    'Never Have I Ever': 'Lang Fisher',
    'Numberblocks': 'Joe Elliot',
    'Octonauts: Above & Beyond': "Darragh O'Connell",
    'Oggy Oggy': 'Jean Cayrol',
    'Okupas': 'Bruno Stagnaro',
    'Oldsters': 'Juho Kuosmanen',
    'On the Verge': 'Julie Delpy',
    'Open Your Eyes': 'Anna Jadowska',
    'Orange Is the New Black': 'Andrew McCarthy',
    'Outer Banks': 'Jonas Pate',
    'Pokémon Master Journeys: The Series': 'Daiki Tomiyasu',
    'Pororo - The Little Penguin': 'Kim Il-kwon',
    'Post Mortem: No One Dies in Skarnes': 'Janic Heen',
    'Puffin Rock': 'Maurice Joyce',
    'Q-Force': 'Gabe Liedman',
    'RESIDENT EVIL: Infinite Darkness': 'Eiichirō Hasumi',
    'RIDE ON TIME': 'Katsuhiko Nishino',
    'Rainbow Rangers': 'Michael Maliani',
    'Raja Rasoi Aur Anya Kahaniyan': 'Akshar Pillai',
    'Rascal Does Not Dream of Bunny Girl Senpai': 'Sōichi Masui',
    'Rebellion': 'Aku Louhimies',
    'Resurrection: Ertugrul': 'Metin Günay',
    'Revelations: The Masters of the Universe: Revelation Aftershow': 'Kevin Smith',
    'Richie Rich': 'Phill Lewis',
    'Ridley Jones': 'Chris Nee',
    'SHAMAN KING': 'Joji Furuta',
    'Sailor Moon Crystal': 'Munehisa Sakai',
    'Saved by the Bell': 'Tracey Wigfield',
    'Scream': 'Jamie Travis',
    'Sex Education': 'Ben Taylor',
    'Sex/Life': 'Stacy Rukeyser',
    'Sexy Beasts': 'Sam Campbell',
    'Sharkdog': 'Jacinth Tan',
    'Shtisel': 'Alon Zingman',
    'Sky Rojo': 'David Victori',
    'Some Assembly Required': 'Dan Signer',
    'Somos.': 'Alvaro Curiel',
    'Sparking Joy': 'Yuka Kanzaki',
    'Squid Game': 'Hwang Dong-hyuk',
    'StarBeam': 'Jon Izen',
    'Stories by Rabindranath Tagore': 'Anurag Basu',
    'Tales by Light': 'Abraham Joffe',
    'Tattoo Redo': "Bryan O'Donnell",
    'Tayo and Little Wizards': 'Ryu Jung-woo',
    'Tayo the Little Bus': 'Shin Chang-hwan',
    'Terrace House: Opening New Doors': 'Masato Maeda',
    'The A List': 'Dan Berlinka',
    'The Chair': 'Daniel Gray Longino',
    'The Circle': 'Sam Strauss',
    'The Cook of Castamar': 'Iñaki Peñafiel',
    'The Creative Indians': 'Pragya Tiwari',
    'The Crowned Clown': 'Kim Hee-won',
    'The Daily Life of the Immortal King': 'Li Haoling',
    'The Defeated': 'Björn Stein',
    'The Ingenuity of the Househusband': 'Chiaki Kon',
    'The Kingdom': 'Kim Seong-hun',
    'The Movies That Made Us': 'Brian Volk-Weiss',
    'The New Legends of Monkey': 'Gerard Johnstone',
    'The Prince Who Turns into a Frog': 'Chen Ming-chang',
    'The Seven Deadly Sins': 'Tensai Okamura',
    'The Snitch Cartel: Origins': 'Carlos Moreno',
    'The Walking Dead': 'Greg Nicotero',
    'The War Next-door': 'Noé Santillán-López',
    "The World's Most Amazing Vacation Rentals": 'George Verschoor',
    'The Worst Witch': 'Brian Grant',
    'Titipo Titipo': 'Ryu Jung-woo',
    'Titletown High': 'Jason Sciavicco',
    'Tobot Galaxy Detectives': 'Lee Young-jun',
    'Too Hot To Handle: Latino': 'Laura Lehmus',
    'Too Hot to Handle: Brazil': 'Chico Barros',
    'Top Secret UFO Projects: Declassified': 'Petr Vachler',
    'Touch Your Heart': 'Park Joon-hwa',
    'Transformers: War for Cybertron: Kingdom': 'Takashi Kamei',
    'Turning Point: 9/11 and the War on Terror': 'Brian Knappenberger',
    'Two Fathers': 'Liu Jun-jie',
    'Undercover': 'Eshref Reybrouck',
    'Vendetta: Truth, Lies and The Mafia': 'Davide Gambino',
    'Virgin River': 'Andy Mikita',
    'We the People': 'Peter Ramsey',
    'Wheel of Fortune': 'Robert Bowdon',
    'Winx Club': 'Iginio Straffi',
    "Workin' Moms": 'Catherine Reitman',
    'Wynonna Earp': 'Paolo Barzman',
    'YooHoo to the Rescue': 'David Feiss',
    'You Are My Spring': 'Jung Ji-hyun',
    "You're My Destiny": 'Zhou Xiao-peng',
    'Young Royals': 'Rojda Sekersöz',
    'Yowamushi Pedal': 'Osamu Nabeshima'
}

In [213]:
len(movies_and_directors_1)

201

In [214]:
df['director'] = df['director'].fillna(df['title'].map(movies_and_directors_1))
remaining_nulls = df['director'].isnull().sum()
print(f"Remaining null values in director column: {remaining_nulls}")

Remaining null values in director column: 2433

In [215]:
na_directors_titles_2 = missing_directors_title[201:402]
na_directors_titles_2

['Sisters on Track',
 'The Naked Director',
 'The Parisian Agency: Exclusive Properties',
 'Too Hot to Handle',
 'This Is Pop',
 'The Mole',
 'Nevertheless,',
 'Bangkok Love Stories: Innocence',
 'Black Lightning',
 'Call My Agent!',
 'Champions',
 'Charité at War',
 'Deadwind',
 'Glee',
 'Hap and Leonard',
 'Locked Up',
 'No Time for Shame',
 'Pose',
 'REA(L)OVE',
 "Schitt's Creek",
 'The Assassination of Gianni Versace',
 'The Judgement',
 'The Last Dance',
 'Why Are You Like This',
 'Elite',
 'Hospital Playlist',
 'So Not Worth It',
 'Black Summer',
 'Elite Short Stories: Carla Samuel',
 'Katla',
 'Record of Ragnarok',
 'The Gift',
 'Elite Short Stories: Omar Ander Alexis',
 'Millennials',
 'Penguin Town',
 'Avengers Climate Conundrum',
 'Beyond Evil',
 'Elite Short Stories: Nadia Guzmán',
 'Headspace: Unwind Your Mind',
 'Power Rangers Dino Fury',
 'Rhyme Time Town',
 'Elite Short Stories: Guzmán Caye Rebe',
 'Bling Empire - The Afterparty',
 'Cobra Kai - The Afterparty',
 'Love (ft. Marriage and Divorce)',
 'To All the Boys: Always and Forever - The Afterparty',
 'LEGO Friends: The Power of Friendship',
 'Lupin',
 'Trese After Dark',
 'Locombianos',
 'Fresh, Fried & Crispy',
 'L.A.’s Finest',
 'Guru Aur Bhole',
 'Newly Rich, Newly Poor',
 'Kitty Love: An Homage to Cats',
 'Human: The World Within',
 'Sweet Tooth',
 "Creator's File: GOLD",
 'Summertime',
 'Attack on Titan',
 "Ben & Holly's Little Kingdom",
 'Cocomelon',
 'Downton Abbey',
 'Happy Endings',
 'Racket Boys',
 'The Adventures of Sonic the Hedgehog',
 'The Platform',
 'Dirty John',
 'The Kominsky Method',
 'Black Space',
 'Eden',
 'Ragnarok',
 'High on the Hog: How African American Cuisine Transformed America',
 "JoJo's Bizarre Adventure",
 'Mad for Each Other',
 'Master of None',
 'Sam Smith: Love Goes - Live at Abbey Road Studios',
 '99 Songs (Tamil)',
 '99 Songs (Telugu)',
 'Creating an Army of the Dead',
 'Jurassic World Camp Cretaceous',
 'The Neighbor',
 'Special',
 'The Magic School Bus',
 'Who Killed Sara?',
 'Booba: Food Puzzle',
 'Alma Matters',
 'Haunted',
 'Love, Death & Robots',
 'Move to Heaven',
 'The Upshaws - The Afterparty',
 'Castlevania',
 'The Upshaws',
 'Money, Explained',
 'Mine',
 "Jupiter's Legacy",
 'The Circle - The Afterparty',
 'Lava Ka Dhaava',
 'Selena: The Series',
 'StartUp',
 'Trash Truck',
 'Angelina Ballerina',
 'Barney and Friends',
 'Miniforce: Super Dino Power',
 'Pet Stars',
 'The Unremarkable Juanquini',
 'Yasuke',
 'Headspace Guide to Sleep',
 'Sexify',
 'Fatma',
 'Shadow and Bone - The Afterparty',
 'Shadow and Bone',
 'Life in Color with David Attenborough',
 'Searching For Sheela',
 'Zero',
 "Izzy's Koala World",
 'Keymon and Nani in Space Adventure',
 'Rudra: The Rise of King Pharaoh',
 'Free to Play',
 'Luis Miguel - The Series',
 'PJ Masks',
 'Bakugan: Geogan Rising',
 'Dad Stop Embarrassing Me - The Afterparty',
 'Love Naggers',
 'Dancing Angels',
 'Durarara!!',
 'Gilmore Girls',
 'High-Rise Invasion',
 'Next in Fashion',
 'Peasants Rebellion',
 'Power Players',
 'Ricky Zoom',
 'Sonic X',
 'Ajaibnya Cinta',
 'Dad Stop Embarrassing Me!',
 'Fate: The Winx Saga',
 'House of Cards',
 'Indian Matchmaking',
 'Jeffrey Epstein: Filthy Rich',
 'Law School',
 'Living with Yourself',
 'Signal',
 'Slasher',
 'Unnatural Selection',
 'The Baker and the Beauty',
 'Nicky, Ricky, Dicky & Dawn',
 "Don't be the First one",
 "Heaven Official's Blessing",
 'The Way of the Househusband',
 'Dolly Parton: A MusiCares Tribute',
 'The Big Day',
 'The Wedding Coach',
 "This Is a Robbery: The World's Biggest Art Heist",
 'Glimpses of a Future',
 'Magical Andes',
 'Murder Maps',
 'Prank Encounters',
 'Secrets of Great British Castles',
 'Worn Stories',
 'Robocar Poli',
 'Yu-Gi-Oh!',
 'Rainbow High',
 'Bad Trip',
 'Big Time Rush',
 'Elizabeth and Margaret: Love and Loyalty',
 'Magic for Humans Spain',
 'The Irregulars',
 "DOTA: Dragon's Blood",
 'Pui Pui Molcar',
 'Navillera',
 'Mighty Morphin Power Rangers',
 'Alien TV',
 'Country Comfort',
 'Formula 1: Drive to Survive',
 'B: The Beginning',
 'Waffles + Mochi',
 'Abla Fahita: Drama Queen',
 'The Lost Pirate Kingdom',
 'Zero Chill',
 'Love Alarm',
 'Paradise PD',
 'The One',
 'Last Chance U: Basketball',
 'Marriage or Mortgage',
 'The Houseboat',
 'Bombay Begums',
 'My Way',
 'City of Ghosts',
 'Pokémon Journeys: The Series',
 'Pacific Rim: The Black',
 'Word Party',
 'TIGER & BUNNY',
 'Ginny & Georgia - The Afterparty',
 'El final del paraíso',
 'Sin senos sí hay paraíso',
 'The Last Bastion',
 'Age of Samurai: Battle for Japan',
 'Canine Intervention',
 'Ginny & Georgia',
 'Two Sentence Horror Stories',
 'Zindagi in Short']

In [216]:
movies_and_directors_2 = {
    '99 Songs (Tamil)': 'Vishwesh Krishnamoorthy',
    '99 Songs (Telugu)': 'Vishwesh Krishnamoorthy',
    'Abla Fahita: Drama Queen': 'Khaled Marei',
    'Age of Samurai: Battle for Japan': 'Stephen Scott',
    'Ajaibnya Cinta': 'Emmi Sufian',
    'Alien TV': 'Ian Brown',
    'Alma Matters': 'Pratik Patra',
    'Angelina Ballerina': 'Kitty Taylor',
    'Attack on Titan': 'Tetsurō Araki',
    'Avengers Climate Conundrum': 'Michael D. Black',
    'B: The Beginning': 'Kazuto Nakazawa',
    'Bad Trip': 'Kitao Sakurai',
    'Bakugan: Geogan Rising': 'Kazuya Ichikawa',
    'Bangkok Love Stories: Innocence': 'Danai Nimunna',
    'Barney and Friends': 'Fred Holmes',
    "Ben & Holly's Little Kingdom": 'Neville Astley',
    'Beyond Evil': 'Sim Na-yeon',
    'Big Time Rush': 'Savage Steve Holland',
    'Black Lightning': 'Salim Akil',
    'Black Space': 'Ofir Lobel',
    'Black Summer': 'John Hyams',
    'Bling Empire - The Afterparty': 'Krysia Plonka',
    'Bombay Begums': 'Alankrita Shrivastava',
    'Booba: Food Puzzle': 'Nick Solovov',
    'Call My Agent!': 'Cédric Klapisch',
    'Canine Intervention': 'Nikki Yochum',
    'Castlevania': 'Sam Deats',
    'Champions': 'Javier Fesser',
    'Charité at War': 'Anno Saul',
    'City of Ghosts': 'Elizabeth Ito',
    'Cobra Kai - The Afterparty': 'Krysia Plonka',
    'Cocomelon': 'Jay Jeon',
    'Country Comfort': 'Kelly Park',
    'Creating an Army of the Dead': 'Zack Snyder',
    "Creator's File: GOLD": 'Takashi Fujii',
    'Dad Stop Embarrassing Me - The Afterparty': 'Krysia Plonka',
    'Dad Stop Embarrassing Me!': 'Ken Whittingham',
    'Dancing Angels': 'Kassim Hamid',
    'Deadwind': 'Samuli Valkama',
    'Dirty John': 'Jeffrey Reiner',
    'Dolly Parton: A MusiCares Tribute': 'Leon Knoles',
    "Don't be the First one": 'Yoo Ki-hwan',
    "DOTA: Dragon's Blood": 'Park So-young',
    'Downton Abbey': 'Brian Percival',
    'Durarara!!': 'Takahiro Omori',
    'Eden': 'Yasuhiro Irie',
    'El final del paraíso': 'Gustavo Bolívar',
    'Elite': 'Ramón Salazar',
    'Elite Short Stories: Carla Samuel': 'Jorge Torregrossa',
    'Elite Short Stories: Guzmán Caye Rebe': 'Dani de la Orden',
    'Elite Short Stories: Nadia Guzmán': 'Dani de la Orden',
    'Elite Short Stories: Omar Ander Alexis': 'Jorge Torregrossa',
    'Elizabeth and Margaret: Love and Loyalty': 'James Rogan',
    'Fatma': 'Özer Feyzioğlu',
    'Fate: The Winx Saga': 'Brian Young',
    'Formula 1: Drive to Survive': 'James Gay-Rees',
    'Free to Play': 'Valve Corporation',
    'Fresh, Fried & Crispy': 'Michael Pearlman',
    "Gilmore Girls": 'Amy Sherman-Palladino',
    'Ginny & Georgia': 'Anya Adams',
    'Ginny & Georgia - The Afterparty': 'Krysia Plonka',
    'Glee': 'Ryan Murphy',
    'Glimpses of a Future': 'Valerie Veatch',
    'Guru Aur Bhole': 'Yunus Bukhari',
    'Hap and Leonard': 'Jim Mickle',
    'Happy Endings': 'Anthony Russo',
    'Haunted': 'Jan Pavlacky',
    'Headspace Guide to Sleep': 'Arthur Jones',
    'Headspace: Unwind Your Mind': 'Arthur Jones',
    "Heaven Official's Blessing": 'Li Haoling',
    'High-Rise Invasion': 'Masahiro Takata',
    'High on the Hog: How African American Cuisine Transformed America': 'Roger Ross Williams',
    'Hospital Playlist': 'Shin Won-ho',
    'House of Cards': 'David Fincher',
    'Human: The World Within': 'Stephen David',
    'Indian Matchmaking': 'Smriti Mundhra',
    "Izzy's Koala World": 'Diederick Santer',
    'Jeffrey Epstein: Filthy Rich': 'Lisa Bryant',
    "JoJo's Bizarre Adventure": 'Naokatsu Tsuda',
    "Jupiter's Legacy": 'Steven S. DeKnight',
    'Jurassic World Camp Cretaceous': 'Lane Lueras',
    'Katla': 'Baltasar Kormákur',
    'Keymon and Nani in Space Adventure': 'Yunus Bukhari',
    'Kitty Love: An Homage to Cats': 'Mark Verkerk',
    'L.A.’s Finest': 'Anton Cropper',
    'Last Chance U: Basketball': 'Greg Whiteley',
    'Lava Ka Dhaava': 'Jaaved Jaaferi',
    'Law School': 'Kim Suk-yoon',
    'LEGO Friends: The Power of Friendship': 'Christian Kjaer',
    'Life in Color with David Attenborough': 'Adam Geiger',
    'Living with Yourself': 'Jonathan Dayton',
    'Locked Up': 'Jesús Colmenar',
    'Locombianos': 'Fernando Ayllón',
    'Love Alarm': 'Lee Na-jung',
    'Love, Death & Robots': 'Tim Miller',
    'Love (ft. Marriage and Divorce)': 'Yoo Jung-joon',
    'Love Naggers': 'Kim Ji-yoon',
    'Luis Miguel - The Series': 'Humberto Hinojosa Ozcariz',
    'Lupin': 'Louis Leterrier',
    'Mad for Each Other': 'Lee Tae-gon',
    'Magic for Humans Spain': 'Rafa Parbus',
    'Magical Andes': 'Luis Ara',
    'Marriage or Mortgage': 'Michael Pearlman',
    'Master of None': 'Aziz Ansari',
    'Mighty Morphin Power Rangers': 'Robert Hughes',
    'Millennials': 'Mauro Scandolari',
    'Mine': 'Lee Na-jung',
    'Miniforce: Super Dino Power': 'Lee Young-jun',
    'Money, Explained': 'Trish Lipman',
    'Mortel': 'Simon Astier',
    'Move to Heaven': 'Kim Sung-ho',
    'Murder Maps': 'Daniel Kontur',
    'My Way': 'Danny Sangra',
    'Navillera': 'Han Dong-hwa',
    'Nevertheless,': 'Kim Ga-ram',
    'Newly Rich, Newly Poor': 'Lee Chang-min',
    'Next in Fashion': 'Rebecca Taylor',
    'No Time for Shame': 'Santiago Mitre',
    'Pacific Rim: The Black': 'Hiroyuki Hayashi',
    'Paradise PD': 'Waco O\'Guin',
    'Peasants Rebellion': 'Shin Chang-hwan',
    'Penguin Town': 'Cayley Christos',
    'Pet Stars': 'Jared Cohen',
    'PJ Masks': 'Christian De Vita',
    'Pokémon Journeys: The Series': 'Daiki Tomiyasu',
    'Pose': 'Ryan Murphy',
    'Power Rangers Dino Fury': 'Simon Bennett',
    'Power Players': 'Tarig Rimawi',
    'Prank Encounters': 'Anthony Gonzales',
    'Pui Pui Molcar': 'Tomoki Misato',
    'Racket Boys': 'Jo Young-kwang',
    'Ragnarok': 'Mogens Hagedorn',
    'Rainbow High': 'Jerome Mouscadet',
    'REA(L)OVE': 'Hayato Onaka',
    'Record of Ragnarok': 'Masao Ōkubo',
    'Rhyme Time Town': 'Darragh O\'Connell',
    'Ricky Zoom': 'Franck Michel',
    'Robocar Poli': 'Lee Dong-woo',
    'Rudra: The Rise of King Pharaoh': 'Sumit Das',
    'Sam Smith: Love Goes - Live at Abbey Road Studios': 'Paul Dugdale',
    "Schitt's Creek": 'Jerry Ciccoritti',
    'Searching For Sheela': 'Shakun Batra',
    'Secrets of Great British Castles': 'Gerry Hoban',
    'Selena: The Series': 'Hiromi Kamata',
    'Sexify': 'Kalia Alabrudzińska',
    'Shadow and Bone': 'Lee Toland Krieger',
    'Shadow and Bone - The Afterparty': 'Krysia Plonka',
    'Sin senos sí hay paraíso': 'Herney Luna',
    'Sisters on Track': 'Tone Grøttjord-Glenne',
    'Slasher': 'Craig David Wallace',
    'So Not Worth It': 'Kwon Ik-joon',
    'Sonic X': 'Hajime Kamegaki',
    'Special': 'Ryan O\'Connell',
    'StartUp': 'Ben Ketai',
    'Sweet Tooth': 'Jim Mickle',
    'Summertime': 'Lorenzo Sportiello',
    'The Adventures of Sonic the Hedgehog': 'Kent Butterworth',
    'The Assassination of Gianni Versace': 'Ryan Murphy',
    'The Baker and the Beauty': 'David Frankel',
    'The Big Day': 'Ashish Sawhny',
    'The Circle - The Afterparty': 'Krysia Plonka',
    'The Gift': 'Ozan Açıktan',
    'The Houseboat': 'Lars Jessen',
    'The Irregulars': 'Johnny Allan',
    'The Judgement': 'Khuntham Khunmongkol',
    'The Kominsky Method': 'Chuck Lorre',
    'The Last Bastion': 'Gaurav Shukla',
    'The Last Dance': 'Jason Hehir',
    'The Magic School Bus': 'Charles E. Bastien',
    'The Mole': 'Ben Hardy',
    'The Naked Director': 'Masaharu Take',
    'The Neighbor': 'Nacho Vigalondo',
    'The One': 'Jeremy Lovering',
    'The Parisian Agency: Exclusive Properties': 'Martin Kretz',
    'The Platform': 'Galder Gaztelu-Urrutia',
    'The Unremarkable Juanquini': 'Antonio Sanint',
    'The Upshaws': 'Sheldon Epps',
    'The Upshaws - The Afterparty': 'Krysia Plonka',
    'The Way of the Househusband': 'Chiaki Kon',
    'The Wedding Coach': 'Michael Pearlman',
    'This Is Pop': 'Del Cowie',
    'TIGER & BUNNY': 'Keiichi Satou',
    'To All the Boys: Always and Forever - The Afterparty': 'Krysia Plonka',
    'Too Hot to Handle': 'Laura Lehmus',
    'Trash Truck': 'Max Keane',
    'Trese After Dark': 'Jay Oliva',
    'Two Sentence Horror Stories': 'Vera Miao',
    'Unnatural Selection': 'Leeor Kaufman',
    'Waffles + Mochi': 'Jeremy Konner',
    'Who Killed Sara?': 'David Ruiz',
    'Why Are You Like This': 'Jessie Oldfield',
    'Word Party': 'Alex Rockwell',
    'Worn Stories': 'Jenna Elfman',
    'Yu-Gi-Oh!': 'Kunihisa Sugishima',
    'Zero': 'Ivan Silvestrini',
    'Zero Chill': 'Angelo Abela',
    'Zindagi in Short': 'Punakit Singh'
}

In [217]:
df['director'] = df['director'].fillna(df['title'].map(movies_and_directors_2))
remaining_nulls = df['director'].isnull().sum()
print(f"Remaining null values in director column: {remaining_nulls}")

Remaining null values in director column: 2237

In [218]:
na_directors_titles_3 = missing_directors_title[402:639]
na_directors_titles_3

['Vincenzo',
 'Fate: The Winx Saga - The Afterparty',
 'Tribes of Europa',
 'Hello, Me!',
 'Sisyphus',
 'Thus Spoke Kishibe Rohan',
 'Amend: The Fight for America',
 'Behind Her Eyes',
 'MeatEater',
 'Good Girls',
 'Booba',
 'The Crew',
 'Buried by the Bernards',
 "Chappelle's Show",
 'Nadiya Bakes',
 'Capitani',
 'El Chema',
 'Five Came Back: The Reference Films',
 'ICarly',
 'The Sinner',
 'Hache',
 'Invisible City',
 'Firefly Lane',
 'Pablo Escobar, el patrón del mal',
 'Power Rangers Ninja Steel',
 'Tiffany Haddish Presents: They Ready',
 'Heartland',
 'Love Daily',
 'My Dead Ex',
 'The Unsettling',
 'Total Drama',
 'Zac and Mia',
 'Zig & Sharko',
 'We Are: The Brooklyn Saints',
 '50M2',
 'BONDING',
 'Outlander',
 'Go Dog Go',
 'Blown Away',
 'Busted!',
 'Demon Slayer: Kimetsu no Yaiba',
 'Daughter From Another Mother',
 'Spycraft',
 'Hello Ninja',
 'Bling Empire',
 'Carmen Sandiego',
 'Disenchantment',
 'Henry Danger',
 'The Magicians',
 "Creating The Queen's Gambit",
 'Inside the World’s Toughest Prisons',
 'Mighty Little Bheem: Kite Festival',
 'Pretend It’s a City',
 'Stuck Apart',
 'Surviving Death',
 'History of Swear Words',
 'Nailed It! Mexico',
 'Korean Pork Belly Rhapsody',
 'QB1: Beyond the Lights',
 'Cobra Kai',
 'Dream Home Makeover',
 'Headspace Guide to Meditation',
 'Jenni Rivera: Mariposa de Barrio',
 'Monarca',
 'Running Man',
 'The Haunted Hathaways',
 'The Minimalists: Less Is Now',
 'Best of Stand-Up 2020',
 'Chilling Adventures of Sabrina',
 'Best Leftovers Ever!',
 'Dare Me',
 'Equinox',
 'Still Game',
 'Transformers: War for Cybertron: Earthrise',
 'A Love So Beautiful',
 'Sakho & Mangane',
 'Regiment Diaries',
 'Bridgerton',
 'Lovestruck in the City',
 'Rhyme Time Town Singalongs',
 'Shaun the Sheep',
 'Timmy Time',
 'Diamond City',
 'Home for Christmas',
 "Ma Rainey's Black Bottom: A Legacy Brought to Screen",
 'Morphle',
 'Run On',
 'How To Ruin Christmas',
 'Marvel Anime: Wolverine',
 'Marvel Anime: X-Men',
 'Black Ink Crew New York',
 'Pup Academy',
 'Song Exploder',
 'Teen Mom 2',
 'The Challenge',
 'Hilda',
 'Tiny Pretty Things',
 'The Netflix Afterparty: The Best Shows of The Worst Year',
 'Children of Adam',
 'Grizzy et les Lemmings',
 'The Mess You Leave Behind',
 'Alice in Borderland',
 'Masameer Classics',
 'Once Upon a Time',
 'The Big Show Show',
 'The Expanding Universe of Ashley Garcia',
 "The Surgeon's Cut",
 'Emicida: AmarElo - It’s All For Yesterday',
 'Juman',
 'Mr. Iglesias',
 '100 Days My Prince',
 'Manhunt: Deadly Games',
 'Bhaag Beanie Bhaag',
 'Big Mouth',
 "Kings of Jo'Burg",
 'Leyla Everlasting',
 'The Great British Baking Show: Holidays',
 'Alien Worlds',
 'Check The Store Next Door: The Next Chapter',
 'Hazel Brugger: Tropical',
 'Are You The One',
 'Gormiti',
 'Ink Master',
 'Octonauts',
 'Oddbods',
 'Stargate SG-1',
 'The Bachelorette',
 'The Guest',
 'The Holiday Movies That Made Us',
 'The Repair Shop',
 'The Uncanny Counter',
 'Fabulous Lives of Bollywood Wives',
 'Heartbreak High',
 'Over Christmas',
 'Sugar Rush Christmas',
 'Great Pretender',
 'Valentino',
 'Strongest Deliveryman',
 'Flavorful Origins',
 'Heart & Soul',
 'Mismatched',
 'Voices of Fire',
 'Holiday Home Makeover with Mr. Christmas',
 'The Boss Baby: Back in Business',
 'We Are the Champions',
 "America's Next Top Model",
 'Beyblade Burst Rise',
 'Polly Pocket',
 'Survivor',
 'The Crown',
 'American Horror Story',
 'Ethos',
 'Graceful Friends',
 "Aunty Donna's Big Ol' House of Fun",
 'The Liberator',
 'Trial 4',
 'We Are All For The Fatherland',
 'DASH & LILY',
 'Bakugan: Armored Alliance',
 'Bakugan: Battle Planet',
 'Country Ever After',
 'Wrong Kind of Black',
 'Paranormal',
 'A Christmas Catch',
 'Love & Anarchy',
 'Ya no estoy aquí: Una conversación entre Guillermo del Toro y Alfonso Cuarón',
 'Can You Hear Me?',
 '60 Days In',
 "Dawson's Creek",
 'Forged in Fire',
 'Leah Remini: Scientology and the Aftermath',
 'LEGO Jurassic World: Legend of Isla Nublar',
 'LEGO Jurassic World: Secret Exhibit',
 'LEGO Ninjago',
 'LEGO Ninjago: Masters of Spinjitzu',
 'LEGO: CITY Adventures',
 'The Garfield Show',
 'The Good Detective',
 'Voice',
 "Zumbo's Just Desserts",
 'Kongsuni and Friends',
 "Marvel's Agents of S.H.I.E.L.D.",
 'Somebody Feed Phil',
 'Suburra: Blood on Rome',
 'Blood of Zeus',
 'Chico Bon Bon: Monkey with a Tool Belt',
 'Barbarians',
 'Stolen Away',
 "The Queen's Gambit",
 'My Next Guest Needs No Introduction With David Letterman',
 'Unsolved Mysteries',
 'Start-Up',
 'Grand Army',
 'La Révolution',
 'The Last Kids on Earth',
 'Fireman Sam',
 'Half & Half',
 'One on One',
 'Power Rangers Beast Morphers',
 'Social Distance',
 'The Cabin with Bert Kreischer',
 'Kipo and the Age of Wonderbeasts',
 'Deaf U',
 'Super Monsters: Dia de los Monsters',
 'The Haunting of Bly Manor',
 'Do Do Sol Sol La La Sol',
 'Private Lives',
 'The 100',
 'Bad Boy Billionaires: India',
 'Pat a Pat Como',
 'Qurious Como',
 'DreamWorks Happy Holidays from Madagascar',
 'Emily in Paris',
 'H2O: Just Add Water',
 'Evil',
 'Familiar Wife',
 'Food Wars!: Shokugeki no Soma',
 'Good Morning, Verônica',
 'Journey of an African Colony',
 'Oktoberfest: Beer & Blood',
 'Secreto bien guardado',
 'Sword Art Online',
 'The Parkers',
 'The Unicorn',
 'You Cannot Hide',
 'Black Butler',
 'Man with a Plan',
 'The Boys in the Band: Something Personal',
 'Wentworth',
 'Whose Vote Counts, Explained',
 'Van Helsing',
 'The Good Place',
 'A Perfect Crime',
 'Mighty Little Bheem',
 'Sneakerheads',
 'The School Nurse Files',
 'Zulu Man in Japan']

In [219]:
movies_and_directors_3 = {
    '100 Days My Prince': 'Lee Jong-jae',
    '50M2': 'Burak Aksak',
    '60 Days In': 'Gregory Henry',
    'A Christmas Catch': 'Justin G. Dyck',
    'A Love So Beautiful': 'Seo Min-jung',
    'A Perfect Crime': 'Jan Peter',
    'Alice in Borderland': 'Shinsuke Sato',
    'Alien Worlds': 'Tom Stephens',
    'Amend: The Fight for America': 'Kenny Leon',
    "America's Next Top Model": 'Ken Mok',
    'American Horror Story': 'Ryan Murphy',
    'Are You The One': 'Lighthearted Entertainment',
    "Aunty Donna's Big Ol' House of Fun": 'Max Miller',
    'BONDING': 'Rightor Doyle',
    'Bad Boy Billionaires: India': 'Dylan Mohan Gray',
    'Bakugan: Armored Alliance': 'Kazuya Ichikawa',
    'Bakugan: Battle Planet': 'Kazuya Ichikawa',
    'Barbarians': 'Barbara Eder',
    'Behind Her Eyes': 'Erik Richter Strand',
    'Best Leftovers Ever!': 'Michael Pearlman',
    'Best of Stand-Up 2020': 'Michael Pearlman',
    'Beyblade Burst Rise': 'Katsuhito Akiyama',
    'Bhaag Beanie Bhaag': 'Ishaan Nair',
    'Big Mouth': 'Nick Kroll',
    'Black Butler': 'Shinohara Toshiya',
    'Black Ink Crew New York': 'Daniel Blau Rogge',
    'Bling Empire': 'Jeff Jenkins',
    'Blood of Zeus': 'Shaunt Nigoghossian',
    'Blown Away': 'Michael Pearlman',
    'Booba': 'Nick Solovov',
    'Bridgerton': 'Julie Anne Robinson',
    'Buried by the Bernards': 'Ramy Romany',
    'Busted!': 'Cho Hyo-jin',
    'Can You Hear Me?': 'Miryam Bouchard',
    'Capitani': 'Christophe Wagner',
    'Carmen Sandiego': 'Duane Capizzi',
    "Chappelle's Show": 'Neal Brennan',
    'Check The Store Next Door: The Next Chapter': 'Sarawut Wichiensarn',
    'Chico Bon Bon: Monkey with a Tool Belt': "Darragh O'Connell",
    'Children of Adam': 'Ahmed Nader Galal',
    'Chilling Adventures of Sabrina': 'Lee Toland Krieger',
    'Cobra Kai': 'Jon Hurwitz',
    'Country Ever After': 'Michael Pearlman',
    "Creating The Queen's Gambit": 'Scott Frank',
    'DASH & LILY': 'Fred Savage',
    'Dare Me': 'Steph Green',
    'Daughter From Another Mother': 'Fernando Sariñana',
    "Dawson's Creek": 'Kevin Williamson',
    'Deaf U': 'Nyle DiMarco',
    'Demon Slayer: Kimetsu no Yaiba': 'Haruo Sotozaki',
    'Diamond City': 'Tope Oshin',
    'Disenchantment': 'Matt Groening',
    'Do Do Sol Sol La La Sol': 'Kim Min-kyung',
    'Dream Home Makeover': 'Michael Pearlman',
    'DreamWorks Happy Holidays from Madagascar': 'David Soren',
    'El Chema': 'Danny Gavidia',
    'Emicida: AmarElo - It’s All For Yesterday': 'Fred Ouro Preto',
    'Emily in Paris': 'Andrew Fleming',
    'Equinox': 'Søren Balle',
    'Ethos': 'Berkun Oya',
    'Evil': 'Robert King',
    'Fabulous Lives of Bollywood Wives': 'Uttam Domale',
    'Familiar Wife': 'Lee Sang-yob',
    'Fate: The Winx Saga - The Afterparty': 'Krysia Plonka',
    'Firefly Lane': "Peter O'Fallon",
    'Fireman Sam': 'Gary Andrews',
    'Five Came Back: The Reference Films': 'Laurent Bouzereau',
    'Flavorful Origins': 'Chen Xiaoqing',
    'Food Wars!: Shokugeki no Soma': 'Yoshitomo Yonetani',
    'Forged in Fire': 'Michael Pearlman',
    'Gormiti': 'Pascal Jardin',
    'Go Dog Go': 'Morgana Ducruz',
    'Good Girls': 'Dean Parisot',
    'Good Morning, Verônica': 'José Henrique Fonseca',
    'Graceful Friends': 'Song Hyun-wook',
    'Grand Army': 'Katie Cappiello',
    'Great Pretender': 'Hiro Kaburagi',
    'Grizzy et les Lemmings': 'Victor Moulin',
    'H2O: Just Add Water': 'Jonathan M. Shiff',
    'Hache': 'Jorge Torregrossa',
    'Half & Half': 'Jeffrey Melman',
    'Hazel Brugger: Tropical': 'Hazel Brugger',
    'Headspace Guide to Meditation': 'Arthur Jones',
    'Heart & Soul': 'Tope Oshin',
    'Heartbreak High': 'Ben Gannon',
    'Heartland': 'Dean Bennett',
    'Hello Ninja': 'Michael Dowding',
    'Hello, Me!': 'Lee Hyun-suk',
    'Henry Danger': 'Dan Schneider',
    'Hilda': 'Andy Coyle',
    'History of Swear Words': "Christopher D'Elia",
    'Holiday Home Makeover with Mr. Christmas': 'Michael Pearlman',
    'Home for Christmas': 'Per-Olav Sørensen',
    'How To Ruin Christmas': 'Johnny Barbuzano',
    'ICarly': 'Dan Schneider',
    'Ink Master': 'Dave Navarro',
    'Inside the World’s Toughest Prisons': 'David Harrison',
    'Invisible City': 'Carlos Saldanha',
    'Jenni Rivera: Mariposa de Barrio': 'Luis Manzo',
    'Journey of an African Colony': 'Olasupo Shasore',
    'Juman': 'Khaled Jamal',
    "Kings of Jo'Burg": 'Shona Ferguson',
    'Kipo and the Age of Wonderbeasts': 'Radford Sechrist',
    'Kongsuni and Friends': 'Kim Kil-tae',
    'Korean Pork Belly Rhapsody': 'Kim Jin-young',
    'La Révolution': 'Aurélien Molas',
    'Leah Remini: Scientology and the Aftermath': 'Alex Weresow',
    'LEGO Jurassic World: Legend of Isla Nublar': 'Ken Cunningham',
    'LEGO Jurassic World: Secret Exhibit': 'Andrew Duncan',
    'LEGO Ninjago': 'Tommy Andreasen',
    'LEGO Ninjago: Masters of Spinjitzu': 'Michael Hegner',
    'LEGO: CITY Adventures': 'Saxton Moore',
    'Leyla Everlasting': 'Ezel Akay',
    'Love & Anarchy': 'Lisa Langseth',
    'Love Daily': 'Michael Gallagher',
    'Lovestruck in the City': 'Park Shin-woo',
    "Ma Rainey's Black Bottom: A Legacy Brought to Screen": 'George C. Wolfe',
    'Man with a Plan': 'James Burrows',
    'Manhunt: Deadly Games': 'Michael Dinner',
    'Marvel Anime: Wolverine': 'Hiroshi Aoyama',
    'Marvel Anime: X-Men': 'Fuminori Kizaki',
    "Marvel's Agents of S.H.I.E.L.D.": 'Joss Whedon',
    'Masameer Classics': 'Malik Nejer',
    'MeatEater': 'Steven Rinella',
    'Mighty Little Bheem': 'Rajiv Chilaka',
    'Mighty Little Bheem: Kite Festival': 'Rajiv Chilaka',
    'Mismatched': 'Akarsh Khurana',
    'Monarca': 'Diego Gutierrez',
    'Morphle': 'Arthur van Merwijk',
    'Mr. Iglesias': 'Andy Ackerman',
    'My Dead Ex': 'Chris Rossi',
    'My Next Guest Needs No Introduction With David Letterman': 'Michael Steed',
    'Nadiya Bakes': 'Ben Warwick',
    'Nailed It! Mexico': 'Paul Starkman',
    'Octonauts': 'Darragh O\'Connell',
    'Oddbods': 'Richard Thomas',
    'Oktoberfest: Beer & Blood': 'Hannu Salonen',
    'Once Upon a Time': 'Mark Mylod',
    'One on One': 'Eunetta T. Boone',
    'Outlander': 'Ronald D. Moore',
    'Over Christmas': 'Tobi Baumann',
    'Pablo Escobar, el patrón del mal': 'Carlos Moreno',
    'Paranormal': 'Amr Salama',
    'Pat a Pat Como': 'Kim Ji-yoon',
    'Polly Pocket': 'Jon Izen',
    'Power Rangers Beast Morphers': 'Simon Bennett',
    'Power Rangers Ninja Steel': 'Simon Bennett',
    'Pretend It’s a City': 'Martin Scorsese',
    'Private Lives': 'Nam Gun',
    'Pup Academy': 'Anna McRoberts',
    'QB1: Beyond the Lights': 'Peter Berg',
    'Qurious Como': 'Kim Ji-yoon',
    'Regiment Diaries': 'Gaurav Shukla',
    'Rhyme Time Town Singalongs': 'Darragh O\'Connell',
    'Run On': 'Lee Jae-hoon',
    'Running Man': 'Cho Hyo-jin',
    'Sakho & Mangane': 'Jean Luc Herbulot',
    'Secreto bien guardado': 'Alberto Lecchi',
    'Shaun the Sheep': 'Christopher Sadler',
    'Sisyphus': 'Jin Hyuk',
    'Sneakerheads': 'Dave Meyers',
    'Social Distance': 'Diego Velasco',
    'Somebody Feed Phil': 'John Bedolis',
    'Song Exploder': 'Morgan Neville',
    'Spycraft': 'Garth Ancier',
    'Stargate SG-1': 'Brad Wright',
    'Start-Up': 'Oh Choong-hwan',
    'Still Game': 'Michael Hines',
    'Stolen Away': 'Iñaki Peñafiel',
    'Strongest Deliveryman': 'Jeon Woo-sung',
    'Stuck Apart': 'Yaçmır Taylan',
    'Suburra: Blood on Rome': 'Michele Placido',
    'Sugar Rush Christmas': 'Michael Pearlman',
    'Super Monsters: Dia de los Monsters': 'Dustin McKenzie',
    'Surviving Death': 'Ricki Stern',
    'Survivor': 'Charlie Parsons',
    'Sword Art Online': 'Tomohiko Itō',
    'Teen Mom 2': 'Morgan J. Freeman',
    'The 100': 'Jason Rothenberg',
    'The Bachelorette': 'Mike Fleiss',
    'The Big Show Show': 'Jason Berger',
    'The Boss Baby: Back in Business': 'Brandon Sawyer',
    'The Boys in the Band: Something Personal': 'Joe Mantello',
    'The Cabin with Bert Kreischer': 'Jeff Tomsic',
    'The Challenge': 'Jonathan Murray',
    'The Crew': 'Jeff Lowell',
    'The Crown': 'Benjamin Caron',
    'The Expanding Universe of Ashley Garcia': 'Mario Lopez',
    'The Garfield Show': 'Philippe Vidal',
    'The Good Detective': 'Jo Nam-gook',
    'The Good Place': 'Michael Schur',
    'The Great British Baking Show: Holidays': 'Andy Devonshire',
    'The Guest': 'Kim Hong-sun',
    'The Haunted Hathaways': 'Robert Peacock',
    'The Haunting of Bly Manor': 'Mike Flanagan',
    'The Holiday Movies That Made Us': 'Brian Volk-Weiss',
    'The Last Kids on Earth': 'William Lau',
    'The Liberator': 'Greg Jonkajtys',
    'The Magicians': 'Mike Cahill',
    'The Mess You Leave Behind': 'Carlos Montero',
    'The Minimalists: Less Is Now': 'Matt D\'Avella',
    'The Netflix Afterparty: The Best Shows of The Worst Year': 'Krysia Plonka',
    'The Parkers': 'Sara Finney-Johnson',
    "The Queen's Gambit": 'Scott Frank',
    'The Repair Shop': 'Rob Butterfield',
    'The School Nurse Files': 'Lee Kyoung-mi',
    'The Sinner': 'Antonio Campos',
    "The Surgeon's Cut": 'James Newton',
    'The Uncanny Counter': 'Yoo Sun-dong',
    'The Unicorn': 'Bill Martin',
    'The Unsettling': 'Andrew Fleming',
    'Thus Spoke Kishibe Rohan': 'Toshiyuki Kato',
    'Tiffany Haddish Presents: They Ready': 'Marcus Raboy',
    'Timmy Time': 'David Scanlon',
    'Tiny Pretty Things': 'Gary Fleder',
    'Total Drama': 'Tom McGillis',
    'Transformers: War for Cybertron: Earthrise': 'Takashi Kamei',
    'Tribes of Europa': 'Philip Koch',
    'Trial 4': 'Rémy Burkel',
    'Unsolved Mysteries': 'Marcus A. Clarke',
    'Valentino': 'Alejandro Lozano',
    'Van Helsing': 'Michael Nankin',
    'Vincenzo': 'Kim Hee-won',
    'Voice': 'Kim Hong-sun',
    'Voices of Fire': 'Pharrell Williams',
    'We Are All For The Fatherland': 'Gaurav Shukla',
    'We Are the Champions': 'Brian Golden Davis',
    'We Are: The Brooklyn Saints': 'Rudy Valdez',
    'Wentworth': 'Kevin Carlin',
    'Whose Vote Counts, Explained': 'Trish Lipman',
    'Wrong Kind of Black': 'Catriona McKenzie',
    'Ya no estoy aquí: Una conversación entre Guillermo del Toro y Alfonso Cuarón': 'Guillermo del Toro',
    'You Cannot Hide': 'Alejandro Lozano',
    'Zac and Mia': 'Jason Perlman',
    'Zig & Sharko': 'Olivier Jean-Marie',
    "Zumbo's Just Desserts": 'Evan Wilkes',
    'Zulu Man in Japan': 'Nasty C'}

In [220]:
df['director'] = df['director'].fillna(df['title'].map(movies_and_directors_3))
remaining_nulls = df['director'].isnull().sum()
print(f"Remaining null values in director column: {remaining_nulls}")

Remaining null values in director column: 2000

In [221]:
na_directors_titles_4 = missing_directors_title[639:839]
na_directors_titles_4

['The Chef Show',
 'The Playbook',
 'Fukrey Boyzzz',
 'Ratched',
 'The American Barbecue Showdown',
 'The Blacklist',
 "Dragon's Dogma",
 'The Last Word',
 'Baby',
 'Challenger',
 'Criminal: UK',
 'Signs',
 'Sing On!',
 'Taco Chronicles',
 'Buddi',
 'Family Business',
 'Girlfriends',
 'The Barrier',
 'The Duchess',
 'Greenleaf',
 'Get Organized with The Home Edit',
 'Record of Youth',
 'Transformers: Cyberverse',
 'Cleverman',
 'Away',
 'Spirit Riding Free: Riding Academy',
 'Young Wallander',
 "Chef's Table: BBQ",
 'The Witcher: A Look Inside the Episodes',
 'Blue Exorcist',
 'Bookmarks',
 'Borgen',
 'Erased',
 'Felipe Esparza: Bad Decisions',
 'H',
 'Heidi',
 'Sister, Sister',
 'The Promised Neverland',
 'I AM A KILLER: RELEASED',
 'Masaba Masaba',
 'Aggretsuko',
 "Her Mother's Killer",
 'Million Dollar Beach House',
 'Rising Phoenix',
 "Emily's Wonder Lab",
 'Trinkets',
 'Baewatch: Parental Guidance',
 "Ojos in d' House",
 'Hoops',
 'Rust Valley Restorers',
 'John Was Trying to Contact Aliens',
 'DeMarcus Family Rules',
 'High Score',
 'Glitch Techs',
 'Stranger',
 'Dérè: An African Tale',
 'Rita',
 'Takki',
 '3%',
 'Teenage Bounty Hunters',
 'The Great Heist',
 'The Legend of Korra',
 'Zoids Wild',
 '(Un)Well',
 'GAME ON: A Comedy Crossover Event',
 'Terrace House: Tokyo 2019-2020',
 'The Governor',
 'High Seas',
 'Selling Sunset',
 'Sing On! Germany',
 'Tiny Creatures',
 'Wizards: Tales of Arcadia',
 'Word Party Songs',
 'Ever After High',
 'The Rain',
 "World's Most Wanted",
 'Mystery Lab',
 'Immigration Nation',
 'Moesha',
 'My Perfect Landing',
 'Nagi-Asu: A Lull in the Sea',
 'The Next Step',
 'Toradora!',
 'Transformers Rescue Bots Academy',
 'Get Even',
 'Sugar Rush',
 'The Umbrella Academy',
 'Transformers: War For Cybertron Trilogy',
 'Last Chance U',
 'Shameless (U.S.)',
 'Sing On! Spain',
 'Fear City: New York vs The Mafia',
 'Norsemen',
 'Street Food: Latin America',
 'Killer Women with Piers Morgan',
 'Gigantosaurus',
 'Single Wives',
 'Cursed',
 'In The Dark',
 'Kissing Game',
 'Dark Desire',
 'Little Singham: Legend of Dugabakka',
 'Skin Decision: Before and After',
 'Sunny Bunnies',
 'The Business of Drugs',
 'Down to Earth with Zac Efron',
 'The Epic Tales of Captain Underpants in Space',
 'Japan Sinks: 2020',
 'The Protector',
 'Was It Love?',
 'Stateless',
 'Little Singham',
 'Cable Girls',
 'JU-ON: Origins',
 'Southern Survival',
 'The Baby-Sitters Club',
 'Supermarket Sweep',
 'Warrior Nun',
 '21 Again',
 'A Touch of Green',
 'Say I Do',
 'Trotro',
 'BNA',
 'Homemade',
 'Dark',
 'All For Love',
 'Home Game',
 'Seven (Tamil)',
 'Seven (Telugu)',
 'Twogether',
 'Crazy Delicious',
 'Roswell, New Mexico',
 "It's Okay to Not Be Okay",
 'Babies',
 'Disclosure',
 'Floor Is Lava',
 'Most Beautiful Thing',
 'The Politician',
 'The Order',
 'The Chase',
 'The Show Must Go On: The Queen + Adam Lambert Story',
 'Alexa & Katie',
 'How to Get Away with Murder',
 'Dating Around',
 'F is for Family',
 'Frank Elstner: Just One Last Question',
 'ONE PIECE',
 'The Search',
 'The Woods',
 'Curon',
 'Lenox Hill',
 'My Mister',
 'Reality Z',
 'Queen of the South',
 '13 Reasons Why',
 'Queer Eye',
 'The Light of My Eyes',
 'BAKI',
 'Alone',
 'True: Rainbow Rescue',
 'Cardcaptor Sakura',
 'Dear My Friends',
 'Megalobox',
 'Midnight Diner',
 'My Shy Boss',
 'Revolutionary Love',
 'Space Force',
 "Can't Cope, Won't Cope",
 'Dorohedoro',
 'Mako Mermaids: An H2O Adventure',
 'Betaal',
 'Dynasty',
 'History 101',
 'Mystic Pop-up Bar',
 'Especial 20 años Fútbol de Primera',
 'The Queen and the Conqueror',
 'Sweet Magnolias',
 'The Big Flower Fight',
 'Patriot Act with Hasan Minhaj',
 'Boys Over Flowers',
 'Iris',
 'Avatar: The Last Airbender',
 'Madam Secretary',
 'Magic for Humans',
 'Parasyte: The Maxim',
 'She-Ra and the Princesses of Power',
 'Strangers from Hell',
 'The Wiggles',
 'White Lines',
 'True: Terrific Tales',
 'Bordertown',
 'Trial By Media',
 'Dead to Me',
 'Restaurants on the Edge',
 'The Hollow',
 'Hangar 1: The UFO Files',
 'Hoarders',
 'The Universe: Ancient Mysteries Solved',
 'WWII in HD',
 'Hollywood']

In [222]:
movies_and_directors_4 = {
    '(Un)Well': 'Ken Druckerman',
    '13 Reasons Why': 'Brian Yorkey',
    '21 Again': 'Gaby Koppel',
    '3%': 'César Charlone',
    'A Touch of Green': 'Tsao Jui-yuan',
    'Alexa & Katie': 'Heather Wordham',
    'All For Love': 'Liliana Bocanegra',
    'Alone': 'Michael Gara',
    'Avatar: The Last Airbender': 'Michael Dante DiMartino',
    'Away': 'Andrew Hinderaker',
    'BAKI': 'Toshiki Hirano',
    'Baby': 'Andrea De Sica',
    'Baewatch: Parental Guidance': 'Dan Adamson',
    'Betaal': 'Patrick Graham',
    'Blue Exorcist': 'Tensai Okamura',
    'Bookmarks': 'Fracaswell Hyman',
    'Borgen': 'Adam Price',
    'Bordertown': 'Miikko Oikkonen',
    'Boys Over Flowers': 'Jeon Ki-sang',
    'Buddi': 'Jason Jameson',
    'Cable Girls': 'Ramón Campos',
    'Cardcaptor Sakura': 'Morio Asaka',
    'Challenger': 'Daniel Junge',
    "Chef's Table: BBQ": 'David Gelb',
    'Cleverman': 'Ryan Griffen',
    'Cursed': 'Frank Miller',
    'Crazy Delicious': 'Rebecca Taylor',
    'Criminal: UK': 'Jim Field Smith',
    'Curon': 'Fabio Mollo',
    'Dark': 'Baran bo Odar',
    'Dark Desire': 'Kenya Marquez',
    'Dating Around': 'Chris Culvenor',
    'DeMarcus Family Rules': 'John Feldmann',
    'Dead to Me': 'Liz Feldman',
    'Dear My Friends': 'Hong Jong-chan',
    'Dérè: An African Tale': 'Bodunrin Sasore',
    'Disclosure': 'Sam Feder',
    'Down to Earth with Zac Efron': 'Zac Efron',
    "Dragon's Dogma": 'Shinya Sugai',
    'Dynasty': 'Sallie Patrick',
    "Emily's Wonder Lab": 'Emily Calandrelli',
    'Especial 20 años Fútbol de Primera': 'Marcelo Araujo',
    'Erased': 'Tomohiko Itō',
    'Ever After High': 'Audu Paden',
    'F is for Family': 'Bill Burr',
    'Family Business': 'Igor Gotesman',
    'Fear City: New York vs The Mafia': 'Sam Hobkinson',
    'Felipe Esparza: Bad Decisions': 'Nate Bargatze',
    'Floor Is Lava': 'Irad Eyal',
    'Frank Elstner: Just One Last Question': 'Frank Elstner',
    'Fukrey Boyzzz': 'Avinash Walzade',
    'GAME ON: A Comedy Crossover Event': 'Bob Koherr',
    'Get Even': 'Sarah Walker',
    'Get Organized with The Home Edit': 'Michael Pearlman',
    'Gigantosaurus': 'Olivier Lelardoux',
    'Girlfriends': 'Kay Mellor',
    'Glitch Techs': 'Eric Robles',
    'Greenleaf': 'Craig Wright',
    'H': 'Franck Magnier',
    'Hangar 1: The UFO Files': 'Douglas Cohen',
    'Heidi': 'Alain Gsponer',
    "Her Mother's Killer": 'Liliana Bocanegra',
    'High Score': 'France Costrel',
    'High Seas': 'Ramón Campos',
    'Hoarders': 'Dave J. Foster',
    'Hollywood': 'Ryan Murphy',
    'Home Game': 'Andrew Fried',
    'Homemade': 'Pablo Larraín',
    'Hoops': 'Ben Hoffman',
    'How to Get Away with Murder': 'Peter Nowalk',
    'I AM A KILLER: RELEASED': 'Ned Parker',
    'Immigration Nation': 'Christina Clusiau',
    'In The Dark': 'Gilles Paquet-Brenner',
    'Iris': 'Kim Kyu-tae',
    "It's Okay to Not Be Okay": 'Park Shin-woo',
    'JU-ON: Origins': 'Sho Miyake',
    'Japan Sinks: 2020': 'Masaaki Yuasa',
    'John Was Trying to Contact Aliens': 'Matthew Killip',
    'Killer Women with Piers Morgan': 'James Cohen',
    'Kissing Game': 'Esmir Filho',
    'Last Chance U': 'Greg Whiteley',
    'Lenox Hill': 'Ruthie Shatz',
    'Little Singham': 'Rajiv Chilaka',
    'Little Singham: Legend of Dugabakka': 'Rajiv Chilaka',
    'Madam Secretary': 'Barbara Hall',
    'Magic for Humans': 'Justin Willman',
    'Mako Mermaids: An H2O Adventure': 'Jonathan M. Shiff',
    'Masaba Masaba': 'Sonarika Bhadoria',
    'Megalobox': 'Yō Moriyama',
    'Midnight Diner': 'Joji Matsuoka',
    'Million Dollar Beach House': 'Nick Solovov',
    'Moesha': 'Sara Finney-Johnson',
    'Most Beautiful Thing': 'Giuliano Cedroni',
    'My Mister': 'Kim Won-seok',
    'My Perfect Landing': 'Frank van Keeken',
    'My Shy Boss': 'Song Hyun-wook',
    'Mystery Lab': 'Felipe Castanhari',
    'Nagi-Asu: A Lull in the Sea': 'Toshiya Shinohara',
    'Nadiya Bakes': 'Ben Warwick',
    'Norsemen': 'Jon Iver Helgaker',
    'ONE PIECE': 'Eiichiro Oda',
    "Ojos in d' House": 'Ojos de Brujo',
    'Parasyte: The Maxim': 'Kenichi Shimizu',
    'Patriot Act with Hasan Minhaj': 'Hasan Minhaj',
    'Queen of the South': 'M.A. Fortin',
    'Queer Eye': 'David Collins',
    'Ratched': 'Ryan Murphy',
    'Reality Z': 'Claudio Torres',
    'Record of Youth': 'Ahn Gil-ho',
    'Restaurants on the Edge': 'Michael Pearlman',
    'Revolutionary Love': 'Song Hyun-wook',
    'Rising Phoenix': 'Ian Bonhôte',
    'Rita': 'Christian Torpe',
    'Roswell, New Mexico': 'Carina Adly MacKenzie',
    'Rust Valley Restorers': 'Matt Shewchuk',
    'Say I Do': 'David Collins',
    'Selling Sunset': 'Adam DiVello',
    'Seven (Tamil)': 'Nizar Shafi',
    'Seven (Telugu)': 'Nizar Shafi',
    'Shameless (U.S.)': 'John Wells',
    'She-Ra and the Princesses of Power': 'ND Stevenson',
    'Signs': 'Jakub Miszczak',
    'Sing On!': 'Tituss Burgess',
    'Sing On! Germany': 'Palina Rojinski',
    'Sing On! Spain': 'Emma García',
    'Sister, Sister': 'Kim Bass',
    'Skin Decision: Before and After': 'Michael Pearlman',
    'Southern Survival': 'Ramy Romany',
    'Space Force': 'Greg Daniels',
    'Spirit Riding Free: Riding Academy': 'Josh Taback',
    'Stranger': 'Ahn Gil-ho',
    'Strangers from Hell': 'Lee Chang-hee',
    'Street Food: Latin America': 'David Gelb',
    'Sugar Rush': 'David Collins',
    'Sunny Bunnies': 'Andrew Ledenev',
    'Supermarket Sweep': 'Al De吸ro',
    'Sweet Magnolias': 'Sheryl J. Anderson',
    'Taco Chronicles': 'Pablo Cruz',
    'Takki': 'Mohammad Makki',
    'Teenage Bounty Hunters': 'Kathleen Jordan',
    'Terrace House: Tokyo 2019-2020': 'Masato Maeda',
    'The American Barbecue Showdown': 'Joe Guidry',
    'The Baby-Sitters Club': 'Rachel Shukert',
    'The Barrier': 'Daniel Écija',
    'The Blacklist': 'Jon Bokenkamp',
    'The Business of Drugs': 'Rachel Shukert',
    'The Chase': 'Michael Kelpie',
    'The Chef Show': 'Jon Favreau',
    'The Duchess': 'Katherine Ryan',
    'The Epic Tales of Captain Underpants in Space': 'Todd Grimes',
    'The Governor': 'Biyi Bandele',
    'The Great Heist': 'Pablo González',
    'The Hollow': 'Vito Viscomi',
    'The Last Word': 'Aron Lehmann',
    'The Legend of Korra': 'Michael Dante DiMartino',
    'The Next Step': 'Frank van Keeken',
    'The Order': 'Dennis Heaton',
    'The Playbook': 'Jason Hehir',
    'The Politician': 'Ryan Murphy',
    'The Promised Neverland': 'Mamoru Kanbe',
    'The Protector': 'Binnur Karaevli',
    'The Rain': 'Jannik Tai Mosholt',
    'The Search': 'Alejandro Lozano',
    'The Show Must Go On: The Queen + Adam Lambert Story': 'Christopher Bird',
    'The Umbrella Academy': 'Steve Blackman',
    'The Universe: Ancient Mysteries Solved': 'Douglas Cohen',
    'The Wiggles': 'Anthony Field',
    'The Witcher: A Look Inside the Episodes': 'Lauren Schmidt Hissrich',
    'The Woods': 'Leszek Dawid',
    'Tiny Creatures': 'Jonathan Jones',
    'Toradora!': 'Tatsuyuki Nagai',
    'Transformers Rescue Bots Academy': 'Leo Murphy',
    'Transformers: Cyberverse': 'Ehren Ehren',
    'Transformers: War For Cybertron Trilogy': 'Takashi Kamei',
    'Trinkets': 'Amy Andelson',
    'Trotro': 'Eric Cazes',
    'Twogether': 'Cho Hyo-jin',
    'WWII in HD': 'Frederic Lumiere',
    'Warrior Nun': 'Simon Barry',
    'Was It Love?': 'Kim Do-hyung',
    'White Lines': 'Álex Pina',
    'Wizards: Tales of Arcadia': 'Guillermo del Toro',
    'Word Party Songs': 'Alex Rockwell',
    "World's Most Wanted": 'Thomas Robbins',
    'Young Wallander': 'Ole Endresen',
    'Zoids Wild': 'Norihiko Sutou'
}

In [223]:
df['director'] = df['director'].fillna(df['title'].map(movies_and_directors_4))
remaining_nulls = df['director'].isnull().sum()
print(f"Remaining null values in director column: {remaining_nulls}")

Remaining null values in director column: 1815

In [224]:
na_directors_titles_5 = missing_directors_title[839:1054]
na_directors_titles_5

['Masha and the Bear',
 'Medici: Masters of Florence',
 "Monthly Girls' Nozaki Kun",
 'Oh Yuck',
 'Reckoning',
 'DRIFTING DRAGONS',
 'El señor de los Cielos',
 'Good Witch',
 'Extracurricular',
 'Murder to Mercy: The Cyntoia Brown Story',
 'Nadiya’s Time to Eat',
 'Tjovitjo',
 'Coronavirus, Explained',
 'The Last Kingdom',
 'My Secret Romance',
 'دفعة القاهرة',
 'After Life',
 'DreamWorks Spooky Stories: Volume 2',
 'Love 101',
 'Ghost in the Shell: SAC_2045',
 'The House of Flowers',
 'Absurd Planet',
 'Win the Wilderness',
 'Bleach',
 'Nicky Jam: El Ganador',
 'Cooked with Cannabis',
 'The Midnight Gospel',
 'ChuChu TV Nursery Rhymes & Kids Songs (Hindi)',
 'The King: Eternal Monarch',
 '#blackAF',
 'El Dragón: Return of a Warrior',
 'Hasmukh',
 'Fauda',
 'The Innocence Files',
 'Surviving R. Kelly: The Impact',
 'Brews Brothers',
 'LA Originals',
 'Hi Score Girl',
 'The Circle France',
 'El Reemplazante',
 'Legacies',
 'Community',
 'How to Fix a Drug Scandal',
 'Man Like Mobeen',
 'Pokémon the Series',
 'Saint Seiya',
 "Sunderland 'Til I Die",
 'The Iliza Shlesinger Sketch Show',
 'The Windsors',
 'Well-Intended Love',
 'Akbar\xa0Birbal',
 'Dave Chappelle: The Kennedy Center Mark Twain Prize for American Humor',
 'Tree House Tales',
 'Rugal',
 'Happy!',
 'Ladies Up',
 'Ozark',
 'Wassup Man GO!',
 '7SEEDS',
 'Unorthodox',
 'Crip Camp: A Disability Revolution',
 'Freud',
 'J-Style Trip',
 'Barbie Dreamhouse Adventures: Go Team Roberts',
 "Archibald's Next Big Thing",
 'Dino Girl Gauko',
 'Greenhouse Academy',
 'Self Made: Inspired by the Life of Madam C.J. Walker',
 'She',
 'The English Game',
 'The Letter for the King',
 'Vampires',
 'Caliphate',
 'Women Of The Night',
 'Shaun the Sheep: Adventures from Mossy Bottom',
 'We Speak Dance',
 '100 Humans',
 'Bloodride',
 'The Valhalla Murders',
 'Dirty Money',
 'On My Block',
 'The Circle Brazil',
 'Ugly Delicious',
 'Mighty Little Bheem: Festival of Colors',
 'Akame ga Kill!',
 'Babylon Berlin',
 'Calico Critters Mini Episodes Clover',
 'Always a Witch',
 'Amit Tandon: Family Tandoncies',
 'Queen Sono',
 'Toy Boy',
 'Unstoppable',
 'Altered Carbon',
 'Followers',
 'I Am Not Okay With This',
 'The Trials of Gabriel Fernandez',
 'Hi Bye, Mama!',
 'Gentefied',
 'Hyena',
 'Passion. Panache. Pep',
 'Puerta 7',
 'Spectros',
 "DreamWorks Shrek's Swamp Stories",
 'Talking Tom and Friends',
 'Taj Mahal 1989',
 'Love Is Blind',
 'Narcos: Mexico',
 'Palazuelos mi rey',
 'We Bare Bears',
 'Captain Underpants Epic Choice-o-Rama',
 'Better Call Saul',
 'Dragons: Rescue Riders',
 'Fifty: The Series',
 'Locke & Key',
 'My Holo Love',
 'Who Killed Malcolm X?',
 'Cagaster of an Insect Cage',
 'Team Kaylie',
 'Is It Wrong to Try to Pick Up Girls in a Dungeon?',
 'Itaewon Class',
 'Night on Earth: Shot in the Dark',
 'No Game No Life',
 'Pop Team Epic',
 'Shopkins',
 'Diablero',
 'Luna Nera',
 'Unauthorized Living',
 'Ainori Love Wagon: African Journey',
 'THE STRANGER',
 'What the Love! with Karan Johar',
 'Find Yourself',
 'Night on Earth',
 'Omniscient',
 'Rise of Empires: Ottoman',
 'Sons of the Caliphate',
 'The goop lab with Gwyneth Paltrow',
 'The Ranch',
 'October Faction',
 '\u200bSAINT SEIYA: Knights of the Zodiac',
 'Pandemic: How to Prevent an Outbreak',
 'Playing with Fire',
 'DreamWorks How to Train Your Dragon Legends',
 'Ares',
 'Hip-Hop Evolution',
 'Nailed It! Germany',
 'Tiny House Nation',
 'Handsome Siblings',
 'Soul Eater',
 'Killer Inside: The Mind of Aaron Hernandez',
 'The Ollie & Moon Show',
 'The Healing Powers of Dude',
 'AJ and the Queen',
 'Giri / Haji',
 'Harvey Street Kids',
 'Medical Police',
 'The InBESTigators',
 'Until Dawn',
 'Cheer',
 'Dracula',
 'Anne with an E',
 'Sex, Explained',
 'Thieves of the Wood',
 'Because This Is My First Life',
 "Border Security: America's Front Line",
 'Cells at Work!',
 'Chhota Bheem Kung Fu Dhamaka Series',
 'Live Up To Your Name',
 'Messiah',
 'Mia and Me',
 'Reply 1988',
 'Save Me',
 'Spinning Out',
 'The Bride of Habaek',
 "ARASHI's Diary -Voyage-",
 'Occupied',
 'Pucca: Love Recipe',
 'Rainbow Ruby',
 'Robot Trains',
 'The Degenerates',
 'Yanxi Palace: Princess Adventures',
 'The Disastrous Life of Saiki K.: Reawakened',
 'Kevin Hart: Don’t F**k This Up',
 'The Bonfire of Destiny',
 'CAROLE & TUESDAY',
 'Lost in Space',
 'Private Practice',
 'Agent',
 'The Witcher',
 'Twice Upon A Time',
 'Ultraviolet',
 'Soundtrack',
 'Cinderella and the Four Knights',
 'Cocomong',
 'Crash Landing on You',
 'Scooby-Doo!: Mystery Incorporated',
 "What's New Scooby-Doo?",
 'Astronomy Club: The Sketch Show',
 'Fuller House',
 'Spirit Riding Free: Spirit of Christmas',
 'Teasing Master Takagi-san',
 'Three Days of Christmas',
 'Triad Princess',
 'The Irishman: In Conversation',
 'V Wars',
 'The Last O.G.',
 'The Prince of Tennis ~ Match! Tennis Juniors ~',
 'The Road to Love',
 'Nightflyers',
 'Eastsiders',
 'Lakeeran',
 'Space Jungle',
 'Chocolate',
 'Chip and Potato',
 'La Reina del Sur',
 'The Charming Stepmom']

In [225]:
movies_and_directors_5 = {
    '#blackAF': 'Kenya Barris',
    '100 Humans': 'Rupert Smith',
    '7SEEDS': 'Yukio Takahashi',
    'ARASHI\'s Diary -Voyage-': 'Yōko Kashiwagi',
    'AJ and the Queen': 'Michael Patrick King',
    'Absurd Planet': 'Hugh Heckman',
    'After Life': 'Ricky Gervais',
    'Agent': 'Ariyan A. Johnson',
    'Ainori Love Wagon: African Journey': 'Masato Maeda',
    'Akame ga Kill!': 'Tomoki Kobayashi',
    'Akbar\xa0Birbal': 'Sanjeev Sharma',
    'Always a Witch': 'Liliana Bocanegra',
    'Altered Carbon': 'Alex Graves',
    'Amit Tandon: Family Tandoncies': 'Amit Tandon',
    'Anne with an E': 'Helen Shaver',
    'Ares': 'Giancarlo Sanchez',
    'Astronomy Club: The Sketch Show': 'J.J. Adler',
    'Babylon Berlin': 'Tom Tykwer',
    'Barbie Dreamhouse Adventures: Go Team Roberts': 'Patrice Berube',
    'Because This Is My First Life': 'Park Joon-hwa',
    'Better Call Saul': 'Vince Gilligan',
    'Bleach': 'Noriyuki Abe',
    'Bloodride': 'Atle Knudsen',
    'Border Security: America\'s Front Line': 'Danny Field',
    'Brews Brothers': 'Greg Schaffer',
    'CAROLE & TUESDAY': 'Shinichirō Watanabe',
    'Cagaster of an Insect Cage': 'Koichi Chigira',
    'Calico Critters Mini Episodes Clover': 'Invasion',
    'Caliphate': 'Goran Kapetanović',
    'Captain Underpants Epic Choice-o-Rama': 'Todd Grimes',
    'Cells at Work!': 'Kenichi Suzuki',
    'Cheer': 'Greg Whiteley',
    'Chhota Bheem Kung Fu Dhamaka Series': 'Rajiv Chilaka',
    'Chip and Potato': 'Jayson Thiessen',
    'Chocolate': 'Lee Hyung-min',
    'ChuChu TV Nursery Rhymes & Kids Songs (Hindi)': 'Vinoth Chandar',
    'Cinderella and the Four Knights': 'Kwon Hyuk-chan',
    'Cocomong': 'Min-sung Kim',
    'Community': 'Joe Russo',
    'Cooked with Cannabis': 'Michael Pearlman',
    'Coronavirus, Explained': 'Trish Lipman',
    'Crash Landing on You': 'Lee Jung-hyo',
    'Crip Camp: A Disability Revolution': 'Nicole Newnham',
    'Dave Chappelle: The Kennedy Center Mark Twain Prize for American Humor': 'Chris Robinson',
    'Diablero': 'J.M. Cravioto',
    'Dino Girl Gauko': 'Akira Shigino',
    'Dirty Money': 'Alex Gibney',
    'Dracula': 'Jonny Campbell',
    'Dragons: Rescue Riders': 'Greg Rankin',
    'DreamWorks How to Train Your Dragon Legends': 'John Sanford',
    'DreamWorks Shrek\'s Swamp Stories': 'Tom Owens',
    'DreamWorks Spooky Stories: Volume 2': 'Tom Owens',
    'Eastsiders': 'Kit Williamson',
    'El Dragón: Return of a Warrior': 'Carlos Cock Marín',
    'El Reemplazante': 'Nicolás Acuña',
    'El señor de los Cielos': 'Danny Gavidia',
    'Extracurricular': 'Kim Jin-min',
    'Fauda': 'Assaf Bernstein',
    'Fifty: The Series': 'Tope Oshin',
    'Find Yourself': 'Ding Zi-guang',
    'Followers': 'Mika Ninagawa',
    'Freud': 'Marvin Kren',
    'Fuller House': 'Rich Correll',
    'Gentefied': 'Marvin Lemus',
    'Ghost in the Shell: SAC_2045': 'Kenji Kamiyama',
    'Giri / Haji': 'Julian Farino',
    'Good Witch': 'Craig Pryce',
    'Greenhouse Academy': 'Roee Florentin',
    'Handsome Siblings': 'Zou Jicheng',
    'Happy!': 'Brian Taylor',
    'Harvey Street Kids': 'Brendan Hay',
    'Hasmukh': 'Amritpal Singh Bindra',
    'Hi Bye, Mama!': 'Yoo Je-won',
    'Hi Score Girl': 'Yoshiki Yamakawa',
    'Hip-Hop Evolution': 'Darby Wheeler',
    'How to Fix a Drug Scandal': 'Erin Lee Carr',
    'Hyena': 'Jang Tae-yoo',
    'I Am Not Okay With This': 'Jonathan Entwistle',
    'Is It Wrong to Try to Pick Up Girls in a Dungeon?': 'Yoshiki Yamakawa',
    'Itaewon Class': 'Kim Sung-yoon',
    'J-Style Trip': 'Jay Chou',
    'Kevin Hart: Don’t F**k This Up': 'Luke Kelly-Clyne',
    'Killer Inside: The Mind of Aaron Hernandez': 'Geno McDermott',
    'LA Originals': 'Estevan Oriol',
    'La Reina del Sur': 'Walter Doehner',
    'Ladies Up': 'Karan Mady',
    'Lakeeran': 'Bhupinder Sayan',
    'Legacies': 'Chris Grismer',
    'Live Up To Your Name': 'Hong Jong-chan',
    'Locke & Key': 'Michael Morris',
    'Lost in Space': 'Tim Southam',
    'Love 101': 'Ahmet Katıksız',
    'Love Is Blind': 'Chris Coelen',
    'Luna Nera': 'Francesca Comencini',
    'Man Like Mobeen': 'Ollie Parsons',
    'Masha and the Bear': 'Oleg Kuzovkov',
    'Medical Police': 'David Wain',
    'Medici: Masters of Florence': 'Sergio Mimica-Gezzan',
    'Messiah': 'James McTeigue',
    'Mia and Me': 'Gerhard Hahn',
    'Mighty Little Bheem: Festival of Colors': 'Rajiv Chilaka',
    'Monthly Girls\' Nozaki Kun': 'Mitsue Yamazaki',
    'Murder to Mercy: The Cyntoia Brown Story': 'Daniel H. Birman',
    'My Holo Love': 'Lee Sang-yeob',
    'My Secret Romance': 'Kang Cheol-woo',
    'Nadiya’s Time to Eat': 'Ben Warwick',
    'Nailed It! Germany': 'Paul Starkman',
    'Narcos: Mexico': 'Andrés Baiz',
    'Night on Earth': 'Peter Fison',
    'Night on Earth: Shot in the Dark': 'Peter Fison',
    'Nightflyers': 'Andrew McCarthy',
    'Nicky Jam: El Ganador': 'Jessy Terrero',
    'No Game No Life': 'Atsuko Ishizuka',
    'Occupied': 'Erik Skjoldbjærg',
    'October Faction': 'Damian Kindler',
    'Oh Yuck': 'Ryan Polito',
    'Omniscient': 'Pedro Aguilera',
    'On My Block': 'Lauren Iungerich',
    'Ozark': 'Jason Bateman',
    'Palazuelos mi rey': 'Roberto Palazuelos',
    'Pandemic: How to Prevent an Outbreak': 'Doug Shultz',
    'Passion. Panache. Pep': 'Tope Oshin',
    'Playing with Fire': 'Andy Fickman',
    'Pop Team Epic': 'Jun Aoki',
    'Pucca: Love Recipe': 'Ahn Byoung-wook',
    'Puerta 7': 'Israel Adrián Caetano',
    'Private Practice': 'Mark Tinker',
    'Pokémon the Series': 'Kunihiko Yuyama',
    'Queen Sono': 'Kagiso Lediga',
    'Rainbow Ruby': 'Trevor Wall',
    'Reckoning': 'Shawn Seet',
    'Reply 1988': 'Shin Won-ho',
    'Rise of Empires: Ottoman': 'Emre Şahin',
    'Robot Trains': 'Han Dong-woo',
    'Rugal': 'Kang Cheol-woo',
    'SAINT SEIYA: Knights of the Zodiac': 'Yoshiharu Ashino',
    'Saint Seiya': 'Kōzō Morishita',
    'Save Me': 'Kim Sung-soo',
    'Scooby-Doo!: Mystery Incorporated': 'Victor Cook',
    'Self Made: Inspired by the Life of Madam C.J. Walker': 'DeMane Davis',
    'Sex, Explained': 'Trish Lipman',
    'Shaun the Sheep: Adventures from Mossy Bottom': 'Christopher Sadler',
    'She': 'Arif Ali',
    'Shopkins': 'Invasion',
    'Sons of the Caliphate': 'Kenneth Gyang',
    'Soul Eater': 'Takuya Igarashi',
    'Space Jungle': 'Han Dong-woo',
    'Spinning Out': 'Samantha Stratton',
    'Spirit Riding Free: Spirit of Christmas': 'Josh Taback',
    'Sunderland \'Til I Die': 'Spiro Curtis',
    'Surviving R. Kelly: The Impact': 'dream hampton',
    'THE STRANGER': 'Daniel Nettheim',
    'Taj Mahal 1989': 'Pushpendra Nath Misra',
    'Talking Tom and Friends': 'Stefan Fjeldmark',
    'Team Kaylie': 'Bob Koherr',
    'Teasing Master Takagi-san': 'Hiroaki Akagi',
    'The Bonfire of Destiny': 'Alexandre Laurent',
    'The Bride of Habaek': 'Kim Byung-soo',
    'The Charming Stepmom': 'Peerapol Kirdjareun',
    'The Circle France': 'Sam Strauss',
    'The Circle Brazil': 'Sam Strauss',
    'The Degenerates': 'Michael Pearlman',
    'The Disastrous Life of Saiki K.: Reawakened': 'Hiroaki Sakurai',
    'The English Game': 'Birgitte Stærmose',
    'The Healing Powers of Dude': 'Richie Keen',
    'The House of Flowers': 'Manolo Caro',
    'The Iliza Shlesinger Sketch Show': 'Laura Murphy',
    'The InBESTigators': 'Wayne Hope',
    'The Innocence Files': 'Liz Garbus',
    'The Irishman: In Conversation': 'Martin Scorsese',
    'The King: Eternal Monarch': 'Baek Sang-hoon',
    'The Last Kingdom': 'Peter Hoar',
    'The Last O.G.': 'Jorma Taccone',
    'The Letter for the King': 'Alex Holmes',
    'The Midnight Gospel': 'Pendleton Ward',
    'The Ollie & Moon Show': 'Florian Thouret',
    'The Playbook': 'Jason Hehir',
    'The Prince of Tennis ~ Match! Tennis Juniors ~': 'Benny Lau',
    'The Ranch': 'David Trainer',
    'The Road to Love': 'Andrés Marroquín',
    'The Trials of Gabriel Fernandez': 'Brian Knappenberger',
    'The Valhalla Murders': 'Thordur Palsson',
    'The Windsors': 'Adam Miller',
    'The Witcher': 'Stephen Surjik',
    'The goop lab with Gwyneth Paltrow': 'Rhonda Vigeant',
    'Thieves of the Wood': 'Maarten Moerkerke',
    'Three Days of Christmas': 'Pau Freixas',
    'Tiny House Nation': 'Michael Pearlman',
    'Tjovitjo': 'Vincent Moloi',
    'Toy Boy': 'Iñaki Mercero',
    'Triad Princess': 'Neal Wu',
    'Twice Upon A Time': 'Guillaume Nicloux',
    'Ugly Delicious': 'Eddie Schmidt',
    'Ultraviolet': 'Jan Komaser',
    'Unauthorized Living': 'Marc Vigil',
    'Unorthodox': 'Maria Schrader',
    'Unstoppable': 'Oliver Blackburn',
    'V Wars': 'Brad Turner',
    'Vampires': 'Benjamin Dupas',
    'Wassup Man GO!': 'Park Joon-hyung',
    'We Bare Bears': 'Daniel Chong',
    'We Speak Dance': 'Brian Becker',
    'Well-Intended Love': 'Wu Qiang',
    'What the Love! with Karan Johar': 'Karan Johar',
    'What\'s New Scooby-Doo?': 'Chuck Sheetz',
    'Who Killed Malcolm X?': 'Rachel Dretzin',
    'Win the Wilderness': 'Giles Harrison',
    'Women Of The Night': 'Ben Sombogaart',
    'Yanxi Palace: Princess Adventures': 'Hu Guanhua',
    'Soundtrack': 'Joshua Safran',
    'دفعة القاهرة': 'Ali Al-Ali'
}

In [226]:
df['director'] = df['director'].fillna(df['title'].map(movies_and_directors_5))
remaining_nulls = df['director'].isnull().sum()
print(f"Remaining null values in director column: {remaining_nulls}")

Remaining null values in director column: 1606

In [227]:
na_directors_titles_6 = missing_directors_title[1054:1260]
na_directors_titles_6

['Levius',
 'Lugar de Mulher',
 'Merry Happy Whatever',
 'Mythomaniac',
 'The Crime',
 'True: Winter Wishes',
 'Zona Rosa',
 'Once Upon A Time In Lingjian Mountain',
 "Dolly Parton's Heartstrings",
 'Mike Birbiglia: What I Should Have Said Was Nothing: Tales from My Secret Public Journal',
 'Nailed It! Holiday!',
 'Narcoworld: Dope Stories',
 "Nobody's Looking",
 'Singapore Social',
 'The Dragon Prince',
 'Trolls: The Beat Goes On!',
 'Bangkok Buddies',
 'Holiday Secrets',
 'Who Killed Little Gregory?',
 'Miss Culinary',
 'Candy Online',
 'At the Dolphin Bay',
 "I'm with the Band: Nasty Cherry",
 'Inheritors',
 'K-On!',
 'La Robe De Mariee Des Cieux',
 'Llama Llama',
 'My MVP Valentine',
 'My Sassy Girl',
 'The Club',
 'The Stranded',
 'The Toys That Made Us',
 'The Yard',
 'Westside Story',
 'My Dear Warrior',
 'Maradona in Mexico',
 'Chief of Staff',
 'Put Your Head on My Shoulder',
 'Little Things',
 'Greatest Events of WWII in Colour',
 'Green Eggs and Ham',
 'Wild District',
 'SCAMS',
 'Sam & Cat',
 'The End of the F***ing World',
 'Meet the Adebanjos',
 'The Devil Next Door',
 '100 Things to do Before High School',
 'Bella and the Bulldogs',
 'Victorious',
 'A Year In Space',
 'Ad Vitam',
 'Billy on the Street',
 'CLANNAD',
 'Haikyu!!',
 'Love, Chunibyo & Other Delusions!',
 'Maid-Sama!',
 'Mobile Suit Gundam: Iron-Blooded Orphans',
 "Queer Eye: We're in Japan!",
 'The Boulet Brothers Dragula',
 'The Deep',
 'True: Grabbleapple Harvest',
 'Vientos de agua',
 'We Are the Wave',
 'KENGAN ASHURA',
 'Sleepless Society: Bedtime Wishes',
 'Tomorrow with You',
 'Tunnel',
 'Shine On with Reese',
 'The Road to El Camino: Behind the Scenes of El Camino: A Breaking Bad Movie',
 'Wait, My Youth',
 'A Little Thing Called First Love',
 'BoJack Horseman',
 'Brotherhood',
 'Drug Squad: Costa del Sol',
 'Monzón: A Knockout Blow',
 'Nailed It! France',
 'Nailed It! Spain',
 'The Untamed',
 'Daybreak',
 'Breakfast, Lunch & Dinner',
 'ChuChu TV Kids Songs, Learning Videos & Bedtime Stories',
 'ChuChuTV Bedtime Stories & Moral Stories for Kids (English)',
 'ChuChuTV Bedtime Stories & Moral Stories for Kids (Hindi)',
 'ChuChuTV Surprise Eggs Learning Videos (English)',
 'ChuChuTV Surprise Eggs Learning Videos (Hindi)',
 'Interior Design Masters',
 'Little Baby Bum: Nursery Rhyme Friends',
 'Mighty Little Bheem: Diwali',
 'MONKART',
 'Spirit Riding Free: Pony Tales',
 'Toon',
 'Chosen',
 'THE UNLISTED',
 'Another Miss Oh',
 'Second 20s',
 'The Lies Within',
 'Insatiable',
 'The Hook Up Plan',
 'Beyblade Burst Turbo',
 'Ultramarine Magmell',
 'Rhythm + Flow',
 'The Spooky Tale of Captain Underpants Hack-a-ween',
 'Legend Quest: Masters of Myth',
 'My Country: The New Age',
 'A Plastic Ocean',
 'Creeped Out',
 'Peaky Blinders',
 'Raising Dion',
 'Rotten',
 'Super Monsters',
 'Seis Manos',
 'Living Undocumented',
 'Chicago Typewriter',
 'College Romance',
 'Engineering Girls',
 'Girls Hostel',
 'Inmates',
 'Little Baby Bum: Go Buster',
 'Miniforce X',
 'The K2',
 'The Liar and His Lover',
 'Bard of Blood',
 'El Marginal',
 'The Inmate',
 'Abstract: The Art of Design',
 'Glitch',
 'Vagabond',
 'Criminal: France',
 'Criminal: Germany',
 'Fastest Car',
 "Inside Bill's Brain: Decoding Bill Gates",
 'True: Tricky Treat Day',
 'When the Camellia Blooms',
 'Surviving R. Kelly',
 'Kabaneri of the Iron Fortress: The Battle of Unato',
 'Marianne',
 'Top Boy',
 'Unbelievable',
 'The I-Land',
 'The Mind, Explained',
 'The Spy',
 'American Factory: A Conversation with the Obamas',
 'Loo Loo Kids: Johny & Friends Musical Adventures',
 'Moving Art',
 'Serial Killer with Piers Morgan',
 'Luo Bao Bei',
 'Styling Hollywood',
 'The Dark Crystal: Age of Resistance',
 'The Good Bandit',
 'True and the Rainbow Kingdom',
 'Million Pound Menu',
 '13 Reasons Why: Beyond the Reasons',
 'HERO MASK',
 'Hyperdrive',
 'Our Planet - Behind The Scenes',
 '45 rpm',
 'Apache: The Life of Carlos Tevez',
 'Better Than Us',
 'Diagnosis',
 'Green Frontier',
 'Invader Zim: Enter the Florpus',
 'MINDHUNTER',
 'Super Monsters Back to School',
 "The King's Avatar",
 'Victim Number 8',
 'Cannon Busters',
 'Happy Jail',
 'Knightfall',
 'DC Super Hero Girls',
 'GLOW',
 'IZombie',
 'Sintonia',
 'Bad Guys',
 'Dollar',
 'Jane The Virgin',
 "Let's Eat 2",
 'Let’s Eat',
 'Misaeng',
 'Oh My Ghost',
 'Wu Assassins',
 'No Good Nick',
 'Basketball or Nothing',
 'Otherhood',
 'Sleepless Society: Nyctophobia',
 'The Letdown',
 'Twelve Forever',
 'My First First Love',
 'Another Life',
 'Beat Bugs',
 'Sexy Central',
 'The Epic Tales of Captain Underpants',
 'Typewriter',
 'Rookie Historian Goo Hae-Ryung',
 'Pinky Malinky',
 'Unrequited Love',
 'Angel Beats!',
 'Anohana: The Flower We Saw That Day',
 'God Eater',
 'GRANBLUE FANTASY the Animation',
 '3Below: Tales of Arcadia',
 'Bonus Family',
 'Extreme Engagement',
 'One Spring Night',
 'PILI Fantasy: War of Dragons',
 'True Tunes']

In [228]:
movies_and_directors_6 = {
    'Levius': 'Hiroyuki Seshita, Keisuke Ide',
    'Lugar de Mulher': 'Tatiana Issa, Guto Barra',
    'Merry Happy Whatever': 'Pamela Fryman, Phill Lewis',
    'Mythomaniac': 'Fabrice Gobert',
    'The Crime': 'Maciej Pieprzyca',
    'True: Winter Wishes': 'Jamie Whitney, Harold Harris',
    'Zona Rosa': 'Rodrigo Toro',
    'Once Upon A Time In Lingjian Mountain': 'Yu Zhongzhong',
    "Dolly Parton's Heartstrings": 'Timothy Busfield, Peter Werner',
    'Mike Birbiglia: What I Should Have Said Was Nothing: Tales from My Secret Public Journal': 'Seth Barrish',
    'Nailed It! Holiday!': 'Alan Carter',
    'Narcoworld: Dope Stories': 'Andrew Shea',
    "Nobody's Looking": 'Daniel Rezende',
    'Singapore Social': 'Ineke de Vos',
    'The Dragon Prince': 'Villads Spangsberg, Giancarlo Volpe',
    'Trolls: The Beat Goes On!': 'Jim Mortensen, Alex Almaguer',
    'Bangkok Buddies': 'Sivaroj Bussabandhu',
    'Holiday Secrets': 'Samira Radsi',
    'Who Killed Little Gregory?': 'Gilles Marchand',
    'Miss Culinary': 'Kittikoon Sadasawat',
    'Candy Online': 'Ziqiang Feng',
    'At the Dolphin Bay': 'Lin Helong',
    "I'm with the Band: Nasty Cherry": 'Luke Monaghan',
    'Inheritors': 'Kang Shin-hyo, Boo Sung-chul',
    'K-On!': 'Naoko Yamada',
    'La Robe De Mariee Des Cieux': 'Shen Yi',
    'Llama Llama': 'Chuck Sheetz',
    'My MVP Valentine': 'Chen Ming Zhang',
    'My Sassy Girl': 'Kwak Jae-yong',
    'The Club': 'Camila Ibarra',
    'The Stranded': 'Sophon Sakdaphisit',
    'The Toys That Made Us': 'Brian Volk-Weiss, Tom Stern',
    'The Yard': 'Yüksel Aksu, Hülya Gezer',
    'Westside Story': 'Steven Spielberg',
    'My Dear Warrior': 'David Bigander',
    'Maradona in Mexico': 'Angus Macqueen',
    'Chief of Staff': 'Kwak Jung-hwan',
    'Put Your Head on My Shoulder': 'Qi Qi',
    'Little Things': 'Ajay Bhuyan, Ruchir Arun',
    'Greatest Events of WWII in Colour': 'Max Barber',
    'Green Eggs and Ham': 'Lawrence Gong, Piero Piluso',
    'Wild District': 'Javier Fuentes-León, Carlos Moreno',
    'SCAMS': 'Kobashi Shota, Nishimura Shinya',
    'Sam & Cat': 'Steve Hoefer, Dan Schneider',
    'The End of the F***ing World': 'Jonathan Entwistle, Lucy Tcherniak',
    'Meet the Adebanjos': 'Debisi Alamin, Andrew Osayemi',
    'The Devil Next Door': 'Yossi Bloch, Daniel Sivan',
    '100 Things to do Before High School': 'Jonathan Judge, Savage Steve Holland',
    'Bella and the Bulldogs': 'Jonathan Judge, Shannon Flynn',
    'Victorious': 'Steve Hoefer, Adam Weissman',
    'A Year In Space': 'Shaul Schwarz, Shaheen Nazerali',
    'Ad Vitam': 'Thomas Cailley',
    'Billy on the Street': 'Michael Blieden',
    'CLANNAD': 'Tatsuya Ishihara',
    'Haikyu!!': 'Susumu Mitsunaka',
    'Love, Chunibyo & Other Delusions!': 'Tatsuya Ishihara',
    'Maid-Sama!': 'Hiroaki Sakurai',
    'Mobile Suit Gundam: Iron-Blooded Orphans': 'Tatsuyuki Nagai',
    "Queer Eye: We're in Japan!": 'Hisham Abed',
    'The Boulet Brothers Dragula': 'Michael Varrati',
    'The Deep': 'Trent Carlson',
    'True: Grabbleapple Harvest': 'Jamie Whitney',
    'Vientos de agua': 'Juan José Campanella',
    'We Are the Wave': 'Anca Miruna Lăzărescu, Mark Monheim',
    'KENGAN ASHURA': 'Seiji Kishi',
    'Sleepless Society: Bedtime Wishes': 'Pantham Thongsang',
    'Tomorrow with You': 'Yoo Je-won',
    'Tunnel': 'Shin Yong-hwi',
    'Shine On with Reese': 'Molly Sims',
    'The Road to El Camino: Behind the Scenes of El Camino: A Breaking Bad Movie': 'Vince Gilligan',
    'Wait, My Youth': 'Shen Qin-yuan',
    'A Little Thing Called First Love': 'Qi Xiaohui',
    'BoJack Horseman': 'Amy Winfrey, J.C. Gonzalez',
    'Brotherhood': 'Pedro Morelli',
    'Drug Squad: Costa del Sol': 'Marco A. Castillo, Iñaki Mercero',
    'Monzón: A Knockout Blow': 'Jesús Braceras',
    'Nailed It! France': 'Alan Carter',
    'Nailed It! Spain': 'Alan Carter',
    'The Untamed': 'Zheng Weiwen, Chen Jialin',
    'Daybreak': 'Brad Peyton, Michael Patrick Jann',
    'Breakfast, Lunch & Dinner': 'Morgan Neville',
    'ChuChu TV Kids Songs, Learning Videos & Bedtime Stories': 'Vinoth Chandar',
    'ChuChuTV Bedtime Stories & Moral Stories for Kids (English)': 'Vinoth Chandar',
    'ChuChuTV Bedtime Stories & Moral Stories for Kids (Hindi)': 'Vinoth Chandar',
    'ChuChuTV Surprise Eggs Learning Videos (English)': 'Vinoth Chandar',
    'ChuChuTV Surprise Eggs Learning Videos (Hindi)': 'Vinoth Chandar',
    'Interior Design Masters': 'Mark Saben',
    'Little Baby Bum: Nursery Rhyme Friends': 'Derek Jacombs',
    'Mighty Little Bheem: Diwali': 'Rajiv Chilaka',
    'MONKART': 'Kim Jin-chul',
    'Spirit Riding Free: Pony Tales': 'Josh Taback',
    'Toon': 'Beerend Houdijk',
    'Chosen': 'Tony Krawitz',
    'THE UNLISTED': 'Tony Krawitz, Nicholas Verso',
    'Another Miss Oh': 'Song Hyun-wook',
    'Second 20s': 'Kim Hyung-shik',
    'The Lies Within': 'Lee Yoon-jung',
    'Insatiable': 'Andrew Fleming, Brian Dannelly',
    'The Hook Up Plan': 'Noémie Saglio, Renaud Bertrand',
    'Beyblade Burst Turbo': 'Katsuhito Akiyama',
    'Ultramarine Magmell': 'Hayato Date',
    'Rhythm + Flow': 'Christopher Callis',
    'The Spooky Tale of Captain Underpants Hack-a-ween': 'Mark Banker',
    'Legend Quest: Masters of Myth': 'Gerdas Zeinitas',
    'My Country: The New Age': 'Kim Jin-won',
    'A Plastic Ocean': 'Craig Leeson',
    'Creeped Out': 'Bruce McDonald, Steve Wright',
    'Peaky Blinders': 'Colm McCarthy, Tim Mielants',
    'Raising Dion': 'Seith Mann, Rachel Goldberg',
    'Rotten': 'Ted Bourne',
    'Super Monsters': 'Dustin Mckenzie',
    'Seis Manos': 'Willis Bulliner',
    'Living Undocumented': 'Anna Chai, Aaron Saidman',
    'Chicago Typewriter': 'Kim Cheol-kyu',
    'College Romance': 'Simarpreet Singh',
    'Engineering Girls': 'Apoorv Singh Karki',
    'Girls Hostel': 'Chaitanya Kumbhakonum',
    'Inmates': 'Apoorv Singh Karki',
    'Little Baby Bum: Go Buster': 'Derek Jacombs',
    'Miniforce X': 'Lee Young-joon',
    'The K2': 'Kwak Jung-hwan',
    'The Liar and His Lover': 'Kim Jin-min',
    'Bard of Blood': 'Ribhu Dasgupta',
    'El Marginal': 'Luis Ortega, Alejandro Ciancio',
    'The Inmate': 'Jorge Colón, Mariano Ardanaz',
    'Abstract: The Art of Design': 'Morgan Neville, Brian Oakes',
    'Glitch': 'Emma Freeman, Tony Ayres',
    'Vagabond': 'Yoo In-shik',
    'Criminal: France': 'Frédéric Mermoud',
    'Criminal: Germany': 'Oliver Hirschbiegel',
    'Fastest Car': 'Gavin Fitzgerald',
    "Inside Bill's Brain: Decoding Bill Gates": 'Davis Guggenheim',
    'True: Tricky Treat Day': 'Jamie Whitney',
    'When the Camellia Blooms': 'Cha Yeong-hoon',
    'Surviving R. Kelly': 'Nigel Bellis, Astrid Miller',
    'Kabaneri of the Iron Fortress: The Battle of Unato': 'Tetsurō Araki',
    'Marianne': 'Samuel Bodin',
    'Top Boy': 'Yann Demange, Reinaldo Marcus Green',
    'Unbelievable': 'Lisa Cholodenko, Michael Dinner',
    'The I-Land': 'Neil LaBute, Jonathan Scarfe',
    'The Mind, Explained': 'Erika Frankel',
    'The Spy': 'Gideon Raff',
    'American Factory: A Conversation with the Obamas': 'Julia Reichert, Steven Bognar',
    'Loo Loo Kids: Johny & Friends Musical Adventures': 'Aurel bumps',
    'Moving Art': 'Louie Schwartzberg',
    'Serial Killer with Piers Morgan': 'Gary Johnston',
    'Luo Bao Bei': 'Alex Broad',
    'Styling Hollywood': 'Carlos King',
    'The Dark Crystal: Age of Resistance': 'Louis Leterrier',
    'The Good Bandit': 'Andrés Marroquín, Mario Ribero',
    'True and the Rainbow Kingdom': 'Jamie Whitney, Harold Harris',
    'Million Pound Menu': 'Genna Gibson',
    '13 Reasons Why: Beyond the Reasons': 'Jessica Yu',
    'HERO MASK': 'Hiroyasu Aoki',
    'Hyperdrive': 'Michael Driscoll',
    'Our Planet - Behind The Scenes': 'Alastair Fothergill',
    '45 rpm': 'David Pinillos, Gustavo Ron',
    'Apache: The Life of Carlos Tevez': 'Adrián Caetano',
    'Better Than Us': 'Andrey Dzhunkovskiy',
    'Diagnosis': 'Gary Shaffer',
    'Green Frontier': 'Ciro Guerra, Jacques Toulemonde Vidal',
    'Invader Zim: Enter the Florpus': 'Jhonen Vasquez, Jake Wyatt',
    'MINDHUNTER': 'David Fincher, Carl Franklin',
    'Super Monsters Back to School': 'Dustin Mckenzie',
    "The King's Avatar": 'Shi Kiyen',
    'Victim Number 8': 'Alejandro Bazzano, Iñaki Mercero',
    'Cannon Busters': 'LeSean Thomas',
    'Happy Jail': 'Michele Josue',
    'Knightfall': 'Douglas Mackinnon, Metin Hüseyin',
    'DC Super Hero Girls': 'Lauren Faust',
    'GLOW': 'Lynn Shelton, Jesse Peretz',
    'IZombie': 'John Kretchmer, Michael Fields',
    'Sintonia': 'KondZilla, Johnny Araújo',
    'Bad Guys': 'Kim Jung-min',
    'Dollar': 'Samer Al Barkawi',
    'Jane The Virgin': 'Brad Silberling, Melanie Mayron',
    "Let's Eat 2": 'Park Joon-hwa, Choi Kyu-shik',
    'Let’s Eat': 'Park Joon-hwa',
    'Misaeng': 'Kim Won-seok',
    'Oh My Ghost': 'Yoo Je-won',
    'Wu Assassins': 'Stephen Fung, Toa Fraser',
    'No Good Nick': 'Andy Fickman, Bob Koherr',
    'Basketball or Nothing': 'Matt Howley',
    'Otherhood': 'Cindy Chupack',
    'Sleepless Society: Nyctophobia': 'Sivaroj Bussabandhu',
    'The Letdown': 'Trent O\'Donnell, Amanda Brotchie',
    'Twelve Forever': 'Julia Vickerman',
    'My First First Love': 'Oh Jin-seok',
    'Another Life': 'Sheree Folkson, Allan Arkush',
    'Beat Bugs': 'Josh Wakely',
    'Sexy Central': 'Pavel Giroud',
    'The Epic Tales of Captain Underpants': 'Todd Grimes',
    'Typewriter': 'Sujoy Ghosh',
    'Rookie Historian Goo Hae-Ryung': 'Kang Il-soo, Han Hyun-hee',
    'Pinky Malinky': 'Chris Garbutt, Riki Lindhome',
    'Unrequited Love': 'Ding Pei',
    'Angel Beats!': 'Seiji Kishi',
    'Anohana: The Flower We Saw That Day': 'Tatsuyuki Nagai',
    'God Eater': 'Takayuki Hirao',
    'GRANBLUE FANTASY the Animation': 'Yuuki Itoh',
    '3Below: Tales of Arcadia': 'Rodrigo Blaas, Guillermo del Toro',
    'Bonus Family': 'Felix Herngren, Martin Persson',
    'Extreme Engagement': 'Luke Cornish',
    'One Spring Night': 'Ahn Pan-seok',
    'PILI Fantasy: War of Dragons': 'Huang Qianghua',
    'True Tunes': 'Michael Beaudoin'
}

In [229]:
df['director'] = df['director'].fillna(df['title'].map(movies_and_directors_6))
remaining_nulls = df['director'].isnull().sum()
print(f"Remaining null values in director column: {remaining_nulls}")

Remaining null values in director column: 1400

In [230]:
na_directors_titles_7 = missing_directors_title[1260:1460]
na_directors_titles_7

['Free Rein',
 'The Legend of White Snake',
 'Kakegurui',
 'Stranger Things',
 'The Last Czars',
 'Yummy Mummies',
 'Bangkok Love Stories: Objects of Affection',
 'Bangkok Love Stories: Plead',
 'Designated Survivor: 60 Days',
 'DreamWorks Kung Fu Panda Awesome Secrets',
 'Hatchimals | Adventures in Hatchtopia',
 'Molang',
 'Rabbids Invasion',
 'Record of Grancrest War',
 'Scare Tactics',
 'Dope',
 'Exhibit A',
 'Instant Hotel',
 'Motown Magic',
 'Paquita Salas',
 'Answer for Heaven',
 'Hikaru Utada Laughter in the Dark Tour 2018',
 'Forest of Piano',
 'Girls Incarcerated',
 'Go! Live Your Way',
 'Magi: The Labyrinth of Magic',
 'Neon Genesis Evangelion',
 'Shooter',
 'The Casketeers',
 'The Confession Tapes',
 'Fate/Zero',
 'Kill la Kill',
 'Puella Magi Madoka Magica',
 'Somewhere Only We Know',
 'Unit 42',
 'Awake: The Million Dollar Game',
 'Black Spot',
 'El desconocido',
 "Girlfriends' Guide to Divorce",
 'Leila',
 'Marlon',
 "Marvel's Jessica Jones",
 'Yankee',
 'Jinn',
 'Upin & Ipin',
 'Designated Survivor',
 'Super Monsters Monster Pets',
 'Tales of the City',
 'Black Mirror',
 'Documentary Now!',
 'Malibu Rescue: The Series',
 'Arthdal Chronicles',
 'A Thousand Goodnights',
 'March Comes in Like a Lion',
 'Bad Blood',
 'Killer Ratings',
 'When They See Us',
 'Historical Roasts',
 'Hyper HardBoiled Gourmet Report',
 "She's Gotta Have It",
 'WHAT / IF',
 'Prince of Peoria',
 'Rosario Tijeras',
 "It's Bruno!",
 'White Gold',
 'Dennis and Gnasher Unleashed',
 'Heidi, bienvenida a casa',
 'I Hear You',
 'Revisions',
 'Still LAUGH-IN: The Stars Celebrate',
 'The Defected',
 'Easy',
 'Jailbirds',
 'The Mechanism',
 'The Princess Weiyoung',
 'The Society',
 'Away From Home',
 'Bibik-Bibikku',
 'Cinta 100KG',
 'Cinta Iris',
 'Cinta Si Wedding Planner',
 'Cinta Teruna Kimchi',
 'Secret of Success',
 'The Missing Menu',
 'Unchained Fate',
 'Abyss',
 'I Have a Script',
 'In the Bosom of a Thorn',
 'The Writer',
 'What If?',
 'Cupcake & Dino - General Services',
 'Flinch',
 'Tuca & Bertie',
 'Code Geass: Lelouch of the Rebellion',
 "Angel 'N' Devil",
 'Hong Kong West Side Stories',
 'Ingress: The Animation',
 'K.O. One Re-act',
 'K.O.3an Guo',
 'KO One Return',
 'The Outsiders',
 'Ash vs. Evil Dead',
 'Señora Acero',
 'Chambers',
 'Street Food',
 'KO One',
 'Lunatics',
 'My Dear Boy',
 'Rilakkuma and Kaoru',
 'Samantha!',
 'Super Monsters Furever Friends',
 'Crazy Ex-Girlfriend',
 'Francesco De Carlo: Cose di Questo Mondo',
 'Huge in France',
 'New Girl',
 'You vs. Wild',
 'Time: The Kalief Browder Story',
 'Derek',
 'Imposters',
 'Our Planet',
 'Quicksand',
 'Rimba Racer',
 'Roman Empire: Reign of Blood',
 'Spirit: Riding Free',
 'Tijuana',
 'Possessed',
 'Tango',
 'Kicko & Super Speedo',
 'That Winter, the Wind Blows',
 'Ultraman',
 'Pablo',
 'Osmosis',
 'Santa Clarita Diet',
 'The Terminal',
 'Traitors',
 'Versailles',
 'Ainori Love Wagon: Asian Journey',
 "The Eagle of El-Se'eed",
 "Charlie's Colorforms City",
 'Crime Diaries: The Candidate',
 'Delhi Crime',
 'The 10 Sins',
 'The OA',
 'Antoine Griezmann: The Making of a Legend',
 'Bo on the Go!',
 'Stay Tuned!',
 'February 9',
 "My Husband Won't Fit",
 'Green Door',
 "If I Hadn't Met You",
 'My Pride',
 'Robozuna',
 'The Disappearance of Madeleine McCann',
 'Turn Up Charlie',
 'More to Say',
 'The Land of Hypocrisy',
 'Eugenie Nights',
 'This Evening',
 'Into the Badlands',
 'Bangkok Love Stories: Hey You!',
 'Disappearance',
 'Immortals',
 'The Confrontation',
 'American Crime Story: The People v. O.J. Simpson',
 'Secret City',
 'A Korean Odyssey',
 'Cricket Fever: Mumbai Indians',
 'Larva Island',
 'Losers',
 'Northern Rescue',
 'The Disastrous Life of Saiki K.',
 'Unsolved',
 "Chef's Table",
 'The Big Family Cooking Showdown',
 'Z4',
 "Larry Charles' Dangerous World of Comedy",
 'The 43',
 'The Kirlian Frequency',
 'Barbie Dreamhouse Adventures',
 'Velvet Colección',
 'Iron Ladies',
 'The Break',
 'One Day at a Time',
 'The Last of the Schmucks',
 'Hidden Worlds',
 'Live',
 'Safe',
 'Tayee',
 'Violet Evergarden',
 'Romance is a bonus book',
 "Free Rein: Valentine's Day",
 'LEGO Marvel Super Heroes: Guardians of the Galaxy',
 'Littlest Pet Shop: A World of Our Own',
 'Russian Doll',
 'Sparta',
 'Sword Art Online Alternative: Gun Gale Online',
 'True: Happy Hearts Day',
 'Paprika',
 'A Taiwanese Tale of Two Cities',
 'Z Nation']

In [231]:
movies_and_directors_7 = {
    'Free Rein': 'Marek Losey, Paul Hoen',
    'The Legend of White Snake': 'Zhi Lei',
    'Kakegurui': 'Yuichiro Hayashi',
    'Stranger Things': 'Matt Duffer, Ross Duffer',
    'The Last Czars': 'Adrian McDowall, Gareth Tunley',
    'Yummy Mummies': 'Ben Davies, Miro Bilbrough',
    'Bangkok Love Stories: Objects of Affection': 'Danai Bander',
    'Bangkok Love Stories: Plead': 'Ekkachai Uekrongtham',
    'Designated Survivor: 60 Days': 'Yoo Jong-seon',
    'DreamWorks Kung Fu Panda Awesome Secrets': 'Lane Lueras, Luther McLaurin',
    'Hatchimals | Adventures in Hatchtopia': 'Ken Cunningham',
    'Molang': 'Marie-Caroline Villand',
    'Rabbids Invasion': 'Franz Kirchner',
    'Record of Grancrest War': 'Mamoru Hatakeyama',
    'Scare Tactics': 'Michael John Warren, Scott Hallock',
    'Dope': 'Rick Famuyiwa',
    'Exhibit A': 'Kelly Loudenberg',
    'Instant Hotel': 'Michael Brooks',
    'Motown Magic': 'Josh Wakely',
    'Paquita Salas': 'Javier Calvo, Javier Ambrossi',
    'Answer for Heaven': 'Sivaroj Bussabandhu',
    'Hikaru Utada Laughter in the Dark Tour 2018': 'Shinya Yamada',
    'Forest of Piano': 'Gaku Nakatani',
    'Girls Incarcerated': 'Nick Green',
    'Go! Live Your Way': 'Mauro Scandolari',
    'Magi: The Labyrinth of Magic': 'Koji Masunari',
    'Neon Genesis Evangelion': 'Hideaki Anno',
    'Shooter': 'Simon Cellan Jones',
    'The Casketeers': 'Susan Leonard',
    'The Confession Tapes': 'Kelly Loudenberg',
    'Fate/Zero': 'Ei Aoki',
    'Kill la Kill': 'Hiroyuki Imaishi',
    'Puella Magi Madoka Magica': 'Akiyuki Shinbo',
    'Somewhere Only We Know': 'Jingle Ma',
    'Unit 42': 'Indra Siera, Roel Mondelaers',
    'Awake: The Million Dollar Game': 'Michael Dempsey',
    'Black Spot': 'Thierry Poiraud, Julien Despaux',
    'El desconocido': 'Gonzalo Gonzalez',
    "Girlfriends' Guide to Divorce": 'Robert Duncan McNeill',
    'Leila': 'Deepa Mehta, Shanker Raman',
    'Marlon': 'Andy Ackerman',
    "Marvel's Jessica Jones": 'S. J. Clarkson, David Petrarca',
    'Yankee': 'Carlos Carrera',
    'Jinn': 'Mir-Jean Bou Chaaya',
    'Upin & Ipin': 'Mohd Nizam Abdul Razak',
    'Designated Survivor': 'Paul McGuigan',
    'Super Monsters Monster Pets': 'Dustin McKenzie',
    'Tales of the City': 'Alan Poul, Silas Howard',
    'Black Mirror': 'Owen Harris, Carl Tibbetts',
    'Documentary Now!': 'Rhys Thomas, Alex Buono',
    'Malibu Rescue: The Series': 'Savage Steve Holland',
    'Arthdal Chronicles': 'Kim Won-seok',
    'A Thousand Goodnights': 'Lin Ching-chieh',
    'March Comes in Like a Lion': 'Akiyuki Shinbo',
    'Bad Blood': 'Alain Desrochers',
    'Killer Ratings': 'Daniel Bogado',
    'When They See Us': 'Ava DuVernay',
    'Historical Roasts': 'B. J. Porter',
    'Hyper HardBoiled Gourmet Report': 'Kenji Kamiyama',
    "She's Gotta Have It": 'Spike Lee',
    'WHAT / IF': 'Phillip Noyce',
    'Prince of Peoria': 'Jon Rosenbaum',
    'Rosario Tijeras': 'Chava Cartas',
    "It's Bruno!": 'Solvan Naim',
    'White Gold': 'Damon Beesley',
    'Dennis and Gnasher Unleashed': 'Boris Hiestand',
    'Heidi, bienvenida a casa': 'Jorge Edelstein',
    'I Hear You': 'Qiu Mang',
    'Revisions': 'Goro Taniguchi',
    'Still LAUGH-IN: The Stars Celebrate': 'Carrie Havel',
    'The Defected': 'So Man-chung',
    'Easy': 'Joe Swanberg',
    'Jailbirds': 'R.J. Cutler',
    'The Mechanism': 'José Padilha',
    'The Princess Weiyoung': 'Li Huizhu',
    'The Society': 'Marc Webb',
    'Away From Home': 'Benedict Mique',
    'Bibik-Bibikku': 'Eoon Shuhaini',
    'Cinta 100KG': 'Megat Sharizal',
    'Cinta Iris': 'Raja Ahmad Alauddin',
    'Cinta Si Wedding Planner': 'Feroz Kader',
    'Cinta Teruna Kimchi': 'Tuan Faisal',
    'Secret of Success': 'Robert B. Weide',
    'The Missing Menu': 'Kabir Khan',
    'Unchained Fate': 'David Attwood',
    'Abyss': 'Yoo Je-won',
    'I Have a Script': 'Ali Al-Ali',
    'In the Bosom of a Thorn': 'Mohammad Al-Awali',
    'The Writer': 'Rami Hanna',
    'What If?': 'Bryan Andrews',
    'Cupcake & Dino - General Services': 'Pedro Eboli',
    'Flinch': 'Anthony Owen',
    'Tuca & Bertie': 'Lisa Hanawalt, Amy Winfrey',
    'Code Geass: Lelouch of the Rebellion': 'Goro Taniguchi',
    "Angel 'N' Devil": 'Weng Jingting',
    'Hong Kong West Side Stories': 'Justin Cheung',
    'Ingress: The Animation': 'Yuhei Sakuragi',
    'K.O. One Re-act': 'Ke Zhengming',
    'K.O.3an Guo': 'Wu Jianxin',
    'KO One Return': 'Ke Zhengming',
    'The Outsiders': 'Han Han, Ko Han-chen',
    'Ash vs. Evil Dead': 'Sam Raimi, Michael J. Bassett',
    'Señora Acero': 'Miguel Varoni, Walter Doehner',
    'Chambers': 'Alfonso Gomez-Rejon',
    'Street Food': 'David Gelb',
    'KO One': 'Liao Feiyu',
    'Lunatics': 'Chris Lilley',
    'My Dear Boy': 'Hsub Chao-jen',
    'Rilakkuma and Kaoru': 'Masahito Kobayashi',
    'Samantha!': 'Luis Pinheiro',
    'Super Monsters Furever Friends': 'Dustin McKenzie',
    'Crazy Ex-Girlfriend': 'Marc Webb, Alex Hardcastle',
    'Francesco De Carlo: Cose di Questo Mondo': 'Cristiano D\'Alisera',
    'Huge in France': 'Andrew Mogel, Jarrad Paul',
    'New Girl': 'Trent O\'Donnell, Peyton Reed',
    'You vs. Wild': 'Ben Simms',
    'Time: The Kalief Browder Story': 'Jenner Furst',
    'Derek': 'Ricky Gervais',
    'Imposters': 'Adam Brooks',
    'Our Planet': 'Alastair Fothergill',
    'Quicksand': 'Per-Olav Sørensen, Lisa Farzaneh',
    'Rimba Racer': 'Glue Animation',
    'Roman Empire: Reign of Blood': 'Richard Lopez',
    'Spirit: Riding Free': 'Josh Taback',
    'Tijuana': 'Hammudi Al-Rahmoun Font, Clara Roquet',
    'Possessed': 'Oh Hyun-jong',
    'Tango': 'Elie Sfeir',
    'Kicko & Super Speedo': 'Rajiv Chilaka',
    'That Winter, the Wind Blows': 'Kim Kyu-tae',
    'Ultraman': 'Kenji Kamiyama, Shinji Aramaki',
    'Pablo': 'David McGrath',
    'Osmosis': 'Julius Berg, Mona Achache',
    'Santa Clarita Diet': 'Ruben Fleischer, Marc Buckland',
    'The Terminal': 'Steven Spielberg',
    'Traitors': 'Dearbhla Walsh, Alex Winckler',
    'Versailles': 'Jalil Lespert, Thomas Vincent',
    'Ainori Love Wagon: Asian Journey': 'Netflix Production Team',
    "The Eagle of El-Se'eed": 'Yasser Sami',
    "Charlie's Colorforms City": 'Derek Moore',
    'Crime Diaries: The Candidate': 'Hiromi Kamata',
    'Delhi Crime': 'Richie Mehta',
    'The 10 Sins': 'Samhua Movie',
    'The OA': 'Zal Batmanglij',
    'Antoine Griezmann: The Making of a Legend': 'Alex Dell',
    'Bo on the Go!': 'Ian Richter',
    'Stay Tuned!': 'Shinya Sugai',
    'February 9': 'Philippe Martinez',
    "My Husband Won't Fit": 'Yuki Tanada',
    'Green Door': 'Leste Chen',
    "If I Hadn't Met You": 'Kiko Ruiz Claverol',
    'My Pride': 'Maddi Patton',
    'Robozuna': 'Ed Bignell',
    'The Disappearance of Madeleine McCann': 'Chris Smith',
    'Turn Up Charlie': 'Matt Lipsey, Tristram Shapeero',
    'More to Say': 'Rebecca Sugar',
    'The Land of Hypocrisy': 'Sameh Abdulaziz',
    'Eugenie Nights': 'Hani Khalifa',
    'This Evening': 'Hatem Ali',
    'Into the Badlands': 'David Dobkin, Guy Ferland',
    'Bangkok Love Stories: Hey You!': 'Sivaroj Bussabandhu',
    'Disappearance': 'Boudewijn Koole',
    'Immortals': 'Alphan Eşeli',
    'The Confrontation': 'Jan Verheyen',
    'American Crime Story: The People v. O.J. Simpson': 'Ryan Murphy, Anthony Hemingway',
    'Secret City': 'Emma Freeman, Tony Krawitz',
    'A Korean Odyssey': 'Park Hong-kyun',
    'Cricket Fever: Mumbai Indians': 'James Watkins',
    'Larva Island': 'Ahn Byoung-wook',
    'Losers': 'Mickey Duzyj',
    'Northern Rescue': 'Bradley Walsh, Gail Harvey',
    'The Disastrous Life of Saiki K.': 'Hiroaki Sakurai',
    'Unsolved': 'Anthony Hemingway, Mark Pellington',
    "Chef's Table": 'David Gelb',
    'The Big Family Cooking Showdown': 'Southan Morris',
    'Z4': 'Tizuka Yamasaki',
    "Larry Charles' Dangerous World of Comedy": 'Larry Charles',
    'The 43': 'Alejandro Turner',
    'The Kirlian Frequency': 'Cristian Ponce',
    'Barbie Dreamhouse Adventures': 'Patrice Berube',
    'Velvet Colección': 'Gustavo Ron, Jorge Torregrossa',
    'Iron Ladies': 'Lin Ching-fang',
    'The Break': 'Matthieu Donck',
    'One Day at a Time': 'Phill Lewis, Gloria Calderón Kellett',
    'The Last of the Schmucks': 'Jan Verheyen',
    'Hidden Worlds': 'BBC Natural History Unit',
    'Live': 'Kim Kyu-tae',
    'Safe': 'Julia Ford, Daniel Nettheim',
    'Tayee': 'Amr Arafa',
    'Violet Evergarden': 'Taichi Ishidate',
    'Romance is a bonus book': 'Lee Jeong-hyo',
    "Free Rein: Valentine's Day": 'Marek Losey',
    'LEGO Marvel Super Heroes: Guardians of the Galaxy': 'Michael D. Black',
    'Littlest Pet Shop: A World of Our Own': 'Gillian Comerford',
    'Russian Doll': 'Leslye Headland, Jamie Babbit',
    'Sparta': 'Egor Baranov',
    'Sword Art Online Alternative: Gun Gale Online': 'Masayuki Sakoi',
    'True: Happy Hearts Day': 'Jamie Whitney',
    'Paprika': 'Satoshi Kon',
    'A Taiwanese Tale of Two Cities': 'Tien-Lun Yeh',
    'Z Nation': 'John Hyams, Tim Andrew'
}

In [232]:
df['director'] = df['director'].fillna(df['title'].map(movies_and_directors_7))
remaining_nulls = df['director'].isnull().sum()
print(f"Remaining null values in director column: {remaining_nulls}")

Remaining null values in director column: 1200

In [233]:
na_directors_titles_8 = missing_directors_title[1460:1660]
na_directors_titles_8

['Black Earth Rising',
 'Club of Crows',
 'Examination of Conscience',
 'Polar',
 'The Perfect Match',
 'Conversations with a Killer: The Ted Bundy Tapes',
 'Close',
 "Marvel's The Punisher",
 'Memory Love',
 "The World's Most Extraordinary Homes",
 'Trigger Warning with Killer Mike',
 'Adhugo',
 'Lavender',
 'La Grande Chaumière Violette',
 'Back with the Ex',
 'Friends from College',
 'Hardy Bucks',
 'Horrid Henry',
 'Pocoyo',
 'When Heroes Fly',
 'See You in Time',
 'Déjà Vu',
 'A Series of Unfortunate Events',
 'COMEDIANS of the world',
 'The Paper',
 'Tidying Up with Marie Kondo',
 'Bill Hicks: Reflections',
 'Gina Yashere: Skinny B*tch',
 'Sam Kinison: The Scream Continues',
 'Secrets in the Hot Spring',
 'Tim Allen: ReWires America',
 'Pioneers: First Women Filmmakers*',
 'In Family We Trust',
 'Black Mirror: Bandersnatch',
 'Hashoter Hatov',
 'Murder Mountain',
 'Selection Day',
 'Stand Up and Away! with Brian Regan',
 'Way Back into Love',
 "Demon's Path",
 'People Just Do Nothing',
 'Single Ladies Senior',
 '7 Days Out',
 "Jojo's World",
 'LAST HOPE',
 'Lion Pride',
 'Love @ Seventeen',
 'Perfume',
 'Sirius the Jaeger',
 'Wolf',
 'Fate/stay night: Unlimited Blade Works',
 'Ashes of Love',
 'DreamWorks Holiday Classics',
 'Flowers',
 'Once in a Lifetime Sessions with George Ezra',
 'Once in a Lifetime Sessions with OneRepublic',
 'Hymn of Death',
 'Inside the Real Narcos',
 'The Fix',
 'The Innocent Man',
 'Tidelands',
 'Travelers',
 'Voltron: Legendary Defender',
 'Back Street Girls -GOKUDOLS-',
 'Dogs of Berlin',
 'Neo Yokio',
 'The Sound of Your Heart: Reboot',
 'Memories of the Alhambra',
 'Haunted House',
 'Oddbods: The Festive Menace',
 'Roll With Me',
 '1983',
 'Death by Magic',
 'Love and Fortune',
 'Spy Kids: Mission Critical',
 'Bumping Mics with Jeff Ross & Dave Attell',
 'Minecraft: Story Mode',
 'Frontier',
 'Fugitiva',
 'Sick Note',
 'Mystery Science Theater 3000: The Return',
 'Kulipari: Dream Walker',
 'Paap-O-Meter',
 'The Final Table',
 'Eternal Love',
 'La Doña',
 'Silvana Sin Lana',
 'Ponysitters Club',
 'The Princess Switch',
 'Vai Anitta',
 'Beyblade Burst Evolution',
 'Warrior',
 'Age of Tanks',
 'Medal of Honor',
 'Super Drags',
 'The Queen of Flow',
 'Treehouse Detectives',
 'Westside',
 'Transfers',
 'Damnation',
 "John Leguizamo's Latin History for Morons",
 'Kopitiam',
 'Brainchild',
 'Creators',
 'Follow This',
 'The Great British Baking Show: The Beginnings',
 'Yeh Hai Bakrapur',
 'Fate/EXTRA Last Encore',
 'Santo Cachón',
 'Terrorism Close Calls',
 'DreamWorks Spooky Stories',
 'Great News',
 'Here to Heart',
 'The Hollywood Masters',
 'Accidentally in Love',
 'Ask the Doctor',
 'Best.Worst.Weekend.Ever.',
 'Derren Brown: Sacrifice',
 'Making a Murderer',
 "Marvel's Daredevil",
 'Oddbods: Party Monsters',
 'Project S The Series',
 'Wanderlust',
 "My Babysitter's a Vampire",
 'Rake',
 'Stunt Science',
 "Edgar Rice Burroughs' Tarzan and Jane",
 'The Curious Creations of Christine McConnell',
 'The Haunting of Hill House',
 'Ordinary Heroes',
 'Salt Fat Acid Heat',
 'Blood Pact',
 'Sofia the First',
 'Dancing Queen',
 'Empire Games',
 'LOST SONG',
 'Super Monsters Save Halloween',
 'YG Future Strategy Office',
 'Violet Evergarden: Special',
 'Monty Python Best Bits (mostly)',
 'Monty Python: Live at Aspen',
 "Monty Python's Almost the Truth",
 "Monty Python's Fliegender Zirkus",
 "Monty Python's Flying Circus",
 "Monty Python's Personal Best",
 'Hot Date',
 'Strong',
 'Three Wives One Husband',
 'Made in Mexico',
 'Reboot: The Guardian Code',
 'Skylanders Academy',
 'Battlefish',
 'DRAGON PILOT: Hisone & Masotan',
 'Maniac',
 'Rafinha Bastos: Ultimatum',
 'The Good Cop',
 'Mobile Suit Gundam UC',
 'Transformers: Rescue Bots',
 'Al Hayba',
 'American Vandal',
 'Boca Juniors Confidential',
 'Ingobernable',
 'Norm Macdonald Has a Show',
 'Super Monsters Monster Party',
 'The Rise of Phoenixes',
 'Reversing Roe',
 'Life',
 'Daniel Sloss: Live Shows',
 'If I were an Animal',
 'Show Me the Money',
 'Transformers Prime',
 'Transformers: Robots in Disguise',
 'First and Last',
 "Marvel's Iron Fist",
 'Stretch Armstrong & the Flex Fighters',
 'Monkey Twins',
 'Quantico',
 'Sisters',
 'Cathedral of the Sea',
 'Inside the Criminal Mind',
 'The Comedy Lineup',
 'Ultimate Beastmaster',
 'Ultimate Beastmaster México',
 'Undercover Law',
 "Chicken Soup for the Soul's Being Dad",
 'The Innocents',
 'Party Monster: Scratching the Surface',
 'Stay Here',
 '72 Dangerous Animals: Asia',
 'Afflicted',
 'All About the Washingtons',
 'The Originals',
 'Pretty Man',
 'On Children',
 'Cocaine Coast',
 'Dinotrux Supercharged',
 'Becoming Champions',
 'Switched',
 'The Could’ve-Gone-All-the-Way Committee',
 'A Very Secret Service']

In [234]:
movies_and_directors_8 = {
    'Black Earth Rising': 'Hugo Blick',
    'Club of Crows': 'Gary Alazraki, Mariana Chenillo',
    'Examination of Conscience': 'Albert Solé',
    'Polar': 'Jonas Åkerlund',
    'The Perfect Match': 'Luo An-de',
    'Conversations with a Killer: The Ted Bundy Tapes': 'Joe Berlinger',
    'Close': 'Vicky Jewson',
    "Marvel's The Punisher": 'Tom Shankland, Andy Goddard',
    'Memory Love': 'Andrei Tan, Lin Qing-zhen',
    "The World's Most Extraordinary Homes": 'Ed Stobart, Charlie Luxton',
    'Trigger Warning with Killer Mike': 'Vikram Gandhi',
    'Adhugo': 'Ravi Babu',
    'Lavender': 'Ed Gass-Donnelly',
    'La Grande Chaumière Violette': 'Wu Meng-en',
    'Back with the Ex': 'Nick Murray',
    'Friends from College': 'Nicholas Stoller',
    'Hardy Bucks': 'Chris Tordoff, Mike Cockayne',
    'Horrid Henry': 'Dave Unwin, Hilary Audus',
    'Pocoyo': 'Guillermo García Carsí, Alfonso Rodríguez',
    'When Heroes Fly': 'Omri Givon',
    'See You in Time': 'Mao Xun-rong',
    'Déjà Vu': 'Tan Qiuyu',
    'A Series of Unfortunate Events': 'Barry Sonnenfeld, Mark Palansky',
    'COMEDIANS of the world': 'Raul Campos, Jan Suter',
    'The Paper': 'Dalibor Matanić',
    'Tidying Up with Marie Kondo': 'Jade Taylor',
    'Bill Hicks: Reflections': 'Janine Hicks',
    'Gina Yashere: Skinny B*tch': 'Laura Murphy',
    'Sam Kinison: The Scream Continues': 'Walter C. Miller',
    'Secrets in the Hot Spring': 'Lin Kuan-hui',
    'Tim Allen: ReWires America': 'John Pasquin',
    'Pioneers: First Women Filmmakers*': 'Alice Guy-Blaché, Lois Weber',
    'In Family We Trust': 'Songyos Sugmakanan',
    'Black Mirror: Bandersnatch': 'David Slade',
    'Hashoter Hatov': 'Eitan Tzur, Tomer Aviram',
    'Murder Mountain': 'Joshua Zeman',
    'Selection Day': 'Udayan Prasad, Karan Boolani',
    'Stand Up and Away! with Brian Regan': 'Dan Beers',
    'Way Back into Love': 'Shen Qin-yuan',
    "Demon's Path": 'Patrick Kong, Sun Liji',
    'People Just Do Nothing': 'Jack Clough',
    'Single Ladies Senior': 'Turkish Production Team',
    '7 Days Out': 'Andrew Rossi',
    "Jojo's World": 'Yu-Chuan Han',
    'LAST HOPE': 'Shoji Kawamori, Hidekazu Sato',
    'Lion Pride': 'Chen Rong-hui',
    'Love @ Seventeen': 'Chou Shiah-jau',
    'Perfume': 'Philipp Kadelbach',
    'Sirius the Jaeger': 'Masahiro Andō',
    'Wolf': 'Jim Taihuttu',
    'Fate/stay night: Unlimited Blade Works': 'Takahiro Miura',
    'Ashes of Love': 'Chu Yui-bin',
    'DreamWorks Holiday Classics': 'Tim Johnson, Rex Grignon',
    'Flowers': 'Will Sharpe',
    'Once in a Lifetime Sessions with George Ezra': 'Michael John Warren',
    'Once in a Lifetime Sessions with OneRepublic': 'Michael John Warren',
    'Hymn of Death': 'Park Soo-jin',
    'Inside the Real Narcos': 'James Waldron',
    'The Fix': 'Ryan Polito',
    'The Innocent Man': 'Clay Tweel',
    'Tidelands': 'Toa Fraser, Catriona McKenzie',
    'Travelers': 'Andy Mikita, Amanda Tapping',
    'Voltron: Legendary Defender': 'Joaquim Dos Santos, Lauren Montgomery',
    'Back Street Girls -GOKUDOLS-': 'Chiaki Kon',
    'Dogs of Berlin': 'Christian Alvart',
    'Neo Yokio': 'Ezra Koenig, Nick Weidenfeld',
    'The Sound of Your Heart: Reboot': 'Evillive',
    'Memories of the Alhambra': 'Ahn Gil-ho',
    'Haunted House': 'Korean Animation Studio',
    'Oddbods: The Festive Menace': 'Richard Thomas',
    'Roll With Me': 'Lisa France',
    '1983': 'Agnieszka Holland, Kasia Adamik',
    'Death by Magic': 'Simon Dinsell',
    'Love and Fortune': 'Mai Sakai',
    'Spy Kids: Mission Critical': 'Michael Mullen',
    'Bumping Mics with Jeff Ross & Dave Attell': 'Andrew Jarecki',
    'Minecraft: Story Mode': 'Dennis Adams',
    'Frontier': 'Brad Peyton, John Vatcher',
    'Fugitiva': 'Belén Macías, Sergio Cabrera',
    'Sick Note': 'Matt Lipsey',
    'Mystery Science Theater 3000: The Return': 'Robert Cohen, Keith Gordon',
    'Kulipari: Dream Walker': 'Chuck Patton',
    'Paap-O-Meter': 'Sony YAY! Production',
    'The Final Table': 'Russell Norman',
    'Eternal Love': 'Lam Yuk-fan',
    'La Doña': 'Carlos Villegas, Carlos Santos',
    'Silvana Sin Lana': 'Luis Manzo, Ricardo Schwarz',
    'Ponysitters Club': 'Justin G. Dyck',
    'The Princess Switch': 'Mike Rohl',
    'Vai Anitta': 'Andrucha Waddington',
    'Beyblade Burst Evolution': 'Katsuhito Akiyama',
    'Warrior': 'Assaf Bernstein',
    'Age of Tanks': 'Jean-Baptiste Gallot',
    'Medal of Honor': 'James Moll',
    'Super Drags': 'Fernando Mendonça',
    'The Queen of Flow': 'Rodrigo Lalinde, Liliana Bocanegra',
    'Treehouse Detectives': 'Paul Demeyer',
    'Westside': 'James Carroll',
    'Transfers': 'Olivier Guignard, Antoine Charreyron',
    'Damnation': 'David Mackenzie, Rod Lurie',
    "John Leguizamo's Latin History for Morons": 'Spike Lee',
    'Kopitiam': 'Ng Ping Ho',
    'Brainchild': 'Benidict Moore',
    'Creators': 'Italian Production Team',
    'Follow This': 'BuzzFeed Production Team',
    'The Great British Baking Show: The Beginnings': 'Andy Devonshire',
    'Yeh Hai Bakrapur': 'Janaki Vishwanathan',
    'Fate/EXTRA Last Encore': 'Akiyuki Shinbo, Yukihiro Miyamoto',
    'Santo Cachón': 'Andrés Marroquín',
    'Terrorism Close Calls': 'Docuseries Production Team',
    'DreamWorks Spooky Stories': 'Gary Trousdale, Raman Hui',
    'Great News': 'Beth McCarthy-Miller',
    'Here to Heart': 'Huang Tianren',
    'The Hollywood Masters': 'Stephen Galloway',
    'Accidentally in Love': 'Tien-Lun Yeh',
    'Ask the Doctor': 'Rachel Robinson',
    'Best.Worst.Weekend.Ever.': 'Jeremy Garelick',
    'Derren Brown: Sacrifice': 'Ben Caron',
    'Making a Murderer': 'Laura Ricciardi, Moira Demos',
    "Marvel's Daredevil": 'Phil Abraham, Peter Hoar',
    'Oddbods: Party Monsters': 'Richard Thomas',
    'Project S The Series': 'Songyos Sugmakanan, Jerajuni Lamasiri',
    'Wanderlust': 'Luke Snellin, Lucy Tcherniak',
    "My Babysitter's a Vampire": 'Bruce McDonald',
    'Rake': 'Peter Duncan, David Caesar',
    'Stunt Science': 'Docuseries Production Team',
    "Edgar Rice Burroughs' Tarzan and Jane": 'Avi Arad',
    'The Curious Creations of Christine McConnell': 'Kirk R. Thatcher',
    'The Haunting of Hill House': 'Mike Flanagan',
    'Ordinary Heroes': 'Ann Hui',
    'Salt Fat Acid Heat': 'Caroline Suh',
    'Blood Pact': 'Adrian Teijido, Alecurtis Barros',
    'Sofia the First': 'Jamie Mitchell',
    'Dancing Queen': 'John Asher',
    'Empire Games': 'Docuseries Production Team',
    'LOST SONG': 'Morita Tohei',
    'Super Monsters Save Halloween': 'Dustin McKenzie',
    'YG Future Strategy Office': 'Park Joon-soo',
    'Violet Evergarden: Special': 'Taichi Ishidate',
    'Monty Python Best Bits (mostly)': 'BBC Production Team',
    'Monty Python: Live at Aspen': 'John Moffitt',
    "Monty Python's Almost the Truth": 'Bill Jones, Ben Timlett',
    "Monty Python's Fliegender Zirkus": 'Ian MacNaughton',
    "Monty Python's Flying Circus": 'Ian MacNaughton',
    "Monty Python's Personal Best": 'Monty Python Team',
    'Hot Date': 'Luke Kelly-Clyne, Matthew Pollock',
    'Strong': 'Reality Show Production Team',
    'Three Wives One Husband': 'Docuseries Production Team',
    'Made in Mexico': 'Reality Show Production Team',
    'Reboot: The Guardian Code': 'Michael Paton, Pat Williams',
    'Skylanders Academy': 'Arthur Qwak, Solène Azernour',
    'Battlefish': 'Docuseries Production Team',
    'DRAGON PILOT: Hisone & Masotan': 'Shinji Higuchi, Hiroshi Kobayashi',
    'Maniac': 'Cary Joji Fukunaga',
    'Rafinha Bastos: Ultimatum': 'Comedy Special Production Team',
    'The Good Cop': 'Randy Zisk, Craig Zisk',
    'Mobile Suit Gundam UC': 'Kazuhiro Furuhashi',
    'Transformers: Rescue Bots': 'Frank Molieri',
    'Al Hayba': 'Samer Al Barkawi',
    'American Vandal': 'Tony Yacenda',
    'Boca Juniors Confidential': 'Rodrigo H. Vila',
    'Ingobernable': 'Pedro Pablo Ibarra, José Luis García Agraz',
    'Norm Macdonald Has a Show': 'Steve Higgins',
    'Super Monsters Monster Party': 'Dustin McKenzie',
    'The Rise of Phoenixes': 'Shen Yan, Liu Hai-bo',
    'Reversing Roe': 'Ricki Stern, Annie Sundberg',
    'Life': 'Hong Jong-chan',
    'Daniel Sloss: Live Shows': 'Comedy Special Production Team',
    'If I were an Animal': 'Docuseries Production Team',
    'Show Me the Money': 'Mnet Production Team',
    'Transformers Prime': 'David Hartman, Shaunt Nigoghossian',
    'Transformers: Robots in Disguise': 'David Hartman',
    'First and Last': 'Docuseries Production Team',
    "Marvel's Iron Fist": 'John Dahl, Uta Briesewitz',
    'Stretch Armstrong & the Flex Fighters': 'Victor Cook',
    'Monkey Twins': 'Nonthakor Baandjorn',
    'Quantico': 'David McWhirter, Patrick R. Norris',
    'Sisters': 'Emma Freeman',
    'Cathedral of the Sea': 'Jordi Frades',
    'Inside the Criminal Mind': 'Docuseries Production Team',
    'The Comedy Lineup': 'Comedy Special Production Team',
    'Ultimate Beastmaster': 'Reality Show Production Team',
    'Ultimate Beastmaster México': 'Reality Show Production Team',
    'Undercover Law': 'Andrés Beltrán, Mateo Stivelberg',
    "Chicken Soup for the Soul's Being Dad": 'Docuseries Production Team',
    'The Innocents': 'Farren Blackburn, Jamie Donoughue',
    'Party Monster: Scratching the Surface': 'Christian Simmons',
    'Stay Here': 'Reality Show Production Team',
    '72 Dangerous Animals: Asia': 'Docuseries Production Team',
    'Afflicted': 'Docuseries Production Team',
    'All About the Washingtons': 'Don Reo, Andrew D. Weyman',
    'The Originals': 'Chris Grismer, Matthew Hastings',
    'Pretty Man': 'Chinese Drama Production Team',
    'On Children': 'Chen Wei-ling',
    'Cocaine Coast': 'Carlos Sedes, Jorge Torregrossa',
    'Dinotrux Supercharged': 'David Jones',
    'Becoming Champions': 'Docuseries Production Team',
    'Switched': 'Hiroaki Matsuyama',
    'The Could’ve-Gone-All-the-Way Committee': 'Japanese Production Team',
    'A Very Secret Service': 'Alexandre Courtès'
}

In [235]:
df['director'] = df['director'].fillna(df['title'].map(movies_and_directors_8))
remaining_nulls = df['director'].isnull().sum()
print(f"Remaining null values in director column: {remaining_nulls}")

Remaining null values in director column: 1000

In [236]:
na_directors_titles_9 = missing_directors_title[1660:1860]
na_directors_titles_9

['SWORDGAI The Animation',
 'Kath and Kim',
 'El Chapo',
 'Smoking',
 'Welcome to the Family',
 'Amazing Interiors',
 'Dark Tourist',
 'Father of the Year',
 'Home: Adventures with Tip & Oh',
 'Jimmy: The True Story of a True Idiot',
 'Luna Petunia: Return to Amazia',
 'El club de los buenos infieles',
 'Camarón Revolution',
 'The Joel McHale Show with Joel McHale',
 'Meteor Garden',
 'Mossad 101',
 'Baby Ballroom',
 'Drug Lords',
 'First Team: Juventus',
 'NCIS',
 'Somewhere Between',
 'Churchill’s Secret Agents: The New Recruits',
 'Kiss Me First',
 'Hotel Transylvania',
 'Borges',
 'Life Sentence',
 'Derren Brown: Miracle',
 "Marvel's Luke Cage",
 'Club de Cuervos Presents: The Ballad of Hugo Sánchez',
 'True: Magical Friends',
 'True: Wonderful Wishes',
 'The Staircase',
 'The Night Shift',
 'Dinosaur King',
 'November 13: Attack on Paris',
 'Unbreakable Kimmy Schmidt',
 'Arrested Development',
 'The Break with Michelle Wolf',
 'Something in the Rain',
 'Trollhunters',
 'Mob Psycho 100',
 'Dance & Sing with True',
 'Inspector Gadget',
 'Saint Seiya: The Lost Canvas',
 'Bill Nye Saves the World',
 'The Who Was? Show',
 'A Little Help with Carol Burnett',
 'Kong: King of the Apes',
 'Pocoyo & Cars',
 'Pocoyo Carnival',
 'Pocoyo Halloween: Space Halloween',
 'Pocoyo Halloween: Spooky Movies',
 'Simon',
 'Spiritual House',
 'Black Crows',
 'Goodnight DJ 1',
 'Moving On',
 'Trio and a Bed',
 '海的儿子',
 'Charité',
 'The Chalet',
 'The Honeymoon Stand Up Special',
 'The Magic School Bus Rides Again',
 'AMO',
 'Troy',
 'Wakfu',
 'Star Trek: The Next Generation',
 'Fallet',
 'Loaded',
 'Doctor Foster',
 'Rapture',
 'Trailer Park Boys',
 'Trump: An American Dream',
 'Requiem',
 'The Standups',
 'Edha',
 'Wild Wild Country',
 'Secret of the Nile',
 'Tabula Rasa',
 'Children of the Whales',
 'Collateral',
 'Bad Guys: Vile City',
 'Borderliner',
 'Flint Town',
 '21 Thunder',
 'Adel Karam: Live from Beirut',
 'Derren Brown: The Push',
 'Best Lover',
 'Marseille',
 'Seven Seconds',
 "Hitler's Circle of Evil",
 'The Frankenstein Chronicles',
 'Dragons: Race to the Edge',
 'Everything Sucks!',
 'Re:Mind',
 'Valor',
 'Coach Snoop',
 'Liberated: The New Sexual Revolution',
 'Retribution',
 'Mau Nieto: Viviendo sobrio… desde el bar',
 'The Adventures of Puss in Boots',
 'Prison Playbook',
 'The Shannara Chronicles',
 'Love and Hong Kong',
 'Tiempos de guerra',
 'Katt Williams: Great America',
 'Disjointed',
 'Alejandro Riaño: Especial de stand up',
 'Tundukkan Playboy Itu',
 'Episodes',
 'Fullmetal Alchemist',
 'Lovesick',
 'Pokémon: Indigo League',
 'The Frozen Dead',
 'La Mante',
 'Wadi',
 'Part-Time Idol',
 '72 Dangerous Animals: Latin America',
 'The Indian Detective',
 'Hello, My Twenties!',
 'Cheuk Wan-Chi: Two Night Stand',
 'Wormwood',
 'Halt and Catch Fire',
 'Dawai Asmara',
 'All Hail King Julien',
 'Dhia Sofea',
 'DreamWorks Home: For the Holidays',
 'Kantaro: The Sweet Tooth Salaryman',
 'Padamu Aku Bersujud',
 "TURN: Washington's Spies",
 'Man Down',
 'Broadchurch',
 'The Many Faces of Ito',
 'Trailer Park Boys: Out of the Park: USA',
 'Argon',
 'Godless',
 'Longmire',
 'Luna Petunia',
 'Shot in the Dark',
 'The Irregular at Magic High School',
 'The Method',
 'Blazing Transfer Students',
 'Lady Dynamite',
 'Fate/Apocrypha',
 'Project Mc²',
 'Alias Grace',
 'The Family Court',
 'The Golden Path',
 'The Little Nyonya',
 'The Truth',
 'Together',
 'Beyond Stranger Things',
 'The Mist',
 'W1A',
 'Haters Back Off',
 'The Day I Met El Chapo',
 'In Laws',
 'Laws of Attraction',
 'Seven and Me',
 'West Coast Customs',
 'ID-0',
 'Kibaoh Klashers',
 'Beyblade Burst',
 'Equestria Girls: Tales of Canterlot High',
 'Justice in the City',
 'Noddy Toyland Detective',
 'Star Trek: Enterprise',
 'Star Trek: Voyager',
 'Sudden',
 'The Dream Catchers',
 'What She Put on the Table',
 'The Royal House of Windsor',
 'Mak Cun',
 "Paul Hollywood's Big Continental Road Trip",
 'Real Rob',
 'Satu Hari',
 'Terrace House: Aloha State',
 'Dark Matter',
 'VeggieTales in the City',
 'Offspring',
 'Apaches',
 'Fire Chasers',
 'No Tomorrow',
 'Reign',
 'Frequency',
 'The Vampire Diaries',
 'A Boy Name Flora A',
 'A House of Blocks',
 'Alias JJ, la celebridad del mal',
 'Chadi Jawani Budhe Nu',
 'FINAL FANTASY XIV Dad of Light',
 'Gurren Lagann',
 'High Risk',
 'LEGO Elves: Secrets of Elvendale',
 'Narcos',
 'Dinotrux',
 "Marvel's The Defenders",
 '20 Minutes',
 'Million Yen Women',
 'Wet Hot American Summer: Ten Years Later']

In [237]:
movies_and_directors_9 = {
    'SWORDGAI The Animation': 'Takahiro Ikezoe, Tomohito Naka',
    'Kath and Kim': 'Ted Emery',
    'El Chapo': 'Ernesto Contreras, José Manuel Cravioto',
    'Smoking': 'Kenji Katagiri',
    'Welcome to the Family': 'Pau Freixas',
    'Amazing Interiors': 'Docuseries Production Team',
    'Dark Tourist': 'David Farrier',
    'Father of the Year': 'Tyler Spindel',
    'Home: Adventures with Tip & Oh': 'Tristram Shapeero, TJ Sullivan',
    'Jimmy: The True Story of a True Idiot': 'Michio Mitsuno',
    'Luna Petunia: Return to Amazia': 'Jamie Whitney',
    'El club de los buenos infieles': 'Lluís Segura',
    'Camarón Revolution': 'José Escudier',
    'The Joel McHale Show with Joel McHale': 'Beth McCarthy-Miller',
    'Meteor Garden': 'Lin Helong',
    'Mossad 101': 'Daniel Syrkin',
    'Baby Ballroom': 'Docuseries Production Team',
    'Drug Lords': 'Docuseries Production Team',
    'First Team: Juventus': 'Docuseries Production Team',
    'NCIS': 'Dennis Smith, Thomas J. Wright',
    'Somewhere Between': 'Duane Clark',
    'Churchill’s Secret Agents: The New Recruits': 'Garfield Carrott, Jules Endersby',
    'Kiss Me First': 'Misha Manson-Smith, Tom Green',
    'Hotel Transylvania': 'Genndy Tartakovsky',
    'Borges': 'Alejandro de Grazia',
    'Life Sentence': 'John T. Kretchmer',
    'Derren Brown: Miracle': 'Ben Caron',
    "Marvel's Luke Cage": 'Andy Goddard, Marc Jobst',
    'Club de Cuervos Presents: The Ballad of Hugo Sánchez': 'Mark Alazraki',
    'True: Magical Friends': 'Jamie Whitney',
    'True: Wonderful Wishes': 'Jamie Whitney',
    'The Staircase': 'Jean-Xavier de Lestrade',
    'The Night Shift': 'Timothy Busfield, David Boyd',
    'Dinosaur King': 'Yoshio Gai',
    'November 13: Attack on Paris': 'Gédéon Naudet, Jules Naudet',
    'Unbreakable Kimmy Schmidt': 'Michael Engler, Tristram Shapeero',
    'Arrested Development': 'Joe Russo, Anthony Russo',
    'The Break with Michelle Wolf': 'Stan Lathan',
    'Something in the Rain': 'Ahn Pan-seok',
    'Trollhunters': 'Rodrigo Blaas, Guillermo del Toro',
    'Mob Psycho 100': 'Yuzuru Tachikawa',
    'Dance & Sing with True': 'Jamie Whitney',
    'Inspector Gadget': 'Phillip Stamp',
    'Saint Seiya: The Lost Canvas': 'Osamu Nabeshima',
    'Bill Nye Saves the World': 'Ryan Polito',
    'The Who Was? Show': 'Andy Juett',
    'A Little Help with Carol Burnett': 'Russell Norman',
    'Kong: King of the Apes': 'Vit Hayma',
    'Pocoyo & Cars': 'Guillermo García Carsí',
    'Pocoyo Carnival': 'Guillermo García Carsí',
    'Pocoyo Halloween: Space Halloween': 'Guillermo García Carsí',
    'Pocoyo Halloween: Spooky Movies': 'Guillermo García Carsí',
    'Simon': 'Julien Cayot',
    'Spiritual House': 'Horror Film Production Team',
    'Black Crows': 'Ali Mustafa',
    'Goodnight DJ 1': 'Malaysian Production Team',
    'Moving On': 'Gary Williams',
    'Trio and a Bed': 'Drama Production Team',
    '海的儿子': 'Chinese Production Team',
    'Charité': 'Sönke Wortmann',
    'The Chalet': 'Camille Bordes-Resnais',
    'The Honeymoon Stand Up Special': 'Comedy Special Production Team',
    'The Magic School Bus Rides Again': 'Richard Weston',
    'AMO': 'Brillante Mendoza',
    'Troy': 'David Farr',
    'Wakfu': 'Anthony Roux',
    'Star Trek: The Next Generation': 'Cliff Bole, Les Landau',
    'Fallet': 'Simen Alsvik',
    'Loaded': 'Ian Fitzgibbon',
    'Doctor Foster': 'Tom Vaughan',
    'Rapture': 'Docuseries Production Team',
    'Trailer Park Boys': 'Mike Clattenburg',
    'Trump: An American Dream': 'Daniel Bogado',
    'Requiem': 'Mahalia Belo',
    'The Standups': 'Comedy Special Production Team',
    'Edha': 'Daniel Burman',
    'Wild Wild Country': 'Maclain Way, Chapman Way',
    'Secret of the Nile': 'Hatem Ali',
    'Tabula Rasa': 'Kaat Beels, Jonas Govaerts',
    'Children of the Whales': 'Kyōhei Ishiguro',
    'Collateral': 'S. J. Clarkson',
    'Bad Guys: Vile City': 'Han Dong-hwa',
    'Borderliner': 'Gunnar Vikene',
    'Flint Town': 'Zackary Canepari, Drea Cooper',
    '21 Thunder': 'Jim Donovan, Jerry Ciccoritti',
    'Adel Karam: Live from Beirut': 'Jon Watts',
    'Derren Brown: The Push': 'Ben Caron',
    'Best Lover': 'Chinese-Korean Production Team',
    'Marseille': 'Florent Emilio Siri',
    'Seven Seconds': 'Gavin O\'Connor',
    "Hitler's Circle of Evil": 'Docuseries Production Team',
    'The Frankenstein Chronicles': 'Benjamin Ross',
    'Dragons: Race to the Edge': 'Elaine Bogan, John Sanford',
    'Everything Sucks!': 'Michael Mohan, Ry Russo-Young',
    'Re:Mind': 'Akira Uchikata',
    'Valor': 'Michael Robin',
    'Coach Snoop': 'Docuseries Production Team',
    'Liberated: The New Sexual Revolution': 'Dan Hunt',
    'Retribution': 'Sam Miller',
    'Mau Nieto: Viviendo sobrio… desde el bar': 'Comedy Special Production Team',
    'The Adventures of Puss in Boots': 'Roy Burdine, Johnny Castuciano',
    'Prison Playbook': 'Shin Won-ho',
    'The Shannara Chronicles': 'Brad Turner, James Marshall',
    'Love and Hong Kong': 'Japanese Production Team',
    'Tiempos de guerra': 'Manuel Gómez Pereira',
    'Katt Williams: Great America': 'Leslie Small',
    'Disjointed': 'James Burrows',
    'Alejandro Riaño: Especial de stand up': 'Comedy Special Production Team',
    'Tundukkan Playboy Itu': 'Malaysian Production Team',
    'Episodes': 'James Griffiths',
    'Fullmetal Alchemist': 'Fumihiko Sori',
    'Lovesick': 'Gordon Anderson',
    'Pokémon: Indigo League': 'Kunihiko Yuyama',
    'The Frozen Dead': 'Laurent Herbiet',
    'La Mante': 'Alexandre Laurent',
    'Wadi': 'Egyptian Production Team',
    'Part-Time Idol': 'Korean Production Team',
    '72 Dangerous Animals: Latin America': 'Docuseries Production Team',
    'The Indian Detective': 'Sandy Johnson',
    'Hello, My Twenties!': 'Lee Tae-gon',
    'Cheuk Wan-Chi: Two Night Stand': 'Comedy Special Production Team',
    'Wormwood': 'Errol Morris',
    'Halt and Catch Fire': 'Juan José Campanella, Karyn Kusama',
    'Dawai Asmara': 'Indonesian Production Team',
    'All Hail King Julien': 'Christo Stamboliev',
    'Dhia Sofea': 'Malaysian Production Team',
    'DreamWorks Home: For the Holidays': 'Tristram Shapeero',
    'Kantaro: The Sweet Tooth Salaryman': 'Kentaro Moriya',
    'Padamu Aku Bersujud': 'Indonesian Production Team',
    "TURN: Washington's Spies": 'Jeremy Webb, Andrew McCarthy',
    'Man Down': 'Al Campbell',
    'Broadchurch': 'James Strong, Euros Lyn',
    'The Many Faces of Ito': 'Ryuichi Hiroki',
    'Trailer Park Boys: Out of the Park: USA': 'Ron Murphy',
    'Argon': 'Lee Yoon-jung',
    'Godless': 'Scott Frank',
    'Longmire': 'Christopher Chulack',
    'Luna Petunia': 'Jamie Whitney',
    'Shot in the Dark': 'Docuseries Production Team',
    'The Irregular at Magic High School': 'Manabu Ono',
    'The Method': 'Yuri Bykov',
    'Blazing Transfer Students': 'Toshio Lee',
    'Lady Dynamite': 'Robert Cohen, Ben Berman',
    'Fate/Apocrypha': 'Yoshiyuki Asai',
    'Project Mc²': 'Michael McGowan, Ken Sanzel',
    'Alias Grace': 'Mary Harron',
    'The Family Court': 'Singaporean Production Team',
    'The Golden Path': 'Singaporean Production Team',
    'The Little Nyonya': 'Chia Men Yiang',
    'The Truth': 'Singaporean Production Team',
    'Together': 'Singaporean Production Team',
    'Beyond Stranger Things': 'Michael Dempsey',
    'The Mist': 'Guy Ferland, Nick Copus',
    'W1A': 'John Morton',
    'Haters Back Off': 'Todd Biermann, Andrew Gaynord',
    'The Day I Met El Chapo': 'Carlos Armella',
    'In Laws': 'Drama Production Team',
    'Laws of Attraction': 'Thai Drama Production Team',
    'Seven and Me': 'Luc Chalifour',
    'West Coast Customs': 'Reality Show Production Team',
    'ID-0': 'Goro Taniguchi',
    'Kibaoh Klashers': 'Animation Production Team',
    'Beyblade Burst': 'Katsuhito Akiyama',
    'Equestria Girls: Tales of Canterlot High': 'Ishi Rudell',
    'Justice in the City': 'Taiwanese Production Team',
    'Noddy Toyland Detective': 'Albert Pereira-Lazaro',
    'Star Trek: Enterprise': 'David Livingston, Allan Kroeker',
    'Star Trek: Voyager': 'David Livingston, Winrich Kolbe',
    'Sudden': 'Singaporean Production Team',
    'The Dream Catchers': 'Singaporean Production Team',
    'What She Put on the Table': 'Tien-Lun Yeh',
    'The Royal House of Windsor': 'Docuseries Production Team',
    'Mak Cun': 'Erma Fatima',
    "Paul Hollywood's Big Continental Road Trip": 'Docuseries Production Team',
    'Real Rob': 'Rob Schneider',
    'Satu Hari': 'Malaysian Production Team',
    'Terrace House: Aloha State': 'Reality Show Production Team',
    'Dark Matter': 'Ron Murphy, Bruce McDonald',
    'VeggieTales in the City': 'Tim Hodge',
    'Offspring': 'Emma Freeman, Kate Dennis',
    'Apaches': 'Daniel Calparsoro',
    'Fire Chasers': 'Docuseries Production Team',
    'No Tomorrow': 'Brad Silberling',
    'Reign': 'Fred Gerber, Holly Dale',
    'Frequency': 'Brad Anderson',
    'The Vampire Diaries': 'Chris Grismer, Marcos Siega',
    'A Boy Name Flora A': 'Chu Yu-ning',
    'A House of Blocks': 'Taiwanese Production Team',
    "Alias JJ, la celebridad del mal": 'Luis Alberto Restrepo',
    'Chadi Jawani Budhe Nu': 'Punjabi Production Team',
    'FINAL FANTASY XIV Dad of Light': 'Teruo Noguchi',
    'Gurren Lagann': 'Hiroyuki Imaishi',
    'High Risk': 'Wong Jing',
    'LEGO Elves: Secrets of Elvendale': 'Kirby Atkins',
    'Narcos': 'Andrés Baiz, Josef Kubota Wladyka',
    'Dinotrux': 'David Jones',
    "Marvel's The Defenders": 'S. J. Clarkson, Peter Hoar',
    '20 Minutes': 'Ali Bilgin',
    'Million Yen Women': 'Michihito Fujii',
    'Wet Hot American Summer: Ten Years Later': 'David Wain'
}

In [238]:
df['director'] = df['director'].fillna(df['title'].map(movies_and_directors_9))
remaining_nulls = df['director'].isnull().sum()
print(f"Remaining null values in director column: {remaining_nulls}")

Remaining null values in director column: 800

In [239]:
na_directors_titles_10 = missing_directors_title[1860:2060]
na_directors_titles_10

['Bountiful Blessings',
 'Close Your Eyes Before It’s Dark',
 'Entangled',
 'Fartsa',
 'Have You Ever Fallen in Love, Miss Jiang?',
 'Life Plan A and B',
 'Locust',
 'Love Storm',
 'Surviving Escobar - Alias JJ',
 'The In-Laws',
 'The IT Crowd',
 'Vexed',
 'World War II in Colour',
 'Dawn of the Croods',
 'Diamond Lover',
 'King’s War',
 'Qin Empire: Alliance',
 'The Legend of Bruce Lee',
 'Against the Tide',
 'Barbie Life in the Dreamhouse',
 'Breakout',
 'Intersection',
 'Learning Songs by Little Baby Bum: Nursery Rhyme Friends',
 'Mystic Whispers',
 'Spice Up',
 'The Oath',
 'The Truth Seekers',
 'The Ultimatum',
 'Unriddle',
 'World at Your Feet',
 'Yes We Can!',
 'Yours Fatefully',
 'Criminal Minds',
 'Gypsy',
 'Little Witch Academia',
 'Young & Hungry',
 'Pac-Man and the Ghostly Adventures',
 'Aquarius',
 '28 Moons',
 'Magic Phone',
 'My Little Baby',
 'Singles Villa',
 'Under the Black Moonlight',
 'My Only Love Song',
 'Crashing',
 'Flaked',
 'Mind Game',
 'Miniforce',
 'Off Camera',
 'The Day Will Come',
 'The Dream Job',
 'Bloodline',
 "Highland: Thailand's Marijuana Awakening",
 'The Keepers',
 'All Hail King Julien: Exiled',
 'Kazoops!',
 'Jumping Girl',
 'President',
 'What in the World Happened?',
 'Mar de Plástico',
 'Fangbone',
 'Girlboss',
 'The Mr. Peabody and Sherman Show',
 'The Miracle',
 'The Get Down',
 'Burned Cocoon',
 'Bridget Christie: Stand Up for Her',
 'Bottersnikes & Gumbles',
 'One-Punch Man',
 "Julie's Greenroom",
 'Outback Truckers',
 'Samurai Gourmet',
 'Cheer Squad',
 'Buddy Thunderstruck',
 'One More Time',
 'Love Is in the Air',
 'Tong: Memories',
 'Legend Quest',
 'The Sound of Your Heart',
 'Love Me As I Am',
 'Love for Ten: Generation of Youth',
 'Nightmare High',
 'Spark',
 'White Nights',
 'Cyborg 009: Call of Justice',
 'Grillo vs Grillo',
 "We're Lalaloopsy",
 'Star Trek: Deep Space Nine',
 'My Runway',
 'AJIN: Demi-Human',
 'Chasing Cameron',
 'Sense8',
 'Crazyhead',
 'Color of Woman',
 'Goodbye My Wife',
 'Happy And',
 "Heaven's Garden",
 'Ice Fantasy',
 'Immortal Classic',
 'InuYasha',
 'K-POP Extreme Survival',
 'Miss Panda & Mr. Hedgehog',
 'Tokyo Trial',
 'Captive',
 'White Rabbit Project',
 'Miss in Kiss',
 'The Cuba Libre Story',
 'From Dusk Till Dawn',
 'Lost & Found Music Studios',
 'Back to 1989',
 'Bromance',
 'Refresh Man',
 'Gilmore Girls: A Year in the Life',
 'La Niña',
 'Paranoid',
 'Einsatzgruppen: The Nazi Death Squads',
 'Case',
 'Danger Mouse',
 'Inborn Pair',
 'Just You',
 'Love Around',
 'Love Family',
 'Love Me or Leave Me',
 'Love Now',
 'Trailer Park Boys: Out of the Park: Europe',
 'Containment',
 'DEATH NOTE',
 'Spotless',
 'Vampire Knight',
 'StoryBots Super Songs',
 'Be with Me',
 'Be with You',
 'Fall in Love with Me',
 'Love Cheque Charge',
 "Masha's Spooky Stories",
 "Murphy's Law of Love",
 "Pac's Scary Halloween",
 'Someone Like You',
 'When I See You Again',
 'VeggieTales in the House',
 'Karol Modzelewski, Łukasz „Lotek” Lodkowski No Offense',
 'Katarzyna Piasecka, Rafał Pacześ Seriously Funny',
 'Mariusz Kałamaga, Karol Kopiec, Wiolka Walaszczyk Hilarious Trio',
 'Rafał Banaś, Michał Leja Laugh out Loud',
 'The Best of Rafał Rutkowski Olka Szczęśniak',
 'Tomasz Jachimek, Jacek Stramik Laugh at Live',
 'Jandino: Whatever it Takes',
 "Chef's Table: France",
 'Kulipari: An Army of Frogs',
 'Conspiracy',
 'Dead Set',
 'Forensic Files',
 'Saudi Arabia Uncovered',
 'The Fierce Wife',
 'Witches: A Century of Murder',
 'Glitter Force',
 'Behind Enemy Lines',
 'Caught on Camera',
 'Real Crime: Supermarket Heist (Tesco Bomber)',
 'Cocaine',
 'Edge of the Universe',
 'La Esclava Blanca',
 'LEGO Bionicle: The Journey to One',
 'Popples',
 'Marco Polo',
 'Justin Time GO!',
 'Hibana: Spark',
 '72 Cutest Animals',
 '72 Dangerous Places to Live',
 'Patton Oswalt: Talking for Clapping',
 'Cyborg 009 VS Devilman',
 'Justin Time',
 'Terrace House: Boys & Girls in the City',
 'Netflix Presents: The Characters',
 'Your lie in April',
 'Cooked',
 'Care Bears & Cousins',
 'Turbo FAST',
 "Masha's Tales",
 'Chelsea Does',
 'Sammy & Co',
 'Atelier',
 'W/ Bob & David',
 'Wakfu: The Quest for the Six Eliatrope Dofus',
 'Wet Hot American Summer',
 'H2O: Mermaid Adventures',
 'Danger Mouse: Classic Collection',
 "Oscar's Oasis",
 'Virunga: Gorillas in Peril',
 'Iliza Shlesinger: Freezing Hot',
 "BoJack Horseman Christmas Special: Sabrina's Christmas Wish",
 'Lilyhammer',
 'Goosebumps',
 'The Borgias',
 'The 4400',
 'Breaking Bad',
 'Feb-09',
 "'89",
 'แผนร้ายนายเจ้าเล่ห์',
 'Şubat']

In [240]:
movies_and_directors_10 = {
    'Bountiful Blessings': 'Kok Wai-chun',
    'Close Your Eyes Before It’s Dark': 'Chen Yu-hsun, Ko Chen-nien',
    'Entangled': 'Chineze Anyaene',
    'Fartsa': 'Egor Baranov',
    'Have You Ever Fallen in Love, Miss Jiang?': 'Wang Ming-tai',
    'Life Plan A and B': 'Tien-Lun Yeh, Huang Tian-ren',
    'Locust': 'Shahad Ameen',
    'Love Storm': 'Chiang Feng-chuan',
    'Surviving Escobar - Alias JJ': 'Luis Alberto Restrepo, Juan Carlos Vásquez',
    'The In-Laws': 'John Schultz',
    'The IT Crowd': 'Graham Linehan',
    'Vexed': 'Matt Lipsey, Ian Fitzgibbon',
    'World War II in Colour': 'Max Barber',
    'Dawn of the Croods': 'Alex Almaguer, Ruolin Li',
    'Diamond Lover': 'Chen Mingzhang',
    'King’s War': 'Gao Xixi',
    'Qin Empire: Alliance': 'Ding Hei',
    'The Legend of Bruce Lee': 'Li Wenqi',
    'Against the Tide': 'Chia Men Yiang',
    'Barbie Life in the Dreamhouse': 'Andrew Tan, Kyran Kelly',
    'Breakout': 'Singaporean Production Team',
    'Intersection': 'Gökçen Usta',
    'Learning Songs by Little Baby Bum: Nursery Rhyme Friends': 'Derek Jacombs',
    'Mystic Whispers': 'Singaporean Production Team',
    'Spice Up': 'Singaporean Production Team',
    'The Oath': 'Singaporean Production Team',
    'The Truth Seekers': 'Singaporean Production Team',
    'The Ultimatum': 'Singaporean Production Team',
    'Unriddle': 'Ng Woon Hing',
    'World at Your Feet': 'Singaporean Production Team',
    'Yes We Can!': 'Singaporean Production Team',
    'Yours Fatefully': 'Singaporean Production Team',
    'Criminal Minds': 'Glenn Kershaw, Edward Allen Bernero',
    'Gypsy': 'Sam Taylor-Johnson, Scott Winant',
    'Little Witch Academia': 'Yoh Yoshinari',
    'Young & Hungry': 'Andy Cadiff, Phill Lewis',
    'Pac-Man and the Ghostly Adventures': 'Motofumi Ruki, Avi Arad',
    'Aquarius': 'Kleber Mendonça Filho',
    '28 Moons': 'Choi Hyung-joon',
    'Magic Phone': 'Choi Hyeong-jun',
    'My Little Baby': 'Han Chul-soo, Lee Soon-ok',
    'Singles Villa': 'Chen Mingzhang',
    'Under the Black Moonlight': 'Lee Jung-pyo',
    'My Only Love Song': 'Min Do-sik',
    'Crashing': 'Phoebe Waller-Bridge',
    'Flaked': 'Wally Pfister, Tom DiCillo',
    'Mind Game': 'Masaaki Yuasa',
    'Miniforce': 'Lee Young-joon',
    'Off Camera': 'Sam Jones',
    'The Day Will Come': 'Jesper W. Nielsen',
    'The Dream Job': 'Singaporean Production Team',
    'Bloodline': 'Ed Bianchi, Daniel Attias',
    "Highland: Thailand's Marijuana Awakening": 'Docuseries Production Team',
    'The Keepers': 'Ryan White',
    'All Hail King Julien: Exiled': 'Christo Stamboliev',
    'Kazoops!': 'Richard Jeffrey',
    'Jumping Girl': 'Korean Web Drama Team',
    'President': 'Korean Production Team',
    'What in the World Happened?': 'Korean Web Drama Team',
    'Mar de Plástico': 'Alejandro Bazzano, Javier Quintas',
    'Fangbone': 'Selwyn Jayakar',
    'Girlboss': 'Christian Ditter, Jamie Babbit',
    'The Mr. Peabody and Sherman Show': 'Mike Bell, Greg Miller',
    'The Miracle': 'Korean Web Drama Team',
    'The Get Down': 'Baz Luhrmann, Ed Bianchi',
    'Burned Cocoon': 'Turkish Production Team',
    'Bridget Christie: Stand Up for Her': 'Comedy Special Production Team',
    'Bottersnikes & Gumbles': 'David Webster',
    'One-Punch Man': 'Shingo Natsume',
    "Julie's Greenroom": 'Joey Mazzarino',
    'Outback Truckers': 'Docuseries Production Team',
    'Samurai Gourmet': 'Michihito Fujii',
    'Cheer Squad': 'Docuseries Production Team',
    'Buddy Thunderstruck': 'Harry Chaskin',
    'One More Time': 'Korean Drama Team',
    'Love Is in the Air': 'Turkish Production Team',
    'Tong: Memories': 'Choi Sung-hyun',
    'Legend Quest': 'Guillermo Magee',
    'The Sound of Your Heart': 'Ha Byung-hoon',
    'Love Me As I Am': 'Turkish Production Team',
    'Love for Ten: Generation of Youth': 'Korean Web Drama Team',
    'Nightmare High': 'Hyun Moon-sub',
    'Spark': 'Korean Web Drama Team',
    'White Nights': 'Lee Jae-dong',
    'Cyborg 009: Call of Justice': 'Kenji Kamiyama, Kōdai Kakimoto',
    'Grillo vs Grillo': 'Comedic Documentary Team',
    "We're Lalaloopsy": 'Animation Production Team',
    'Star Trek: Deep Space Nine': 'David Livingston, Les Landau',
    'My Runway': 'Korean Web Drama Team',
    'AJIN: Demi-Human': 'Hiroaki Andō',
    'Chasing Cameron': 'Docuseries Production Team',
    'Sense8': 'Lana Wachowski, Lilly Wachowski',
    'Crazyhead': 'Al Mackay, Declan O\'Dwyer',
    'Color of Woman': 'Korean Drama Team',
    'Goodbye My Wife': 'Kim Pyung-joong',
    'Happy And': 'Korean Drama Team',
    "Heaven's Garden": 'Korean Drama Team',
    'Ice Fantasy': 'Ju Jue-liang',
    'Immortal Classic': 'Korean Drama Team',
    'InuYasha': 'Yasunao Aoki, Masashi Ikeda',
    'K-POP Extreme Survival': 'Lee Jung-pyo',
    'Miss Panda & Mr. Hedgehog': 'Lee Jung-sub',
    'Tokyo Trial': 'Rob W. King, Pieter Verhoeff',
    'Captive': 'Docuseries Production Team',
    'White Rabbit Project': 'Docuseries Production Team',
    'Miss in Kiss': 'Yu Zhongzhong',
    'The Cuba Libre Story': 'Emmanuel Amara, Kai Christiansen',
    'From Dusk Till Dawn': 'Robert Rodriguez',
    'Lost & Found Music Studios': 'Paul Fox, Keith Samples',
    'Back to 1989': 'Guo Chun-hui',
    'Bromance': 'Chen Rong-hui',
    'Refresh Man': 'Eriq Lin, Chang Chin-jung',
    'Gilmore Girls: A Year in the Life': 'Amy Sherman-Palladino, Daniel Palladino',
    'La Niña': 'Rodrigo Triana, Camilo Vega',
    'Paranoid': 'Mark Tonderai, John Duthie',
    'Einsatzgruppen: The Nazi Death Squads': 'Michaël Prazan',
    'Case': 'Baldvin Zophoníasson',
    'Danger Mouse': 'Robert Cullen',
    'Inborn Pair': 'Feng Kai',
    'Just You': 'Guo Chun-hui',
    'Love Around': 'Chang Chin-jung',
    'Love Family': 'Taiwanese Production Team',
    'Love Me or Leave Me': 'Taiwanese Production Team',
    'Love Now': 'Chang Chin-jung',
    'Trailer Park Boys: Out of the Park: Europe': 'Ron Murphy',
    'Containment': 'David Nutter, Charles Beeson',
    'DEATH NOTE': 'Tetsurō Araki',
    'Spotless': 'Pascal Chaumeil, Philip John',
    'Vampire Knight': 'Kiyoko Sayama',
    'StoryBots Super Songs': 'Evan Spiridellis, Gregg Spiridellis',
    'Be with Me': 'Taiwanese Production Team',
    'Be with You': 'Taiwanese Production Team',
    'Fall in Love with Me': 'Guo Chun-hui',
    'Love Cheque Charge': 'Taiwanese Production Team',
    "Masha's Spooky Stories": 'Animation Production Team',
    "Murphy's Law of Love": 'Taiwanese Production Team',
    "Pac's Scary Halloween": 'Avi Arad',
    'Someone Like You': 'Chen Rong-hui',
    'When I See You Again': 'Chen Rong-hui',
    'VeggieTales in the House': 'Tim Hodge',
    'Karol Modzelewski, Łukasz „Lotek” Lodkowski No Offense': 'Comedy Special Production Team',
    'Katarzyna Piasecka, Rafał Pacześ Seriously Funny': 'Comedy Special Production Team',
    'Mariusz Kałamaga, Karol Kopiec, Wiolka Walaszczyk Hilarious Trio': 'Comedy Special Production Team',
    'Rafał Banaś, Michał Leja Laugh out Loud': 'Comedy Special Production Team',
    'The Best of Rafał Rutkowski Olka Szczęśniak': 'Comedy Special Production Team',
    'Tomasz Jachimek, Jacek Stramik Laugh at Live': 'Comedy Special Production Team',
    'Jandino: Whatever it Takes': 'Comedy Special Production Team',
    "Chef's Table: France": 'David Gelb',
    'Kulipari: An Army of Frogs': 'Chuck Patton',
    'Conspiracy': 'Frank Pierson',
    'Dead Set': 'Yann Demange',
    'Forensic Files': 'Paul Dowling',
    'Saudi Arabia Uncovered': 'James Jones',
    'The Fierce Wife': 'Hsu Fu-chun',
    'Witches: A Century of Murder': 'Docuseries Production Team',
    'Glitter Force': 'Takashi Otsuka',
    'Behind Enemy Lines': 'John Moore',
    'Caught on Camera': 'Docuseries Production Team',
    'Real Crime: Supermarket Heist (Tesco Bomber)': 'Documentary Production Team',
    'Cocaine': 'Documentary Production Team',
    'Edge of the Universe': 'Docuseries Production Team',
    'La Esclava Blanca': 'Liliana Bocanegra, Humberto Rivera',
    'LEGO Bionicle: The Journey to One': 'Matt Ahrens',
    'Popples': 'Animation Production Team',
    'Marco Polo': 'Daniel Minahan, David Petrarca',
    'Justin Time GO!': 'Harold Harris',
    'Hibana: Spark': 'Ryuichi Hiroki',
    '72 Cutest Animals': 'Docuseries Production Team',
    '72 Dangerous Places to Live': 'Docuseries Production Team',
    'Patton Oswalt: Talking for Clapping': 'Marcus Raboy',
    'Cyborg 009 VS Devilman': 'Jun Kawagoe',
    'Justin Time': 'Harold Harris',
    'Terrace House: Boys & Girls in the City': 'Reality Show Production Team',
    'Netflix Presents: The Characters': 'Comedy Production Team',
    'Your lie in April': 'Kyōhei Ishiguro',
    'Cooked': 'Alex Gibney',
    'Care Bears & Cousins': 'Andrew Young',
    'Turbo FAST': 'Chris Prynoski',
    "Masha's Tales": 'Animation Production Team',
    'Chelsea Does': 'Eddie Schmidt',
    'Sammy & Co': 'Animation Production Team',
    'Atelier': 'Michiko Ohara',
    'W/ Bob & David': 'Keith Truesdell',
    'Wakfu: The Quest for the Six Eliatrope Dofus': 'Anthony Roux',
    'Wet Hot American Summer': 'David Wain',
    'H2O: Mermaid Adventures': 'Tian Meifeng',
    'Danger Mouse: Classic Collection': 'Animation Production Team',
    "Oscar's Oasis": 'Tae-Sik Shin',
    'Virunga: Gorillas in Peril': 'Orlando von Einsiedel',
    'Iliza Shlesinger: Freezing Hot': 'Jay Chapman',
    "BoJack Horseman Christmas Special: Sabrina's Christmas Wish": 'Joel Moser',
    'Lilyhammer': 'Simen Alsvik, Geir Henning Hopland',
    'Goosebumps': 'Rob Letterman',
    'The Borgias': 'Neil Jordan',
    'The 4400': 'Scott Peters',
    'Breaking Bad': 'Vince Gilligan',
    'Feb-09': 'Philippe Martinez',
    "'89": 'Dave Stewart',
    'แผนร้ายนายเจ้าเล่ห์': 'Thai Drama Production Team',
    'Şubat': 'Volkan Kocatürk'
}

In [241]:
df['director'] = df['director'].fillna(df['title'].map(movies_and_directors_10))
remaining_nulls = df['director'].isnull().sum()
print(f"Remaining null values in director column: {remaining_nulls}")

Remaining null values in director column: 600

In [242]:
na_directors_titles_11 = missing_directors_title[2060:2260]
na_directors_titles_11

['100 Days Of Solitude',
 '100% Hotter',
 '12 Years Promise',
 '13TH: A Conversation with Oprah Winfrey & Ava DuVernay',
 '2015 Dream Concert',
 '21 Sarfarosh: Saragarhi 1897',
 '9 Months That Made You',
 'A Good Wife',
 'A Man Called God',
 'A new Capitalism',
 "A Young Doctor's Notebook and Other Stories",
 'A.D. Kingdom and Empire',
 'Abdo Mota',
 'Adam Ruins Everything',
 'Africa',
 'Age Gap Love',
 'Age of Glory',
 'Agent Raghav',
 'Ainsley Eats the Streets',
 'Alarmoty in the Land of Fire',
 'Alphablocks',
 "America's Book of Secrets",
 'American Crime',
 'American Odyssey',
 'An Innocent Mistake',
 'Ancient Aliens',
 'Anjaan: Rural Myths',
 'Anjaan: Special Crimes Unit',
 'Anthony Bourdain: Parts Unknown',
 '忍者ハットリくん',
 'Atomic Puppet',
 'Aussie Gold Hunters',
 'Bad Education',
 'Badalte Rishton Ki Dastaan',
 'Bala Loca',
 'Bangkok Bachelors',
 'Bat Pat',
 'Bates Motel',
 'Battle Creek',
 'Battlefield Recovery',
 'Be-Be-Bears',
 'Beary Tales',
 'Beast Legends',
 'Beating Again',
 'Beauty & the Beast',
 'Beauty and the Bitches',
 'Behind the Newsroom',
 'Behzat Ç.',
 'Being Mary Jane: The Series',
 'Ben 10',
 'Berlin, I Love You',
 'Beyblade: Metal Fusion',
 'Bh Se Bhade',
 'Bhaage Re Mann',
 'Big Bad Beetleborgs',
 'Big Dreams, Small Spaces',
 'Bitten',
 'Black Heart',
 'Blood & Treasures',
 'Blue Planet II',
 'Bob Ross: Beauty Is Everywhere',
 'Bondi Rescue',
 'Border Patrol',
 'Borderline',
 'Botched Up Bodies',
 'Brain Games',
 'Braxton Family Values',
 'Bringing Sexy Back',
 'Brown Nation',
 'Buddha',
 'Bure Kaam Bura Natija, Kyun Bhai Chacha Haan Bhatija',
 'Burnistoun',
 'Cabins in the Wild with Dick Strawbridge',
 'Cain and Abel',
 'Calico Critters',
 'Call Me Francis',
 'Camp X',
 'Can We Get Married?',
 'Cannabis',
 'Care Bears: Welcome to Care-a-Lot',
 'Case Closed',
 'Castle of Stars',
 'Chasing Monsters',
 'Cheapest Weddings',
 'Cheers',
 'Chef & My Fridge',
 "Chewin' the Fat",
 'Chewing Gum',
 'Chill with Bob Ross',
 'Christiane Amanpour: Sex & Love Around the World',
 'Chuck Chicken',
 'City in the Sky',
 'Civilizations',
 'Classic Legends',
 'Click for Murder',
 'Club Friday The Series 6',
 'Club Friday The Series 7',
 'Club Friday The Series 8',
 'Club Friday To Be Continued - Friend & Enemy',
 'Club Friday To Be Continued - My Beautiful Tomboy',
 'Club Friday To Be Continued - The Promise',
 'Cold Case Files',
 'Cold Case Files Classic',
 'Comedy Bang! Bang!',
 'Comedy High School',
 'Conan Without Borders',
 'Cooking on High',
 'Court Justice',
 'Crime Time',
 "Dad's Army",
 'Dance Academy',
 'Dandy',
 'Dangerous Roads',
 'Dare to Be Wild',
 'Darr Sabko Lagta Hai',
 'Day and Night',
 'Days We Stared at the Sun',
 'Deep Undercover Collection',
 'Deep Water',
 'Devlok with Devdutt Pattanaik',
 'Dexter',
 'Diana: In Her Own Words',
 'Dinner for Five',
 'Dino Hunt',
 'Diva Brides',
 'Doomsday Preppers',
 'Dramaworld',
 'Driven to Dance',
 'Drugs, Inc.',
 'Dueños del paraíso',
 'Earth to Luna!',
 "Earth's Natural Wonders",
 "Earth's Natural Wonders: Life at the Extremes",
 'Easy Fortune Happy Life',
 'El Barco',
 'El Cartel',
 'El Cartel 2',
 'El Chavo',
 'El Clon',
 'El Vato',
 'Emogenius',
 'Encerrados',
 'Encounters with Evil',
 'Enemigo íntimo',
 'Ethirmarai',
 'Eurovision Song Contest',
 'Everyday Miracles',
 'Ex-Boyfriend',
 'Extras',
 'Ezel',
 'Fairy Tail',
 'Fake or Fortune?',
 'Fatal Destiny',
 'Fear Files... Har Mod Pe Darr',
 'Filinta',
 'Fit for Fashion',
 'Fix It and Finish It',
 'Flowering Heart',
 'Food: Delicious Science',
 'Footprints in the Sand',
 'For the Win',
 'Forces of Nature',
 'Forget Me Not',
 'Four Seasons in Havana',
 'Frasier',
 'Friday Night Tykes',
 'Friends',
 'Frozen Planet: On Thin Ice',
 'Frozen Planet: The Epic Journey',
 'Gabru: Hip Hop Revolution',
 'Galavant',
 'Game Winning Hit',
 'Gangs of Hassepur',
 'Gargantia on the Verdurous Planet',
 'Gender Revolution: A Journey with Katie Couric',
 'Genius of the Ancient World',
 'Genius of the Modern World',
 'Gentlemen and Gangsters',
 'Get Shorty',
 'Ghost Town Gold',
 'Glowing Embers',
 'Goldie & Bear',
 'Gomorrah',
 'Gossip Girl',
 'Grand Designs',
 'Grand Hotel',
 'Great Interior Design Challenge',
 'Great Yellowstone Thaw',
 'Gunslinger Girl',
 'Ha Unlimited',
 'Haapus',
 'Hannibal',
 'Happy 300 Days',
 'Happy Valley',
 'Happyish',
 'Harlem Globetrotters: The Team That Changed the World',
 'Harold Shipman - Driven to Kill',
 'Hart of Dixie',
 'Hati Perempuan',
 'Haven']

In [243]:
movies_and_directors_11 = {
    '100 Days Of Solitude': 'José Díaz, Gerardo Olivares',
    '100% Hotter': 'Reality Show Production Team',
    '12 Years Promise': 'Kim Do-hyung, Yoon Jae-won',
    '13TH: A Conversation with Oprah Winfrey & Ava DuVernay': 'Ava DuVernay',
    '2015 Dream Concert': 'Music Concert Production Team',
    '21 Sarfarosh: Saragarhi 1897': 'Raj Acharya',
    '9 Months That Made You': 'Docuseries Production Team',
    'A Good Wife': 'Chen Rong-hui',
    'A Man Called God': 'Lee Hyung-sun',
    'A new Capitalism': 'Daniel Rezende',
    "A Young Doctor's Notebook and Other Stories": 'Alex Hardcastle, Robert McKillop',
    'A.D. Kingdom and Empire': 'Roma Downey, Mark Burnett',
    'Abdo Mota': 'Mohamed Hamdy',
    'Adam Ruins Everything': 'Paul Briganti, Laura Murphy',
    'Africa': 'Alastair Fothergill',
    'Age Gap Love': 'Docuseries Production Team',
    'Age of Glory': 'Malaysian Production Team',
    'Agent Raghav': 'Jitendra Wilkhoo',
    'Ainsley Eats the Streets': 'Docuseries Production Team',
    'Alarmoty in the Land of Fire': 'Moataz El Fany',
    'Alphablocks': 'Joe Elliot',
    "America's Book of Secrets": 'Docuseries Production Team',
    'American Crime': 'John Ridley',
    'American Odyssey': 'Peter Horton',
    'An Innocent Mistake': 'Chinese Drama Production Team',
    'Ancient Aliens': 'Docuseries Production Team',
    'Anjaan: Rural Myths': 'Indian Docuseries Team',
    'Anjaan: Special Crimes Unit': 'Indian Drama Production Team',
    'Anthony Bourdain: Parts Unknown': 'Tom Vitale',
    '忍者ハットリくん': 'Hiroshi Sasagawa',
    'Atomic Puppet': 'Jerry Reynolds',
    'Aussie Gold Hunters': 'Docuseries Production Team',
    'Bad Education': 'Ben Gregor, Al Campbell',
    'Badalte Rishton Ki Dastaan': 'Ravi Bhushan',
    'Bala Loca': 'Gabriel Díaz, Oscar Godoy',
    'Bangkok Bachelors': 'Thai Production Team',
    'Bat Pat': 'Roberto Foster',
    'Bates Motel': 'Tucker Gates, Ed Bianchi',
    'Battle Creek': 'Bryan Singer, Andrew Bernstein',
    'Battlefield Recovery': 'Docuseries Production Team',
    'Be-Be-Bears': 'Alexey Mironov',
    'Beary Tales': 'Animation Production Team',
    'Beast Legends': 'Docuseries Production Team',
    'Beating Again': 'Ji Yeong-soo',
    'Beauty & the Beast': 'Gary Trousdale, Kirk Wise',
    'Beauty and the Bitches': 'Thai Drama Production Team',
    'Behind the Newsroom': 'Chinese Drama Production Team',
    'Behzat Ç.': 'Serdar Akar, Sadullah Şentürk',
    'Being Mary Jane: The Series': 'Salim Akil',
    'Ben 10': 'Man of Action',
    'Berlin, I Love You': 'Dianna Agron, Peter Chelsom',
    'Beyblade: Metal Fusion': 'Kunihiko Yuyama',
    'Bh Se Bhade': 'Kedar Shinde',
    'Bhaage Re Mann': 'Indian Drama Production Team',
    'Big Bad Beetleborgs': 'John Putch',
    'Big Dreams, Small Spaces': 'Docuseries Production Team',
    'Bitten': 'James Dunnison, Grant Harvey',
    'Black Heart': 'Turkish Production Team',
    'Blood & Treasures': 'Action Production Team',
    'Blue Planet II': 'James Honeyborne',
    'Bob Ross: Beauty Is Everywhere': 'Bob Ross',
    'Bondi Rescue': 'Docuseries Production Team',
    'Border Patrol': 'Docuseries Production Team',
    'Borderline': 'Matt Lipsey',
    'Botched Up Bodies': 'Docuseries Production Team',
    'Brain Games': 'Docuseries Production Team',
    'Braxton Family Values': 'Reality Show Production Team',
    'Bringing Sexy Back': 'Reality Show Production Team',
    'Brown Nation': 'Matt Grubb',
    'Buddha': 'Dharmesh Shah',
    'Bure Kaam Bura Natija, Kyun Bhai Chacha Haan Bhatija': 'Indian Animation Team',
    'Burnistoun': 'Iain Davidson',
    'Cabins in the Wild with Dick Strawbridge': 'Docuseries Production Team',
    'Cain and Abel': 'Kim Hyung-shik',
    'Calico Critters': 'Animation Production Team',
    'Call Me Francis': 'Daniele Luchetti',
    'Camp X': 'Docuseries Production Team',
    'Can We Get Married?': 'Kim Yoon-cheol',
    'Cannabis': 'Lucie Borleteau',
    'Care Bears: Welcome to Care-a-Lot': 'Jeff Gordon',
    'Case Closed': 'Kenji Kodama, Yasuichiro Yamamoto',
    'Castle of Stars': 'Animation Production Team',
    'Chasing Monsters': 'Docuseries Production Team',
    'Cheapest Weddings': 'Docuseries Production Team',
    'Cheers': 'James Burrows',
    'Chef & My Fridge': 'Korean Variety Show Team',
    "Chewin' the Fat": 'Michael Hines',
    'Chewing Gum': 'Tom Marshall, Simon Neal',
    'Chill with Bob Ross': 'Bob Ross',
    'Christiane Amanpour: Sex & Love Around the World': 'Docuseries Production Team',
    'Chuck Chicken': 'Animation Production Team',
    'City in the Sky': 'Docuseries Production Team',
    'Civilizations': 'Docuseries Production Team',
    'Classic Legends': 'Indian Docuseries Team',
    'Click for Murder': 'Docuseries Production Team',
    'Club Friday The Series 6': 'Thai Production Team',
    'Club Friday The Series 7': 'Thai Production Team',
    'Club Friday The Series 8': 'Thai Production Team',
    'Club Friday To Be Continued - Friend & Enemy': 'Thai Production Team',
    'Club Friday To Be Continued - My Beautiful Tomboy': 'Thai Production Team',
    'Club Friday To Be Continued - The Promise': 'Thai Production Team',
    'Cold Case Files': 'Docuseries Production Team',
    'Cold Case Files Classic': 'Docuseries Production Team',
    'Comedy Bang! Bang!': 'Benjamin Berman',
    'Comedy High School': 'Indian Variety Team',
    'Conan Without Borders': 'Conan O\'Brien',
    'Cooking on High': 'Reality Show Production Team',
    'Court Justice': 'Docuseries Production Team',
    'Crime Time': 'Gustavo Bonafé',
    "Dad's Army": 'David Croft',
    'Dance Academy': 'Jeffrey Walker, Cherie Nowlan',
    'Dandy': 'Drama Production Team',
    'Dangerous Roads': 'Docuseries Production Team',
    'Dare to Be Wild': 'Vivienne De Courcy',
    'Darr Sabko Lagta Hai': 'Soumik Sen',
    'Day and Night': 'Wang Wei',
    'Days We Stared at the Sun': 'Cheng Yu-chieh',
    'Deep Undercover Collection': 'Docuseries Production Team',
    'Deep Water': 'Richard Roxburgh',
    'Devlok with Devdutt Pattanaik': 'Indian Docuseries Team',
    'Dexter': 'John Dahl, Steve Shill',
    'Diana: In Her Own Words': 'David Tillman',
    'Dinner for Five': 'Jon Favreau',
    'Dino Hunt': 'Docuseries Production Team',
    'Diva Brides': 'Reality Show Production Team',
    'Doomsday Preppers': 'Docuseries Production Team',
    'Dramaworld': 'Chris Martin',
    'Driven to Dance': 'Docuseries Production Team',
    'Drugs, Inc.': 'Docuseries Production Team',
    'Dueños del paraíso': 'Lilo Vilaplana, Nicolás Di Blasi',
    'Earth to Luna!': 'Celia Catunda, Kiko Mistrorigo',
    "Earth's Natural Wonders": 'Docuseries Production Team',
    "Earth's Natural Wonders: Life at the Extremes": 'Docuseries Production Team',
    'Easy Fortune Happy Life': 'Liu Jun-jie',
    'El Barco': 'David Molina, Sandra Gallego',
    'El Cartel': 'Luis Alberto Restrepo',
    'El Cartel 2': 'Luis Alberto Restrepo',
    'El Chavo': 'Enrique Segoviano, Roberto Gómez Bolaños',
    'El Clon': 'Mauricio Cruz, Agustín Restrepo',
    'El Vato': 'Chava Cartas',
    'Emogenius': 'Game Show Production Team',
    'Encerrados': 'Docuseries Production Team',
    'Encounters with Evil': 'Docuseries Production Team',
    'Enemigo íntimo': 'Danny Gavidia, Felipe Aguilar',
    'Ethirmarai': 'Tamil Production Team',
    'Eurovision Song Contest': 'Live Television Production Team',
    'Everyday Miracles': 'Docuseries Production Team',
    'Ex-Boyfriend': 'Taiwanese Production Team',
    'Extras': 'Ricky Gervais, Stephen Merchant',
    'Ezel': 'Uluç Bayraktar',
    'Fairy Tail': 'Shinji Ishihira',
    'Fake or Fortune?': 'Docuseries Production Team',
    'Fatal Destiny': 'Drama Production Team',
    'Fear Files... Har Mod Pe Darr': 'Indian Horror Production Team',
    'Filinta': 'Kudret Sabancı',
    'Fit for Fashion': 'Reality Show Production Team',
    'Fix It and Finish It': 'Reality Show Production Team',
    'Flowering Heart': 'Animation Production Team',
    'Food: Delicious Science': 'Docuseries Production Team',
    'Footprints in the Sand': 'Drama Production Team',
    'For the Win': 'Reality Show Production Team',
    'Forces of Nature': 'Docuseries Production Team',
    'Forget Me Not': 'Kei Horie',
    'Four Seasons in Havana': 'Felix Viscarret',
    'Frasier': 'David Lee, Kelsey Grammer',
    'Friday Night Tykes': 'Docuseries Production Team',
    'Friends': 'Gary Halvorson, Kevin S. Bright',
    'Frozen Planet: On Thin Ice': 'Alastair Fothergill',
    'Frozen Planet: The Epic Journey': 'Alastair Fothergill',
    'Gabru: Hip Hop Revolution': 'Indian Production Team',
    'Galavant': 'Chris Koch, John Fortenberry',
    'Game Winning Hit': 'Sports Production Team',
    'Gangs of Hassepur': 'Indian Comedy Production Team',
    'Gargantia on the Verdurous Planet': 'Kazuya Murata',
    'Gender Revolution: A Journey with Katie Couric': 'Katie Couric',
    'Genius of the Ancient World': 'Docuseries Production Team',
    'Genius of the Modern World': 'Docuseries Production Team',
    'Gentlemen and Gangsters': 'Mikael Marcimain',
    'Get Shorty': 'Adam Arkin, Adam Bernstein',
    'Ghost Town Gold': 'Docuseries Production Team',
    'Glowing Embers': 'Drama Production Team',
    'Goldie & Bear': 'Chris Gilligan',
    'Gomorrah': 'Stefano Sollima, Francesca Comencini',
    'Gossip Girl': 'Mark Piznarski, Norman Buckley',
    'Grand Designs': 'Docuseries Production Team',
    'Grand Hotel': 'Carlos Sedes',
    'Great Interior Design Challenge': 'Docuseries Production Team',
    'Great Yellowstone Thaw': 'Docuseries Production Team',
    'Gunslinger Girl': 'Morio Asaka',
    'Ha Unlimited': 'Comedy Special Production Team',
    'Haapus': 'Avadhoot Gupte',
    'Hannibal': 'David Slade, Michael Rymer',
    'Happy 300 Days': 'Taiwanese Production Team',
    'Happy Valley': 'Euros Lyn, Sally Wainwright',
    'Happyish': 'Ken Kwapis',
    'Harlem Globetrotters: The Team That Changed the World': 'Docuseries Production Team',
    'Harold Shipman - Driven to Kill': 'Docuseries Production Team',
    'Hart of Dixie': 'David Paymer, Tim Matheson',
    'Hati Perempuan': 'Malaysian Production Team',
    'Haven': 'T.W. Peacocke, Lee Rose'
}

In [244]:
df['director'] = df['director'].fillna(df['title'].map(movies_and_directors_11))
remaining_nulls = df['director'].isnull().sum()
print(f"Remaining null values in director column: {remaining_nulls}")

Remaining null values in director column: 400

In [245]:
na_directors_titles_12 = missing_directors_title[2260:2460]
na_directors_titles_12

['Heavy Rescue: 401',
 'Helix',
 'Hell on Wheels',
 'Herrens veje',
 'Hidden Singer',
 'Highway Thru Hell',
 'Highway to Heaven',
 'Hinterland',
 'Historia de un clan',
 "History's Greatest Hoaxes",
 'Hogie the Globehopper',
 'Hormones',
 'Horror Homes',
 'Hotel Beau Séjour',
 'How to Live Mortgage Free with Sarah Beeny',
 'Humsafar',
 'Hunters of the South Seas',
 'Huntik: Secrets and Seekers',
 "Hyori's Bed & Breakfast",
 'I Am Me!',
 "I'm Sorry",
 'Idiotest',
 'In Between',
 "India: Nature's Wonderland",
 'Inside The Freemasons',
 'Inside the Mind of a Serial Killer',
 'Inside the Mossad',
 'Inst@famous',
 'Intelligence',
 'Iron Man: Armored Adventures',
 'Islands of the Future',
 '마녀사냥',
 "Jake's Buccaneer Blast",
 'Japanese Style Originator',
 'Jeopardy!',
 'Jericho',
 'Jhansi Ki Rani',
 'JingleKids',
 'John Mellencamp: Plain Spoken',
 'Juana Brava',
 'Juana Inés',
 'Julius Jr.',
 'K',
 'Kaçak',
 'Kanika',
 'Ken Burns: The West',
 'Khaani',
 'Khan: No. 1 Crime Hunter',
 'Khelti Hai Zindagi Aankh Micholi',
 'Khotey Sikkey',
 'Kikoriki',
 'Kiss The Series',
 'Kitten Rescuers',
 'Knights of Sidonia',
 'Kon Kon Kon',
 'Krish Trish and Baltiboy',
 'Krish Trish and Baltiboy: Part II',
 'Krishna Balram',
 'Kurt Seyit & Sura',
 'La Familia P. Luche',
 'La Femme',
 'La Piloto',
 'La Rosa de Guadalupe',
 'Lady-Like',
 'Lady, la vendedora de rosas',
 'Land Girls',
 'Last',
 'Learning Time with Timmy',
 'Legends of Strength',
 'Lego Friends',
 'LEGO Ninjago: Masters of Spinjitzu: Day of the Departed',
 'Leo & Tig',
 'License to Drill: Louisiana',
 'Life on Location',
 'Life Story',
 "Limmy's Show!",
 'Little Lunch',
 'Little Singham Bandarpur Mein Hu Ha Hu',
 'Liv and Maddie',
 'Lo que la verdad esconde: El caso Asunta (Operacion Nenúfar)',
 'Lo que la vida me robó',
 'LoliRock',
 'Los 10 años de Peter Capusotto',
 'Lost Girl',
 'Love Cuisine',
 'Love Rain',
 'Love Rhythms - Accidental Daddy',
 'Love Your Garden',
 'Lucky Days',
 'Mad Men',
 'Magi: Adventure of Sinbad',
 'Maharakshak Devi',
 'Maharakshak: Aryan',
 'Mahi Way',
 'Mahmut & Meryem',
 'Man vs Wild with Sunny Leone',
 'Marching Orders',
 'Maron',
 'Married at First Sight',
 'Mary Portas: Secret Shopper',
 'Mega Food',
 'MegaTruckers',
 'Melodies of Life - Born This Way',
 'Mere Papa Hero Hiralal',
 'Merlí',
 'Mexico Diseña',
 'Midnight Misadventures With Mallika Dua',
 'Mighty Morphin Alien Rangers',
 'Mini Wolf',
 'Minute to Win It',
 'Miss Dynamite',
 'Miss Rose',
 'Momo Salon',
 'Money for Nothing',
 'Monkey Planet',
 'Monster Math Squad',
 "Monty Don's Italian Gardens",
 'Mr. Young',
 'Murderous Affairs',
 'Mutant Busters',
 'My Hotter Half',
 'My Life My Story',
 'My Tattoo Addiction',
 'Mystery Science Theater 3000',
 'Nature: Animals With Cameras',
 'NATURE: Natural Born Hustlers',
 'Nature: Raising the Dinosaur Giant',
 "Nature's Great Events (2009)",
 "Nature's Great Events: Diaries",
 "Nature's Great Race",
 "Nature's Weirdest Events",
 'Nazi Mega Weapons',
 'Nightmare Tenants, Slum Landlords',
 'Ninja Hattori',
 'Ninja Turtles: The Next Mutation',
 'Nobel',
 'North & South',
 'NOVA: Bird Brain',
 'NOVA: Killer Floods',
 'NSU German History X',
 'Nuestra Lucha Libre',
 'Nura: Rise of the Yokai Clan: Demon Capital',
 'Nurse Jackie',
 'Nurses Who Kill',
 'O-Negative, Love Can’t Be Designed',
 'OCTB',
 "Oh No! It's an Alien Invasion",
 'Ollie & Moon',
 'One Heart: The A.R. Rahman Concert Film',
 'One Strange Rock',
 'Operation Gold Rush',
 'Operation Ouch!',
 'Operation Proposal',
 'Our Shining Days',
 'P. King Duckling',
 'Pacific Heat',
 'Pajanimals',
 'Paranormal Survivor',
 'Parks and Recreation',
 'Pasión de Gavilanes',
 'Pawn Stars',
 "Pee-wee's Playhouse",
 'Penny Dreadful',
 'Person of Interest',
 'Planet Earth II',
 'Portlandia',
 'Powder',
 'Power Battle Watch Car',
 'Power Rangers Dino Charge',
 'Power Rangers Dino Super Charge',
 'Power Rangers Dino Thunder',
 'Power Rangers in Space',
 'Power Rangers Jungle Fury',
 'Power Rangers Lightspeed Rescue',
 'Power Rangers Lost Galaxy',
 'Power Rangers Mystic Force',
 'Power Rangers Ninja Storm',
 'Power Rangers Operation Overdrive',
 'Power Rangers RPM',
 'Power Rangers S.P.D.',
 'Power Rangers Samurai',
 'Power Rangers Samurai: Christmas Together, Friends Forever (Christmas Special)',
 'Power Rangers Samurai: Clash of the Red Rangers',
 'Power Rangers Samurai: Party Monsters (Halloween Special)',
 'Power Rangers Super Megaforce',
 'Power Rangers Super Samurai',
 'Power Rangers Super Samurai: Stuck on Christmas',
 'Power Rangers Super Samurai: Trickster Treat',
 'Power Rangers Time Force',
 'Power Rangers Turbo',
 'Power Rangers Wild Force',
 'Power Rangers Zeo',
 'Power Rangers: Megaforce',
 'Power Rangers: Megaforce: Raising Spirits',
 'Prohibition: A Film by Ken Burns and Lynn Novick',
 'Psiconautas',
 'Pyaar Tune Kya Kiya',
 'Qué pena tu serie',
 'Queen of No Marriage',
 'Queens of Comedy']

In [246]:
movies_and_directors_12 = {
    'Heavy Rescue: 401': 'Docuseries Production Team',
    'Helix': 'Brad Turner, Steven A. Adelson',
    'Hell on Wheels': 'David Von Ancken, Michael Nankin',
    'Herrens veje': 'Kaspar Munk',
    'Hidden Singer': 'Korean Variety Team',
    'Highway Thru Hell': 'Docuseries Production Team',
    'Highway to Heaven': 'Michael Landon',
    'Hinterland': 'Marc Evans, Gareth Bryn',
    'Historia de un clan': 'Luis Ortega',
    "History's Greatest Hoaxes": 'Docuseries Production Team',
    'Hogie the Globehopper': 'Animation Production Team',
    'Hormones': 'Songyos Sugmakanan',
    'Horror Homes': 'Docuseries Production Team',
    'Hotel Beau Séjour': 'Nathalie Basteyns, Kaat Beels',
    'How to Live Mortgage Free with Sarah Beeny': 'Docuseries Production Team',
    'Humsafar': 'Sarmad Khoosat',
    'Hunters of the South Seas': 'Docuseries Production Team',
    'Huntik: Secrets and Seekers': 'Iginio Straffi',
    "Hyori's Bed & Breakfast": 'Ma Geon-young, Jung Hyo-min',
    'I Am Me!': 'Drama Production Team',
    "I'm Sorry": 'Andrea Savage',
    'Idiotest': 'Game Show Production Team',
    'In Between': 'Taiwanese Production Team',
    "India: Nature's Wonderland": 'Docuseries Production Team',
    'Inside The Freemasons': 'Docuseries Production Team',
    'Inside the Mind of a Serial Killer': 'Docuseries Production Team',
    'Inside the Mossad': 'Duki Dror',
    'Inst@famous': 'Documentary Production Team',
    'Intelligence': 'Michael Offer, Alrick Riley',
    'Iron Man: Armored Adventures': 'Stephane Juffe, Philippe Guyenne',
    'Islands of the Future': 'Docuseries Production Team',
    '마녀사냥': 'JTBC Production Team',
    "Jake's Buccaneer Blast": 'Animation Production Team',
    'Japanese Style Originator': 'Japanese Variety Team',
    'Jeopardy!': 'Kevin McCarthy, Clay Jacobsen',
    'Jericho': 'Jon Turteltaub, Sanford Bookstaver',
    'Jhansi Ki Rani': 'Jitendra Srivastava',
    'JingleKids': 'Anton Vereshchagin',
    'John Mellencamp: Plain Spoken': 'Paul Shoulberg',
    'Juana Brava': 'Nicolás Acuña',
    'Juana Inés': 'Patricia Arriaga Jordán',
    'Julius Jr.': 'Brooks Wachtel',
    'K': 'Shingo Suzuki',
    'Kaçak': 'Volkan Kocatürk',
    'Kanika': 'Thai Horror Team',
    'Ken Burns: The West': 'Stephen Ives',
    'Khaani': 'Anjum Shahzad',
    'Khan: No. 1 Crime Hunter': 'Pakistani Production Team',
    'Khelti Hai Zindagi Aankh Micholi': 'Ravi Bhushan',
    'Khotey Sikkey': 'Luv Ranjan',
    'Kikoriki': 'Denis Chernov',
    'Kiss The Series': 'Chatkaew Susiwa',
    'Kitten Rescuers': 'Docuseries Production Team',
    'Knights of Sidonia': 'Kobun Shizuno, Hiroyuki Seshita',
    'Kon Kon Kon': 'Drama Production Team',
    'Krish Trish and Baltiboy': 'Munjal Shroff, Tilak Shetty',
    'Krish Trish and Baltiboy: Part II': 'Munjal Shroff, Tilak Shetty',
    'Krishna Balram': 'Rajiv Chilaka',
    'Kurt Seyit & Sura': 'Hilal Saral',
    'La Familia P. Luche': 'Roberto Gómez Bolaños, Eugenio Derbez',
    'La Femme': 'Drama Production Team',
    'La Piloto': 'Alvaro Curiel, David Ruiz',
    'La Rosa de Guadalupe': 'José Ángel García',
    'Lady-Like': 'Tyler Cole',
    'Lady, la vendedora de rosas': 'Juan Felipe Cano',
    'Land Girls': 'Paul Gibson',
    'Last': 'Jo Nam-gook',
    'Learning Time with Timmy': 'Animation Production Team',
    'Legends of Strength': 'Docuseries Production Team',
    'Lego Friends': 'Trylle Vangsgaard',
    'LEGO Ninjago: Masters of Spinjitzu: Day of the Departed': 'Peter Hausner',
    'Leo & Tig': 'Nikolai Kozlov',
    'License to Drill: Louisiana': 'Docuseries Production Team',
    'Life on Location': 'Docuseries Production Team',
    'Life Story': 'Emma Napper',
    "Limmy's Show!": 'Brian Limond',
    'Little Lunch': 'Ian Reba',
    'Little Singham Bandarpur Mein Hu Ha Hu': 'Rajiv Chilaka',
    'Liv and Maddie': 'Andy Fickman, John D. Beck',
    'Lo que la verdad esconde: El caso Asunta (Operacion Nenúfar)': 'Elías León Siminiani',
    'Lo que la vida me robó': 'Sergio Cataño, Claudio Reyes Rubio',
    'LoliRock': 'Jean-Louis Vandestoc',
    'Los 10 años de Peter Capusotto': 'Pedro Saborido',
    'Lost Girl': 'John Fawcett, Steve DiMarco',
    'Love Cuisine': 'Taiwanese Production Team',
    'Love Rain': 'Yoon Seok-ho',
    'Love Rhythms - Accidental Daddy': 'Thai Production Team',
    'Love Your Garden': 'Docuseries Production Team',
    'Lucky Days': 'Taiwanese Production Team',
    'Mad Men': 'Phil Abraham, Lesli Linka Glatter',
    'Magi: Adventure of Sinbad': 'Yoshikazu Miyao',
    'Maharakshak Devi': 'Indian Production Team',
    'Maharakshak: Aryan': 'Indian Production Team',
    'Mahi Way': 'Nupur Asthana',
    'Mahmut & Meryem': 'Mehmet Ada Öztekin',
    'Man vs Wild with Sunny Leone': 'Reality Show Production Team',
    'Marching Orders': 'Docuseries Production Team',
    'Maron': 'Marc Maron, Luke Matheny',
    'Married at First Sight': 'Reality Show Production Team',
    'Mary Portas: Secret Shopper': 'Docuseries Production Team',
    'Mega Food': 'Docuseries Production Team',
    'MegaTruckers': 'Docuseries Production Team',
    'Melodies of Life - Born This Way': 'Thai Production Team',
    'Mere Papa Hero Hiralal': 'Indian Drama Team',
    'Merlí': 'Eduard Cortés',
    'Mexico Diseña': 'Reality Show Production Team',
    'Midnight Misadventures With Mallika Dua': 'Indian Variety Team',
    'Mighty Morphin Alien Rangers': 'Robert Hughes, Isaac Florentine',
    'Mini Wolf': 'Animation Production Team',
    'Minute to Win It': 'Game Show Production Team',
    'Miss Dynamite': 'Alvaro Curiel',
    'Miss Rose': 'Taiwanese Production Team',
    'Momo Salon': 'Korean Web Drama Team',
    'Money for Nothing': 'Docuseries Production Team',
    'Monkey Planet': 'Docuseries Production Team',
    'Monster Math Squad': 'Animation Production Team',
    "Monty Don's Italian Gardens": 'Docuseries Production Team',
    'Mr. Young': 'Adam Weissman, Savage Steve Holland',
    'Murderous Affairs': 'Docuseries Production Team',
    'Mutant Busters': 'Freddy Córdoba, Roger Córdoba',
    'My Hotter Half': 'Reality Show Production Team',
    'My Life My Story': 'Docuseries Production Team',
    'My Tattoo Addiction': 'Docuseries Production Team',
    'Mystery Science Theater 3000': 'Joel Hodgson, Kevin Murphy',
    'Nature: Animals With Cameras': 'Docuseries Production Team',
    'NATURE: Natural Born Hustlers': 'Docuseries Production Team',
    'Nature: Raising the Dinosaur Giant': 'Docuseries Production Team',
    "Nature's Great Events (2009)": 'Jeff Turner',
    "Nature's Great Events: Diaries": 'Docuseries Production Team',
    "Nature's Great Race": 'Docuseries Production Team',
    "Nature's Weirdest Events": 'Docuseries Production Team',
    'Nazi Mega Weapons': 'Docuseries Production Team',
    'Nightmare Tenants, Slum Landlords': 'Docuseries Production Team',
    'Ninja Hattori': 'Hiroshi Sasagawa',
    'Ninja Turtles: The Next Mutation': 'Robert Hughes',
    'Nobel': 'Per-Olav Sørensen',
    'North & South': 'Brian Percival',
    'NOVA: Bird Brain': 'Docuseries Production Team',
    'NOVA: Killer Floods': 'Docuseries Production Team',
    'NSU German History X': 'Christian Schwochow, Züli Aladag',
    'Nuestra Lucha Libre': 'Documentary Production Team',
    'Nura: Rise of the Yokai Clan: Demon Capital': 'Michio Fukuda',
    'Nurse Jackie': 'Paul Feig, Randall Einhorn',
    'Nurses Who Kill': 'Docuseries Production Team',
    'O-Negative, Love Can’t Be Designed': 'Thai Drama Production Team',
    'OCTB': 'Danny Chan',
    "Oh No! It's an Alien Invasion": 'Animation Production Team',
    'Ollie & Moon': 'Florian Thouret',
    'One Heart: The A.R. Rahman Concert Film': 'YM Movies Team',
    'One Strange Rock': 'Darren Aronofsky',
    'Operation Gold Rush': 'Docuseries Production Team',
    'Operation Ouch!': 'Docuseries Production Team',
    'Operation Proposal': 'Kim Woo-sun',
    'Our Shining Days': 'Wang Ran',
    'P. King Duckling': 'Eddy Tang',
    'Pacific Heat': 'Rob Sitch',
    'Pajanimals': 'David Gumpel',
    'Paranormal Survivor': 'Docuseries Production Team',
    'Parks and Recreation': 'Dean Holland, Michael Schur',
    'Pasión de Gavilanes': 'Rodrigo Triana',
    'Pawn Stars': 'Reality Show Production Team',
    "Pee-wee's Playhouse": 'Stephen R. Johnson, Paul Reubens',
    'Penny Dreadful': 'James Hawes, J.A. Bayona',
    'Person of Interest': 'Chris Fisher, Richard J. Lewis',
    'Planet Earth II': 'Elizabeth White, Justin Anderson',
    'Portlandia': 'Jonathan Krisel',
    'Powder': 'Atul Sabharwal',
    'Power Battle Watch Car': 'Lee Young-joon',
    'Power Rangers Dino Charge': 'Jonathan Brough, Charlie Haskell',
    'Power Rangers Dino Super Charge': 'Jonathan Brough, Charlie Haskell',
    'Power Rangers Dino Thunder': 'Charlie Haskell, Andrew Merrifield',
    'Power Rangers in Space': 'John Blizek, Worth Keeter',
    'Power Rangers Jungle Fury': 'Mark Beesley, Charlie Haskell',
    'Power Rangers Lightspeed Rescue': 'Ryuta Tasaki, Worth Keeter',
    'Power Rangers Lost Galaxy': 'Ryuta Tasaki, Worth Keeter',
    'Power Rangers Mystic Force': 'Charlie Haskell, Mark Beesley',
    'Power Rangers Ninja Storm': 'Charlie Haskell, Paul Grinder',
    'Power Rangers Operation Overdrive': 'Mark Beesley, Charlie Haskell',
    'Power Rangers RPM': 'Jonathan Brough, Peter Burger',
    'Power Rangers S.P.D.': 'Greg Aronowitz, Charlie Haskell',
    'Power Rangers Samurai': 'John Logan, Jonathan Brough',
    'Power Rangers Samurai: Christmas Together, Friends Forever (Christmas Special)': 'Jonathan Brough',
    'Power Rangers Samurai: Clash of the Red Rangers': 'Jonathan Brough',
    'Power Rangers Samurai: Party Monsters (Halloween Special)': 'Jonathan Brough',
    'Power Rangers Super Megaforce': 'Jonathan Tzachor',
    'Power Rangers Super Samurai': 'Jonathan Brough',
    'Power Rangers Super Samurai: Stuck on Christmas': 'Jonathan Brough',
    'Power Rangers Super Samurai: Trickster Treat': 'Jonathan Brough',
    'Power Rangers Time Force': 'Koichi Sakamoto, Worth Keeter',
    'Power Rangers Turbo': 'David Winning, Shuki Levy',
    'Power Rangers Wild Force': 'Koichi Sakamoto, Worth Keeter',
    'Power Rangers Zeo': 'Robert Radler, Isaac Florentine',
    'Power Rangers: Megaforce': 'Jonathan Tzachor',
    'Power Rangers: Megaforce: Raising Spirits': 'Jonathan Tzachor',
    'Prohibition: A Film by Ken Burns and Lynn Novick': 'Ken Burns, Lynn Novick',
    'Psiconautas': 'Pedro Rivero, Alberto Vázquez',
    'Pyaar Tune Kya Kiya': 'Indian Drama Team',
    'Qué pena tu serie': 'Nicolás López',
    'Queen of No Marriage': 'Lin Qing-zhen',
    'Queens of Comedy': 'Reality Show Production Team'
}

In [247]:
df['director'] = df['director'].fillna(df['title'].map(movies_and_directors_12))
remaining_nulls = df['director'].isnull().sum()
print(f"Remaining null values in director column: {remaining_nulls}")

Remaining null values in director column: 200

In [248]:
na_directors_titles_13 = missing_directors_title[2460:2660]
na_directors_titles_13

['Queens vs. Kings',
 'Rab Se Sohna Isshq',
 'Ramayan',
 'Razia Sultan',
 'Reality of Dream',
 'Rebelde',
 'Rectify',
 'Red vs. Blue',
 'Reggie Yates Outside Man',
 'Republic of Doyle',
 'Revenge',
 'Rica, Famosa, Latina',
 'Ripper Street',
 'Rishta.com',
 'Robotech',
 'Roonpi Secret Love',
 'Rubi',
 'Rurouni Kenshin',
 'Russell Peters vs. the World',
 'Satrangi',
 'Save Our Shelter',
 'Scandal',
 'Secret Affair',
 'Sensitive Skin',
 'Servant of the People',
 'Shadow of Truth',
 'Shaka Zulu',
 'She Did That',
 'Sherlock',
 'Sid the Science Kid',
 'Silver Spoon',
 'Sin senos no hay paraíso',
 'Sin Senos sí Hay Paraíso',
 'Skin Wars',
 'Skin Wars: Fresh Paint',
 "Slobby's World",
 'Smash: Motorized Mayhem',
 'Sotus The Series',
 'Space Racers',
 'Spartacus',
 'Splash and Bubbles',
 'Star-Crossed',
 'Station Horizon',
 'Stoked',
 'Stone Age',
 'Storage Wars: Northern Treasures',
 'Strawberry Shortcake: Berry Bitty Adventures',
 'Strong Girl Bong-soon',
 'Strongland',
 'Suits',
 'Super Bheem',
 'Super Wings',
 'SuperNature: Wild Flyers',
 'Surviving R. Kelly Part II: The Reckoning',
 'Swami Baba Ramdev: The Untold Story',
 'Sym-Bionic Titan',
 'Taken',
 'Tales of the City (1993)',
 'Teresa',
 'Thackeray',
 "That '70s Show",
 'The 2000s',
 'The Adjusters',
 'The Adventures of Figaro Pho',
 'The Andy Griffith Show',
 'The Apartment',
 'The Bachelor',
 'The Beat',
 "The Bible's Buried Secrets",
 'The Big Catch',
 'The Bomb Squad',
 'The Bund',
 "The Chefs' Line",
 'The Code',
 'The Cravings',
 'The Curse of Oak Island',
 'The Darkest Dawn',
 'The Day My Butt Went Psycho!',
 'The Devil Is a Part-Timer!',
 'The Drunk and on Drugs Happy Funtime Hour',
 'The Eighties',
 'The Fosters',
 'The Furchester Hotel',
 'The Future of Water',
 'The Golden Years with Javed Akhtar',
 'The Great Battle',
 'The Great British Baking Show: Masterclass',
 'The Great Train Robbery',
 'The Guild',
 'The Homecoming',
 'The House That Made Me',
 'The Hunt',
 'The Inbetweeners',
 'The Investigator: A British Crime Story',
 'The Irish Mob',
 'The Jaime Maussan Show',
 'The Jungle Book',
 'The Kindness Diaries',
 'The L Word',
 'The Lady in Dignity',
 'The Liar',
 'The Lizzie Borden Chronicles',
 'The Making of Frozen Planet',
 'The Messengers',
 'The Mind of a Chef',
 'The Minimighty Kids',
 'The Ministry of Time',
 'The Mortified Guide',
 'The Most Beautiful Hands of Delhi',
 'The Murder Detectives',
 'The Netflix Afterparty',
 'The Nineties',
 'The Office (U.S.)',
 'The Pyramid Code',
 'The Rap Game',
 'The Real Football Factories',
 'The Returned',
 'The Road to Calvary',
 'The Seventies',
 'The Sniffer',
 'The Story of God with Morgan Freeman',
 'The Story of Us with Morgan Freeman',
 'The Super Mario Bros. Super Show!',
 'The Traffickers',
 'The Tudors',
 'The Twilight Zone (Original Series)',
 'The Underwear',
 'The Universe',
 'The War: A Film by Ken Burns and Lynn Novick',
 'The West Wing',
 'The Womanizer',
 'The Year of Happiness and Love',
 'ThirTEEN Terrors',
 'This Is My Love',
 'Tientsin Mystic',
 'Timeless Season',
 'Timeline',
 'Tip the Mouse',
 'Tobot',
 'Top 10 Secrets and Mysteries',
 'Top Grier',
 'Towies',
 'Trotsky',
 'Twin Peaks',
 'Twirlywoos',
 'Twisted Trunk, Big Fat Body',
 'Ugly Duckling',
 'V.R. Troopers',
 'ViR: The Robot Boy',
 'Vroomiz',
 'Wake Up',
 'Wartime Portraits',
 'Weeds',
 'Weird Wonders of the World',
 'What Happens to My Family',
 'What Is Love?',
 'When Calls the Heart',
 "Who's the One",
 'Wild Alaska',
 'Wild Arabia',
 'Winsanity',
 'Winter Sun',
 'Women Behind Bars',
 "World's Busiest Cities",
 'Yeh Meri Family',
 'Yo-Kai Watch',
 'Yoko',
 'Yoko and His Friends',
 'YOM',
 'Yu-Gi-Oh! Arc-V',
 'Yunus Emre',
 'Zak Storm',
 'Zindagi Gulzar Hai',
 'Zombie Dumb']

In [249]:
movies_and_directors_13 = {
    'Queens vs. Kings': 'Reality Show Production Team',
    'Rab Se Sohna Isshq': 'Mohit Hussein',
    'Ramayan': 'Ramanand Sagar',
    'Razia Sultan': 'Kamal Amrohi',
    'Reality of Dream': 'Documentary Production Team',
    'Rebelde': 'Luis Pardo, Juan Carlos Muñoz',
    'Rectify': 'Ray McKinnon',
    'Red vs. Blue': 'Burnie Burns, Matt Hullum',
    'Reggie Yates Outside Man': 'Reggie Yates',
    'Republic of Doyle': 'Allan Hawco',
    'Revenge': 'Phillip Noyce, Kenneth Fink',
    'Rica, Famosa, Latina': 'Reality Show Production Team',
    'Ripper Street': 'Tom Shankland, Andy Wilson',
    'Rishta.com': 'Rishabh Seth',
    'Robotech': 'Robert Barron, Ishiguro Noboru',
    'Roonpi Secret Love': 'Thai Production Team',
    'Rubi': 'Benjamín Cann, Eric Morales',
    'Rurouni Kenshin': 'Kazuhiro Furuhashi',
    'Russell Peters vs. the World': 'Russell Peters',
    'Satrangi': 'Pakistani Production Team',
    'Save Our Shelter': 'Reality Show Production Team',
    'Scandal': 'Tom Verica, Shonda Rhimes',
    'Secret Affair': 'Ahn Pan-seok',
    'Sensitive Skin': 'Don McKellar',
    'Servant of the People': 'Oleksiy Kiryushchenko',
    'Shadow of Truth': 'Yotam Guendelman, Ari Pines',
    'Shaka Zulu': 'William C. Faure',
    'She Did That': 'Renae Bluitt',
    'Sherlock': 'Paul McGuigan, Nick Hurran',
    'Sid the Science Kid': 'Hugh Martin, Katy Garretson',
    'Silver Spoon': 'Aleksandr Tsekalo',
    'Sin senos no hay paraíso': 'Miguel Varoni, Ramiro Meneses',
    'Sin Senos sí Hay Paraíso': 'Diego Mejía, Herney Luna',
    'Skin Wars': 'Reality Show Production Team',
    'Skin Wars: Fresh Paint': 'Reality Show Production Team',
    "Slobby's World": 'Reality Show Production Team',
    'Smash: Motorized Mayhem': 'Docuseries Production Team',
    'Sotus The Series': 'Lit Samajarn',
    'Space Racers': 'Mark Risley',
    'Spartacus': 'Michael Hurst, Jesse Warn',
    'Splash and Bubbles': 'John Tartaglia',
    'Star-Crossed': 'Gary Fleder',
    'Station Horizon': 'Pierre-Adrian Irlé, Romain Graf',
    'Stoked': 'Faruk Kabir',
    'Stone Age': 'Animation Production Team',
    'Storage Wars: Northern Treasures': 'Reality Show Production Team',
    'Strawberry Shortcake: Berry Bitty Adventures': 'Bob Hathcock',
    'Strong Girl Bong-soon': 'Lee Hyung-min',
    'Strongland': 'Docuseries Production Team',
    'Suits': 'Kevin Bray, Anton Cropper',
    'Super Bheem': 'Rajiv Chilaka',
    'Super Wings': 'Jung Gil-hoon',
    'SuperNature: Wild Flyers': 'Docuseries Production Team',
    'Surviving R. Kelly Part II: The Reckoning': 'Nigel Bellis, Astrid Miller',
    'Swami Baba Ramdev: The Untold Story': 'Indian Production Team',
    'Sym-Bionic Titan': 'Genndy Tartakovsky',
    'Taken': 'Alex Graves, Nick Gomez',
    'Tales of the City (1993)': 'Alastair Reid',
    'Teresa': 'Mónica Miguel, Alejandro Gamboa',
    'Thackeray': 'Abhijit Panse',
    "That '70s Show": 'David Trainer',
    'The 2000s': 'Docuseries Production Team',
    'The Adjusters': 'Drama Production Team',
    'The Adventures of Figaro Pho': 'Luke Jurevicius',
    'The Andy Griffith Show': 'Bob Sweeney',
    'The Apartment': 'Billy Wilder',
    'The Bachelor': 'Reality Show Production Team',
    'The Beat': 'Drama Production Team',
    "The Bible's Buried Secrets": 'Docuseries Production Team',
    'The Big Catch': 'Reality Show Production Team',
    'The Bomb Squad': 'Docuseries Production Team',
    'The Bund': 'Pratya Pinkaew',
    "The Chefs' Line": 'Reality Show Production Team',
    'The Code': 'Shawn Piller',
    'The Cravings': 'Lee Byung-heon',
    'The Curse of Oak Island': 'Docuseries Production Team',
    'The Darkest Dawn': 'Drew Casson',
    'The Day My Butt Went Psycho!': 'Matt Ferguson',
    'The Devil Is a Part-Timer!': 'Naoto Hosoda',
    'The Drunk and on Drugs Happy Funtime Hour': 'Ron Murphy',
    'The Eighties': 'Docuseries Production Team',
    'The Fosters': 'Norman Buckley, Peter Paige',
    'The Furchester Hotel': 'Jack Jameson',
    'The Future of Water': 'Docuseries Production Team',
    'The Golden Years with Javed Akhtar': 'Indian Docuseries Team',
    'The Great Battle': 'Kim Kwang-sik',
    'The Great British Baking Show: Masterclass': 'Docuseries Production Team',
    'The Great Train Robbery': 'Julian Jarrold, James Strong',
    'The Guild': 'Sean Becker',
    'The Homecoming': 'Björn Runge',
    'The House That Made Me': 'Docuseries Production Team',
    'The Hunt': 'Craig Zobel',
    'The Inbetweeners': 'Ben Palmer',
    'The Investigator: A British Crime Story': 'Docuseries Production Team',
    'The Irish Mob': 'Docuseries Production Team',
    'The Jaime Maussan Show': 'Reality Show Production Team',
    'The Jungle Book': 'Jon Favreau',
    'The Kindness Diaries': 'Leon Logothetis',
    'The L Word': 'Rose Troche, Angela Robinson',
    'The Lady in Dignity': 'Kim Yoon-cheol',
    'The Liar': 'Korean Drama Team',
    'The Lizzie Borden Chronicles': 'Stephen Kay',
    'The Making of Frozen Planet': 'Docuseries Production Team',
    'The Messengers': 'Stephen Williams',
    'The Mind of a Chef': 'David Gelb',
    'The Minimighty Kids': 'Animation Production Team',
    'The Ministry of Time': 'Marc Vigil',
    'The Mortified Guide': 'Michael Mayer',
    'The Most Beautiful Hands of Delhi': 'Hannes Holm',
    'The Murder Detectives': 'Ben Anthony',
    'The Netflix Afterparty': 'Comedy Production Team',
    'The Nineties': 'Docuseries Production Team',
    'The Office (U.S.)': 'Greg Daniels, Ken Kwapis',
    'The Pyramid Code': 'Carmen Boulter',
    'The Rap Game': 'Reality Show Production Team',
    'The Real Football Factories': 'Docuseries Production Team',
    'The Returned': 'Fabrice Gobert',
    'The Road to Calvary': 'Konstantin Khudyakov',
    'The Seventies': 'Docuseries Production Team',
    'The Sniffer': 'Artem Litvinenko',
    'The Story of God with Morgan Freeman': 'Docuseries Production Team',
    'The Story of Us with Morgan Freeman': 'Docuseries Production Team',
    'The Super Mario Bros. Super Show!': 'John Grusd',
    'The Traffickers': 'Docuseries Production Team',
    'The Tudors': 'Ciaran Donnelly, Dearbhla Walsh',
    'The Twilight Zone (Original Series)': 'Rod Serling',
    'The Underwear': 'Thai Production Team',
    'The Universe': 'Docuseries Production Team',
    'The War: A Film by Ken Burns and Lynn Novick': 'Ken Burns, Lynn Novick',
    'The West Wing': 'Thomas Schlamme, Christopher Misiano',
    'The Womanizer': 'Taiwanese Production Team',
    'The Year of Happiness and Love': 'Taiwanese Production Team',
    'ThirTEEN Terrors': 'GMM One Production Team',
    'This Is My Love': 'Lee Tae-gon',
    'Tientsin Mystic': 'Tian Li',
    'Timeless Season': 'Drama Production Team',
    'Timeline': 'Richard Donner',
    'Tip the Mouse': 'Andrea Bozzetto',
    'Tobot': 'Animation Production Team',
    'Top 10 Secrets and Mysteries': 'Docuseries Production Team',
    'Top Grier': 'Reality Show Production Team',
    'Towies': 'Reality Show Production Team',
    'Trotsky': 'Alexander Kott, Konstantin Statsky',
    'Twin Peaks': 'David Lynch',
    'Twirlywoos': 'CBeebies Production Team',
    'Twisted Trunk, Big Fat Body': 'Indian Production Team',
    'Ugly Duckling': 'Thai Drama Production Team',
    'V.R. Troopers': 'Worth Keeter',
    'ViR: The Robot Boy': 'Anish Patel',
    'Vroomiz': 'Animation Production Team',
    'Wake Up': 'Thai Drama Production Team',
    'Wartime Portraits': 'Documentary Production Team',
    'Weeds': 'Craig Zisk, Michael Trim',
    'Weird Wonders of the World': 'Docuseries Production Team',
    'What Happens to My Family': 'Jeon Chang-geun',
    'What Is Love?': 'Taiwanese Production Team',
    'When Calls the Heart': 'Michael Landon Jr., Neill Fearnley',
    "Who's the One": 'Taiwanese Production Team',
    'Wild Alaska': 'Docuseries Production Team',
    'Wild Arabia': 'Docuseries Production Team',
    'Winsanity': 'Game Show Production Team',
    'Winter Sun': 'Murat Onbul',
    'Women Behind Bars': 'Docuseries Production Team',
    "World's Busiest Cities": 'Docuseries Production Team',
    'Yeh Meri Family': 'Sameer Saxena',
    'Yo-Kai Watch': 'Shinji Ushiro',
    'Yoko': 'Juanjo Elordi',
    'Yoko and His Friends': 'Juanjo Elordi',
    'YOM': 'Indian Animation Team',
    'Yu-Gi-Oh! Arc-V': 'Katsumi Ono',
    'Yunus Emre': 'Emre Konuk',
    'Zak Storm': 'Philippe Guyenne',
    'Zindagi Gulzar Hai': 'Sultana Siddiqui',
    'Zombie Dumb': 'Animation Production Team'
}

In [250]:
df['director'] = df['director'].fillna(df['title'].map(movies_and_directors_13))
remaining_nulls = df['director'].isnull().sum()
print(f"Remaining null values in director column: {remaining_nulls}")

Remaining null values in director column: 26

In [251]:
missing_directors_2 = df.loc[df['director'].isna(), ['title', 'director']]
missing_directors.sample(5)

                                  title director
5671                   Immortal Classic      NaN
4207                    When Heroes Fly      NaN
715   Elite Short Stories: Nadia Guzmán      NaN
4137         Free Rein: Valentine's Day      NaN
7685                   Our Shining Days      NaN

In [252]:
na_directors_titles_14 = list(missing_directors_2['title'])
na_directors_titles_14

['Yasuke',
 'Signal',
 'Nicky, Ricky, Dicky & Dawn',
 "This Is a Robbery: The World's Biggest Art Heist",
 'The Lost Pirate Kingdom',
 'Aggretsuko',
 'Single Wives',
 'Stateless',
 'BNA',
 'Babies',
 'The Light of My Eyes',
 'True: Rainbow Rescue',
 "Can't Cope, Won't Cope",
 'Dorohedoro',
 'History 101',
 'Mystic Pop-up Bar',
 'The Queen and the Conqueror',
 'The Big Flower Fight',
 'True: Terrific Tales',
 'Trial By Media',
 'DRIFTING DRAGONS',
 'Tree House Tales',
 "Archibald's Next Big Thing",
 'Spectros',
 '\u200bSAINT SEIYA: Knights of the Zodiac',
 'Until Dawn']

In [253]:
movies_and_directors_14 = {
    'Yasuke': 'LeSean Thomas, Takeru Satō',
    'Signal': 'Kim Won-seok',
    'Nicky, Ricky, Dicky & Dawn': 'Eric Dean Seaton, Trevor Kirschner',
    "This Is a Robbery: The World's Biggest Art Heist": 'Colin Barnicle',
    'The Lost Pirate Kingdom': 'Stan Griffin, Patrick Dickinson',
    'Aggretsuko': 'Rarecho',
    'Single Wives': 'Reality Show Production Team',
    'Stateless': 'Emma Freeman, Jocelyn Moorhouse',
    'BNA': 'Yoh Yoshinari',
    'Babies': 'Docuseries Production Team',
    'The Light of My Eyes': 'Wael Ihsan',
    'True: Rainbow Rescue': 'Jamie Whitney, Harold Harris',
    "Can't Cope, Won't Cope": 'Cathy Brady, Imogen Murphy',
    'Dorohedoro': 'Yuichiro Hayashi',
    'History 101': 'Marc Tiley, Nick Clarke Powell',
    'Mystic Pop-up Bar': 'Jeon Chang-geun',
    'The Queen and the Conqueror': 'Camilo Villamizar, Juan Carlos Vásquez',
    'The Big Flower Fight': 'Reality Show Production Team',
    'True: Terrific Tales': 'Jamie Whitney, Harold Harris',
    'Trial By Media': 'Docuseries Production Team',
    'DRIFTING DRAGONS': 'Tadahiro Yoshihira',
    'Tree House Tales': 'Animation Production Team',
    "Archibald's Next Big Thing": 'Adam Gunn, Brian Hatfield',
    'Spectros': 'Douglas Petrie, Michael Ruman',
    '\u200bSAINT SEIYA: Knights of the Zodiac': 'Yoshiharu Ashino',
    'Until Dawn': 'David F. Sandberg'
}

In [254]:
df['director'] = df['director'].fillna(df['title'].map(movies_and_directors_14))
remaining_nulls = df['director'].isnull().sum()
print(f"Remaining null values in director column: {remaining_nulls}")

Remaining null values in director column: 0

##### **`cast` Column:**

In [255]:
df['cast'].unique()

array([nan,
       'Ama Qamata, Khosi Ngema, Gail Mabalane, Thabang Molaba, Dillon Windvogel, Natasha Thahane, Arno Greeff, Xolile Tshabalala, Getmore Sithole, Cindy Mahlangu, Ryle De Morny, Greteli Fincham, Sello Maake Ka-Ncube, Odwa Gwanya, Mekaila Mathys, Sandi Schultz, Duane Williams, Shamilla Miller, Patrick Mofokeng',
       'Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabiha Akkari, Sofia Lesaffre, Salim Kechiouche, Noureddine Farihi, Geert Van Rampelberg, Bakary Diombera',
       ...,
       'Jesse Eisenberg, Woody Harrelson, Emma Stone, Abigail Breslin, Amber Heard, Bill Murray, Derek Graf',
       'Tim Allen, Courteney Cox, Chevy Chase, Kate Mara, Ryan Newman, Michael Cassidy, Spencer Breslin, Rip Torn, Kevin Zegers',
       'Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanana, Manish Chaudhary, Meghna Malik, Malkeet Rauni, Anita Shabdish, Chittaranjan Tripathy'],
      shape=(7693,), dtype=object)

In [256]:
missing_cast= df.loc[df['cast'].isna(), ['title', 'cast']]
missing_cast.sample(5)

                                           title cast
4199                            Back with the Ex  NaN
4416  ReMastered: Tricky Dick & The Man in Black  NaN
1060                          Indian Matchmaking  NaN
2032            Get Organized with The Home Edit  NaN
900                             Money, Explained  NaN

In [257]:
missing_cast_titles = list(missing_cast['title'])
len(missing_cast_titles)

825

In [258]:
missing_cast_titles_1 = missing_cast_titles[:225]
missing_cast_titles_1

['Dick Johnson Is Dead',
 'Jailbirds New Orleans',
 'Vendetta: Truth, Lies and The Mafia',
 'Crime Stories: India Detectives',
 "Europe's Most Dangerous Man: Otto Skorzeny in Spain",
 'Monsters Inside: The 24 Faces of Billy Milligan',
 'My Heroes Were Cowboys',
 'Raja Rasoi Aur Anya Kahaniyan',
 'Stories by Rabindranath Tagore',
 "The World's Most Amazing Vacation Rentals",
 'The Women and the Murderer',
 'Untold: Breaking Point',
 'Countdown: Inspiration4 Mission to Space',
 'Money Heist: From Tokyo to Berlin',
 'Final Account',
 'Luv Kushh',
 'Pororo - The Little Penguin',
 'How to Be a Cowboy',
 'Turning Point: 9/11 and the War on Terror',
 'Untold: Crime & Penalties',
 'Titletown High',
 'John of God: The Crimes of a Spiritual Healer',
 'Motel Makeover',
 'The River Runner',
 'Count Me In',
 'Oggy Oggy',
 'Untold: Caitlyn Jenner',
 'Comedy Premium League',
 'Memories of a Murderer: The Nilsen Tapes',
 'Untold: Deal With the Devil',
 'Mother Goose Club',
 'The Creative Indians',
 'Bake Squad',
 'Misha and the Wolves',
 'Untold: Malice at the Palace',
 'City of God: 10 Years Later',
 'Cocaine Cowboys: The Kings of Miami',
 'Pray Away',
 'Top Secret UFO Projects: Declassified',
 'Glow Up',
 'Khawatir',
 'Myth & Mogul: John DeLorean',
 'Fantastic Fungi',
 'Tattoo Redo',
 'The Movies That Made Us',
 '9to5: The Story of a Movement',
 'Sexy Beasts',
 'Explained',
 'Naomi Osaka',
 'Lift Like a Girl',
 'This Changes Everything',
 'Heist',
 'My Unorthodox Life',
 'Born to Play',
 'Elize Matsunaga: Once Upon a Crime',
 'Awon Boyz',
 'Cat People',
 'Dogs',
 'Chelsea',
 'I AM A KILLER',
 'Larva',
 'Big Timber',
 'Audible',
 "Droppin' Cash: Los Angeles",
 'Sophie: A Murder in West Cork',
 'Sisters on Track',
 'Murder by the Coast',
 'This Is Pop',
 'Cleo & Cuquin',
 'Penguin Town',
 'The Reason I Jump',
 'Picture a Scientist',
 'Trese After Dark',
 'Fresh, Fried & Crispy',
 'Fireplace 4K: Classic Crackling Fireplace from Fireplace for Your Home',
 'Fireplace 4K: Crackling Birchwood from Fireplace for Your Home',
 'Human: The World Within',
 'From Stress to Happiness',
 'Black Holes | The Edge of All We Know',
 'Cocomelon',
 'The Least Expected Day: Inside the Movistar Team 2019',
 'High on the Hog: How African American Cuisine Transformed America',
 'Nail Bomber: Manhunt',
 '99 Songs (Tamil)',
 '99 Songs (Telugu)',
 'Creating an Army of the Dead',
 'Hating Peter Tatchell',
 'The Last Days',
 'Alma Matters',
 'Haunted',
 'Money, Explained',
 "In Our Mothers' Gardens",
 'Sab Jholmaal Hai',
 'The Sons of Sam: A Descent into Darkness',
 'Angelina Ballerina',
 'Miniforce: Super Dino Power',
 'Pet Stars',
 'Keymon and Nani in Space Adventure',
 'Free to Play',
 'Dancing Angels',
 'Ajaibnya Cinta',
 'Indian Matchmaking',
 'Jeffrey Epstein: Filthy Rich',
 'Unnatural Selection',
 'Why Did You Kill Me?',
 'My Love: Six Stories of True Love',
 'Shiva VS Autobots',
 'Shiva: Journey to Plunotaria',
 'Shiva: The Secret World Of Vedas City',
 'The Big Day',
 'The Wedding Coach',
 "This Is a Robbery: The World's Biggest Art Heist",
 'Coded Bias',
 'Glimpses of a Future',
 'Ibrahim a Fate to Define',
 'Magical Andes',
 'Worn Stories',
 'Haunted: Latin America',
 'Marked',
 'Elizabeth and Margaret: Love and Loyalty',
 'Pui Pui Molcar',
 'Seaspiracy',
 'Formula 1: Drive to Survive',
 'Under Suspicion: Uncovering the Wesphael Case',
 'The Last Blockbuster',
 'Last Chance U: Basketball',
 'Marriage or Mortgage',
 'Nevenka: Breaking the Silence',
 'Murder Among the Mormons',
 'Made You Look: A True Story About Fake Art',
 'Pelé',
 'Zindagi in Short',
 'Perú: Tesoro escondido',
 'The Most Unknown',
 'Buried by the Bernards',
 'Crime Scene: The Vanishing at the Cecil Hotel',
 'Five Came Back: The Reference Films',
 'Strip Down, Rise Up',
 'Zig & Sharko',
 'We Are: The Brooklyn Saints',
 'Blown Away',
 'Spycraft',
 'Bling Empire',
 'Night Stalker: The Hunt for a Serial Killer',
 'Crack: Cocaine, Corruption & Conspiracy',
 "Creating The Queen's Gambit",
 'Surviving Death',
 'QB1: Beyond the Lights',
 'Dream Home Makeover',
 'The Minimalists: Less Is Now',
 'SanPa: Sins of the Savior',
 'Regiment Diaries',
 'Morphle',
 'BREAK IT ALL: The History of Rock in Latin America',
 'How To Ruin Christmas',
 'The Ripper',
 'Canvas',
 "The Surgeon's Cut",
 'Room 2806: The Accusation',
 'Alien Worlds',
 'The Bachelorette',
 'The Holiday Movies That Made Us',
 'The Repair Shop',
 'Fabulous Lives of Bollywood Wives',
 'If Anything Happens I Love You',
 'We Are the Champions',
 'Whose Streets?',
 'The Beginning of Life 2: Outside',
 'Trial 4',
 'We Are All For The Fatherland',
 'A Lion in the House',
 'Bakugan: Armored Alliance',
 'Country Ever After',
 'Carmel: Who Killed Maria Marta?',
 'The Beginning of Life',
 '60 Days In',
 'LEGO Jurassic World: Legend of Isla Nublar',
 'Secrets of the Saqqara Tomb',
 'Guillermo Vilas: Settling the Score',
 'Move',
 'Bending the Arc',
 'Unsolved Mysteries',
 'Rooting for Roona',
 'The Three Deaths of Marisela Escobedo',
 'Deaf U',
 'Super Monsters: Dia de los Monsters',
 'Bad Boy Billionaires: India',
 'Pat a Pat Como',
 'Qurious Como',
 'Human Nature',
 "I'm Leaving Now",
 'American Murder: The Family Next Door',
 'Bully',
 'Whose Vote Counts, Explained',
 'A Perfect Crime',
 'Mighty Little Bheem',
 'The Playbook',
 'A Love Song for Latasha',
 'Challenger',
 'Hope Frozen: A Quest to Live Twice',
 'Taco Chronicles',
 'Get Organized with The Home Edit',
 'La Línea: Shadow of Narco',
 'My Octopus Teacher',
 'Waiting for "Superman"',
 "Chef's Table: BBQ",
 'I AM A KILLER: RELEASED',
 'Million Dollar Beach House',
 'Rising Phoenix',
 'Baewatch: Parental Guidance',
 'John Was Trying to Contact Aliens',
 'DeMarcus Family Rules',
 'High Score',
 'Islands of Faith',
 "Beyond the Boundary: ICC Women's T20 World Cup Australia 2020",
 '(Un)Well',
 'Selling Sunset',
 'Word Party Songs',
 "World's Most Wanted",
 'Immigration Nation',
 'The Umbrella Academy',
 'The Speed Cubers',
 'Tread',
 'Sinatra: All or Nothing at All',
 'Fear City: New York vs The Mafia']

In [259]:
netflix_cast_dict_1 = {
    'Dick Johnson Is Dead': 'Dick Johnson, Kirsten Johnson',
    'Jailbirds New Orleans': 'Megan Hawkins, Harley Himber',
    'Vendetta: Truth, Lies and The Mafia': 'Pino Maniaci, Silvana Saguto',
    'Crime Stories: India Detectives': 'Bengaluru Police Officers',
    "Europe's Most Dangerous Man: Otto Skorzeny in Spain": 'Otto Skorzeny',
    'Monsters Inside: The 24 Faces of Billy Milligan': 'Billy Milligan',
    'My Heroes Were Cowboys': 'Robin Wiltshire',
    'Raja Rasoi Aur Anya Kahaniyan': 'Pushpesh Pant',
    'Stories by Rabindranath Tagore': 'Radhika Apte, Bhoomika Chawla, Amrita Puri',
    "The World's Most Amazing Vacation Rentals": 'Luis D. Ortiz, Megan Batoon, Jo Franco',
    'The Women and the Murderer': 'Brigitte Vital-Durand, Marie-Laure Picat',
    'Untold: Breaking Point': 'Mardy Fish, Andy Roddick',
    'Countdown: Inspiration4 Mission to Space': 'Jared Isaacman, Hayley Arceneaux, Sian Proctor, Christopher Sembroski',
    'Money Heist: From Tokyo to Berlin': 'Úrsula Corberó, Álvaro Morte, Itziar Ituño',
    'Final Account': 'Adolf Hitler, Concentration Camp Survivors',
    'Luv Kushh': 'Animated Characters',
    'Pororo - The Little Penguin': 'Lee Sun, Ham Soo-jung',
    'How to Be a Cowboy': 'Dale Brisby',
    'Turning Point: 9/11 and the War on Terror': 'Various Interviewees',
    'Untold: Crime & Penalties': 'Jimmy Galante, A.J. Galante',
    'Titletown High': 'Rush Propst, Amari Jones',
    'John of God: The Crimes of a Spiritual Healer': 'João Teixeira de Faria',
    'Motel Makeover': 'April Brown, Sarah Sklash',
    'The River Runner': 'Scott Lindgren',
    'Count Me In': 'Nicko McBrain, Stewart Copeland, Taylor Hawkins',
    'Oggy Oggy': 'Animated Characters',
    'Untold: Caitlyn Jenner': 'Caitlyn Jenner',
    'Comedy Premium League': 'Prajakta Koli, Rahul Subramanian, Aadar Malik',
    'Memories of a Murderer: The Nilsen Tapes': 'Dennis Nilsen',
    'Untold: Deal With the Devil': 'Christy Martin',
    'Mother Goose Club': 'Abigail Isom, Ivy Rhodes',
    'The Creative Indians': 'Various Indian Artists',
    'Bake Squad': 'Christina Tosi, Christophe Rull, Maya-Camille Broussard, Ashley Holt',
    'Misha and the Wolves': 'Misha Defonseca',
    'Untold: Malice at the Palace': 'Jermaine O\'Neal, Metta Sandiford-Artest, Stephen Jackson',
    'City of God: 10 Years Later': 'Alexandre Rodrigues, Leandro Firmino',
    'Cocaine Cowboys: The Kings of Miami': 'Sal Magluta, Willy Falcon',
    'Pray Away': 'Michael Bussee, John Paulk',
    'Top Secret UFO Projects: Declassified': 'Various Experts',
    'Glow Up': 'Stacey Dooley, Val Garland, Dominic Skinner',
    'Khawatir': 'Ahmad Al Shugairi',
    'Myth & Mogul: John DeLorean': 'John DeLorean',
    'Fantastic Fungi': 'Brie Larson, Paul Stamets',
    'Tattoo Redo': 'Jessimae Peluso, Tommy Montoya, Miryam Lumpini',
    'The Movies That Made Us': 'Danny Wallace',
    '9to5: The Story of a Movement': 'Jane Fonda, Lily Tomlin',
    'Sexy Beasts': 'Rob Delaney',
    'Explained': 'Various Celebrity Narrators',
    'Naomi Osaka': 'Naomi Osaka',
    'Lift Like a Girl': 'Asmaa Ramadan, Captain Ramadan',
    'This Changes Everything': 'Geena Davis, Meryl Streep',
    'Heist': 'Re-enactment Cast',
    'My Unorthodox Life': 'Julia Haart, Batsheva Haart, Shlomo Haart',
    'Born to Play': 'Boston Renegades Team Members',
    'Elize Matsunaga: Once Upon a Crime': 'Elize Matsunaga',
    'Awon Boyz': 'Area Boys of Lagos',
    'Cat People': 'Various Cat Owners',
    'Dogs': 'Various Dog Owners',
    'Chelsea': 'Chelsea Handler',
    'I AM A KILLER': 'Death Row Inmates',
    'Larva': 'Animated Characters',
    'Big Timber': 'Kevin Wenstob, Sarah Fleming',
    'Audible': 'Amaree McKenstry-Hall',
    "Droppin' Cash: Los Angeles": 'Various Rappers and Athletes',
    'Sophie: A Murder in West Cork': 'Ian Bailey',
    'Sisters on Track': 'Tai Sheppard, Rainn Sheppard, Brooke Sheppard',
    'Murder by the Coast': 'Rocío Wanninkhof, Dolores Vázquez',
    'This Is Pop': 'Various Musical Artists',
    'Cleo & Cuquin': 'Animated Characters',
    'Penguin Town': 'Patton Oswalt',
    'The Reason I Jump': 'Jordan O\'Doneogan',
    'Picture a Scientist': 'Nancy Hopkins, Raychelle Burks, Jane Willenbring',
    'Trese After Dark': 'Liza Soberano, Shay Mitchell',
    'Fresh, Fried & Crispy': 'Daym Drops',
    'Fireplace 4K: Classic Crackling Fireplace from Fireplace for Your Home': 'Ambient Fireplace',
    'Fireplace 4K: Crackling Birchwood from Fireplace for Your Home': 'Ambient Fireplace',
    'Human: The World Within': 'Jad Abumrad',
    'From Stress to Happiness': 'Matthieu Ricard, Brother David Steindl-Rast',
    'Black Holes | The Edge of All We Know': 'Stephen Hawking, Shep Doeleman',
    'Cocomelon': 'Animated Characters',
    'The Least Expected Day: Inside the Movistar Team 2019': 'Mikel Landa, Nairo Quintana, Alejandro Valverde',
    'High on the Hog: How African American Cuisine Transformed America': 'Stephen Satterfield',
    'Nail Bomber: Manhunt': 'Arthur Collins',
    '99 Songs (Tamil)': 'Ehan Bhat, Edilsy Vargas',
    '99 Songs (Telugu)': 'Ehan Bhat, Edilsy Vargas',
    'Creating an Army of the Dead': 'Zack Snyder',
    'Hating Peter Tatchell': 'Peter Tatchell, Ian McKellen',
    'The Last Days': 'Tom Lantos, Alice Lok Cahana',
    'Alma Matters': 'IIT Kharagpur Students and Faculty',
    'Haunted': 'Real Storytellers',
    'Money, Explained': 'Tiffany Haddish, Bobby Cannavale, Edie Falco',
    "In Our Mothers' Gardens": 'Various Subjects',
    'Sab Jholmaal Hai': 'Animated Characters',
    'The Sons of Sam: A Descent into Darkness': 'Paul Giamatti',
    'Angelina Ballerina': 'Finty Williams',
    'Miniforce: Super Dino Power': 'Animated Characters',
    'Pet Stars': 'Johanna Rosenberg, Melissa May Curtis',
    'Keymon and Nani in Space Adventure': 'Animated Characters',
    'Free to Play': 'Danil Ishutin, Benedict Lim, Clinton Loomis',
    'Dancing Angels': 'Documentary Cast',
    'Ajaibnya Cinta': 'Silas Wong, Kristina Vinokurova',
    'Indian Matchmaking': 'Sima Taparia',
    'Jeffrey Epstein: Filthy Rich': 'Virginia Roberts Giuffre, Maria Farmer',
    'Unnatural Selection': 'Kevin Esvelt, Josiah Zayner',
    'Why Did You Kill Me?': 'Belinda Lane',
    'My Love: Six Stories of True Love': 'Various Long-term Couples',
    'Shiva VS Autobots': 'Animated Characters',
    'Shiva: Journey to Plunotaria': 'Animated Characters',
    'Shiva: The Secret World Of Vedas City': 'Animated Characters',
    'The Big Day': 'Featured Brides and Grooms',
    'The Wedding Coach': 'Jamie Lee',
    "This Is a Robbery: The World's Biggest Art Heist": 'Investigators and Art Experts',
    'Coded Bias': 'Joy Buolamwini',
    'Glimpses of a Future': 'Documentary Contributors',
    'Ibrahim a Fate to Define': 'Ibrahim Hamato',
    'Magical Andes': 'Various Andean Residents',
    'Worn Stories': 'Various Wardrobe Enthusiasts',
    'Haunted: Latin America': 'Real Storytellers',
    'Marked': 'Tattoo Enthusiasts and Anthropologists',
    'Elizabeth and Margaret: Love and Loyalty': 'Queen Elizabeth II, Princess Margaret',
    'Pui Pui Molcar': 'Stop-motion Guinea Pigs',
    'Seaspiracy': 'Ali Tabrizi',
    'Formula 1: Drive to Survive': 'Max Verstappen, Lewis Hamilton, Daniel Ricciardo, Toto Wolff',
    'Under Suspicion: Uncovering the Wesphael Case': 'Bernard Wesphael',
    'The Last Blockbuster': 'Sandi Harding, Kevin Smith, Ione Skye',
    'Last Chance U: Basketball': 'John Mosley',
    'Marriage or Mortgage': 'Nichole Holmes, Shena Williams',
    'Nevenka: Breaking the Silence': 'Nevenka Fernández',
    'Murder Among the Mormons': 'Mark Hofmann',
    'Made You Look: A True Story About Fake Art': 'Ann Freedman, M.H. de Young',
    'Pelé': 'Pelé',
    'Zindagi in Short': 'Neena Gupta, Divyendu Sharma, Sanjay Kapoor',
    'Perú: Tesoro escondido': 'Various Peruvian Locals',
    'The Most Unknown': 'Jennifer Macalady, Davide D\'Angelo',
    'Buried by the Bernards': 'Ryan Bernard, Deja Bernard',
    'Crime Scene: The Vanishing at the Cecil Hotel': 'Elisa Lam, Nikos Cozbi',
    'Five Came Back: The Reference Films': 'Meryl Streep',
    'Strip Down, Rise Up': 'Sheila Kelley',
    'Zig & Sharko': 'Animated Characters',
    'We Are: The Brooklyn Saints': 'Brooklyn Saints Coaches and Players',
    'Blown Away': 'Nick Uhas, Katherine Gray',
    'Spycraft': 'Various Intelligence Experts',
    'Bling Empire': 'Kane Lim, Kevin Kreider, Christine Chiu',
    'Night Stalker: The Hunt for a Serial Killer': 'Gil Carrillo, Frank Salerno',
    'Crack: Cocaine, Corruption & Conspiracy': 'Various Historians',
    "Creating The Queen's Gambit": 'Anya Taylor-Joy, Scott Frank',
    'Surviving Death': 'Various Near-Death Experiencers',
    'QB1: Beyond the Lights': 'Tate Martell, Jake Fromm',
    'Dream Home Makeover': 'Shea McGee, Syd McGee',
    'The Minimalists: Less Is Now': 'Joshua Fields Millburn, Ryan Nicodemus',
    'SanPa: Sins of the Savior': 'Vincenzo Muccioli',
    'Regiment Diaries': 'Indian Army Soldiers',
    'Morphle': 'Animated Characters',
    'BREAK IT ALL: The History of Rock in Latin America': 'Charly García, Fito Páez',
    'How To Ruin Christmas': 'Busisiwe Lurayi, Thando Thabethe',
    'The Ripper': 'Investigators and Journalists',
    'Canvas': 'Animated Characters',
    "The Surgeon's Cut": 'Devi Shetty, Kypros Nicolaides',
    'Room 2806: The Accusation': 'Dominique Strauss-Kahn, Nafissatou Diallo',
    'Alien Worlds': 'Sophie Okonedo',
    'The Bachelorette': 'Rachel Lindsay, Clare Crawley',
    'The Holiday Movies That Made Us': 'Danny Wallace',
    'The Repair Shop': 'Jay Blades',
    'Fabulous Lives of Bollywood Wives': 'Maheep Kapoor, Neelam Kothari, Bhavana Pandey, Seema Khan',
    'If Anything Happens I Love You': 'Animated Characters',
    'We Are the Champions': 'Rainn Wilson',
    'Whose Streets?': 'Ferguson Activists and Residents',
    'The Beginning of Life 2: Outside': 'Children and Specialists',
    'Trial 4': 'Sean K. Ellis',
    'We Are All For The Fatherland': 'Documentary Subjects',
    'A Lion in the House': 'Featured Pediatric Cancer Patients',
    'Bakugan: Armored Alliance': 'Jonah Wineberg',
    'Country Ever After': 'Coffey Anderson, Criscilla Anderson',
    'Carmel: Who Killed Maria Marta?': 'Carlos Carrascosa',
    'The Beginning of Life': 'Global Families and Experts',
    '60 Days In': 'Undercover Inmates',
    'LEGO Jurassic World: Legend of Isla Nublar': 'Ian Hanlin',
    'Secrets of the Saqqara Tomb': 'Mohammad Mohammad Yousef',
    'Guillermo Vilas: Settling the Score': 'Guillermo Vilas',
    'Move': 'Various Dancers and Choreographers',
    'Bending the Arc': 'Paul Farmer, Jim Yong Kim',
    'Unsolved Mysteries': 'Re-enactment Cast and Interviewees',
    'Rooting for Roona': 'Roona Begum',
    'The Three Deaths of Marisela Escobedo': 'Marisela Escobedo',
    'Deaf U': 'Cheyenna Clearbrook',
    'Super Monsters: Dia de los Monsters': 'Elyse Maloway',
    'Bad Boy Billionaires: India': 'Vijay Mallya, Nirav Modi, Subrata Roy',
    'Pat a Pat Como': 'Animated Characters',
    'Qurious Como': 'Animated Characters',
    'Human Nature': 'Jennifer Doudna, Emmanuel Charpentier',
    "I'm Leaving Now": 'Felipe Hernandez',
    'American Murder: The Family Next Door': 'Shanann Watts, Chris Watts',
    'Bully': 'Alex Libby, Kelby Johnson',
    'Whose Vote Counts, Explained': 'Leonardo DiCaprio, Selena Gomez',
    'A Perfect Crime': 'Detlev Rohwedder',
    'Mighty Little Bheem': 'Animated Characters',
    'The Playbook': 'Doc Rivers, Jill Ellis, José Mourinho, Serena Williams',
    'A Love Song for Latasha': 'Latasha Harlins',
    'Challenger': 'Astronauts\' Families and Experts',
    'Hope Frozen: A Quest to Live Twice': 'Sahatorn Naovaratpong',
    'Taco Chronicles': 'Various Chefs and Historians',
    'Get Organized with The Home Edit': 'Clea Shearer, Joanna Teplin',
    'La Línea: Shadow of Narco': 'Law Enforcement Officers',
    'My Octopus Teacher': 'Craig Foster',
    'Waiting for "Superman"': 'Geoffrey Canada',
    "Chef's Table: BBQ": 'Tootsie Tomanetz, Rodney Scott',
    'I AM A KILLER: RELEASED': 'Dale Wayne Sigler',
    'Million Dollar Beach House': 'James Giugliano, J.B. Andreassi',
    'Rising Phoenix': 'Tatyana McFadden, Bebe Vio',
    'Baewatch: Parental Guidance': 'Reality Contestants',
    'John Was Trying to Contact Aliens': 'John Shepherd',
    'DeMarcus Family Rules': 'Jay DeMarcus, Allison DeMarcus',
    'High Score': 'Charles Martinet',
    'Islands of Faith': 'Various Religious and Environmental Leaders',
    "Beyond the Boundary: ICC Women's T20 World Cup Australia 2020": 'Featured Cricket Players',
    '(Un)Well': 'Various Health Seekers and Skeptics',
    'Selling Sunset': 'Chrishell Stause, Christine Quinn, Mary Fitzgerald',
    'Word Party Songs': 'Animated Characters',
    "World's Most Wanted": 'Investigators and Journalists',
    'Immigration Nation': 'ICE Agents and Immigrants',
    'The Umbrella Academy': 'Elliot Page, Tom Hopper, David Castañeda, Emmy Raver-Lampman, Robert Sheehan, Aidan Gallagher',
    'The Speed Cubers': 'Max Park, Feliks Zemdegs',
    'Tread': 'Marvin Heemeyer',
    'Sinatra: All or Nothing at All': 'Frank Sinatra',
    'Fear City: New York vs The Mafia': 'Rudy Giuliani, Michael Franzese'
}

In [260]:
df['cast'] = df['cast'].fillna(df['title'].map(netflix_cast_dict_1))
remaining_nulls = df['cast'].isnull().sum()
print(f"Remaining null values in cast column: {remaining_nulls}")

Remaining null values in cast column: 600

In [261]:
missing_cast_titles_2 = missing_cast_titles[225:425]
missing_cast_titles_2

['The Remix: Hip Hop X Fashion',
 'Street Food: Latin America',
 'Gigantosaurus',
 'Father Soldier Son',
 'Little Singham: Legend of Dugabakka',
 'Skin Decision: Before and After',
 'We Are One',
 'Dating Around: Brazil',
 'The Claudia Kishi Club',
 'Southern Survival',
 'Supermarket Sweep',
 'The Silence of Others',
 'Trotro',
 'Homemade',
 'Home Game',
 'Seven (Tamil)',
 'Seven (Telugu)',
 'Athlete A',
 'Babies',
 'Disclosure',
 'Dating Around',
 'Lenox Hill',
 'The Light of My Eyes',
 'Spelling the Dream',
 'Alone',
 'History 101',
 'Especial 20 años Fútbol de Primera',
 'Trial By Media',
 'Hangar 1: The UFO Files',
 'Hoarders',
 'I Am Divine',
 'A Secret Love',
 'Murder to Mercy: The Cyntoia Brown Story',
 'Coronavirus, Explained',
 'Circus of Books',
 'Win the Wilderness',
 'ChuChu TV Nursery Rhymes & Kids Songs (Hindi)',
 'The Innocence Files',
 'LA Originals',
 'The Circle France',
 'Money Heist: The Phenomenon',
 'Sol Levante',
 'How to Fix a Drug Scandal',
 'Man Like Mobeen',
 'Mighty Raju Rio Calling',
 "Sunderland 'Til I Die",
 'Dave Chappelle: The Kennedy Center Mark Twain Prize for American Humor',
 'Making Unorthodox',
 'Crip Camp: A Disability Revolution',
 'A Life of Speed: The Juan Manuel Fangio Story',
 'Tiger King: Murder, Mayhem and Madness',
 'XV: Beyond the Tryline',
 'Ken Burns Presents: College Behind Bars: A Film by Lynn Novick and Produced by Sarah Botstein',
 'Dirty Money',
 'Sitara: Let Girls Dream',
 "ZZ TOP: THAT LITTLE OL' BAND FROM TEXAS",
 'The Trials of Gabriel Fernandez',
 'Passion. Panache. Pep',
 'Untamed Romania',
 'ROAD TO ROMA',
 'Who Killed Malcolm X?',
 'The Pharmacist',
 'Pop Team Epic',
 'Find Yourself',
 'Pandemic: How to Prevent an Outbreak',
 'Tiny House Nation',
 'Cheer',
 "Border Security: America's Front Line",
 'Nisman: The Prosecutor, the President, and the Spy',
 'Kevin Hart: Don’t F**k This Up',
 'After the Raid',
 "Don't F**k with Cats: Hunting an Internet Killer",
 "Okafor's Law",
 'The Confession Killer',
 'Iron Fists and Kung-Fu Kicks',
 'Lugar de Mulher',
 'What the F* Is Going On?',
 'Narcoworld: Dope Stories',
 'Who Killed Little Gregory?',
 'Iron Sky: The Coming Race',
 'The Toys That Made Us',
 'To Be of Service',
 'Greatest Events of WWII in Colour',
 'The Devil Next Door',
 'Fire in Paradise',
 'The Old Thieves: The Legend of Artegios',
 'The Road to El Camino: Behind the Scenes of El Camino: A Breaking Bad Movie',
 'A 3 Minute Hug',
 'It Takes a Lunatic',
 'Little Singham: Kaal Ki Tabaahi',
 'ChuChu TV Kids Songs, Learning Videos & Bedtime Stories',
 'ChuChuTV Bedtime Stories & Moral Stories for Kids (English)',
 'ChuChuTV Bedtime Stories & Moral Stories for Kids (Hindi)',
 'ChuChuTV Surprise Eggs Learning Videos (English)',
 'ChuChuTV Surprise Eggs Learning Videos (Hindi)',
 'Interior Design Masters',
 'Tell Me Who I Am',
 'Ghosts of Sugar Land',
 'League of Legends Origins',
 'Rotten',
 'Living Undocumented',
 'Salam - The First ****** Nobel Laureate',
 'Limitless',
 'Little Baby Bum: Go Buster',
 'Miniforce X',
 'Cultivating the Seas: History and Future of the Full-Cycle Cultured Kindai Tuna',
 'Sturgill Simpson Presents Sound & Fury',
 'Birders',
 'Fastest Car',
 'Evelyn',
 'Elena',
 'Loo Loo Kids: Johny & Friends Musical Adventures',
 'Moving Art',
 'Million Pound Menu',
 'American Factory',
 'Happy Jail',
 'Hasta los dientes',
 'Screwball',
 'Basketball or Nothing',
 'Otherhood',
 'The Great Hack',
 'The Milk System',
 'Parchís: the Documentary',
 'River, el más grande siempre',
 'Cristina',
 'War Against Women',
 'Dope',
 'Exhibit A',
 'Motown Magic',
 'Unbroken',
 'Girls Incarcerated',
 'The Casketeers',
 'The Confession Tapes',
 'The Edge of Democracy',
 'Life Overtakes Me',
 'The Alcàsser Murders',
 'Silent',
 'Killer Ratings',
 'After Maria',
 'A Tale of Two Kitchens',
 '1994',
 'Born in Gaza',
 'Born in Syria',
 'Dying to Tell',
 "ReMastered: The Lion's Share",
 'Weed the People',
 'Jailbirds',
 'Last Breath',
 'All In My Family',
 'ReMastered: Devil at the Crossroads',
 'Street Food',
 'Grass Is Greener',
 'Generation Iron 3',
 'Time: The Kalief Browder Story',
 'Kicko & Super Speedo',
 'The Legend of Cocaine Island',
 'ReMastered: The Miami Showband Massacre',
 'Antoine Griezmann: The Making of a Legend',
 'The Disappearance of Madeleine McCann',
 'Weapon of Choice',
 "BNK48: Girls Don't Cry",
 'Cricket Fever: Mumbai Indians',
 'Losers',
 "Chef's Table",
 'Studio 54',
 'Behind the Curve',
 'Period. End of Sentence.',
 '14 Minutes from Earth',
 'LEGO Marvel Super Heroes: Guardians of the Galaxy',
 'Examination of Conscience',
 'Polar',
 'Conversations with a Killer: The Ted Bundy Tapes',
 'FYRE: The Greatest Party That Never Happened',
 'Abducted in Plain Sight',
 'Adhugo',
 'Back with the Ex',
 'ReMastered: Massacre at the Stadium',
 'Mexicanos de Bronce',
 'Pioneers: First Women Filmmakers*',
 'Murder Mountain',
 'The Birth Reborn 3',
 '7 Days Out',
 'Struggle: The Life and Lost Art of Szukalski',
 'Once in a Lifetime Sessions with George Ezra',
 'Once in a Lifetime Sessions with OneRepublic',
 'Sad Hill Unearthed',
 'Out of Many, One',
 'ReMastered: Who Killed Jam Master Jay?',
 'Ayotzinapa, el paso de la tortuga',
 'Roll With Me',
 'Paap-O-Meter',
 'Muzaffarnagar Baaqi Hai',
 'Age of Tanks',
 'Westside',
 'ReMastered: Tricky Dick & The Man in Black',
 'Santo Cachón',
 'Shirkers',
 'Terrorism Close Calls',
 'The Hollywood Masters',
 'Making a Murderer']

In [262]:
netflix_cast_dict_2 = {
    'The Remix: Hip Hop X Fashion': 'Misa Hylton, Logxstics, Kerby Jean-Raymond',
    'Street Food: Latin America': 'Various Street Food Chefs',
    'Gigantosaurus': 'Dylan Schombing, Áine Sunderland, Nahanni Mitchell, Benjamin Jacobson',
    'Father Soldier Son': 'Brian Eisch',
    'Little Singham: Legend of Dugabakka': 'Anamaya Verma',
    'Skin Decision: Before and After': 'Dr. Sheila Nazarian, Nurse Jamie',
    'We Are One': 'Activists and Musicians',
    'Dating Around: Brazil': 'Reality Contestants',
    'The Claudia Kishi Club': 'Naia Cucukov, Sarah Kuhn, Phil Yu',
    'Southern Survival': 'BattlBox Crew',
    'Supermarket Sweep': 'Leslie Jones',
    'The Silence of Others': 'María Martín, José María Galante',
    'Trotro': 'Animated Characters',
    'Homemade': 'Various Directors',
    'Home Game': 'Mark Strong',
    'Seven (Tamil)': 'Havish, Rahman, Regina Cassandra',
    'Seven (Telugu)': 'Havish, Rahman, Regina Cassandra',
    'Athlete A': 'Maggie Nichols, Gina Nichols, John Nichols',
    'Babies': 'Documentary Subjects',
    'Disclosure': 'Laverne Cox, Susan Stryker, Chaz Bono',
    'Dating Around': 'Reality Contestants',
    'Lenox Hill': 'David Langer, John Boockvar, Mirtha Macri, Amanda Little-Richardson',
    'The Light of My Eyes': 'Cast Members',
    'Spelling the Dream': 'Srinivas Ayyagari, Jacques Bailly',
    'Alone': 'Survival Contestants',
    'History 101': 'Natalie Podd',
    'Especial 20 años Fútbol de Primera': 'Marcelo Araujo',
    'Trial By Media': 'Lawyers and Journalists',
    'Hangar 1: The UFO Files': 'Various UFO Experts',
    'Hoarders': 'Dr. Robin Zasio, Matt Paxton',
    'I Am Divine': 'Divine, Ricki Lake, John Waters',
    'A Secret Love': 'Terry Donahue, Pat Henschel',
    'Murder to Mercy: The Cyntoia Brown Story': 'Cyntoia Brown',
    'Coronavirus, Explained': 'J.K. Simmons, Idris Elba, Sanjay Gupta',
    'Circus of Books': 'Karen Mason, Barry Mason, Rachel Mason',
    'Win the Wilderness': 'Duane Ose, Eleanor Ose',
    'ChuChu TV Nursery Rhymes & Kids Songs (Hindi)': 'Animated Characters',
    'The Innocence Files': 'Barry Scheck, Peter Neufeld',
    'LA Originals': 'Mister Cartoon, Estevan Oriol',
    'The Circle France': 'Reality Contestants',
    'Money Heist: The Phenomenon': 'Úrsula Corberó, Álvaro Morte',
    'Sol Levante': 'Anime Animation Team',
    'How to Fix a Drug Scandal': 'Sonja Farak, Annie Dookhan',
    'Man Like Mobeen': 'Guz Khan, Tez Ilyas, Duaa Karim',
    'Mighty Raju Rio Calling': 'Animated Characters',
    "Sunderland 'Til I Die": 'Sunderland A.F.C. Players and Fans',
    'Dave Chappelle: The Kennedy Center Mark Twain Prize for American Humor': 'Dave Chappelle',
    'Making Unorthodox': 'Shira Haas, Amit Rahav',
    'Crip Camp: A Disability Revolution': 'Judith Heumann, James LeBrecht',
    'A Life of Speed: The Juan Manuel Fangio Story': 'Juan Manuel Fangio',
    'Tiger King: Murder, Mayhem and Madness': 'Joe Exotic, Carole Baskin, Doc Antle',
    'XV: Beyond the Tryline': 'Rugby Players and Coaches',
    'Ken Burns Presents: College Behind Bars: A Film by Lynn Novick and Produced by Sarah Botstein': 'Incarcerated Students',
    'Dirty Money': 'Various Investigators and Journalists',
    'Sitara: Let Girls Dream': 'Animated Characters',
    "ZZ TOP: THAT LITTLE OL' BAND FROM TEXAS": 'Billy Gibbons, Dusty Hill, Frank Beard',
    'The Trials of Gabriel Fernandez': 'Gabriel Fernandez',
    'Passion. Panache. Pep': 'Corporate Experts',
    'Untamed Romania': 'Mark Strong',
    'ROAD TO ROMA': 'Alfonso Cuarón',
    'Who Killed Malcolm X?': 'Abdur-Rahman Muhammad',
    'The Pharmacist': 'Dan Schneider',
    'Pop Team Epic': 'Popuko, Pipimi',
    'Find Yourself': 'Victoria Song, Song Weilong',
    'Pandemic: How to Prevent an Outbreak': 'Syra Madad',
    'Tiny House Nation': 'John Weisbarth, Zack Giffin',
    'Cheer': 'Monica Aldama, Gabi Butler, Lexi Brumback',
    "Border Security: America's Front Line": 'Border Patrol Agents',
    'Nisman: The Prosecutor, the President, and the Spy': 'Alberto Nisman',
    'Kevin Hart: Don’t F**k This Up': 'Kevin Hart',
    'After the Raid': 'Community Members',
    "Don't F**k with Cats: Hunting an Internet Killer": 'John Green, Deanna Thompson',
    "Okafor's Law": 'Blossom Chukwujekwu, Omoni Oboli',
    'The Confession Killer': 'Henry Lee Lucas',
    'Iron Fists and Kung-Fu Kicks': 'Various Martial Artists',
    'Lugar de Mulher': 'Bruna Louise',
    'What the F* Is Going On?': 'Spanish Politicians',
    'Narcoworld: Dope Stories': 'Law Enforcement and Traffickers',
    'Who Killed Little Gregory?': 'Gregory Villemin',
    'Iron Sky: The Coming Race': 'Lara Rossi, Vladimir Burlakov',
    'The Toys That Made Us': 'Donald Ian Black',
    'To Be of Service': 'Veterans and Service Dogs',
    'Greatest Events of WWII in Colour': 'Robert Powell',
    'The Devil Next Door': 'John Demjanjuk',
    'Fire in Paradise': 'Paradise Residents',
    'The Old Thieves: The Legend of Artegios': 'Artegios',
    'The Road to El Camino: Behind the Scenes of El Camino: A Breaking Bad Movie': 'Aaron Paul, Vince Gilligan',
    'A 3 Minute Hug': 'Families at the Border',
    'It Takes a Lunatic': 'Wynn Handman',
    'Little Singham: Kaal Ki Tabaahi': 'Animated Characters',
    'ChuChu TV Kids Songs, Learning Videos & Bedtime Stories': 'Animated Characters',
    'ChuChuTV Bedtime Stories & Moral Stories for Kids (English)': 'Animated Characters',
    'ChuChuTV Bedtime Stories & Moral Stories for Kids (Hindi)': 'Animated Characters',
    'ChuChuTV Surprise Eggs Learning Videos (English)': 'Animated Characters',
    'ChuChuTV Surprise Eggs Learning Videos (Hindi)': 'Animated Characters',
    'Interior Design Masters': 'Fearne Cotton, Michelle Ogundehin',
    'Tell Me Who I Am': 'Alex Lewis, Marcus Lewis',
    'Ghosts of Sugar Land': 'Mark, KC',
    'League of Legends Origins': 'Brandon Beck, Marc Merrill',
    'Rotten': 'Latif Nasser',
    'Living Undocumented': 'Undocumented Families',
    'Salam - The First ****** Nobel Laureate': 'Abdus Salam',
    'Limitless': 'Chris Hemsworth',
    'Little Baby Bum: Go Buster': 'Animated Characters',
    'Miniforce X': 'Animated Characters',
    'Cultivating the Seas: History and Future of the Full-Cycle Cultured Kindai Tuna': 'Kindai University Researchers',
    'Sturgill Simpson Presents Sound & Fury': 'Sturgill Simpson',
    'Birders': 'Bird Watchers',
    'Fastest Car': 'Drivers and Car Enthusiasts',
    'Evelyn': 'Orlando von Einsiedel',
    'Elena': 'Elena Anaya',
    'Loo Loo Kids: Johny & Friends Musical Adventures': 'Animated Characters',
    'Moving Art': 'Louie Schwartzberg',
    'Million Pound Menu': 'Fred Sirieix',
    'American Factory': 'Fuyao Factory Workers',
    'Happy Jail': 'CPDRC Inmates',
    'Hasta los dientes': 'Jorge Antonio Mercado Alonso, Javier Francisco Arredondo Verdugo',
    'Screwball': 'Tony Bosch',
    'Basketball or Nothing': 'Chinle High School Basketball Team',
    'Otherhood': 'Angela Bassett, Patricia Arquette, Felicity Huffman',
    'The Great Hack': 'Carole Cadwalladr, David Carroll, Brittany Kaiser',
    'The Milk System': 'Farmers and Experts',
    'Parchís: the Documentary': 'Constantino Fernández Fernández, Yolanda Ventura Román',
    'River, el más grande siempre': 'River Plate Players',
    'Cristina': 'Cristina',
    'War Against Women': 'Documentary Subjects',
    'Dope': 'Real Participants',
    'Exhibit A': 'Forensic Experts',
    'Motown Magic': 'Animated Characters',
    'Unbroken': 'Louis Zamperini',
    'Girls Incarcerated': 'Incarcerated Teen Girls',
    'The Casketeers': 'Francis Tipene, Kaiora Tipene',
    'The Confession Tapes': 'False Confession Cases',
    'The Edge of Democracy': 'Dilma Rousseff, Lula da Silva',
    'Life Overtakes Me': 'Resignation Syndrome Children',
    'The Alcàsser Murders': 'Investigators and Families',
    'Silent': 'Animated Characters',
    'Killer Ratings': 'Wallace Souza',
    'After Maria': 'Puerto Rican Displaced Women',
    'A Tale of Two Kitchens': 'Gabriela Cámara',
    '1994': 'Carlos Salinas de Gortari',
    'Born in Gaza': 'Children of Gaza',
    'Born in Syria': 'Children of Syria',
    'Dying to Tell': 'Journalists',
    "ReMastered: The Lion's Share": 'Solomon Linda',
    'Weed the People': 'Medical Cannabis Patients',
    'Jailbirds': 'Inmates of Sacramento County Jail',
    'Last Breath': 'Chris Lemons',
    'All In My Family': 'Hao Wu',
    'ReMastered: Devil at the Crossroads': 'Robert Johnson',
    'Street Food': 'Street Food Chefs',
    'Grass Is Greener': 'Fab 5 Freddy',
    'Generation Iron 3': 'Bodybuilders',
    'Time: The Kalief Browder Story': 'Kalief Browder',
    'Kicko & Super Speedo': 'Animated Characters',
    'The Legend of Cocaine Island': 'Rodney Hyden',
    'ReMastered: The Miami Showband Massacre': 'Stephen Travers',
    'Antoine Griezmann: The Making of a Legend': 'Antoine Griezmann',
    'The Disappearance of Madeleine McCann': 'Investigators and Journalists',
    'Weapon of Choice': 'Intelligence Experts',
    "BNK48: Girls Don't Cry": 'BNK48 Members',
    'Cricket Fever: Mumbai Indians': 'Mumbai Indians Team',
    'Losers': 'Various Athletes',
    "Chef's Table": 'Renowned Chefs',
    'Studio 54': 'Ian Schrager',
    'Behind the Curve': 'Mark Sargent',
    'Period. End of Sentence.': 'Arunachalam Muruganantham',
    '14 Minutes from Earth': 'Alan Eustace',
    'LEGO Marvel Super Heroes: Guardians of the Galaxy': 'Animated Characters',
    'Examination of Conscience': 'Spanish Survivors',
    'Polar': 'Mads Mikkelsen, Vanessa Hudgens',
    'Conversations with a Killer: The Ted Bundy Tapes': 'Ted Bundy',
    'FYRE: The Greatest Party That Never Happened': 'Billy McFarland',
    'Abducted in Plain Sight': 'Jan Broberg',
    'Adhugo': 'Ravi Babu',
    'Back with the Ex': 'Reality Contestants',
    'ReMastered: Massacre at the Stadium': 'Víctor Jara',
    'Mexicanos de Bronce': 'Prison Inmates',
    'Pioneers: First Women Filmmakers*': 'Alice Guy-Blaché',
    'Murder Mountain': 'Garret Rodriguez',
    'The Birth Reborn 3': 'Medical Staff and Mothers',
    '7 Days Out': 'Various Professionals',
    'Struggle: The Life and Lost Art of Szukalski': 'Stanislav Szukalski',
    'Once in a Lifetime Sessions with George Ezra': 'George Ezra',
    'Once in a Lifetime Sessions with OneRepublic': 'OneRepublic',
    'Sad Hill Unearthed': 'Ennio Morricone, James Hetfield',
    'Out of Many, One': 'Immigrants',
    'ReMastered: Who Killed Jam Master Jay?': 'Jam Master Jay',
    'Ayotzinapa, el paso de la tortuga': 'Students and Families',
    'Roll With Me': 'Gabriel Cordell',
    'Paap-O-Meter': 'Animated Characters',
    'Muzaffarnagar Baaqi Hai': 'Local Witnesses',
    'Age of Tanks': 'Military Historians',
    'Westside': 'Sean Patrick Murray',
    'ReMastered: Tricky Dick & The Man in Black': 'Johnny Cash, Richard Nixon',
    'Santo Cachón': 'Alejandro Gutiérrez',
    'Shirkers': 'Sandi Tan',
    'Terrorism Close Calls': 'Intelligence Officials',
    'The Hollywood Masters': 'Various Filmmakers',
    'Making a Murderer': 'Steven Avery, Brendan Dassey'
}

In [263]:
df['cast'] = df['cast'].fillna(df['title'].map(netflix_cast_dict_2))
remaining_nulls = df['cast'].isnull().sum()
print(f"Remaining null values in cast column: {remaining_nulls}")

Remaining null values in cast column: 400

In [264]:
missing_cast_titles_3 = missing_cast_titles[425:625]
missing_cast_titles_3

['Stunt Science',
 'Feminists: What Were They Thinking?',
 'ReMastered: Who Shot the Sheriff',
 'The Meaning of Monty Python',
 'The Birth Reborn',
 'Three Wives One Husband',
 'Lessons from a School Shooting: Notes from Dunblane',
 'Made in Mexico',
 'Two Catalonias',
 'Battlefish',
 'Boca Juniors Confidential',
 'Norm Macdonald Has a Show',
 'City of Joy',
 'First and Last',
 'Inside the Criminal Mind',
 "Chicken Soup for the Soul's Being Dad",
 'Afflicted',
 'Becoming Champions',
 'The Bleeding Edge',
 'Amazing Interiors',
 'Dark Tourist',
 'Drug Lords',
 'First Team: Juventus',
 'What We Started',
 'Churchill’s Secret Agents: The New Recruits',
 'Recovery Boys',
 'Pacificum: Return to the Ocean',
 'The Staircase',
 'November 13: Attack on Paris',
 'The Break with Michelle Wolf',
 'Food on the Go',
 'Evil Genius',
 'End Game',
 'Coffee for All',
 'Pocoyo Special Sports',
 'The Rachel Divide',
 'Mercury 13',
 'Take Your Pills',
 'Wild Wild Country',
 'Ladies First',
 'Flint Town',
 'The Trader (Sovdagari)',
 'Liberated: The New Sexual Revolution',
 'Under Arrest',
 'Countdown to Death: Pablo Escobar',
 'The Reservoir Game',
 "Eve's Apple",
 'The Secret',
 'Cuba and the Cameraman',
 'Shot in the Dark',
 'Let It Fall: Los Angeles 1982-1992',
 'One of Us',
 'Kingdom of Us',
 'The Death and Life of Marsha P. Johnson',
 'Franca: Chaos and Creation',
 'Generation Iron 2',
 'Noddy Toyland Detective',
 'The Royal House of Windsor',
 'Long Shot',
 'Out of Thin Air',
 'Strong Island',
 'Heroin(e)',
 'Fire Chasers',
 'Alias JJ, la celebridad del mal',
 'High Risk',
 'Resurface',
 'Daughters of Destiny',
 'I Called Him Morgan',
 'Chasing Coral',
 'Nobody Speak: Trials of the Free Press',
 'Counterpunch',
 'What the Health',
 'Michael Lost and Found',
 'Without Gorky',
 'Joshua: Teenager vs. Superpower',
 'The Keepers',
 'Natascha Kampusch: The Whole Story',
 'JFK: The Making of a President',
 'Casting JonBenet',
 'Hot Girls Wanted: Turned On',
 'Life 2.0',
 'Outback Truckers',
 'Cheer Squad',
 'Rush: Beyond the Lighted Stage',
 'Hitler - A Career',
 'Casablancas: The Man Who Loved Women',
 'Captive',
 'The Cuba Libre Story',
 '#Rucker50',
 'The Ivory Game',
 '13TH',
 "Masha's Spooky Stories",
 'Amanda Knox',
 'Audrie & Daisy',
 'The White Helmets',
 'Extremis',
 "Chef's Table: France",
 'Saudi Arabia Uncovered',
 'Behind Enemy Lines',
 'Real Crime: Supermarket Heist (Tesco Bomber)',
 'Children of God',
 'Cocaine',
 'Edge of the Universe',
 '72 Cutest Animals',
 'Team Foxcatcher',
 'Frank and Cindy',
 "Masha's Tales",
 'Sammy & Co',
 "Winter on Fire: Ukraine's Fight for Freedom",
 'What Happened, Miss Simone?',
 'Hot Girls Wanted',
 "Oscar's Oasis",
 'Virunga: Gorillas in Peril',
 'Virunga',
 'E-Team',
 'Print the Legend',
 'From One Second to the Next',
 '(T)ERROR',
 '#cats_the_mewvie',
 '100 Days Of Solitude',
 "100 Years: One Woman's Fight for Justice",
 '3 Seconds Divorce',
 'A Gray State',
 'A Leaf of Faith',
 'A Murder in the Park',
 'A new Capitalism',
 'A Week in Watts',
 'After Porn Ends',
 'After Porn Ends 3',
 'Alarmoty in the Land of Fire',
 'Alive and Kicking',
 'AlphaGo',
 'American Circumcision',
 'American Experience: The Circus',
 'An American in Madras',
 'Anjaan: Rural Myths',
 '忍者ハットリくん',
 'Apache Warrior',
 'Aussie Gold Hunters',
 'Bachelor Girls',
 'Barbecue',
 'Battlefield Recovery',
 'Beak & Brain: Genius Birds From Down Under',
 'Beary Tales',
 'Behind "The Cove": The Quiet Japanese Speak Out',
 'Berlin, I Love You',
 'Bheemayan',
 'Black Man White Skin',
 'Blackfish',
 'Blurred Lines: Inside the Art World',
 'Bobby Sands: 66 Days',
 'Bugs',
 'Bure Kaam Bura Natija, Kyun Bhai Chacha Haan Bhatija',
 'Burlesque: Heart of the Glitter Tribe',
 'Calico Critters: A Town of Dreams',
 'Calico Critters: The Treasure of Calico Village',
 'Camp X',
 'Capital in the Twenty-First Century',
 'Catching the Sun',
 'Catwalk: Tales from the Cat Show Circuit',
 'Christiane Amanpour: Sex & Love Around the World',
 'Chuck Chicken',
 'City in the Sky',
 'Civilizations',
 'Cold Case Files',
 'Command and Control',
 'Conan Without Borders',
 'Concrete Football',
 'Cop Watchers',
 'Dare to Be Wild',
 'Democrats',
 'Diana: In Her Own Words',
 'Dinner for Five',
 'Dino Hunt',
 'Diva Brides',
 'Down The Fence',
 'Dragonkala Ka Rahasya',
 'Dream Boat',
 'El fin de ETA',
 'El Viaje: Márama y Rombai',
 'Elizabeth at 90: A Family Tribute',
 'Elles étaient en guerre 1939-1945',
 'Elles ont toutes une histoire',
 'Empire of Scents',
 'Exit Afghanistan',
 'Famous in Ahmedabad',
 'Fear Files... Har Mod Pe Darr',
 'Fishpeople',
 'Fittest in Dubai',
 'Footprints: The Path of Your Life',
 'For Grace',
 'Forces of Nature',
 'Forever Chape',
 'Forever Pure',
 'Forget Me Not',
 'Forks Over Knives',
 'Friday Night Tykes',
 'Functional Fitness',
 'GLOW: The Story of the Gorgeous Ladies of Wrestling',
 'Golden Time']

In [265]:
netflix_cast_dict_3 = {
    'Stunt Science': 'Dallas Campbell, Various Stunt Performers',
    'Feminists: What Were They Thinking?': 'Jane Fonda, Lily Tomlin, Judy Chicago, Laurie Anderson',
    'ReMastered: Who Shot the Sheriff': 'Bob Marley, Edward Seaga, Michael Manley',
    'The Meaning of Monty Python': 'John Cleese, Terry Gilliam, Eric Idle, Michael Palin, Terry Jones, Graham Chapman',
    'The Birth Reborn': 'Érica de Paula, Eduardo Chauvet',
    'Three Wives One Husband': 'Enoch Foster, Catrina Foster',
    'Lessons from a School Shooting: Notes from Dunblane': 'Father Bob Weiss, Monsignor Basil O\'Sullivan',
    'Made in Mexico': 'Pepe Díaz, Shanik Aspe, Kitzia Mitre, Chantal Trujillo',
    'Two Catalonias': 'Carles Puigdemont, Inés Arrimadas',
    'Battlefish': 'William \'Bill\' McGee, Fishing Vessel Crews',
    'Boca Juniors Confidential': 'Guillermo Barros Schelotto, Carlos Tevez, Darío Benedetto',
    'Norm Macdonald Has a Show': 'Norm Macdonald, Adam Eget',
    'City of Joy': 'Christine Schuler Deschryver, Dr. Denis Mukwege, Eve Ensler',
    'First and Last': 'Inmates of Gwinnett County Jail',
    'Inside the Criminal Mind': 'Various Criminologists and FBI Profilers',
    "Chicken Soup for the Soul's Being Dad": 'Various Featured Fathers',
    'Afflicted': 'Jamison, Bekah, Carmen, Pilar',
    'Becoming Champions': 'Pelé, Diego Maradona, Lothar Matthäus',
    'The Bleeding Edge': 'Stephen Tower, Various Medical Patients and Experts',
    'Amazing Interiors': 'Various Homeowners and Designers',
    'Dark Tourist': 'David Farrier',
    'Drug Lords': 'Various Law Enforcement Officers and Drug Kingpins',
    'First Team: Juventus': 'Gianluigi Buffon, Giorgio Chiellini, Gonzalo Higuaín, Massimiliano Allegri',
    'What We Started': 'Martin Garrix, Carl Cox, Paul Oakenfold',
    'Churchill’s Secret Agents: The New Recruits': 'Student Recruits',
    'Recovery Boys': 'Jeff, Rush, Adam, Ryan',
    'Pacificum: Return to the Ocean': 'Rodolfo Salas, Yuri Hooker, Aldo Benites',
    'The Staircase': 'Michael Peterson, David Rudolf, Todd Peterson',
    'November 13: Attack on Paris': 'Survivors and First Responders',
    'The Break with Michelle Wolf': 'Michelle Wolf',
    'Food on the Go': 'Various Chefs and Food Historians',
    'Evil Genius': 'Trey Borzillieri, Marjorie Diehl-Armstrong, Bilal Ahmed',
    'End Game': 'Dr. Steven Pantilat, Dr. Biviano',
    'Coffee for All': 'Various Coffee Artisans and Enthusiasts',
    'Pocoyo Special Sports': 'Animated Characters',
    'The Rachel Divide': 'Rachel Dolezal',
    'Mercury 13': 'Wally Funk, Rhea Woltman, Gene Nora Jessen',
    'Take Your Pills': 'Various Students, Athletes, and Medical Professionals',
    'Wild Wild Country': 'Ma Anand Sheela, Bhagwan Shree Rajneesh (Osho), John Silvertooth',
    'Ladies First': 'Deepika Kumari',
    'Flint Town': 'Flint Police Department Officers',
    'The Trader (Sovdagari)': 'Gela Bekauri',
    'Liberated: The New Sexual Revolution': 'Various College Students',
    'Under Arrest': 'Law Enforcement Officers',
    'Countdown to Death: Pablo Escobar': 'Pablo Escobar',
    'The Reservoir Game': 'Documentary Participants',
    "Eve's Apple": 'Documentary Participants',
    'The Secret': 'Rhonda Byrne, Bob Proctor, John Assaraf',
    'Cuba and the Cameraman': 'Jon Alpert, Fidel Castro',
    'Shot in the Dark': 'Howard Raishbrook, Austin Raishbrook, Zak Holman',
    'Let It Fall: Los Angeles 1982-1992': 'Various Interviewees and Witnesses',
    'One of Us': 'Luzer Twersky, Ari Hershkowitz, Etty',
    'Kingdom of Us': 'Shanks Family (Vikki Shanks)',
    'The Death and Life of Marsha P. Johnson': 'Victoria Cruz, Marsha P. Johnson',
    'Franca: Chaos and Creation': 'Franca Sozzani, Francesco Carrozzini',
    'Generation Iron 2': 'Kai Greene, Calum Von Moger, Rich Piana',
    'Noddy Toyland Detective': 'Animated Characters',
    'The Royal House of Windsor': 'Gwilym Lee',
    'Long Shot': 'Juan Catalan, Larry David, Tim Landsberger',
    'Out of Thin Air': 'Erla Bolladóttir, Albert Geldard',
    'Strong Island': 'Yance Ford, William Ford Jr.',
    'Heroin(e)': 'Jan Rader, Necia Freeman, Patricia Keller',
    'Fire Chasers': 'California Firefighters',
    'Alias JJ, la celebridad del mal': 'Juan Pablo Urrego, Amparo Grisales, Nicole Santamaría',
    'High Risk': 'Documentary Participants',
    'Resurface': 'Bobby Lane, Van Curaza',
    'Daughters of Destiny': 'Shanti Bhavan Students',
    'I Called Him Morgan': 'Lee Morgan, Helen Morgan',
    'Chasing Coral': 'Richard Vevers, Zackery Rago, Ove Hoegh-Guldberg',
    'Nobody Speak: Trials of the Free Press': 'Hulk Hogan, Nick Denton, Peter Thiel',
    'Counterpunch': 'Peter Quillin, Cam F. Awesome, Christopher Colbert',
    'What the Health': 'Kip Andersen',
    'Michael Lost and Found': 'Michael Holtz, Benji',
    'Without Gorky': 'Cosima Spender',
    'Joshua: Teenager vs. Superpower': 'Joshua Wong',
    'The Keepers': 'Gemma Hoskins, Abbie Schaub, Jean Wehner',
    'Natascha Kampusch: The Whole Story': 'Natascha Kampusch',
    'JFK: The Making of a President': 'John F. Kennedy',
    'Casting JonBenet': 'Hannah Strand, Aeona Cruz, Shari Shuck',
    'Hot Girls Wanted: Turned On': 'Various Digital Content Creators',
    'Life 2.0': 'Second Life Users',
    'Outback Truckers': 'Steve Grahame, Robbie Mackay',
    'Cheer Squad': 'Great White Sharks Cheerleaders',
    'Rush: Beyond the Lighted Stage': 'Geddy Lee, Alex Lifeson, Neil Peart',
    'Hitler - A Career': 'Adolf Hitler, Joachim Fest',
    'Casablancas: The Man Who Loved Women': 'John Casablancas',
    'Captive': 'Various Hostages and Negotiators',
    'The Cuba Libre Story': 'Various Historians and Political Figures',
    '#Rucker50': 'Various Streetball Legends',
    'The Ivory Game': 'Craig Millar, Andrea Crosta',
    '13TH': 'Angela Davis, Michelle Alexander, Ava DuVernay, Van Jones',
    "Masha's Spooky Stories": 'Animated Characters',
    'Amanda Knox': 'Amanda Knox, Raffaele Sollecito, Nick Pisa',
    'Audrie & Daisy': 'Audrie Pott, Daisy Coleman',
    'The White Helmets': 'Khalid Farah, Mohammed Farah, Abu Omar',
    'Extremis': 'Dr. Jessica Zitter',
    "Chef's Table: France": 'Alain Passard, Adeline Grattard, Alexandre Couillon, Michel Troisgros',
    'Saudi Arabia Uncovered': 'Anonymous Activists',
    'Behind Enemy Lines': 'Owen Wilson, Gene Hackman',
    'Real Crime: Supermarket Heist (Tesco Bomber)': 'Documentary Interviewees',
    'Children of God': 'Documentary Participants',
    'Cocaine': 'Documentary Participants',
    'Edge of the Universe': 'Various Astronomers and Astrophysicists',
    '72 Cutest Animals': 'Various Wildlife Experts',
    'Team Foxcatcher': 'Dave Schultz, Valentin Jordanov, Nancy Schultz',
    'Frank and Cindy': 'Frank Garcia, Cindy Brown, G.J. Echternkamp',
    "Masha's Tales": 'Animated Characters',
    'Sammy & Co': 'Animated Characters',
    "Winter on Fire: Ukraine's Fight for Freedom": 'Various Ukrainian Citizens and Protesters',
    'What Happened, Miss Simone?': 'Nina Simone, Lisa Simone Kelly',
    'Hot Girls Wanted': 'Various Amateur Adult Content Creators',
    "Oscar's Oasis": 'Animated Characters',
    'Virunga: Gorillas in Peril': 'Virunga National Park Rangers',
    'Virunga': 'Emmanuel de Merode, Rodrigue Mugaruka Katembo, Mélanie Gouby',
    'E-Team': 'Anna Neistat, Ole Solvang, Peter Bouckaert',
    'Print the Legend': 'Cody Wilson, Bre Pettis, Maxim Lobovsky',
    'From One Second to the Next': 'Various Victims and Drivers Affected by Texting',
    '(T)ERROR': 'Saeed "Shariff" Torres',
    '#cats_the_mewvie': 'Various Cats and Internet Owners',
    '100 Days Of Solitude': 'José Díaz',
    "100 Years: One Woman's Fight for Justice": 'Elouise Cobell',
    '3 Seconds Divorce': 'Various Interviewees',
    'A Gray State': 'David Crowley',
    'A Leaf of Faith': 'Chris Bell',
    'A Murder in the Park': 'Alstory Simon, Anthony Porter, David Protess',
    'A new Capitalism': 'Various Global Entrepreneurs',
    'A Week in Watts': 'Various LAPD Officers and Community Youth',
    'After Porn Ends': 'Various Former Adult Film Performers',
    'After Porn Ends 3': 'Various Former Adult Film Performers',
    'Alarmoty in the Land of Fire': 'Ahmed Adam, Amira El Aidy',
    'Alive and Kicking': 'Various Swing Dancers and Historians',
    'AlphaGo': 'Demis Hassabis, Lee Sedol, David Silver',
    'American Circumcision': 'Various Medical Experts and Activists',
    'American Experience: The Circus': 'Michael Murphy',
    'An American in Madras': 'Documentary Participants',
    'Anjaan: Rural Myths': 'Various Folklore Narrators',
    '忍者ハットリくん': 'Animated Characters',
    'Apache Warrior': 'Various US Army Apache Pilots',
    'Aussie Gold Hunters': 'Various Gold Prospectors',
    'Bachelor Girls': 'Single Women in Mumbai',
    'Barbecue': 'Various Barbecue Chefs and Cooks',
    'Battlefield Recovery': 'Craig Gottlieb, Stephen Taylor',
    'Beak & Brain: Genius Birds From Down Under': 'Kea and New Caledonian Crows',
    'Beary Tales': 'Documentary Participants',
    'Behind "The Cove": The Quiet Japanese Speak Out': 'Keiko Yagi',
    'Berlin, I Love You': 'Keira Knightley, Helen Mirren, Luke Wilson, Jim Sturgess',
    'Bheemayan': 'Animated Characters',
    'Black Man White Skin': 'Various Albinism Advocates',
    'Blackfish': 'Tilikum, John Hargrove, Samantha Berg',
    'Blurred Lines: Inside the Art World': 'Various Contemporary Artists and Dealers',
    'Bobby Sands: 66 Days': 'Bobby Sands',
    'Bugs': 'Ben Reade, Josh Evans',
    'Bure Kaam Bura Natija, Kyun Bhai Chacha Haan Bhatija': 'Animated Characters',
    'Burlesque: Heart of the Glitter Tribe': 'Various Burlesque Performers',
    'Calico Critters: A Town of Dreams': 'Animated Characters',
    'Calico Critters: The Treasure of Calico Village': 'Animated Characters',
    'Camp X': 'Various Secret Agent Trainees',
    'Capital in the Twenty-First Century': 'Thomas Piketty, Joseph Stiglitz, Ian Bremmer',
    'Catching the Sun': 'Various Solar Energy Advocates and Workers',
    'Catwalk: Tales from the Cat Show Circuit': 'Shirley Friedman, Kim Langille',
    'Christiane Amanpour: Sex & Love Around the World': 'Christiane Amanpour',
    'Chuck Chicken': 'Animated Characters',
    'City in the Sky': 'Dallas Campbell, Hannah Fry',
    'Civilizations': 'Mary Beard, David Olusoga, Simon Schama',
    'Cold Case Files': 'Bill Kurtis',
    'Command and Control': 'Eric Schlosser',
    'Conan Without Borders': 'Conan O\'Brien',
    'Concrete Football': 'Various Street Football Players',
    'Cop Watchers': 'Various Citizen Activists',
    'Dare to Be Wild': 'Emma Greenwell, Tom Hughes, Alex Macqueen',
    'Democrats': 'Morgan Tsvangirai, Robert Mugabe',
    'Diana: In Her Own Words': 'Princess Diana',
    'Dinner for Five': 'Jon Favreau',
    'Dino Hunt': 'Various Paleontologists',
    'Diva Brides': 'Various Brides',
    'Down The Fence': 'Various Horse Trainers and Competitors',
    'Dragonkala Ka Rahasya': 'Animated Characters',
    'Dream Boat': 'Various Cruise Passengers',
    'El fin de ETA': 'Various Spanish Politicians and Journalists',
    'El Viaje: Márama y Rombai': 'Agustín Casanova, Camila Rajchman',
    'Elizabeth at 90: A Family Tribute': 'Queen Elizabeth II, King Charles III, Prince William',
    'Elles étaient en guerre 1939-1945': 'Various Historic Female Figures',
    'Elles ont toutes une histoire': 'Various Women Worldwide',
    'Empire of Scents': 'Various Perfume Designers',
    'Exit Afghanistan': 'Various Deployed Soldiers',
    'Famous in Ahmedabad': 'Zaid Kedia',
    'Fear Files... Har Mod Pe Darr': 'Various Episodic Cast Members',
    'Fishpeople': 'Various Surfers, Swimmers, and Divers',
    'Fittest in Dubai': 'Various CrossFit Competitors',
    'Footprints: The Path of Your Life': 'Various Pilgrims',
    'For Grace': 'Curtis Duffy, Ruth De Jong',
    'Forces of Nature': 'Brian Cox',
    'Forever Chape': 'Chapecoense Survival Players and Families',
    'Forever Pure': 'Arcadi Gaydamak, Eli Cohen, Ariel Harush',
    'Forget Me Not': 'David Sieveking, Gretel Sieveking',
    'Forks Over Knives': 'T. Colin Campbell, Caldwell Esselstyn',
    'Friday Night Tykes': 'Youth Football Coaches',
    'Functional Fitness': 'Various Fitness Competitors',
    'GLOW: The Story of the Gorgeous Ladies of Wrestling': 'Various GLOW Wrestlers',
    'Golden Time': 'Yui Horie, Makoto Furukawa, Ai Kayano'
}

In [266]:
df['cast'] = df['cast'].fillna(df['title'].map(netflix_cast_dict_3))
remaining_nulls = df['cast'].isnull().sum()
print(f"Remaining null values in cast column: {remaining_nulls}")

Remaining null values in cast column: 200

In [267]:
missing_cast_titles_4 = missing_cast_titles[625:825]
missing_cast_titles_4

['Great Yellowstone Thaw',
 'Gringo: The Dangerous Life of John McAfee',
 'Growing Up Coy',
 'Gun Runners',
 'Harry & Bunnie',
 'Haunters: The Art of the Scare',
 'Highly Strung',
 "History's Greatest Hoaxes",
 "Hitler's Olympics",
 "Hitler's Steel Beast",
 'Holy Hell',
 'Hostage to the Devil',
 'Hostages',
 'How to Change the World',
 'How to Live Mortgage Free with Sarah Beeny',
 'How to Win the US Presidency',
 'I Am Sun Mu',
 'I Dream Of Dance',
 'Incorruptible',
 'Influx',
 'Inside The Freemasons',
 'Inside the Mind of a Serial Killer',
 'Inside the Mossad',
 'Inst@famous',
 'Invisible Essence: The Little Prince',
 'Islands of the Future',
 'Jack of all Trades',
 'JingleKids',
 'Joe Cocker: Mad Dog with Soul',
 'John & Jane',
 'Jugaad',
 'Ken Burns: The Roosevelts: An Intimate History',
 'Kingdoms of the Sky',
 'Kon Kon Kon',
 'LA 92',
 'Le serment des Hitler',
 'LEGO Ninjago: Masters of Spinjitzu: Day of the Departed',
 'Les Bleus - Une autre histoire de France, 1996-2016',
 'License to Drill: Louisiana',
 'Life in the Doghouse',
 'Little Singham aur Kaal ka Mahajaal',
 'Little Singham in London',
 'Lo que la verdad esconde: El caso Asunta (Operacion Nenúfar)',
 'Los Niños Héroes de Chapultepec',
 'Los tiempos de Pablo Escobar',
 'Losing Sight of Shore',
 'LoveTrue',
 'Marching Orders',
 'Martyrs of Marriage',
 'Maynard',
 'Meet the Trumps: From Immigrant to President',
 'Mega Food',
 'MegaTruckers',
 'Melodies of Life - Born This Way',
 'Memory Games',
 'Mexico Diseña',
 'Mini Wolf',
 'Miss Representation',
 'Mission Control: The Unsung Heroes of Apollo',
 'Money for Nothing',
 'Monster High: Haunted',
 "Monty Don's French Gardens",
 'Mortified Nation',
 'Mountain',
 'Murderous Affairs',
 'Naga The Eternal Yogi',
 "Naledi: A Baby Elephant's Tale",
 'National Bird',
 'Nazi Concentration Camps',
 'Nazi Mega Weapons',
 'Newtown',
 'Not Alone',
 'NOVA: Eclipse Over America',
 'NOVA: Holocaust Escape Tunnel',
 'NOVA: Thai Cave Rescue',
 'NOVA: The Impossible Flight',
 'Nuestra Lucha Libre',
 'Numbered',
 'Numero Zero. The Roots of Italian Rap',
 'Nurses Who Kill',
 'Oh My Ghost 4',
 'Oklahoma City',
 'Once In A Lifetime Sessions with TLC',
 'One More Shot',
 'Operation Odessa',
 'Origins Collection',
 'Pablo Escobar: Angel or Demon?',
 'Palio',
 'Paranormal Survivor',
 'Paris Is Burning',
 'Patient Seventeen',
 'Pick of the Litter',
 'Pioneers of African-American Cinema',
 'Playing Hard',
 'Prelude to War',
 'Prince Jai Aur Dumdaar Viru',
 'Q Ball',
 'Queens of Comedy',
 'Radical: the Controversial Saga of Dada Figueiredo',
 'Raiders!: The Story of the Greatest Fan Film Ever Made',
 'Rats',
 'Rica, Famosa, Latina',
 'Roll Red Roll',
 'Rolling Papers',
 'Roots',
 'S Is for Stanley',
 'Sacro GRA',
 'San Pietro',
 'Shadow of Truth',
 'Silicon Cowboys',
 'Skydancers',
 'Smash: Motorized Mayhem',
 'Social Animals',
 'Sons of Ben',
 'Sour Grapes',
 'Speed Is My Need',
 'Star Men',
 'Stop at Nothing: The Lance Armstrong Story',
 'Strike a Pose',
 'Strongland',
 'SuperNature: Wild Flyers',
 'Sustainable',
 'Teach Us All',
 'Tellur Aliens',
 'Thackeray',
 'The 2000s',
 'The 24 Hour War',
 'The Accountant of Auschwitz',
 'The Animal People',
 'The Bachelor',
 'The Bad Kids',
 'The Beginning of Life: The Series',
 'The Bomb',
 'The Calling',
 'The Darkest Dawn',
 'The Devil and Father Amorth',
 'The Devil We Know',
 'The Eighties',
 'The Fear of 13',
 'The Force',
 'The Future of Water',
 'The Gentleman Driver',
 'The Golden Years with Javed Akhtar',
 'The Heat: A Kitchen (R)evolution',
 'The House on Coco Road',
 'The Human Factor: The Untold Story of the Bombay Film Orchestras',
 'The Jack King Affair',
 'The Last Resort',
 'The Legend of 420',
 'The Long Goodbye: The Kara Tippetts Story',
 'The Look of Silence',
 'The Lovers and the Despot',
 'The Memphis Belle: A Story of a\nFlying Fortress',
 'The Minimighty Kids',
 'The Mortified Guide',
 'The Murder Detectives',
 'The Negro Soldier',
 'The Nineties',
 'The NSU-Complex',
 'The Perfect Day',
 'The Power of Grayskull: The Definitive History of He-Man and the Masters of the Universe',
 'The Rat Race',
 'The Redeemed and the Dominant: Fittest on Earth',
 'The Search for Life in Space',
 'The Seven Five',
 'The Seventies',
 'The Spy Who Fell to Earth',
 'The Sunshine Makers',
 'The Surrounding Game',
 'The Vietnam War: A Film by Ken Burns and Lynn Novick',
 'The Women Who Kill Lions',
 'Theo Who Lived',
 'This Was Tomorrow',
 'To Be a Miss',
 'Tokyo Idols',
 'Top 10 Secrets and Mysteries',
 'Top Grier',
 'Towies',
 'Treasures from the Wreck of the Unbelievable',
 'Tree Man',
 'Trophy',
 'Tyke Elephant Outlaw',
 'Unacknowledged',
 'Undercover: How to Operate Behind Enemy Lines',
 'Vegas Baby',
 'Wartime Portraits',
 'Water & Power: A California Heist',
 'Waterschool',
 'We, the Marines',
 'What Makes a Psychopath?',
 'When Hari Got Married',
 'When Two Worlds Collide',
 'Why Knot',
 'Why We Fight: The Battle of Russia',
 'Williams',
 'Winnie',
 'Women Behind Bars',
 'Woodstock',
 'WWII: Report from the Aleutians',
 'Zombie Dumb']

In [268]:
netflix_cast_dict_4 = {
    'Great Yellowstone Thaw': 'Kirk Johnson',
    'Gringo: The Dangerous Life of John McAfee': 'John McAfee',
    'Growing Up Coy': 'Coy Mathis',
    'Gun Runners': 'Julius Arile, Robert Matanda',
    'Harry & Bunnie': 'Animated Characters',
    'Haunters: The Art of the Scare': 'John LaFlamboy, Russ McKamey',
    'Highly Strung': 'Alison Avron',
    "History's Greatest Hoaxes": 'Various Narrators',
    "Hitler's Olympics": 'Various Historians',
    "Hitler's Steel Beast": 'Various Historians',
    'Holy Hell': 'Will Allen',
    'Hostage to the Devil': 'Malachi Martin',
    'Hostages': 'Re-enactment Cast',
    'How to Change the World': 'Robert Hunter, Paul Watson',
    'How to Live Mortgage Free with Sarah Beeny': 'Sarah Beeny',
    'How to Win the US Presidency': 'Various Experts',
    'I Am Sun Mu': 'Sun Mu',
    'I Dream Of Dance': 'Denise Wall',
    'Incorruptible': 'Various Interviewees',
    'Influx': 'Various Residents',
    'Inside The Freemasons': 'Various Freemasons',
    'Inside the Mind of a Serial Killer': 'Various Criminologists',
    'Inside the Mossad': 'Former Mossad Agents',
    'Inst@famous': 'Various Influencers',
    'Invisible Essence: The Little Prince': 'Adam Stock, Mark Osborne',
    'Islands of the Future': 'Various Experts',
    'Jack of all Trades': 'Stuart Shea',
    'JingleKids': 'Animated Characters',
    'Joe Cocker: Mad Dog with Soul': 'Joe Cocker',
    'John & Jane': 'Ashim, Glen, Naomi',
    'Jugaad': 'Various Workers',
    'Ken Burns: The Roosevelts: An Intimate History': 'Peter Coyote, Edward Herrmann, Meryl Streep',
    'Kingdoms of the Sky': 'David Attenborough',
    'Kon Kon Kon': 'Animated Characters',
    'LA 92': 'Various Historical Figures',
    'Le serment des Hitler': 'Various Historians',
    'LEGO Ninjago: Masters of Spinjitzu: Day of the Departed': 'Vincent Tong, Michael Adamthwaite, Kelly Metzger',
    'Les Bleus - Une autre histoire de France, 1996-2016': 'Zinedine Zidane, Lilian Thuram',
    'License to Drill: Louisiana': 'Rig Crews',
    'Life in the Doghouse': 'Danny Robertshaw, Ron Danta',
    'Little Singham aur Kaal ka Mahajaal': 'Animated Characters',
    'Little Singham in London': 'Animated Characters',
    'Lo que la verdad esconde: El caso Asunta (Operacion Nenúfar)': 'Alfonso Basterra, Rosario Porto',
    'Los Niños Héroes de Chapultepec': 'Various Historians',
    'Los tiempos de Pablo Escobar': 'Pablo Escobar',
    'Losing Sight of Shore': 'Natalia Cohen, Laura Penhaul, Emma Mitchell, Meg Dyos',
    'LoveTrue': 'Documentary Subjects',
    'Marching Orders': 'Dr. Nikole Roebuck',
    'Martyrs of Marriage': 'Deepika Bhardwaj',
    'Maynard': 'Maynard Jackson',
    'Meet the Trumps: From Immigrant to President': 'Donald Trump',
    'Mega Food': 'Various Chefs',
    'MegaTruckers': 'Jon Kelly',
    'Melodies of Life - Born This Way': 'Various Musicians',
    'Memory Games': 'Yanjaa Wintersoul, Johannes Mallow',
    'Mexico Diseña': 'Various Designers',
    'Mini Wolf': 'Animated Characters',
    'Miss Representation': 'Jane Fonda, Margaret Cho, Katie Couric',
    'Mission Control: The Unsung Heroes of Apollo': 'Gene Kranz, Glynn Lunney',
    'Money for Nothing': 'Jay Blades',
    'Monster High: Haunted': 'Laura Bailey, Cam Clarke',
    "Monty Don's French Gardens": 'Monty Don',
    'Mortified Nation': 'Dave Nadelberg',
    'Mountain': 'Willem Dafoe',
    'Murderous Affairs': 'Re-enactment Cast',
    'Naga The Eternal Yogi': 'Various Yogis',
    "Naledi: A Baby Elephant's Tale": 'Naledi',
    'National Bird': 'Dan, Heather, Lisa',
    'Nazi Concentration Camps': 'Historical Footage',
    'Nazi Mega Weapons': 'Various Historians',
    'Newtown': 'Various Residents',
    'Not Alone': 'Jacqueline Monetta',
    'NOVA: Eclipse Over America': 'PBS Hosts',
    'NOVA: Holocaust Escape Tunnel': 'PBS Hosts',
    'NOVA: Thai Cave Rescue': 'PBS Hosts',
    'NOVA: The Impossible Flight': 'PBS Hosts',
    'Nuestra Lucha Libre': 'Various Luchadores',
    'Numbered': 'Holocaust Survivors',
    'Numero Zero. The Roots of Italian Rap': 'Various Italian Rappers',
    'Nurses Who Kill': 'Various Experts',
    'Oh My Ghost 4': 'Episodic Cast',
    'Oklahoma City': 'Various Witnesses',
    'Once In A Lifetime Sessions with TLC': 'TLC',
    'One More Shot': 'Maya Grobel, Noah Moskin',
    'Operation Odessa': 'Tony Yester, Juan Almeida, Ludwig Fainberg',
    'Origins Collection': 'Various Narrators',
    'Pablo Escobar: Angel or Demon?': 'Pablo Escobar',
    'Palio': 'Giovanni Atzeni, Silvano Vigni',
    'Paranormal Survivor': 'Various Contributors',
    'Paris Is Burning': 'Dorian Corey, Pepper LaBeija, Venus Xtravelganza',
    'Patient Seventeen': 'Roger Leir',
    'Pick of the Litter': 'Guide Dogs and Trainers',
    'Pioneers of African-American Cinema': 'Paul Robeson, Evelyn Preer',
    'Playing Hard': 'Jason VandenBerghe',
    'Prelude to War': 'Walter Huston',
    'Prince Jai Aur Dumdaar Viru': 'Animated Characters',
    'Q Ball': 'Inmates of San Quentin State Prison',
    'Queens of Comedy': 'Various Comedians',
    'Radical: the Controversial Saga of Dada Figueiredo': 'Dada Figueiredo',
    'Raiders!: The Story of the Greatest Fan Film Ever Made': 'Chris Strompolos, Eric Zala',
    'Rats': 'Various Exterminators',
    'Rica, Famosa, Latina': 'Various Reality Cast Members',
    'Roll Red Roll': 'Rachel Dissell',
    'Rolling Papers': 'Ricardo Baca',
    'Roots': 'Historical Re-enactments',
    'S Is for Stanley': 'Emilio D\'Alessandro, Alex Infascelli',
    'Sacro GRA': 'Various Residents',
    'San Pietro': 'John Huston',
    'Shadow of Truth': 'Tair Rada',
    'Silicon Cowboys': 'Rod Canion, Jim Harris, Bill Murto',
    'Skydancers': 'Animated Characters',
    'Smash: Motorized Mayhem': 'Various Drivers',
    'Social Animals': 'Humza Deas, Ava Nirui',
    'Sons of Ben': 'Philadelphia Union Fans',
    'Sour Grapes': 'Rudy Kurniawan',
    'Speed Is My Need': 'Various Motorcycle Racers',
    'Star Men': 'Donald Lynden-Bell, Wal Sargent',
    'Stop at Nothing: The Lance Armstrong Story': 'Lance Armstrong',
    'Strike a Pose': 'Madonna, Luis Camacho, Oliver Crumes',
    'Strongland': 'Various Athletes',
    'SuperNature: Wild Flyers': 'Various Narrators',
    'Sustainable': 'Marty Travis',
    'Teach Us All': 'Various Students and Educators',
    'Tellur Aliens': 'Animated Characters',
    'Thackeray': 'Nawazuddin Siddiqui, Amrita Rao',
    'The 2000s': 'Various Commentators',
    'The 24 Hour War': 'Henry Ford II, Enzo Ferrari',
    'The Accountant of Auschwitz': 'Oskar Gröning',
    'The Animal People': 'Various Activists',
    'The Bachelor': 'Chris Harrison',
    'The Bad Kids': 'Vonda Viland',
    'The Beginning of Life: The Series': 'Global Families and Experts',
    'The Bomb': 'Various Historians',
    'The Calling': 'Various Religious Figures',
    'The Darkest Dawn': 'Bethan Leadley, Cherry Wallis',
    'The Devil and Father Amorth': 'Gabriele Amorth, William Friedkin',
    'The Devil We Know': 'Bucky Bailey',
    'The Eighties': 'Various Commentators',
    'The Fear of 13': 'Nick Yarris',
    'The Force': 'Chief Sean Whent',
    'The Future of Water': 'Various Experts',
    'The Gentleman Driver': 'Ricardo Gonzalez, Michael Guasch',
    'The Golden Years with Javed Akhtar': 'Javed Akhtar',
    'The Heat: A Kitchen (R)evolution': 'Various Female Chefs',
    'The House on Coco Road': 'Fannie Haughton',
    'The Human Factor: The Untold Story of the Bombay Film Orchestras': 'Various Musicians',
    'The Jack King Affair': 'Various Intelligence Historians',
    'The Last Resort': 'Carl Flick, Gary Monroe',
    'The Legend of 420': 'Various Cannabis Advocates',
    'The Long Goodbye: The Kara Tippetts Story': 'Kara Tippetts',
    'The Look of Silence': 'Adi Rukun',
    'The Lovers and the Despot': 'Shin Sang-ok, Choi Eun-hee',
    'The Memphis Belle: A Story of a Flying Fortress': 'Crew Members',
    'The Minimighty Kids': 'Animated Characters',
    'The Mortified Guide': 'Dave Nadelberg',
    'The Murder Detectives': 'Bristol Police Investigators',
    'The Negro Soldier': 'Carlton Moss',
    'The Nineties': 'Various Commentators',
    'The NSU-Complex': 'Various Journalists and Investigators',
    'The Perfect Day': 'Various Participants',
    'The Power of Grayskull: The Definitive History of He-Man and the Masters of the Universe': 'Dolph Lundgren, Frank Langella',
    'The Rat Race': 'Various Participants',
    'The Redeemed and the Dominant: Fittest on Earth': 'Mat Fraser, Tia-Clair Toomey',
    'The Search for Life in Space': 'Various Astrobiologists',
    'The Seven Five': 'Michael Dowd',
    'The Seventies': 'Various Commentators',
    'The Spy Who Fell to Earth': 'Ashraf Marwan',
    'The Sunshine Makers': 'Tim Scully, Nicholas Sand',
    'The Surrounding Game': 'Ben Lockhart, Andy Liu',
    'The Vietnam War: A Film by Ken Burns and Lynn Novick': 'Peter Coyote',
    'The Women Who Kill Lions': 'Various Hunters',
    'Theo Who Lived': 'Theo Padnos',
    'This Was Tomorrow': 'Various Music Producers and DJs',
    'To Be a Miss': 'Various Pageant Contestants',
    'Tokyo Idols': 'Rio Hiiragi',
    'Top 10 Secrets and Mysteries': 'Various Narrators',
    'Top Grier': 'Hayes Grier',
    'Towies': 'Various Tow Truck Operators',
    'Treasures from the Wreck of the Unbelievable': 'Damien Hirst',
    'Tree Man': 'Francois',
    'Trophy': 'Philip Glass, John Hume',
    'Tyke Elephant Outlaw': 'Various Witnesses',
    'Unacknowledged': 'Steven M. Greer',
    'Undercover: How to Operate Behind Enemy Lines': 'US Military Personnel',
    'Vegas Baby': 'Dr. Geoffrey Sher',
    'Wartime Portraits': 'Various Historical Figures',
    'Water & Power: A California Heist': 'Various Investigators',
    'Waterschool': 'Various Students',
    'We, the Marines': 'Gene Hackman',
    'What Makes a Psychopath?': 'Various Criminologists',
    'When Hari Got Married': 'Hari Das',
    'When Two Worlds Collide': 'Alberto Pizango',
    'Why Knot': 'Various Participants',
    'Why We Fight: The Battle of Russia': 'Anthony Veiller',
    'Williams': 'Frank Williams, Claire Williams',
    'Winnie': 'Winnie Madikizela-Mandela',
    'Women Behind Bars': 'Various Inmates',
    'Woodstock': 'Jimi Hendrix, Janis Joplin, Joan Baez',
    'WWII: Report from the Aleutians': 'John Huston',
    'Zombie Dumb': 'Animated Characters'
}

In [269]:
df['cast'] = df['cast'].fillna(df['title'].map(netflix_cast_dict_4))
remaining_nulls = df['cast'].isnull().sum()
print(f"Remaining null values in cast column: {remaining_nulls}")

Remaining null values in cast column: 1

In [270]:
df.loc[df['cast'].isna()]

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
8419,s8420,Movie,The Memphis Belle: A Story of a\nFlying Fortress,William Wyler,NaN,United States,"March 31, 2017",1944,TV-PG,40 min,"Classic Movies, Documentaries",This documentary centers on the crew of the B-...

In [271]:
df.loc[df['title'] == 'The Memphis Belle: A Story of a\nFlying Fortress', 'cast'] = 'Robert Morgan, James Verinis, Charles Leighton'

In [272]:
df['cast'].isna().sum()

np.int64(0)

##### **`country` Column:**

In [273]:
df['country'].value_counts()

country
United States                                    2818
India                                             972
United Kingdom                                    419
Japan                                             245
South Korea                                       199
                                                 ...
Russia, Spain                                       1
Croatia, Slovenia, Serbia, Montenegro               1
Japan, Canada                                       1
United States, France, South Korea, Indonesia       1
United Arab Emirates, Jordan                        1
Name: count, Length: 748, dtype: int64

In [274]:
missing_countries = df.loc[df['country'].isna(), ['title', 'country']]
missing_countries.sample(5)

                                                  title country
3396   ChuChuTV Surprise Eggs Learning Videos (English)     NaN
1442                         Korean Pork Belly Rhapsody     NaN
7231  Krish Trish and Baltiboy: Oversmartness Never ...     NaN
550                            Fear Street Part 1: 1994     NaN
1986                                   Nee Enge En Anbe     NaN

In [275]:
missing_countries.shape

(831, 2)

In [276]:
missing_countries_titles = list(missing_countries['title'])

In [277]:
missing_countries_titles_1 = missing_countries_titles[:216]
missing_countries_titles_1

['Ganglands',
 'Jailbirds New Orleans',
 'Midnight Mass',
 'My Little Pony: A New Generation',
 'Vendetta: Truth, Lies and The Mafia',
 'Bangkok Breaking',
 'Confessions of an Invisible Girl',
 'Crime Stories: India Detectives',
 "Europe's Most Dangerous Man: Otto Skorzeny in Spain",
 'Intrusion',
 'Jaguar',
 'Monsters Inside: The 24 Faces of Billy Milligan',
 'Avvai Shanmughi',
 'Go! Go! Cory Carson: Chrissy Takes the Wheel',
 'Minsara Kanavu',
 'Ankahi Kahaniya',
 'Chicago Party Aunt',
 'Squid Game',
 'Tayo and Little Wizards',
 'The Father Who Moves Mountains',
 'The Stronghold',
 'My Heroes Were Cowboys',
 'The Smart Money Woman',
 'Nightbooks',
 'Schumacher',
 'Too Hot To Handle: Latino',
 'A StoryBots Space Adventure',
 "The World's Most Amazing Vacation Rentals",
 'You vs. Wild: Out Cold',
 'Little Singham - Black Shadow',
 'Tughlaq Durbar',
 'Tughlaq Durbar (Telugu)',
 'Firedrake the Silver Dragon',
 'Metal Shop Masters',
 'Pokémon Master Journeys: The Series',
 'Prey',
 'Titipo Titipo',
 'Blood Brothers: Malcolm X & Muhammad Ali',
 'Mighty Raju',
 'JJ+E',
 'Tobot Galaxy Detectives',
 'Countdown: Inspiration4 Mission to Space',
 'Shadow Parties',
 'Money Heist: From Tokyo to Berlin',
 'Worth',
 'Afterlife of the Party',
 'Here and There',
 'Hotel Del Luna',
 'Luv Kushh',
 "Agatha Christie's Crooked House",
 'Barbie Big City Big Dreams',
 'Brave Animated Series',
 'How to Be a Cowboy',
 'HQ Barbers',
 'Oldsters',
 'The Nutty Professor II: The Klumps',
 'Turning Point: 9/11 and the War on Terror',
 'Untold: Crime & Penalties',
 'Hometown Cha-Cha-Cha',
 'The Ingenuity of the Househusband',
 'Bread Barbershop',
 'Deadly Sins',
 "He's All That",
 'I Heart Arlo',
 'RIDE ON TIME',
 'SAS: Rise of the Black Swan',
 'Titletown High',
 'Bob Ross: Happy Accidents, Betrayal & Greed',
 'Clickbait',
 'John of God: The Crimes of a Spiritual Healer',
 'Motel Makeover',
 'Open Your Eyes',
 'Post Mortem: No One Dies in Skarnes',
 'The River Runner',
 'Oggy Oggy',
 'Untold: Caitlyn Jenner',
 'Boomika',
 'Boomika (Hindi)',
 'Boomika (Malayalam)',
 'Boomika (Telugu)',
 'The Witcher: Nightmare of the Wolf',
 'Comedy Premium League',
 'Everything Will Be Fine',
 'Gunshot',
 'Korean Cold Noodle Rhapsody',
 'Man in Love',
 'The Chair',
 'The Loud House Movie',
 'A Faraway Land',
 'Black Island',
 'Memories of a Murderer: The Nilsen Tapes',
 'Nneka The Pretty Serpent',
 'O Kadhal Kanmani',
 'Out of my league',
 'The Defeated',
 'The Secret Diary of an Exchange Student',
 'Untold: Deal With the Devil',
 'Unroyal',
 'I Need Romance',
 'Takizawa Kabuki ZERO 2020 The Movie',
 'Car Masters: Rust to Riches',
 'Shiny_Flakes: The Teenage Drug Lord',
 'Top Secret UFO Projects: Declassified',
 'Darwin’s Game',
 'Friday Night Lights',
 "I missed you: Director's Cut",
 'The Lost Café',
 'The Vault',
 'Centaurworld',
 "I'm Glad I Did",
 'Khawatir',
 'Myth & Mogul: John DeLorean',
 'Pomegranates and Myrrh',
 'Rurouni Kenshin: The Beginning',
 'The Last Mercenary',
 'Resort to Love',
 'Transformers: War for Cybertron: Kingdom',
 'Tattoo Redo',
 'The Snitch Cartel: Origins',
 'Hostage House',
 'Mimi',
 'Plastic Cup Boyz: Laughing My Mask Off!',
 'African America',
 'Bankrolled',
 'Blood Red Sky',
 'Feels Like Ishq',
 'Kingdom: Ashin of the North',
 'Masters of the Universe: Revelation',
 'Revelations: The Masters of the Universe: Revelation Aftershow',
 '9to5: The Story of a Movement',
 'Chhota Bheem - Dinosaur World',
 'Chhota Bheem - Neeli Pahaadi',
 'Chhota Bheem & Ganesh',
 'Chhota Bheem & Krishna: Mayanagari',
 'Chhota Bheem & Krishna: Pataliputra- City of the Dead',
 'Chhota Bheem And The Crown of Valhalla',
 'Chhota Bheem and the Incan Adventure',
 'Chhota Bheem and The ShiNobi Secret',
 'Chhota Bheem Aur Hanuman',
 'Chhota Bheem aur Krishna vs Zimbara',
 'Chhota Bheem in African Safari',
 'Chhota Bheem Ka Roosi Romanch',
 'Chhota Bheem: Bheem vs Aliens',
 'Chhota Bheem: Dholakpur to Kathmandu',
 'Chhota Bheem: Dus Pe Dus',
 'Chhota Bheem: Journey to Petra',
 'Chhota Bheem: Master of Shaolin',
 'Chhota Bheem: The Rise of Kirmada',
 'Wannabe Courageous',
 'Words Bubble Up Like Soda Pop',
 'Sexy Beasts',
 'Too Hot to Handle: Brazil',
 'Trollhunters: Rise of the Titans',
 'Touch Your Heart',
 '2 Weeks in Lagos',
 'Fear Street Part 3: 1666',
 'La ley de Herodes',
 'Naomi Osaka',
 "Cheech & Chong's Still Smokin",
 'Emicida: AmarElo - Live in São Paulo',
 'My Amanda',
 'The Unknown Saint',
 'Gunpowder Milkshake',
 'Heist',
 'My Unorthodox Life',
 'Private Network: Who Killed Manuel Buendía?',
 'The Guide to the Perfect Family',
 'Bridgerton - The Afterparty',
 'Day of Destiny',
 'The Stand-Up',
 'The Tour',
 'Fear Street Part 2: 1978',
 'Finding Hubby',
 'How I Became a Superhero',
 'How to Become a Tyrant',
 'Last Summer',
 'Lee Su-geun: The Sense Coach',
 'Lethal Love',
 'The Cook of Castamar',
 'Elize Matsunaga: Once Upon a Crime',
 'Awon Boyz',
 'Cat People',
 'Clash',
 'Major Grom: Plague Doctor',
 'Mama Drama',
 'The War Next-door',
 'Therapy',
 'Three Thieves',
 'You Are My Spring',
 'Big Timber',
 'Fear Street Part 1: 1994',
 'Holiday on Mars',
 'Audible',
 'Dynasty Warriors',
 'Generation 56k',
 'Masameer County',
 'Mobile Suit Gundam Hathaway',
 'Pet Sematary 2',
 'Quarantine Tales',
 'Sailor Moon Crystal',
 'Working Title',
 'Deranged',
 'Legend\xa0of\xa0Exorcism',
 'Mommy Issues',
 'Prime Time',
 'Sophie: A Murder in West Cork',
 'A Way Back Home',
 'Wanted',
 'Into the Wind',
 'Ray',
 'Godzilla Singular Point',
 'Jiva!',
 'Sisters on Track',
 'Good on Paper',
 'Murder by the Coast',
 'The House of Flowers: The Movie']

In [278]:
media_countries_1 = {
    'Ganglands': 'France',
    'Jailbirds New Orleans': 'United States',
    'Midnight Mass': 'United States',
    'My Little Pony: A New Generation': 'United States, Ireland, Canada',
    'Vendetta: Truth, Lies and The Mafia': 'Italy',
    'Bangkok Breaking': 'Thailand',
    'Confessions of an Invisible Girl': 'Brazil',
    'Crime Stories: India Detectives': 'India',
    "Europe's Most Dangerous Man: Otto Skorzeny in Spain": 'Spain',
    'Intrusion': 'United States',
    'Jaguar': 'Spain',
    'Monsters Inside: The 24 Faces of Billy Milligan': 'United States',
    'Avvai Shanmughi': 'India',
    'Go! Go! Cory Carson: Chrissy Takes the Wheel': 'United States',
    'Minsara Kanavu': 'India',
    'Ankahi Kahaniya': 'India',
    'Chicago Party Aunt': 'United States',
    'Squid Game': 'South Korea',
    'Tayo and Little Wizards': 'South Korea',
    'The Father Who Moves Mountains': 'Romania',
    'The Stronghold': 'France',
    'My Heroes Were Cowboys': 'United States',
    'The Smart Money Woman': 'Nigeria',
    'Nightbooks': 'United States',
    'Schumacher': 'Germany',
    'Too Hot To Handle: Latino': 'Mexico',
    'A StoryBots Space Adventure': 'United States',
    "The World's Most Amazing Vacation Rentals": 'United States',
    'You vs. Wild: Out Cold': 'United States',
    'Little Singham - Black Shadow': 'India',
    'Tughlaq Durbar': 'India',
    'Tughlaq Durbar (Telugu)': 'India',
    'Firedrake the Silver Dragon': 'Germany',
    'Metal Shop Masters': 'United States',
    'Pokémon Master Journeys: The Series': 'Japan',
    'Prey': 'Germany',
    'Titipo Titipo': 'South Korea',
    'Blood Brothers: Malcolm X & Muhammad Ali': 'United States',
    'Mighty Raju': 'India',
    'JJ+E': 'Sweden',
    'Tobot Galaxy Detectives': 'South Korea',
    'Countdown: Inspiration4 Mission to Space': 'United States',
    'Shadow Parties': 'Nigeria',
    'Money Heist: From Tokyo to Berlin': 'Spain',
    'Worth': 'United States',
    'Afterlife of the Party': 'United States',
    'Here and There': 'Philippines',
    'Hotel Del Luna': 'South Korea',
    'Luv Kushh': 'India',
    "Agatha Christie's Crooked House": 'United Kingdom, United States',
    'Barbie Big City Big Dreams': 'United States',
    'Brave Animated Series': 'Nigeria',
    'How to Be a Cowboy': 'United States',
    'HQ Barbers': 'Nigeria',
    'Oldsters': 'Argentina',
    'The Nutty Professor II: The Klumps': 'United States',
    'Turning Point: 9/11 and the War on Terror': 'United States',
    'Untold: Crime & Penalties': 'United States',
    'Hometown Cha-Cha-Cha': 'South Korea',
    'The Ingenuity of the Househusband': 'Japan',
    'Bread Barbershop': 'South Korea',
    'Deadly Sins': 'United States',
    "He's All That": 'United States',
    'I Heart Arlo': 'United States',
    'RIDE ON TIME': 'Japan',
    'SAS: Rise of the Black Swan': 'United Kingdom',
    'Titletown High': 'United States',
    'Bob Ross: Happy Accidents, Betrayal & Greed': 'United States',
    'Clickbait': 'Australia, United States',
    'John of God: The Crimes of a Spiritual Healer': 'Brazil',
    'Motel Makeover': 'Canada',
    'Open Your Eyes': 'Poland',
    'Post Mortem: No One Dies in Skarnes': 'Norway',
    'The River Runner': 'United States',
    'Oggy Oggy': 'France',
    'Untold: Caitlyn Jenner': 'United States',
    'Boomika': 'India',
    'Boomika (Hindi)': 'India',
    'Boomika (Malayalam)': 'India',
    'Boomika (Telugu)': 'India',
    'The Witcher: Nightmare of the Wolf': 'United States, South Korea',
    'Comedy Premium League': 'India',
    'Everything Will Be Fine': 'Mexico',
    'Gunshot': 'Nigeria',
    'Korean Cold Noodle Rhapsody': 'South Korea',
    'Man in Love': 'Taiwan',
    'The Chair': 'United States',
    'The Loud House Movie': 'United States',
    'A Faraway Land': 'Philippines',
    'Black Island': 'Germany',
    'Memories of a Murderer: The Nilsen Tapes': 'United Kingdom',
    'Nneka The Pretty Serpent': 'Nigeria',
    'O Kadhal Kanmani': 'India',
    'Out of my league': 'Italy',
    'The Defeated': 'Germany, Canada',
    'The Secret Diary of an Exchange Student': 'Brazil',
    'Untold: Deal With the Devil': 'United States',
    'Unroyal': 'Nigeria',
    'I Need Romance': 'Thailand',
    'Takizawa Kabuki ZERO 2020 The Movie': 'Japan',
    'Car Masters: Rust to Riches': 'United States',
    'Shiny_Flakes: The Teenage Drug Lord': 'Germany',
    'Top Secret UFO Projects: Declassified': 'United Kingdom',
    'Darwin’s Game': 'Japan',
    'Friday Night Lights': 'United States',
    "I missed you: Director's Cut": 'South Korea',
    'The Lost Café': 'Nigeria',
    'The Vault': 'Spain',
    'Centaurworld': 'United States',
    "I'm Glad I Did": 'United States',
    'Khawatir': 'Saudi Arabia',
    'Myth & Mogul: John DeLorean': 'United Kingdom',
    'Pomegranates and Myrrh': 'Palestine',
    'Rurouni Kenshin: The Beginning': 'Japan',
    'The Last Mercenary': 'France',
    'Resort to Love': 'United States',
    'Transformers: War for Cybertron: Kingdom': 'United States',
    'Tattoo Redo': 'United States',
    'The Snitch Cartel: Origins': 'Colombia',
    'Hostage House': 'United States',
    'Mimi': 'India',
    'Plastic Cup Boyz: Laughing My Mask Off!': 'United States',
    'African America': 'South Africa, United States',
    'Bankrolled': 'Mexico',
    'Blood Red Sky': 'Germany, United Kingdom',
    'Feels Like Ishq': 'India',
    'Kingdom: Ashin of the North': 'South Korea',
    'Masters of the Universe: Revelation': 'United States',
    'Revelations: The Masters of the Universe: Revelation Aftershow': 'United States',
    '9to5: The Story of a Movement': 'United States',
    'Chhota Bheem - Dinosaur World': 'India',
    'Chhota Bheem - Neeli Pahaadi': 'India',
    'Chhota Bheem & Ganesh': 'India',
    'Chhota Bheem & Krishna: Mayanagari': 'India',
    'Chhota Bheem & Krishna: Pataliputra- City of the Dead': 'India',
    'Chhota Bheem And The Crown of Valhalla': 'India',
    'Chhota Bheem and the Incan Adventure': 'India',
    'Chhota Bheem and The ShiNobi Secret': 'India',
    'Chhota Bheem Aur Hanuman': 'India',
    'Chhota Bheem aur Krishna vs Zimbara': 'India',
    'Chhota Bheem in African Safari': 'India',
    'Chhota Bheem Ka Roosi Romanch': 'India',
    'Chhota Bheem: Bheem vs Aliens': 'India',
    'Chhota Bheem: Dholakpur to Kathmandu': 'India',
    'Chhota Bheem: Dus Pe Dus': 'India',
    'Chhota Bheem: Journey to Petra': 'India',
    'Chhota Bheem: Master of Shaolin': 'India',
    'Chhota Bheem: The Rise of Kirmada': 'India',
    'Wannabe Courageous': 'Taiwan',
    'Words Bubble Up Like Soda Pop': 'Japan',
    'Sexy Beasts': 'United Kingdom, United States',
    'Too Hot to Handle: Brazil': 'Brazil',
    'Trollhunters: Rise of the Titans': 'United States',
    'Touch Your Heart': 'South Korea',
    '2 Weeks in Lagos': 'Nigeria',
    'Fear Street Part 3: 1666': 'United States',
    'La ley de Herodes': 'Mexico',
    'Naomi Osaka': 'United States',
    "Cheech & Chong's Still Smokin": 'United States',
    'Emicida: AmarElo - Live in São Paulo': 'Brazil',
    'My Amanda': 'Philippines',
    'The Unknown Saint': 'Morocco, France, Qatar',
    'Gunpowder Milkshake': 'United States, Germany, France',
    'Heist': 'United States',
    'My Unorthodox Life': 'United States',
    'Private Network: Who Killed Manuel Buendía?': 'Mexico',
    'The Guide to the Perfect Family': 'Canada',
    'Bridgerton - The Afterparty': 'United States',
    'Day of Destiny': 'Nigeria',
    'The Stand-Up': 'United States',
    'The Tour': 'Germany',
    'Fear Street Part 2: 1978': 'United States',
    'Finding Hubby': 'Nigeria',
    'How I Became a Superhero': 'France',
    'How to Become a Tyrant': 'United States',
    'Last Summer': 'Turkey',
    'Lee Su-geun: The Sense Coach': 'South Korea',
    'Lethal Love': 'Brazil',
    'The Cook of Castamar': 'Spain',
    'Elize Matsunaga: Once Upon a Crime': 'Brazil',
    'Awon Boyz': 'Nigeria',
    'Cat People': 'United States',
    'Clash': 'Egypt, France',
    'Major Grom: Plague Doctor': 'Russia',
    'Mama Drama': 'Nigeria',
    'The War Next-door': 'Mexico',
    'Therapy': 'Nigeria',
    'Three Thieves': 'Nigeria',
    'You Are My Spring': 'South Korea',
    'Big Timber': 'Canada',
    'Fear Street Part 1: 1994': 'United States',
    'Holiday on Mars': 'Italy',
    'Audible': 'United States',
    'Dynasty Warriors': 'Hong Kong, China',
    'Generation 56k': 'Italy',
    'Masameer County': 'Saudi Arabia',
    'Mobile Suit Gundam Hathaway': 'Japan',
    'Pet Sematary 2': 'United States',
    'Quarantine Tales': 'Indonesia',
    'Sailor Moon Crystal': 'Japan',
    'Working Title': 'Egypt',
    'Deranged': 'South Korea',
    'Legend of Exorcism': 'China',
    'Mommy Issues': 'Philippines',
    'Prime Time': 'Poland',
    'Sophie: A Murder in West Cork': 'United Kingdom, Ireland',
    'A Way Back Home': 'Philippines',
    'Wanted': 'Australia',
    'Into the Wind': 'Poland',
    'Ray': 'India',
    'Godzilla Singular Point': 'Japan',
    'Jiva!': 'South Africa',
    'Sisters on Track': 'United States',
    'Good on Paper': 'United States',
    'Murder by the Coast': 'Spain',
    'The House of Flowers: The Movie': 'Mexico'
}

In [279]:
df['country'] = df['country'].fillna(df['title'].map(media_countries_1))
remaining_nulls = df['country'].isnull().sum()
print(f"Remaining null values in country column: {remaining_nulls}")

Remaining null values in country column: 616

In [280]:
missing_countries_titles_2 = missing_countries_titles[216:431]
missing_countries_titles_2

['The Parisian Agency: Exclusive Properties',
 'Broken',
 'Osuofia in London II',
 'This Is Pop',
 'Nevertheless,',
 'Charité at War',
 'Gameboys Level-Up Edition',
 'Mobile Suit Gundam II: Soldiers of Sorrow',
 'Mobile Suit Gundam III: Encounters in Space',
 "Mobile Suit Gundam: Char's Counterattack",
 'A Family',
 'Jagame Thandhiram',
 'Mobile Suit Gundam I',
 'Rurouni Kenshin: The Final',
 'So Not Worth It',
 'The Rational Life',
 'Ali & Ratu Ratu Queens',
 'Besieged Bread',
 'Elite Short Stories: Carla Samuel',
 'Record of Ragnarok',
 'A Man For The Week End',
 'Elite Short Stories: Omar Ander Alexis',
 "Let's Eat",
 'Penguin Town',
 'Silver Skates',
 'Beyond Evil',
 'Elite Short Stories: Nadia Guzmán',
 'Headspace: Unwind Your Mind',
 'Rhyme Time Town',
 'Elite Short Stories: Guzmán Caye Rebe',
 'Bling Empire - The Afterparty',
 'Cobra Kai - The Afterparty',
 'To All the Boys: Always and Forever - The Afterparty',
 'Trese After Dark',
 'Guru Aur Bhole',
 'Fireplace 4K: Classic Crackling Fireplace from Fireplace for Your Home',
 'Fireplace 4K: Crackling Birchwood from Fireplace for Your Home',
 'Human: The World Within',
 'Pretty Guardian Sailor Moon Eternal The Movie',
 'Black Holes | The Edge of All We Know',
 'Racket Boys',
 'Seven Souls in the Skull Castle: Season Moon Jogen',
 'Seven Souls in the Skull Castle: Season Moon Kagen',
 'Super Monsters: Once Upon a Rhyme',
 'The Girl King',
 'One Lagos Night',
 'Dog Gone Trouble',
 'The Least Expected Day: Inside the Movistar Team 2019',
 'Word of Honor',
 'Eden',
 'Gatao - The Last Stray',
 'High on the Hog: How African American Cuisine Transformed America',
 'Nail Bomber: Manhunt',
 'A Place in the Stars',
 'Mad for Each Other',
 'Sam Smith: Love Goes - Live at Abbey Road Studios',
 '99 Songs (Tamil)',
 '99 Songs (Telugu)',
 'Creating an Army of the Dead',
 'Strain',
 '678',
 'Little Singham Future mein Satakli',
 'Taxi No. 9211',
 'Love or Money',
 'The Mystic River',
 'The Upshaws - The Afterparty',
 'Wave of Cinema: Filosofi Kopi',
 'Use For My Talent',
 'Dear Affy',
 'The Circle - The Afterparty',
 'Trash Truck',
 'Angelina Ballerina',
 'Barney and Friends',
 'Dead Again in Tombstone',
 'Miniforce: Super Dino Power',
 "Motu Patlu in Dragon's World",
 'Motu Patlu in the Game of Zones',
 'Motu Patlu in Wonderland',
 'Motu Patlu: Deep Sea Adventure',
 'Motu Patlu: Mission Moon',
 'Pet Stars',
 'Seven',
 'The Innocent',
 'The Mitchells vs. The Machines',
 'The Unremarkable Juanquini',
 'Things Heard & Seen',
 'Yasuke',
 'Headspace Guide to Sleep',
 'Legal Hash',
 'Perfume Imaginary Museum “Time Warp”',
 'Wild Dog',
 'Keymon and Nani in Space Adventure',
 'Motu Patlu Dino Invasion',
 'Motu Patlu in Octupus World',
 'Motu Patlu VS Robo Kids',
 'Rudra: Secret of the Black Moon',
 'Rudra: The Rise of King Pharaoh',
 'Bakugan: Geogan Rising',
 'Dad Stop Embarrassing Me - The Afterparty',
 'Dancing Angels',
 "Wave of Cinema: One Day We'll Talk About Today",
 'Ajaibnya Cinta',
 'Motu Patlu in Hong Kong: Kung Fu Kings 3',
 'Motu Patlu in the City of Gold',
 'Motu Patlu Kung Fu Kings 4 The Challenge of Kung Fu Brothers',
 'Motu Patlu the Superheroes – Super Villains from Mars',
 'Shiva VS Autobots',
 'Shiva: Journey to Plunotaria',
 'Shiva: The Secret World Of Vedas City',
 "Don't be the First one",
 'Dolly Parton: A MusiCares Tribute',
 'The Wedding Coach',
 "This Is a Robbery: The World's Biggest Art Heist",
 'The Last Kids on Earth: Happy Apocalypse to You',
 'Glimpses of a Future',
 'Seven Souls in the Skull Castle: Season Bird',
 'Seven Souls in the Skull Castle: Season Wind',
 'Black Is Beltza',
 'Alien TV',
 'Reframe THEATER EXPERIENCE with you',
 "Wave of Cinema: 90's Generation",
 'Audrey',
 'Quiet',
 'Last Chance U: Basketball',
 'Marriage or Mortgage',
 'Pokémon Journeys: The Series',
 'A Perfect Day For Arsenide',
 'Banyuki',
 'Blanche Gardin: The All-Nighter',
 'Connected',
 'Seven Souls in the Skull Castle 2011',
 'Ginny & Georgia - The Afterparty',
 'The Last Bastion',
 'M8 - When Death Rescues Life',
 'Wave of Cinema: Surat dari Timur',
 'Thus Spoke Kishibe Rohan',
 'Hire a Woman',
 'She Is',
 'Chris Rock Total Blackout: The Tamborine Extended Cut',
 'Ratones Paranoicos: The Band that Rocked Argentina',
 'Korean Pork Belly Rhapsody',
 'Running Man',
 'Best of Stand-Up 2020',
 'Transformers: War for Cybertron: Earthrise',
 "Ma Rainey's Black Bottom: A Legacy Brought to Screen",
 'The Wedding Shaman',
 'BREAK IT ALL: The History of Rock in Latin America',
 'A Trash Truck Christmas',
 'Futmalls.com',
 'Super Monsters: Santa’s Super Monster Helpers',
 'Manhunt: Deadly Games',
 'The Great British Baking Show: Holidays',
 'Chico Bon Bon and the Very Berry Holiday',
 'Andhaghaaram',
 'Heart & Soul',
 'Bakugan: Armored Alliance',
 'The Beginning of Life',
 'Ya no estoy aquí: Una conversación entre Guillermo del Toro y Alfonso Cuarón',
 'Kongsuni and Friends',
 'La Gran Ilusión',
 'Unsolved Mysteries',
 'Pat a Pat Como',
 'Qurious Como',
 'A Go! Go! Cory Carson Halloween',
 'Journey of an African Colony',
 'The American Game',
 'Mighty Little Bheem',
 "My Mother's Wound",
 'Zulu Man in Japan',
 'High & Low The Worst',
 'Fukrey Boyzzz',
 "Dragon's Dogma",
 'Nee Enge En Anbe',
 'Dr Jason Leong Hashtag Blessed',
 'Wish Upon a Unicorn',
 'Wonho Chung: Live in New York',
 'Transformers: Cyberverse',
 'The Witcher: A Look Inside the Episodes',
 'Baewatch: Parental Guidance',
 'Little Singham: Kaal Ka Badla',
 'Dérè: An African Tale',
 "Beyond the Boundary: ICC Women's T20 World Cup Australia 2020",
 'Diamonds in the Sky',
 'Selling Sunset',
 'Sin City',
 'A Go! Go! Cory Carson Summer Camp',
 'Tumi or not Tumi',
 'Unlucky Ploy',
 'Street Food: Latin America',
 'Little Singham: Legend of Dugabakka',
 'Your Excellency',
 'Jim Jefferies: Intolerant',
 'PNL - Dans la légende tour',
 'Thackeray (Marathi)',
 'Seven (Telugu)',
 'El límite infinito',
 'Dating Around',
 'The Light of My Eyes',
 'Alone',
 'Mr. Romantic',
 'Fifty Year Old Teenager',
 'Lock Your Girls In',
 'Raya and Sakina',
 'Sayed the Servant',
 'Especial 20 años Fútbol de Primera',
 'Match',
 'Sí, Mi Amor',
 'Hangar 1: The UFO Files',
 'Hoarders',
 'The Universe: Ancient Mysteries Solved',
 'Thomas & Friends: Marvelous Machinery: A New Arrival',
 'Thomas & Friends: Marvelous Machinery: World of Tomorrow',
 'Thomas & Friends: Thomas and the Royal Engine',
 'Lembi 8 Giga',
 'دفعة القاهرة']

In [281]:
media_countries_2 = {
    'The Parisian Agency: Exclusive Properties': 'France',
    'Broken': 'United Kingdom',
    'Osuofia in London II': 'Nigeria',
    'This Is Pop': 'Canada',
    'Nevertheless,': 'South Korea',
    'Charité at War': 'Germany',
    'Gameboys Level-Up Edition': 'Philippines',
    'Mobile Suit Gundam II: Soldiers of Sorrow': 'Japan',
    'Mobile Suit Gundam III: Encounters in Space': 'Japan',
    "Mobile Suit Gundam: Char's Counterattack": 'Japan',
    'A Family': 'Japan',
    'Jagame Thandhiram': 'India',
    'Mobile Suit Gundam I': 'Japan',
    'Rurouni Kenshin: The Final': 'Japan',
    'So Not Worth It': 'South Korea',
    'The Rational Life': 'China',
    'Ali & Ratu Ratu Queens': 'Indonesia',
    'Besieged Bread': 'Syria',
    'Elite Short Stories: Carla Samuel': 'Spain',
    'Record of Ragnarok': 'Japan',
    'A Man For The Week End': 'Cameroon',
    'Elite Short Stories: Omar Ander Alexis': 'Spain',
    "Let's Eat": 'South Korea',
    'Penguin Town': 'United States',
    'Silver Skates': 'Russia',
    'Beyond Evil': 'South Korea',
    'Elite Short Stories: Nadia Guzmán': 'Spain',
    'Headspace: Unwind Your Mind': 'United States',
    'Rhyme Time Town': 'United States',
    'Elite Short Stories: Guzmán Caye Rebe': 'Spain',
    'Bling Empire - The Afterparty': 'United States',
    'Cobra Kai - The Afterparty': 'United States',
    'To All the Boys: Always and Forever - The Afterparty': 'United States',
    'Trese After Dark': 'Philippines',
    'Guru Aur Bhole': 'India',
    'Fireplace 4K: Classic Crackling Fireplace from Fireplace for Your Home': 'United States',
    'Fireplace 4K: Crackling Birchwood from Fireplace for Your Home': 'United States',
    'Human: The World Within': 'United States',
    'Pretty Guardian Sailor Moon Eternal The Movie': 'Japan',
    'Black Holes | The Edge of All We Know': 'United States',
    'Racket Boys': 'South Korea',
    'Seven Souls in the Skull Castle: Season Moon Jogen': 'Japan',
    'Seven Souls in the Skull Castle: Season Moon Kagen': 'Japan',
    'Super Monsters: Once Upon a Rhyme': 'United States',
    'The Girl King': 'Finland, Germany, Canada',
    'One Lagos Night': 'Nigeria',
    'Dog Gone Trouble': 'United States',
    'The Least Expected Day: Inside the Movistar Team 2019': 'Spain',
    'Word of Honor': 'China',
    'Eden': 'Japan, United States',
    'Gatao - The Last Stray': 'Taiwan',
    'High on the Hog: How African American Cuisine Transformed America': 'United States',
    'Nail Bomber: Manhunt': 'United Kingdom',
    'A Place in the Stars': 'Nigeria',
    'Mad for Each Other': 'South Korea',
    'Sam Smith: Love Goes - Live at Abbey Road Studios': 'United Kingdom',
    '99 Songs (Tamil)': 'India',
    '99 Songs (Telugu)': 'India',
    'Creating an Army of the Dead': 'United States',
    'Strain': 'Nigeria',
    '678': 'Egypt',
    'Little Singham Future mein Satakli': 'India',
    'Taxi No. 9211': 'India',
    'Love or Money': 'Philippines',
    'The Mystic River': 'Nigeria',
    'The Upshaws - The Afterparty': 'United States',
    'Wave of Cinema: Filosofi Kopi': 'Indonesia',
    'Use For My Talent': 'China',
    'Dear Affy': 'Nigeria',
    'The Circle - The Afterparty': 'United States',
    'Trash Truck': 'United States',
    'Angelina Ballerina': 'United Kingdom',
    'Barney and Friends': 'United States',
    'Dead Again in Tombstone': 'United States',
    'Miniforce: Super Dino Power': 'South Korea',
    "Motu Patlu in Dragon's World": 'India',
    'Motu Patlu in the Game of Zones': 'India',
    'Motu Patlu in Wonderland': 'India',
    'Motu Patlu: Deep Sea Adventure': 'India',
    'Motu Patlu: Mission Moon': 'India',
    'Pet Stars': 'United States',
    'Seven': 'United States',
    'The Innocent': 'Spain',
    'The Mitchells vs. The Machines': 'United States',
    'The Unremarkable Juanquini': 'Colombia',
    'Things Heard & Seen': 'United States',
    'Yasuke': 'United States, Japan',
    'Headspace Guide to Sleep': 'United States',
    'Legal Hash': 'Nigeria',
    'Perfume Imaginary Museum “Time Warp”': 'Japan',
    'Wild Dog': 'India',
    'Keymon and Nani in Space Adventure': 'India',
    'Motu Patlu Dino Invasion': 'India',
    'Motu Patlu in Octupus World': 'India',
    'Motu Patlu VS Robo Kids': 'India',
    'Rudra: Secret of the Black Moon': 'India',
    'Rudra: The Rise of King Pharaoh': 'India',
    'Bakugan: Geogan Rising': 'Canada, Japan',
    'Dad Stop Embarrassing Me - The Afterparty': 'United States',
    'Dancing Angels': 'Nigeria',
    "Wave of Cinema: One Day We'll Talk About Today": 'Indonesia',
    'Ajaibnya Cinta': 'Malaysia',
    'Motu Patlu in Hong Kong: Kung Fu Kings 3': 'India',
    'Motu Patlu in the City of Gold': 'India',
    'Motu Patlu Kung Fu Kings 4 The Challenge of Kung Fu Brothers': 'India',
    'Motu Patlu the Superheroes – Super Villains from Mars': 'India',
    'Shiva VS Autobots': 'India',
    'Shiva: Journey to Plunotaria': 'India',
    'Shiva: The Secret World Of Vedas City': 'India',
    "Don't be the First one": 'South Korea',
    'Dolly Parton: A MusiCares Tribute': 'United States',
    'The Wedding Coach': 'United States',
    "This Is a Robbery: The World's Biggest Art Heist": 'United States',
    'The Last Kids on Earth: Happy Apocalypse to You': 'United States, Canada',
    'Glimpses of a Future': 'United States',
    'Seven Souls in the Skull Castle: Season Bird': 'Japan',
    'Seven Souls in the Skull Castle: Season Wind': 'Japan',
    'Black Is Beltza': 'Spain',
    'Alien TV': 'Australia, Canada',
    'Reframe THEATER EXPERIENCE with you': 'Japan',
    "Wave of Cinema: 90's Generation": 'Indonesia',
    'Audrey': 'United Kingdom',
    'Quiet': 'United States',
    'Last Chance U: Basketball': 'United States',
    'Marriage or Mortgage': 'United States',
    'Pokémon Journeys: The Series': 'Japan',
    'A Perfect Day For Arsenide': 'Hong Kong',
    'Banyuki': 'Japan',
    'Blanche Gardin: The All-Nighter': 'France',
    'Connected': 'United States',
    'Seven Souls in the Skull Castle 2011': 'Japan',
    'Ginny & Georgia - The Afterparty': 'United States',
    'The Last Bastion': 'Peru',
    'M8 - When Death Rescues Life': 'Brazil',
    'Wave of Cinema: Surat dari Timur': 'Indonesia',
    'Thus Spoke Kishibe Rohan': 'Japan',
    'Hire a Woman': 'Nigeria',
    'She Is': 'Nigeria',
    'Chris Rock Total Blackout: The Tamborine Extended Cut': 'United States',
    'Ratones Paranoicos: The Band that Rocked Argentina': 'Argentina',
    'Korean Pork Belly Rhapsody': 'South Korea',
    'Running Man': 'South Korea',
    'Best of Stand-Up 2020': 'United States',
    'Transformers: War for Cybertron: Earthrise': 'United States',
    "Ma Rainey's Black Bottom: A Legacy Brought to Screen": 'United States',
    'The Wedding Shaman': 'Thailand',
    'BREAK IT ALL: The History of Rock in Latin America': 'Argentina',
    'A Trash Truck Christmas': 'United States',
    'Futmalls.com': 'Taiwan',
    'Super Monsters: Santa’s Super Monster Helpers': 'United States',
    'Manhunt: Deadly Games': 'United States',
    'The Great British Baking Show: Holidays': 'United Kingdom',
    'Chico Bon Bon and the Very Berry Holiday': 'United States',
    'Andhaghaaram': 'India',
    'Heart & Soul': 'Nigeria',
    'Bakugan: Armored Alliance': 'Canada, Japan',
    'The Beginning of Life': 'Brazil',
    'Ya no estoy aquí: Una conversación entre Guillermo del Toro y Alfonso Cuarón': 'Mexico',
    'Kongsuni and Friends': 'South Korea',
    'La Gran Ilusión': 'Spain',
    'Unsolved Mysteries': 'United States',
    'Pat a Pat Como': 'South Korea',
    'Qurious Como': 'South Korea',
    'A Go! Go! Cory Carson Halloween': 'United States',
    'Journey of an African Colony': 'Nigeria',
    'The American Game': 'Egypt',
    'Mighty Little Bheem': 'India',
    "My Mother's Wound": 'Turkey',
    'Zulu Man in Japan': 'South Africa',
    'High & Low The Worst': 'Japan',
    'Fukrey Boyzzz': 'India',
    "Dragon's Dogma": 'Japan, United States',
    'Nee Enge En Anbe': 'India',
    'Dr Jason Leong Hashtag Blessed': 'Malaysia',
    'Wish Upon a Unicorn': 'United States',
    'Wonho Chung: Live in New York': 'Jordan',
    'Transformers: Cyberverse': 'United States',
    'The Witcher: A Look Inside the Episodes': 'United States',
    'Baewatch: Parental Guidance': 'United Kingdom',
    'Little Singham: Kaal Ka Badla': 'India',
    'Dérè: An African Tale': 'Nigeria',
    "Beyond the Boundary: ICC Women's T20 World Cup Australia 2020": 'Australia',
    'Diamonds in the Sky': 'Nigeria',
    'Selling Sunset': 'United States',
    'Sin City': 'United States',
    'A Go! Go! Cory Carson Summer Camp': 'United States',
    'Tumi or not Tumi': 'India',
    'Unlucky Ploy': 'Thailand',
    'Street Food: Latin America': 'United States',
    'Little Singham: Legend of Dugabakka': 'India',
    'Your Excellency': 'Nigeria',
    'Jim Jefferies: Intolerant': 'United States',
    'PNL - Dans la légende tour': 'France',
    'Thackeray (Marathi)': 'India',
    'Seven (Telugu)': 'India',
    'El límite infinito': 'Argentina',
    'Dating Around': 'United States',
    'The Light of My Eyes': 'Egypt',
    'Alone': 'United States',
    'Mr. Romantic': 'Egypt',
    'Fifty Year Old Teenager': 'Egypt',
    'Lock Your Girls In': 'Egypt',
    'Raya and Sakina': 'Egypt',
    'Sayed the Servant': 'Egypt',
    'Especial 20 años Fútbol de Primera': 'Argentina',
    'Match': 'Russia',
    'Sí, Mi Amor': 'Peru',
    'Hangar 1: The UFO Files': 'United States',
    'Hoarders': 'United States',
    'The Universe: Ancient Mysteries Solved': 'United States',
    'Thomas & Friends: Marvelous Machinery: A New Arrival': 'United Kingdom',
    'Thomas & Friends: Marvelous Machinery: World of Tomorrow': 'United Kingdom',
    'Thomas & Friends: Thomas and the Royal Engine': 'United Kingdom',
    'Lembi 8 Giga': 'Egypt',
    'دفعة القاهرة': 'Kuwait'
}

In [282]:
df['country'] = df['country'].fillna(df['title'].map(media_countries_2))
remaining_nulls = df['country'].isnull().sum()
print(f"Remaining null values in country column: {remaining_nulls}")

Remaining null values in country column: 401

In [283]:
missing_countries_titles_3 = missing_countries_titles[431:632]
missing_countries_titles_3

['DreamWorks Spooky Stories: Volume 2',
 'The Circle France',
 'Pokémon the Series',
 'Bal Ganesh',
 'Tree House Tales',
 'Wassup Man GO!',
 '7SEEDS',
 'Barbie Dreamhouse Adventures: Go Team Roberts',
 "Archibald's Next Big Thing",
 "Digs & Discoveries: All Track's Lead to Rome",
 'Digs & Discoveries: Mines of Mystery',
 'Steam Team to the Rescue',
 'Alakada Reloaded',
 'Angu Vaikuntapurathu (Malayalam)',
 'Calico Critters Mini Episodes Clover',
 "Calico Critters: Everyone's Big Dream Flying in the Sky",
 'Velvet Colección: Grand Finale',
 'The Visit',
 'Passion. Panache. Pep',
 'Monster High: Electrified',
 'Palazuelos mi rey',
 'My Holo Love',
 'Find Yourself',
 'Rise of Empires: Ottoman',
 'The Healing Powers of Dude',
 'Chhota Bheem Kung Fu Dhamaka Series',
 "Luccas Neto in: Children's Day",
 'Riot',
 'Pucca: Love Recipe',
 'The Degenerates',
 'The Vendor',
 'Falz Experience',
 'The First Lady',
 'Holy Expectations',
 'Seven and a half dates',
 'Zero Hour',
 'Celebrity Marriage',
 'Triad Princess',
 'Space Jungle',
 'Lagos Real Fake Life',
 'The Charming Stepmom',
 'Little Singham: Mahabali',
 'True: Winter Wishes',
 'Miss Culinary',
 'Westside Story',
 'The House of Flowers Presents: The Funeral',
 'Sleepless Society: Bedtime Wishes',
 'Tunnel',
 'My Next Guest with David Letterman and Shah Rukh Khan',
 'Little Singham: Kaal Ki Tabaahi',
 'ChuChu TV Kids Songs, Learning Videos & Bedtime Stories',
 'ChuChuTV Bedtime Stories & Moral Stories for Kids (English)',
 'ChuChuTV Bedtime Stories & Moral Stories for Kids (Hindi)',
 'ChuChuTV Surprise Eggs Learning Videos (English)',
 'ChuChuTV Surprise Eggs Learning Videos (Hindi)',
 'In My Country',
 'MONKART',
 'Beyblade Burst Turbo',
 'GEN HOSHINO STADIUM TOUR “POP VIRUS”',
 'Super Monsters',
 'Little Baby Bum: Go Buster',
 'Cultivating the Seas: History and Future of the Full-Cycle Cultured Kindai Tuna',
 'Oh! Baby (Malayalam)',
 'Oh! Baby (Tamil)',
 'Criminal: France',
 'Top Boy',
 'Loo Loo Kids: Johny & Friends Musical Adventures',
 'Back to School',
 'Styling Hollywood',
 'HERO MASK',
 'Game Over (Hindi Version)',
 'Game Over (Telugu Version)',
 'Happy Jail',
 'Colin Quinn: Red State Blue State',
 'Léa & I',
 'Whitney Cummings: Can I Touch It?',
 'Extreme Engagement',
 'PILI Fantasy: War of Dragons',
 'True Tunes',
 'Kakegurui',
 'Answer for Heaven',
 'El desconocido',
 'Killer Ratings',
 'Hyper HardBoiled Gourmet Report',
 'The Lonely Island Presents: The Unauthorized Bash Brothers Experience',
 "ReMastered: The Lion's Share",
 'I Hear You',
 'Jailbirds',
 'Away From Home',
 'Bibik-Bibikku',
 'Cinta 100KG',
 'Cinta Iris',
 'Cinta Si Wedding Planner',
 'Cinta Teruna Kimchi',
 'Secret of Success',
 'The Missing Menu',
 'Unchained Fate',
 'I Have a Script',
 'What If?',
 'K.O. One Re-act',
 'KO One Return',
 'The Hateful Eight: Extended Version',
 'Grass Is Greener',
 'Brené Brown: The Call to Courage',
 'HOMECOMING: A film by Beyoncé',
 'Super Monsters Furever Friends',
 'Petta (Telugu Version)',
 'Ricardo Quevedo: Los amargados somos más',
 'Kicko & Super Speedo',
 'The Terminal',
 "The Eagle of El-Se'eed",
 'The 10 Sins',
 'Antoine Griezmann: The Making of a Legend',
 'February 9',
 'My Pride',
 'The Disappearance of Madeleine McCann',
 'Jimmy Carr: The Best of Ultimate Gold Greatest Hits',
 'Bangkok Love Stories: Hey You!',
 'The Confrontation',
 'Sarkar',
 'Larva Island',
 'Losers',
 'Sarvam Thaala Mayam (Tamil Version)',
 "Larry Charles' Dangerous World of Comedy",
 'The 43',
 'Paprika',
 'Maharaja: The Story of Ranjit Singh',
 'Gabriel "Fluffy" Iglesias: One Show Fits All',
 'Alt-Right: Age of Rage',
 'The Perfect Match',
 'Memory Love',
 'Trigger Warning with Killer Mike',
 'Back with the Ex',
 'El Potro: Unstoppable',
 'See You in Time',
 'Déjà Vu',
 'Bill Hicks: Reflections',
 'Gina Yashere: Laughing to America',
 'Taylor Swift reputation Stadium Tour',
 'Pioneers: First Women Filmmakers*',
 'The Birth Reborn 3',
 "Demon's Path",
 'Single Ladies Senior',
 'Inside the Real Narcos',
 'Free Rein: The Twelve Neighs of Christmas',
 'ReMastered: Who Killed Jam Master Jay?',
 'Super Monsters and the Wish Star',
 'RUSSELL BRAND: RE:BIRTH',
 'Haunted House',
 'Oddbods: The Festive Menace',
 'Kulipari: Dream Walker',
 'Paap-O-Meter',
 'Beyblade Burst Evolution',
 'Loudon Wainwright III: Surviving Twin',
 'Brainchild',
 'The Great British Baking Show: The Beginnings',
 'Been So Long',
 'Baahubali: The Beginning (English Version)',
 'Derren Brown: Sacrifice',
 'Oddbods: Party Monsters',
 "Edgar Rice Burroughs' Tarzan and Jane",
 'FIGHTWORLD',
 'Ordinary Heroes',
 'Salt Fat Acid Heat',
 'Dancing Queen',
 'Super Monsters Save Halloween',
 'Violet Evergarden: Special',
 'Joe Rogan: Strange Times',
 'Monty Python Conquers America',
 'Dushman',
 'Freedom at Midnight',
 'The Birth Reborn',
 'Battlefish',
 'Boca Juniors Confidential',
 'Super Monsters Monster Party',
 'If I were an Animal',
 'Show Me the Money',
 'First and Last',
 'Ultimate Beastmaster México',
 'Bert Kreischer: Secret Time',
 'Pretty Man',
 'Dinotrux Supercharged',
 'Camarón Revolution',
 'True: Magical Friends',
 'True: Wonderful Wishes',
 'Dance & Sing with True',
 'Pocoyo & Cars',
 'Pocoyo Carnival',
 'Pocoyo Halloween: Spooky Movies',
 'Pocoyo Special Sports',
 'Spiritual House',
 'Bobby Kennedy for President',
 'Goodnight DJ 1',
 'Moving On',
 'Trio and a Bed',
 '海的儿子',
 'Yoo Byung Jae: Too Much Information',
 'Expedition China',
 'Fred Armisen: Standup For Drummers',
 'Kavin Jay: Everybody Calm Down!',
 'Countdown to Death: Pablo Escobar']

In [284]:
media_countries_3 = {
    'DreamWorks Spooky Stories: Volume 2': 'United States',
    'The Circle France': 'France',
    'Pokémon the Series': 'Japan',
    'Bal Ganesh': 'India',
    'Tree House Tales': 'South Korea',
    'Wassup Man GO!': 'South Korea',
    '7SEEDS': 'Japan',
    'Barbie Dreamhouse Adventures: Go Team Roberts': 'United States',
    "Archibald's Next Big Thing": 'United States',
    "Digs & Discoveries: All Track's Lead to Rome": 'United Kingdom',
    'Digs & Discoveries: Mines of Mystery': 'United Kingdom',
    'Steam Team to the Rescue': 'United Kingdom',
    'Alakada Reloaded': 'Nigeria',
    'Angu Vaikuntapurathu (Malayalam)': 'India',
    'Calico Critters Mini Episodes Clover': 'Japan',
    "Calico Critters: Everyone's Big Dream Flying in the Sky": 'Japan',
    'Velvet Colección: Grand Finale': 'Spain',
    'The Visit': 'United States',
    'Passion. Panache. Pep': 'India',
    'Monster High: Electrified': 'United States',
    'Palazuelos mi rey': 'Mexico',
    'My Holo Love': 'South Korea',
    'Find Yourself': 'China',
    'Rise of Empires: Ottoman': 'Turkey, United States',
    'The Healing Powers of Dude': 'United States',
    'Chhota Bheem Kung Fu Dhamaka Series': 'India',
    "Luccas Neto in: Children's Day": 'Brazil',
    'Riot': 'United Kingdom',
    'Pucca: Love Recipe': 'South Korea',
    'The Degenerates': 'United States',
    'The Vendor': 'Nigeria',
    'Falz Experience': 'Nigeria',
    'The First Lady': 'Nigeria',
    'Holy Expectations': 'Nigeria',
    'Seven and a half dates': 'Nigeria',
    'Zero Hour': 'Nigeria',
    'Celebrity Marriage': 'Nigeria',
    'Triad Princess': 'Taiwan',
    'Space Jungle': 'South Korea',
    'Lagos Real Fake Life': 'Nigeria',
    'The Charming Stepmom': 'Thailand',
    'Little Singham: Mahabali': 'India',
    'True: Winter Wishes': 'Canada, United States',
    'Miss Culinary': 'Thailand',
    'Westside Story': 'United States',
    'The House of Flowers Presents: The Funeral': 'Mexico',
    'Sleepless Society: Bedtime Wishes': 'Thailand',
    'Tunnel': 'South Korea',
    'My Next Guest with David Letterman and Shah Rukh Khan': 'United States',
    'Little Singham: Kaal Ki Tabaahi': 'India',
    'ChuChu TV Kids Songs, Learning Videos & Bedtime Stories': 'India',
    'ChuChuTV Bedtime Stories & Moral Stories for Kids (English)': 'India',
    'ChuChuTV Bedtime Stories & Moral Stories for Kids (Hindi)': 'India',
    'ChuChuTV Surprise Eggs Learning Videos (English)': 'India',
    'ChuChuTV Surprise Eggs Learning Videos (Hindi)': 'India',
    'In My Country': 'Nigeria',
    'MONKART': 'South Korea',
    'Beyblade Burst Turbo': 'Japan',
    'GEN HOSHINO STADIUM TOUR “POP VIRUS”': 'Japan',
    'Super Monsters': 'United States',
    'Little Baby Bum: Go Buster': 'United Kingdom',
    'Cultivating the Seas: History and Future of the Full-Cycle Cultured Kindai Tuna': 'Japan',
    'Oh! Baby (Malayalam)': 'India',
    'Oh! Baby (Tamil)': 'India',
    'Criminal: France': 'France, United Kingdom',
    'Top Boy': 'United Kingdom',
    'Loo Loo Kids: Johny & Friends Musical Adventures': 'Romania',
    'Back to School': 'France',
    'Styling Hollywood': 'United States',
    'HERO MASK': 'Japan',
    'Game Over (Hindi Version)': 'India',
    'Game Over (Telugu Version)': 'India',
    'Happy Jail': 'United States',
    'Colin Quinn: Red State Blue State': 'United States',
    'Léa & I': 'United States',
    'Whitney Cummings: Can I Touch It?': 'United States',
    'Extreme Engagement': 'Australia',
    'PILI Fantasy: War of Dragons': 'Taiwan',
    'True Tunes': 'Canada, United States',
    'Kakegurui': 'Japan',
    'Answer for Heaven': 'Thailand',
    'El desconocido': 'Mexico',
    'Killer Ratings': 'Brazil, United Kingdom',
    'Hyper HardBoiled Gourmet Report': 'Japan',
    'The Lonely Island Presents: The Unauthorized Bash Brothers Experience': 'United States',
    "ReMastered: The Lion's Share": 'United States',
    'I Hear You': 'China',
    'Jailbirds': 'United States',
    'Away From Home': 'Nigeria',
    'Bibik-Bibikku': 'Malaysia',
    'Cinta 100KG': 'Malaysia',
    'Cinta Iris': 'Malaysia',
    'Cinta Si Wedding Planner': 'Malaysia',
    'Cinta Teruna Kimchi': 'Malaysia',
    'Secret of Success': 'Malaysia',
    'The Missing Menu': 'Malaysia',
    'Unchained Fate': 'Malaysia',
    'I Have a Script': 'Kuwait',
    'What If?': 'Kuwait',
    'K.O. One Re-act': 'Taiwan',
    'KO One Return': 'Taiwan',
    'The Hateful Eight: Extended Version': 'United States',
    'Grass Is Greener': 'United States',
    'Brené Brown: The Call to Courage': 'United States',
    'HOMECOMING: A film by Beyoncé': 'United States',
    'Super Monsters Furever Friends': 'United States',
    'Petta (Telugu Version)': 'India',
    'Ricardo Quevedo: Los amargados somos más': 'Colombia',
    'Kicko & Super Speedo': 'India',
    'The Terminal': 'United States',
    "The Eagle of El-Se'eed": 'Egypt',
    'The 10 Sins': 'Egypt',
    'Antoine Griezmann: The Making of a Legend': 'France',
    'February 9': 'Egypt',
    'My Pride': 'Egypt',
    'The Disappearance of Madeleine McCann': 'United Kingdom',
    'Jimmy Carr: The Best of Ultimate Gold Greatest Hits': 'United Kingdom',
    'Bangkok Love Stories: Hey You!': 'Thailand',
    'The Confrontation': 'Egypt',
    'Sarkar': 'India',
    'Larva Island': 'South Korea',
    'Losers': 'United States',
    'Sarvam Thaala Mayam (Tamil Version)': 'India',
    "Larry Charles' Dangerous World of Comedy": 'United States',
    'The 43': 'Mexico',
    'Paprika': 'Italy',
    'Maharaja: The Story of Ranjit Singh': 'India',
    'Gabriel "Fluffy" Iglesias: One Show Fits All': 'United States',
    'Alt-Right: Age of Rage': 'United States',
    'The Perfect Match': 'Taiwan',
    'Memory Love': 'Taiwan',
    'Trigger Warning with Killer Mike': 'United States',
    'Back with the Ex': 'Australia',
    'El Potro: Unstoppable': 'Argentina',
    'See You in Time': 'Taiwan',
    'Déjà Vu': 'Taiwan',
    'Bill Hicks: Reflections': 'United Kingdom',
    'Gina Yashere: Laughing to America': 'United Kingdom',
    'Taylor Swift reputation Stadium Tour': 'United States',
    'Pioneers: First Women Filmmakers*': 'United States',
    'The Birth Reborn 3': 'Brazil',
    "Demon's Path": 'Hong Kong',
    'Single Ladies Senior': 'Egypt',
    'Inside the Real Narcos': 'United Kingdom',
    'Free Rein: The Twelve Neighs of Christmas': 'United Kingdom',
    'ReMastered: Who Killed Jam Master Jay?': 'United States',
    'Super Monsters and the Wish Star': 'United States',
    'RUSSELL BRAND: RE:BIRTH': 'United Kingdom',
    'Haunted House': 'South Korea',
    'Oddbods: The Festive Menace': 'Singapore',
    'Kulipari: Dream Walker': 'United States',
    'Paap-O-Meter': 'India',
    'Beyblade Burst Evolution': 'Japan',
    'Loudon Wainwright III: Surviving Twin': 'United States',
    'Brainchild': 'United States',
    'The Great British Baking Show: The Beginnings': 'United Kingdom',
    'Been So Long': 'United Kingdom',
    'Baahubali: The Beginning (English Version)': 'India',
    'Derren Brown: Sacrifice': 'United Kingdom',
    'Oddbods: Party Monsters': 'Singapore',
    "Edgar Rice Burroughs' Tarzan and Jane": 'United States, Canada',
    'FIGHTWORLD': 'United States',
    'Ordinary Heroes': 'Egypt',
    'Salt Fat Acid Heat': 'United States',
    'Dancing Queen': 'United States',
    'Super Monsters Save Halloween': 'United States',
    'Violet Evergarden: Special': 'Japan',
    'Joe Rogan: Strange Times': 'United States',
    'Monty Python Conquers America': 'United States',
    'Dushman': 'India',
    'Freedom at Midnight': 'India',
    'The Birth Reborn': 'Brazil',
    'Battlefish': 'United States',
    'Boca Juniors Confidential': 'Argentina',
    'Super Monsters Monster Party': 'United States',
    'If I were an Animal': 'France',
    'Show Me the Money': 'South Korea',
    'First and Last': 'United States',
    'Ultimate Beastmaster México': 'United States',
    'Bert Kreischer: Secret Time': 'United States',
    'Pretty Man': 'China',
    'Dinotrux Supercharged': 'United States',
    'Camarón Revolution': 'Spain',
    'True: Magical Friends': 'Canada, United States',
    'True: Wonderful Wishes': 'Canada, United States',
    'Dance & Sing with True': 'Canada, United States',
    'Pocoyo & Cars': 'Spain',
    'Pocoyo Carnival': 'Spain',
    'Pocoyo Halloween: Spooky Movies': 'Spain',
    'Pocoyo Special Sports': 'Spain',
    'Spiritual House': 'Egypt',
    'Bobby Kennedy for President': 'United States',
    'Goodnight DJ 1': 'Malaysia',
    'Moving On': 'Egypt',
    'Trio and a Bed': 'Egypt',
    '海的儿子': 'China',
    'Yoo Byung Jae: Too Much Information': 'South Korea',
    'Expedition China': 'United States',
    'Fred Armisen: Standup For Drummers': 'United States',
    'Kavin Jay: Everybody Calm Down!': 'Malaysia',
    'Countdown to Death: Pablo Escobar': 'Colombia'
}

In [285]:
df['country'] = df['country'].fillna(df['title'].map(media_countries_3))
remaining_nulls = df['country'].isnull().sum()
print(f"Remaining null values in country column: {remaining_nulls}")

Remaining null values in country column: 200

In [286]:
missing_countries_titles_4 = missing_countries_titles[632:832]
missing_countries_titles_4

['Tundukkan Playboy Itu',
 'Wadi',
 'Part-Time Idol',
 'Cheuk Wan-Chi: Two Night Stand',
 'Dawai Asmara',
 'Padamu Aku Bersujud',
 'Trailer Park Boys: Out of the Park: USA',
 'Bright: The Music Videos',
 'Akulah Balqis',
 'The Family Court',
 'The Golden Path',
 'The Little Nyonya',
 'The Truth',
 'In Laws',
 'Laws of Attraction',
 'Justice in the City',
 'Mak Cun',
 'Out of Thin Air',
 'Satu Hari',
 'Joaquín Reyes: Una y no más',
 'Alias JJ, la celebridad del mal',
 'Baahubali 2: The Conclusion (Malayalam Version)',
 'Baahubali 2: The Conclusion (Tamil Version)',
 'Baahubali: The Beginning (Malayalam Version)',
 'Baahubali: The Beginning (Tamil Version)',
 'Have You Ever Fallen in Love, Miss Jiang?',
 'Love Storm',
 'Maz Jobrani: Immigrant',
 'Surviving Escobar - Alias JJ',
 'Breakout',
 'Spice Up',
 'Miniforce',
 'Hasan Minhaj: Homecoming King',
 'All Hail King Julien: Exiled',
 'Five Came Back',
 "Santa Pac's Merry Berry Day",
 "Pac's Scary Halloween",
 'Karol Modzelewski, Łukasz „Lotek” Lodkowski No Offense',
 'Katarzyna Piasecka, Rafał Pacześ Seriously Funny',
 'Mariusz Kałamaga, Karol Kopiec, Wiolka Walaszczyk Hilarious Trio',
 'Rafał Banaś, Michał Leja Laugh out Loud',
 'The Best of Rafał Rutkowski Olka Szczęśniak',
 'Tomasz Jachimek, Jacek Stramik Laugh at Live',
 "Chef's Table: France",
 'Justin Time GO!',
 "Masha's Tales",
 'Wakfu: The Quest for the Six Eliatrope Dofus',
 'Iliza Shlesinger: Freezing Hot',
 'Feb-09',
 'แผนร้ายนายเจ้าเล่ห์',
 '13TH: A Conversation with Oprah Winfrey & Ava DuVernay',
 '3 Deewarein',
 '5 Cowok Jagoan',
 'A Mission in an Old Movie',
 'Age of Glory',
 'Antariksha Ke Rakhwale',
 'Bangkok Bachelors',
 'Beauty and the Bitches',
 'Behind the Newsroom',
 'Best Neighbors',
 'Bheemayan',
 'Bob Ross: Beauty Is Everywhere',
 'Border Patrol',
 'Bringing Sexy Back',
 'Buddha',
 'Bure Kaam Bura Natija, Kyun Bhai Chacha Haan Bhatija',
 'Calico Critters',
 'Calico Critters: A Town of Dreams',
 'Calico Critters: The Treasure of Calico Village',
 'Castle of Stars',
 'Chhota Bheem Aur Kaala Yodha',
 'Chhota Bheem Ka Romani Adventure',
 'Chhota Bheem Ka Troll Se Takkar',
 'Chill with Bob Ross',
 "Chingo Bling: They Can't Deport Us All",
 'Club Friday The Series 6',
 'Club Friday The Series 7',
 'Club Friday The Series 8',
 'Club Friday To Be Continued - Friend & Enemy',
 'Club Friday To Be Continued - My Beautiful Tomboy',
 'Club Friday To Be Continued - The Promise',
 'Comedy High School',
 'Convict',
 'Cop Watchers',
 'Desolate',
 'Diva Brides',
 'Dragonkala Ka Rahasya',
 "Earth's Natural Wonders: Life at the Extremes",
 'El Viaje: Márama y Rombai',
 'Elles étaient en guerre 1939-1945',
 'Elles ont toutes une histoire',
 'Encerrados',
 'Enemigo íntimo',
 'Eurovision Song Contest',
 'Exclusive Edition',
 'Fatal Destiny',
 'Fishpeople',
 'Fit for Fashion',
 'Food: Delicious Science',
 'Glowing Embers',
 'Ha Unlimited',
 'Harlem Globetrotters: The Team That Changed the World',
 'Homeland',
 'Hostages',
 'How to Live Mortgage Free with Sarah Beeny',
 "Hyori's Bed & Breakfast",
 'I Dream Of Dance',
 "It's Fine",
 '최강전사 미니특공대 : 영웅의 탄생',
 "Jake's Buccaneer Blast",
 'Jis Desh Men Ganga Behti Hai',
 'John Mellencamp: Plain Spoken',
 'Jugaad',
 'Kikoriki',
 'Kingdoms of the Sky',
 'Kiss The Series',
 'Kon Kon Kon',
 'Krish Trish and Baltiboy',
 'Krish Trish and Baltiboy: Battle of Wits',
 'Krish Trish and Baltiboy: Best Friends Forever',
 'Krish Trish and Baltiboy: Comics of India',
 'Krish Trish and Baltiboy: Oversmartness Never Pays',
 'Krish Trish and Baltiboy: Part II',
 'Krish Trish and Baltiboy: The Greatest Trick',
 'Krishna Balram',
 'Kuppivala',
 'La Femme',
 'LeapFrog: Sing-along, Read-along',
 'Lego Friends',
 'LEGO House - Home of the Brick',
 'Leo & Tig',
 'Listen Up! The Lives of Quincy Jones',
 'Little Singham aur Kaal ka Mahajaal',
 'Little Singham Bandarpur Mein Hu Ha Hu',
 'Little Singham in London',
 'Los 10 años de Peter Capusotto',
 'Los Niños Héroes de Chapultepec',
 'Love Rhythms - Accidental Daddy',
 'Man vs Wild with Sunny Leone',
 'Mark Gatiss: A Study in Sherlock',
 'Marvel & ESPN Films Present: 1 of 1: Genesis',
 'Melodies of Life - Born This Way',
 'Mere Papa Hero Hiralal',
 'Mighty Morphin Alien Rangers',
 'Money for Nothing',
 'My Life My Story',
 'My Only Mother',
 'My Wife and My Wifey',
 "National Lampoon's Loaded Weapon 1",
 'Nightmare Tenants, Slum Landlords',
 'Nuestra Lucha Libre',
 'O-Negative, Love Can’t Be Designed',
 'Oh My Ghost 4',
 'Operation Odessa',
 'Phamous',
 'Power Battle Watch Car',
 'Power Rangers Dino Super Charge',
 'Power Rangers Super Megaforce',
 'Power Rangers Super Samurai',
 'Prince Jai Aur Dumdaar Viru',
 'Queens of Comedy',
 'Queens vs. Kings',
 'Rab Se Sohna Isshq',
 'Reality of Dream',
 'Refugee',
 'Revenge',
 'Roots',
 'Samudri Lootere',
 'Satrangi',
 'Strongland',
 'Swami Baba Ramdev: The Untold Story',
 'Teenage Mutant Ninja Turtles: The Movie',
 'The Adjusters',
 'The Bachelor',
 'The Beat',
 "The Bulbul's Nest",
 'The Gospel of Mark',
 'The Gospel of Matthew',
 'The Homecoming',
 'The Irish Mob',
 'The Kindness Diaries',
 'The Liar',
 'The Naked Gun 2 1/2: The Smell of Fear',
 'The Perfect Day',
 'The Republic of Imbaba',
 'The Underwear',
 'Three-Quarters Decent',
 'Timeless Season',
 'Timeline',
 'Tom and Jerry: The Magic Ring',
 'Towies',
 'Tremors 2: Aftershocks',
 'ViR: The Robot Boy',
 'Wake Up',
 'Westside vs. the World',
 "World's Weirdest Homes",
 'Yoko',
 'YOM',
 'Zombie Dumb']

In [287]:
media_countries_4 = {
    'Tundukkan Playboy Itu': 'Malaysia',
    'Wadi': 'Malaysia',
    'Part-Time Idol': 'South Korea',
    'Cheuk Wan-Chi: Two Night Stand': 'Hong Kong',
    'Dawai Asmara': 'Indonesia',
    'Padamu Aku Bersujud': 'Malaysia',
    'Trailer Park Boys: Out of the Park: USA': 'Canada',
    'Bright: The Music Videos': 'United States',
    'Akulah Balqis': 'Malaysia',
    'The Family Court': 'Singapore',
    'The Golden Path': 'Singapore',
    'The Little Nyonya': 'Singapore, Malaysia',
    'The Truth': 'Singapore',
    'In Laws': 'Singapore',
    'Laws of Attraction': 'Singapore',
    'Justice in the City': 'Singapore',
    'Mak Cun': 'Malaysia',
    'Out of Thin Air': 'Iceland',
    'Satu Hari': 'Malaysia',
    'Joaquín Reyes: Una y no más': 'Spain',
    'Alias JJ, la celebridad del mal': 'Colombia',
    'Baahubali 2: The Conclusion (Malayalam Version)': 'India',
    'Baahubali 2: The Conclusion (Tamil Version)': 'India',
    'Baahubali: The Beginning (Malayalam Version)': 'India',
    'Baahubali: The Beginning (Tamil Version)': 'India',
    'Have You Ever Fallen in Love, Miss Jiang?': 'Taiwan',
    'Love Storm': 'Taiwan',
    'Maz Jobrani: Immigrant': 'United States',
    'Surviving Escobar - Alias JJ': 'Colombia',
    'Breakout': 'Singapore',
    'Spice Up': 'Singapore',
    'Miniforce': 'South Korea',
    'Hasan Minhaj: Homecoming King': 'United States',
    'All Hail King Julien: Exiled': 'United States',
    'Five Came Back': 'United States',
    "Santa Pac's Merry Berry Day": 'United States, Japan',
    "Pac's Scary Halloween": 'United States, Japan',
    'Karol Modzelewski, Łukasz „Lotek” Lodkowski No Offense': 'Poland',
    'Katarzyna Piasecka, Rafał Pacześ Seriously Funny': 'Poland',
    'Mariusz Kałamaga, Karol Kopiec, Wiolka Walaszczyk Hilarious Trio': 'Poland',
    'Rafał Banaś, Michał Leja Laugh out Loud': 'Poland',
    'The Best of Rafał Rutkowski Olka Szczęśniak': 'Poland',
    'Tomasz Jachimek, Jacek Stramik Laugh at Live': 'Poland',
    "Chef's Table: France": 'United States',
    'Justin Time GO!': 'Canada',
    "Masha's Tales": 'Russia',
    'Wakfu: The Quest for the Six Eliatrope Dofus': 'France',
    'Iliza Shlesinger: Freezing Hot': 'United States',
    'Feb-09': 'Egypt',
    'แผนร้ายนายเจ้าเล่ห์': 'Thailand',
    '13TH: A Conversation with Oprah Winfrey & Ava DuVernay': 'United States',
    '3 Deewarein': 'India',
    '5 Cowok Jagoan': 'Indonesia',
    'A Mission in an Old Movie': 'Egypt',
    'Age of Glory': 'Malaysia',
    'Antariksha Ke Rakhwale': 'India',
    'Bangkok Bachelors': 'Thailand',
    'Beauty and the Bitches': 'Thailand',
    'Behind the Newsroom': 'Egypt',
    'Best Neighbors': 'Egypt',
    'Bheemayan': 'India',
    'Bob Ross: Beauty Is Everywhere': 'United States',
    'Border Patrol': 'New Zealand',
    'Bringing Sexy Back': 'Australia',
    'Buddha': 'India',
    'Bure Kaam Bura Natija, Kyun Bhai Chacha Haan Bhatija': 'India',
    'Calico Critters': 'Japan',
    'Calico Critters: A Town of Dreams': 'Japan',
    'Calico Critters: The Treasure of Calico Village': 'Japan',
    'Castle of Stars': 'Egypt',
    'Chhota Bheem Aur Kaala Yodha': 'India',
    'Chhota Bheem Ka Romani Adventure': 'India',
    'Chhota Bheem Ka Troll Se Takkar': 'India',
    'Chill with Bob Ross': 'United States',
    "Chingo Bling: They Can't Deport Us All": 'United States',
    'Club Friday The Series 6': 'Thailand',
    'Club Friday The Series 7': 'Thailand',
    'Club Friday The Series 8': 'Thailand',
    'Club Friday To Be Continued - Friend & Enemy': 'Thailand',
    'Club Friday To Be Continued - My Beautiful Tomboy': 'Thailand',
    'Club Friday To Be Continued - The Promise': 'Thailand',
    'Comedy High School': 'India',
    'Convict': 'Australia',
    'Cop Watchers': 'United Kingdom',
    'Desolate': 'United States',
    'Diva Brides': 'Egypt',
    'Dragonkala Ka Rahasya': 'India',
    "Earth's Natural Wonders: Life at the Extremes": 'United Kingdom',
    'El Viaje: Márama y Rombai': 'Uruguay',
    'Elles étaient en guerre 1939-1945': 'France',
    'Elles ont toutes une histoire': 'France',
    'Encerrados': 'Argentina',
    'Enemigo íntimo': 'Mexico, United States',
    'Eurovision Song Contest': 'Europe',
    'Exclusive Edition': 'Egypt',
    'Fatal Destiny': 'Egypt',
    'Fishpeople': 'United States',
    'Fit for Fashion': 'Singapore',
    'Food: Delicious Science': 'United Kingdom',
    'Glowing Embers': 'Egypt',
    'Ha Unlimited': 'Egypt',
    'Harlem Globetrotters: The Team That Changed the World': 'United States',
    'Homeland': 'United States',
    'Hostages': 'Israel',
    'How to Live Mortgage Free with Sarah Beeny': 'United Kingdom',
    "Hyori's Bed & Breakfast": 'South Korea',
    'I Dream Of Dance': 'United States',
    "It's Fine": 'Egypt',
    '최강전사 미니특공대 : 영웅의 탄생': 'South Korea',
    "Jake's Buccaneer Blast": 'United States',
    'Jis Desh Men Ganga Behti Hai': 'India',
    'John Mellencamp: Plain Spoken': 'United States',
    'Jugaad': 'India',
    'Kikoriki': 'Russia',
    'Kingdoms of the Sky': 'United Kingdom',
    'Kiss The Series': 'Thailand',
    'Kon Kon Kon': 'Egypt',
    'Krish Trish and Baltiboy': 'India',
    'Krish Trish and Baltiboy: Battle of Wits': 'India',
    'Krish Trish and Baltiboy: Best Friends Forever': 'India',
    'Krish Trish and Baltiboy: Comics of India': 'India',
    'Krish Trish and Baltiboy: Oversmartness Never Pays': 'India',
    'Krish Trish and Baltiboy: Part II': 'India',
    'Krish Trish and Baltiboy: The Greatest Trick': 'India',
    'Krishna Balram': 'India',
    'Kuppivala': 'India',
    'La Femme': 'Egypt',
    'LeapFrog: Sing-along, Read-along': 'United States',
    'Lego Friends': 'Denmark',
    'LEGO House - Home of the Brick': 'Denmark',
    'Leo & Tig': 'Russia',
    'Listen Up! The Lives of Quincy Jones': 'United States',
    'Little Singham aur Kaal ka Mahajaal': 'India',
    'Little Singham Bandarpur Mein Hu Ha Hu': 'India',
    'Little Singham in London': 'India',
    'Los 10 años de Peter Capusotto': 'Argentina',
    'Los Niños Héroes de Chapultepec': 'Mexico',
    'Love Rhythms - Accidental Daddy': 'Thailand',
    'Man vs Wild with Sunny Leone': 'India',
    'Mark Gatiss: A Study in Sherlock': 'United Kingdom',
    'Marvel & ESPN Films Present: 1 of 1: Genesis': 'United States',
    'Melodies of Life - Born This Way': 'Thailand',
    'Mere Papa Hero Hiralal': 'India',
    'Mighty Morphin Alien Rangers': 'United States',
    'Money for Nothing': 'United Kingdom',
    'My Life My Story': 'India',
    'My Only Mother': 'Egypt',
    'My Wife and My Wifey': 'Egypt',
    "National Lampoon's Loaded Weapon 1": 'United States',
    'Nightmare Tenants, Slum Landlords': 'United Kingdom',
    'Nuestra Lucha Libre': 'Mexico',
    'O-Negative, Love Can’t Be Designed': 'Thailand',
    'Oh My Ghost 4': 'Thailand',
    'Operation Odessa': 'United States',
    'Phamous': 'India',
    'Power Battle Watch Car': 'South Korea',
    'Power Rangers Dino Super Charge': 'United States',
    'Power Rangers Super Megaforce': 'United States',
    'Power Rangers Super Samurai': 'United States',
    'Prince Jai Aur Dumdaar Viru': 'India',
    'Queens of Comedy': 'India',
    'Queens vs. Kings': 'Egypt',
    'Rab Se Sohna Isshq': 'India',
    'Reality of Dream': 'Egypt',
    'Refugee': 'India',
    'Revenge': 'Egypt',
    'Roots': 'United States',
    'Samudri Lootere': 'India',
    'Satrangi': 'Pakistan',
    'Strongland': 'Egypt',
    'Swami Baba Ramdev: The Untold Story': 'India',
    'Teenage Mutant Ninja Turtles: The Movie': 'United States, Hong Kong',
    'The Adjusters': 'Egypt',
    'The Bachelor': 'Egypt',
    'The Beat': 'Egypt',
    "The Bulbul's Nest": 'Egypt',
    'The Gospel of Mark': 'United Kingdom, United States',
    'The Gospel of Matthew': 'United Kingdom, United States',
    'The Homecoming': 'Egypt',
    'The Irish Mob': 'United States',
    'The Kindness Diaries': 'United States',
    'The Liar': 'Egypt',
    'The Naked Gun 2 1/2: The Smell of Fear': 'United States',
    'The Perfect Day': 'Egypt',
    'The Republic of Imbaba': 'Egypt',
    'The Underwear': 'Thailand',
    'Three-Quarters Decent': 'Egypt',
    'Timeless Season': 'Egypt',
    'Timeline': 'Thailand',
    'Tom and Jerry: The Magic Ring': 'United States',
    'Towies': 'Australia',
    'Tremors 2: Aftershocks': 'United States',
    'ViR: The Robot Boy': 'India',
    'Wake Up': 'Thailand',
    'Westside vs. the World': 'United States',
    "World's Weirdest Homes": 'United Kingdom',
    'Yoko': 'Russia, Spain',
    'YOM': 'India',
    'Zombie Dumb': 'South Korea'
}

In [288]:
df['country'] = df['country'].fillna(df['title'].map(media_countries_4))
remaining_nulls = df['country'].isnull().sum()
print(f"Remaining null values in country column: {remaining_nulls}")

Remaining null values in country column: 1

In [289]:
df.loc[df['country'].isna()]

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
621,s622,TV Show,Legend of Exorcism,Shen Leping,"Bian Jiang, Chen Jinwen, Ling Fei",NaN,"June 30, 2021",2020,TV-14,1 Season,"Anime Series, Crime TV Shows, International TV...","After leaving Yaojin Palace, Kong Hongjun arri..."

In [290]:
df['country'] = df['country'].fillna('China')

##### **`date_added` Column:**

In [291]:
df['date_added'].value_counts()

date_added
January 1, 2020       109
November 1, 2019       89
March 1, 2018          75
December 31, 2019      74
October 1, 2018        71
                     ...
February 2, 2017        1
September 11, 2019      1
May 17, 2015            1
June 5, 2018            1
October 14, 2017        1
Name: count, Length: 1767, dtype: int64

In [292]:
missing_dates_titles = list(df.loc[df['date_added'].isna(), 'title'])
missing_dates_titles

["A Young Doctor's Notebook and Other Stories",
 'Anthony Bourdain: Parts Unknown',
 'Frasier',
 'Friends',
 'Gunslinger Girl',
 'Kikoriki',
 'La Familia P. Luche',
 'Maron',
 'Red vs. Blue',
 'The Adventures of Figaro Pho']

In [293]:
netflix_added_dates = {
    "A Young Doctor's Notebook and Other Stories": "September 15, 2014",
    "Anthony Bourdain: Parts Unknown": "June 1, 2020",
    "Frasier": "April 1, 2015",
    "Friends": "March 31, 2026",
    "Gunslinger Girl": "January 4, 2016",
    "Kikoriki": "July 6, 2017",
    "La Familia P. Luche": "June 1, 2015",
    "Maron": "November 2, 2018",
    "Red vs. Blue": "March 21, 2015",
    "The Adventures of Figaro Pho": "January 1, 2016"
}

In [294]:
df['date_added'] = df['date_added'].fillna(df['title'].map(netflix_added_dates))
remaining_nulls = df['date_added'].isnull().sum()
print(f"Remaining null values in date_added column: {remaining_nulls}")

Remaining null values in date_added column: 0

In [295]:
df['date_added'] = df['date_added'].str.strip()
df['date_added'] = pd.to_datetime(df['date_added'], format='%B %d, %Y')

In [296]:
df['date_added'] = df['date_added'].dt.strftime('%Y-%m-%d')

##### **`release_year` Column:**

In [297]:
df['release_year'].value_counts()

release_year
2018    1147
2017    1032
2019    1030
2020     953
2016     902
        ...
1961       1
1925       1
1959       1
1966       1
1947       1
Name: count, Length: 74, dtype: int64

In [298]:
df['release_year'].isna().sum()

np.int64(0)

##### **`rating` Column:**

In [299]:
df['rating'].value_counts()

rating
TV-MA       3207
TV-14       2160
TV-PG        863
R            799
PG-13        490
TV-Y7        334
TV-Y         307
PG           287
TV-G         220
NR            80
G             41
TV-Y7-FV       6
NC-17          3
UR             3
74 min         1
84 min         1
66 min         1
Name: count, dtype: int64

In [300]:
rating_min_error = ['74 min', '84 min', '66 min']
df.loc[df['rating'].isin(rating_min_error)]

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
5541,s5542,Movie,Louis C.K. 2017,Louis C.K.,Louis C.K.,United States,2017-04-04,2017,74 min,NaN,Movies,"Louis C.K. muses on religion, eternal love, gi..."
5794,s5795,Movie,Louis C.K.: Hilarious,Louis C.K.,Louis C.K.,United States,2016-09-16,2010,84 min,NaN,Movies,Emmy-winning comedy writer Louis C.K. brings h...
5813,s5814,Movie,Louis C.K.: Live at the Comedy Store,Louis C.K.,Louis C.K.,United States,2016-08-15,2015,66 min,NaN,Movies,The comic puts his trademark hilarious/thought...

In [301]:
df.loc[df['show_id'] == 's5542', 'duration'] = '74 min'
df.loc[df['show_id'] == 's5795', 'duration'] = '84 min'
df.loc[df['show_id'] == 's5814', 'duration'] = '66 min'

In [302]:
rating_min_error = ['74 min', '84 min', '66 min']
df.loc[df['rating'].isin(rating_min_error)]

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
5541,s5542,Movie,Louis C.K. 2017,Louis C.K.,Louis C.K.,United States,2017-04-04,2017,74 min,74 min,Movies,"Louis C.K. muses on religion, eternal love, gi..."
5794,s5795,Movie,Louis C.K.: Hilarious,Louis C.K.,Louis C.K.,United States,2016-09-16,2010,84 min,84 min,Movies,Emmy-winning comedy writer Louis C.K. brings h...
5813,s5814,Movie,Louis C.K.: Live at the Comedy Store,Louis C.K.,Louis C.K.,United States,2016-08-15,2015,66 min,66 min,Movies,The comic puts his trademark hilarious/thought...

In [303]:
df.loc[df['rating'].isin(rating_min_error), 'rating'] = np.nan

In [304]:
missing_rating_titles = list(df.loc[df['rating'].isna(), 'title'])
missing_rating_titles

['Louis C.K. 2017',
 'Louis C.K.: Hilarious',
 'Louis C.K.: Live at the Comedy Store',
 '13TH: A Conversation with Oprah Winfrey & Ava DuVernay',
 'Gargantia on the Verdurous Planet',
 'Little Lunch',
 'My Honor Was Loyalty']

In [305]:
media_content_ratings = {
    "13TH: A Conversation with Oprah Winfrey & Ava DuVernay": "TV-14",
    "Gargantia on the Verdurous Planet": "TV-14",
    "Little Lunch": "TV-G",
    "My Honor Was Loyalty": "PG-13",
    "Louis C.K. 2017": "TV-MA",
    "Louis C.K.: Hilarious": "UR",
    "Louis C.K.: Live at the Comedy Store": "UR"
}

In [306]:
df['rating'] = df['rating'].fillna(df['title'].map(media_content_ratings))
remaining_nulls = df['rating'].isnull().sum()
print(f"Remaining null values in rating column: {remaining_nulls}")

Remaining null values in rating column: 0

##### **`duration` Column:**

In [319]:
df['duration'].value_counts()

duration
1 Season     1793
2 Seasons     425
3 Seasons     199
90 min        152
97 min        146
             ...
228 min         1
18 min          1
205 min         1
201 min         1
191 min         1
Name: count, Length: 220, dtype: int64

In [321]:
df['duration'].isna().sum()

np.int64(0)

##### **`listed_in` Column:**

In [324]:
df['listed_in'].value_counts()

listed_in
Dramas, International Movies                        362
Documentaries                                       359
Stand-Up Comedy                                     334
Comedies, Dramas, International Movies              274
Dramas, Independent Movies, International Movies    252
                                                   ...
Action & Adventure, Cult Movies                       1
Action & Adventure, Comedies, Music & Musicals        1
Classic Movies, Horror Movies, Thrillers              1
Children & Family Movies, Classic Movies, Dramas      1
Cult Movies, Dramas, Thrillers                        1
Name: count, Length: 514, dtype: int64

In [323]:
df['listed_in'].isna().sum()

np.int64(0)

In [325]:
df.loc[df['show_id'] == 's5542', 'listed_in'] = 'Stand-Up Comedy'
df.loc[df['show_id'] == 's5795', 'listed_in'] = 'Stand-Up Comedy'
df.loc[df['show_id'] == 's5814', 'listed_in'] = 'Stand-Up Comedy'

In [331]:
df.to_excel('netflix_data_cleaned.xlsx', index=False)